APM32F10x_SDK: Functions
Functions
Examples » I2C_TwoBoards_Master | Examples » I2C_TwoBoards_Master » Macros
Functions
void Delay (void)
Main program.
void USART_Init (void)
USART configs.
void I2C_Init (void)
I2C Init.
uint8_t I2C_Write (char *pBuffer)
I2C Write.
void APM_MINI_PB_I2C_Isr ()
BUTTON_KEY interrupt service routine.
void I2C_Isr (void)
I2C interrupt service routine.
int main (void)
Main program.
uint32_t I2C_TIMEOUT_UserCallback (uint8_t errorCode)
Used to locate the wrong location of the I2C_Write()
Detailed Description
Function Documentation
APM_MINI_PB_I2C_Isr()
void APM_MINI_PB_I2C_Isr (void)
BUTTON_KEY interrupt service routine.
Parameters
None
Return values
None
Note
This function need to put into EINT0_1_IRQHandler() in apm32f10x_int.c
Definition at line 267 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References EINT_ClearStatusFlag(), EINT_LINE_1, EINT_ReadStatusFlag(), I2C_Write(), and SET.
Referenced by EINT1_IRQHandler().
Delay()
void Delay (void)
Main program.
Delay.
Parameters
None
Return values
None
Definition at line 88 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
I2C_Init()
void I2C_Init (void)
I2C Init.
Parameters
None
Return values
None
Definition at line 122 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References I2C_Config_T::ack, I2C_Config_T::ackAddress, I2C_Config_T::clockSpeed, I2C_Config_T::dutyCycle, GPIO_Config(), GPIO_MODE_AF_OD, GPIO_PIN_6, GPIO_PIN_7, GPIO_SPEED_50MHz, GPIOB, I2C1, I2C_ACK_ADDRESS_7BIT, I2C_ACK_ENABLE, I2C_Config(), I2C_DUTYCYCLE_2, I2C_Enable(), I2C_EnableInterrupt(), I2C_INT_EVT, I2C_MODE_I2C, I2C_Reset(), GPIO_Config_T::mode, I2C_Config_T::mode, NVIC_EnableIRQRequest(), I2C_Config_T::ownAddress1, GPIO_Config_T::pin, RCM_APB1_PERIPH_I2C1, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by I2C_Write(), and main().
I2C_Isr()
void I2C_Isr (void)
I2C interrupt service routine.
Parameters
None
Return values
None
Note
This function need to put into I2C1_IRQHandler() in apm32f10x_int.c
Definition at line 170 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References dat, I2C1, I2C_FLAG_RXBNE, I2C_INT_FLAG_ADDR, I2C_INT_FLAG_STOP, I2C_ReadIntFlag(), I2C_ReadStatusFlag(), I2C_RxData(), and SET.
Referenced by I2C1_EV_IRQHandler().
I2C_TIMEOUT_UserCallback()
uint32_t I2C_TIMEOUT_UserCallback (uint8_t errorCode)
Used to locate the wrong location of the I2C_Write()
Parameters
errorCode
Return values
Error code location information
Definition at line 104 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References I2C_DEBUG_ON.
Referenced by I2C_Write().
I2C_Write()
uint8_t I2C_Write (char * pBuffer)
I2C Write.
Parameters
I2C Specifies the I2C to be configured.
*pBuffer Pointer to data
Return values
0 or ERROR Information
Definition at line 203 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References I2C1, I2C_DIRECTION_TX, I2C_DisableInterrupt(), I2C_EnableGenerateStart(), I2C_EVENT_MASTER_BYTE_TRANSMITTING, I2C_EVENT_MASTER_MODE_SELECT, I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED, I2C_FLAG_BUSBSY, I2C_Init(), I2C_INT_EVT, I2C_ReadEventStatus(), I2C_ReadStatusFlag(), I2C_TIMEOUT_UserCallback(), I2C_Tx7BitAddress(), I2C_TxData(), I2CT_FLAG_TIMEOUT, and I2CT_LONG_TIMEOUT.
Referenced by APM_MINI_PB_I2C_Isr().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 63 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDToggle(), APM_MINI_PBInit(), BUTTON_KEY1, BUTTON_MODE_EINT, Delay(), I2C_Init(), LED2, LED3, and USART_Init().
USART_Init()
void USART_Init (void)
USART configs.
Parameters
None
Return values
None
Definition at line 284 of file I2C/I2C_TwoBoards/I2C_TwoBoards_Master/Source/main.c.
References APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, USART_Config_T::hardwareFlow, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU