APM32F10x_SDK: myiic.c File Reference
myiic.c File Reference
#include "myiic.h"
#include "bsp_delay.h"
Functions
void SDA_IN (void)
Configure SDA as input mode.
void SDA_OUT (void)
Configure SDA as output mode.
void IIC_Init (void)
IIC Init.
void IIC_Start (void)
Generate IIC start signal.
void IIC_Stop (void)
Generate IIC stop signal.
uint8_t IIC_Wait_Ack (void)
Wait for the answer signal to come.
void IIC_Ack (void)
Generate ACK response.
void IIC_NAck (void)
generate NACK response
void IIC_Send_Byte (uint8_t txd)
IIC sends a byte.
uint8_t IIC_Read_Byte (unsigned char ack)
read one byte
Function Documentation
IIC_Ack()
void IIC_Ack (void)
Generate ACK response.
Parameters
None
Return values
None
Definition at line 129 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, and SDA_OUT().
Referenced by IIC_Read_Byte().
IIC_Init()
void IIC_Init (void)
IIC Init.
Parameters
None
Return values
None
Definition at line 40 of file myiic.c.
References GPIO_Config(), GPIO_MODE_OUT_PP, GPIO_SetBit(), GPIO_SPEED_50MHz, GPIOB, IIC_PIN_SCL, IIC_PIN_SDA, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by AT24CXX_Init().
IIC_NAck()
void IIC_NAck (void)
generate NACK response
Parameters
None
Return values
None
Definition at line 148 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_SET, and SDA_OUT().
Referenced by IIC_Read_Byte().
IIC_Read_Byte()
uint8_t IIC_Read_Byte (unsigned char ack)
read one byte
Parameters
ack Flag to send ACK or NACK
Return values
read data
Definition at line 193 of file myiic.c.
References Delay_us(), IIC_Ack(), IIC_NAck(), IIC_READ_SDA, IIC_SCL_RESET, IIC_SCL_SET, and SDA_IN().
Referenced by AT24CXX_ReadOneByte().
IIC_Send_Byte()
void IIC_Send_Byte (uint8_t txd)
IIC sends a byte.
Parameters
txd Data to send
Return values
Whether the slave responds 1: reponse 0: no reponse
Definition at line 168 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_WRITE, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
IIC_Start()
void IIC_Start (void)
Generate IIC start signal.
Parameters
None
Return values
None
Definition at line 60 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, IIC_SDA_SET, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
IIC_Stop()
void IIC_Stop (void)
Generate IIC stop signal.
Parameters
None
Return values
None
Definition at line 79 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, IIC_SDA_SET, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), AT24CXX_WriteOneByte(), and IIC_Wait_Ack().
IIC_Wait_Ack()
uint8_t IIC_Wait_Ack (void)
Wait for the answer signal to come.
Parameters
None
Return values
uint8_t
Note
Return value: 1, failed to receive the response 0, the response is received successfully
Definition at line 100 of file myiic.c.
References Delay_us(), IIC_READ_SDA, IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_SET, IIC_Stop(), and SDA_IN().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
SDA_IN()
void SDA_IN (void)
Configure SDA as input mode.
Parameters
None
Return values
None
Definition at line 12 of file myiic.c.
References GPIOB.
Referenced by IIC_Read_Byte(), and IIC_Wait_Ack().
SDA_OUT()
void SDA_OUT (void)
Configure SDA as output mode.
Parameters
None
Return values
None
Definition at line 26 of file myiic.c.
References GPIOB.
Referenced by IIC_Ack(), IIC_NAck(), IIC_Send_Byte(), IIC_Start(), and IIC_Stop().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU