APM32F10x_SDK: Functions
Functions
USB OTG Library » Driver » USB_Device » Macros
Functions
void USB_OTG_ConfigDeviceTxFifo (uint8_t ep, uint16_t address, uint16_t depth)
Config Depth and start address of TxFifo.
void USB_OTG_OutEpActive (uint8_t ep, USB_EP_TYPE_T epType, uint16_t packSize)
Active OUT endpoint.
void USB_OTG_OutEpDeactive (uint8_t ep)
Deactive OUT endpoint.
void USB_OTG_InEpActive (uint8_t ep, USB_EP_TYPE_T epType, uint8_t txFifoNum, uint32_t packSize)
Active IN endpoint.
void USB_OTG_InEpDeactive (uint8_t ep)
Deactive IN endpoint.
void USB_OTG_SetInEpStall (uint8_t ep)
Stall in endpoint.
void USB_OTG_ClearInEpStall (uint8_t ep)
Clear in endpoint Stall.
void USB_OTG_SetOutEpStall (uint8_t ep)
Stall out endpoint.
void USB_OTG_ClearOutEpStall (uint8_t ep)
Clear OUT endpoint Stall.
void USB_OTG_SetStall (uint8_t ep)
Stall out endpoint and in endpoint.
void USB_OTG_ClearStall (uint8_t ep)
Clear Stall of out endpoint and in endpoint.
void USB_OTG_ReceiveSetupPacket (uint8_t packNum)
Start to receive Setup request packet by RxFIFO.
void USB_OTG_EnableOutEpTransfer (uint8_t ep, uint8_t packNum, uint32_t transferSize)
Start to receive OUT data by RxFIFO.
void USB_OTG_EnableInEpTransfer (uint8_t ep, uint8_t packNum, uint32_t transferSize)
Start to Send data through TxFIFO.
uint8_t USB_OTG_ReadOutEpIntStatus (uint8_t ep, USB_INT_EP_OUT_T flag)
Read the out endpoint interrupt status.
uint8_t USB_OTG_ReadInEpIntStatus (uint8_t ep, USB_INT_EP_IN_T flag)
Read the IN endpoint interrupt status.
uint8_t USB_OTG_ReadEPActive (uint8_t ep)
Read the endpoint active status.
Detailed Description
Function Documentation
USB_OTG_ClearInEpStall()
void USB_OTG_ClearInEpStall (uint8_t ep)
Clear in endpoint Stall.
Parameters
ep IN endpoint
Return values
None
Definition at line 213 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_RESET.
Referenced by USB_OTG_ClearStall(), and USBD_MSV_BOT_ClearFeatureHandler().
USB_OTG_ClearOutEpStall()
void USB_OTG_ClearOutEpStall (uint8_t ep)
Clear OUT endpoint Stall.
Parameters
ep OUT endpoint number
Return values
None
Definition at line 237 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_RESET.
Referenced by USB_OTG_ClearStall().
USB_OTG_ClearStall()
void USB_OTG_ClearStall (uint8_t ep)
Clear Stall of out endpoint and in endpoint.
Parameters
ep endpoint number
Return values
None
Definition at line 264 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References USB_OTG_ClearInEpStall(), USB_OTG_ClearOutEpStall(), and USB_OTG_ReceiveSetupPacket().
USB_OTG_ConfigDeviceTxFifo()
void USB_OTG_ConfigDeviceTxFifo (uint8_t ep, uint16_t address, uint16_t depth)
Config Depth and start address of TxFifo.
Parameters
ep : IN EP number
address : start address of TxFIFO
depth : depth of TxFIFO
Return values
None
Definition at line 341 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
USB_OTG_EnableInEpTransfer()
void USB_OTG_EnableInEpTransfer (uint8_t ep, uint8_t packNum, uint32_t transferSize)
Start to Send data through TxFIFO.
Parameters
ep IN endpoint number
packNum Set pack number
transferSize Set transfer size
Return values
None
Definition at line 319 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_CtrlInData(), USBD_CtrlInProcess(), USBD_CtrlTxStatus(), and USBD_TxData().
USB_OTG_EnableOutEpTransfer()
void USB_OTG_EnableOutEpTransfer (uint8_t ep, uint8_t packNum, uint32_t transferSize)
Start to receive OUT data by RxFIFO.
Parameters
ep OUT endpoint number
packNum Set pack number
transferSize Set transfer size
Return values
None
Definition at line 297 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_CtrlOutData(), USBD_CtrlOutProcess(), USBD_CtrlRxStatus(), and USBD_RxData().
USB_OTG_InEpActive()
void USB_OTG_InEpActive (uint8_t ep, USB_EP_TYPE_T epType, uint8_t txFifoNum, uint32_t packSize)
Active IN endpoint.
Parameters
ep IN endpoint number
epType IN endpoint type. This parameter can be one of the following value:
USB_EP_TYPE_CONTROL : Control endpoint
USB_EP_TYPE_ISO : Isochronous endpoint
USB_EP_TYPE_BULK : Bulk endpoint
USB_EP_TYPE_INTERRUPT : Interrupt endpoint
txFifoNum endpoint specific txFIFO number.
packSize endpoint max pack size
Return values
None
Definition at line 129 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_OpenInEP().
USB_OTG_InEpDeactive()
void USB_OTG_InEpDeactive (uint8_t ep)
Deactive IN endpoint.
Parameters
ep IN endpoint Number
Return values
None
Definition at line 168 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_CloseInEP().
USB_OTG_OutEpActive()
void USB_OTG_OutEpActive (uint8_t ep, USB_EP_TYPE_T epType, uint16_t packSize)
Active OUT endpoint.
Parameters
ep OUT endpoint number
epType OUT endpoint type. This parameter can be one of the following value:
USB_EP_TYPE_CONTROL : Control endpoint
USB_EP_TYPE_ISO : Isochronous endpoint
USB_EP_TYPE_BULK : Bulk endpoint
USB_EP_TYPE_INTERRUPT : Interrupt endpoint
packSize ep max pack size
Return values
None
Definition at line 61 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_OpenOutEP().
USB_OTG_OutEpDeactive()
void USB_OTG_OutEpDeactive (uint8_t ep)
Deactive OUT endpoint.
Parameters
ep OUT endpoint Number
Return values
None
Definition at line 98 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USBD_CloseOutEP().
USB_OTG_ReadEPActive()
uint8_t USB_OTG_ReadEPActive (uint8_t ep)
Read the endpoint active status.
Parameters
ep IN endpoint number
Return values
Return endpoint Active status, 1: Actice
Definition at line 188 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
USB_OTG_ReadInEpIntStatus()
uint8_t USB_OTG_ReadInEpIntStatus (uint8_t ep, USB_INT_EP_IN_T flag)
Read the IN endpoint interrupt status.
Parameters
ep : IN endpiont number
flag : IN ep interrupt flag. This parameter can be one of the following value:
USB_INT_EP_IN_TSFCMP : Transfer completed
USB_INT_EP_IN_EPDIS : Endpoint disabled
USB_INT_EP_IN_TO : Timeout
USB_INT_EP_IN_ITXEMP : IN token received when TxFIFO is empty
USB_INT_EP_IN_IEPNAKE: IN endpoint NAK effective
USB_INT_EP_IN_TXFE : TxFIFO empty
Return values
Return IN endpoint interrupt status
Definition at line 402 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References RESET, and SET.
USB_OTG_ReadOutEpIntStatus()
uint8_t USB_OTG_ReadOutEpIntStatus (uint8_t ep, USB_INT_EP_OUT_T flag)
Read the out endpoint interrupt status.
Parameters
ep : out endpiont number
flag : out ep interrupt flag. This parameter can be one of the following value:
USB_INT_EP_OUT_TSFCMP : Transfer completed
USB_INT_EP_OUT_EPDIS : Endpoint disabled
USB_INT_EP_OUT_SETPCMP: setup completed
USB_INT_EP_OUT_RXOTDIS: OUT token received when endpoint disabled
USB_INT_EP_OUT_RXBSP : Received Back-to-back SETUP packets over 3
Return values
return Out endpoint interrupt status
Definition at line 370 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References RESET, and SET.
USB_OTG_ReceiveSetupPacket()
void USB_OTG_ReceiveSetupPacket (uint8_t packNum)
Start to receive Setup request packet by RxFIFO.
Parameters
packNum setup pack number to receive.
Return values
None
Definition at line 279 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
Referenced by USB_OTG_ClearStall(), USB_OTG_SetStall(), USBD_CtrlRxStatus(), and USBD_CtrlTxStatus().
USB_OTG_SetInEpStall()
void USB_OTG_SetInEpStall (uint8_t ep)
Stall in endpoint.
Parameters
ep IN endpoint number
Return values
None
Definition at line 200 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USB_OTG_SetStall().
USB_OTG_SetOutEpStall()
void USB_OTG_SetOutEpStall (uint8_t ep)
Stall out endpoint.
Parameters
ep OUT endpoint number
Return values
None
Definition at line 225 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References BIT_SET.
Referenced by USB_OTG_SetStall().
USB_OTG_SetStall()
void USB_OTG_SetStall (uint8_t ep)
Stall out endpoint and in endpoint.
Parameters
ep endpoint number
Return values
None
Definition at line 249 of file USB_OTG_Lib/Driver/src/drv_usb_device.c.
References USB_OTG_ReceiveSetupPacket(), USB_OTG_SetInEpStall(), and USB_OTG_SetOutEpStall().
Referenced by USBD_ClassHandler(), USBD_MSC_ClassHandler(), USBD_SetupProcess(), and USBD_StandardReqeust().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU