APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device » Standrad | USB OTG Library » Core Host » Standard » Init
Functions
void USBD_Init (USBD_InitParam_T *param)
USB initialization.
void USBD_InitParamStructInit (USBD_InitParam_T *param)
Init parameter in param.
void USBD_OpenOutEP (uint8_t ep, USB_EP_TYPE_T epType, uint32_t packSize)
Open OUT endpoint.
void USBD_OpenInEP (uint8_t ep, USB_EP_TYPE_T epType, uint32_t packSize)
Open IN endpoint.
void USBD_CloseOutEP (uint8_t ep)
Close OUT endpoint.
void USBD_CloseInEP (uint8_t ep)
Close IN endpoint.
void USB_CoreSoftReset (void)
USB Soft reset.
void USBH_Init (USBH_InitParam_T *param)
USB Host initialization.
void USBH_DeInit (void)
USB Host initialization.
void USB_HostInit (void)
USB Host initialization.
Detailed Description
Function Documentation
USB_CoreSoftReset()
void USB_CoreSoftReset (void)
USB Soft reset.
Parameters
None
Return values
None
Definition at line 320 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References BIT_RESET, BIT_SET, USB_Delay_us(), USB_OTG_EnableCoreSoftReset, USB_OTG_ReadAHBMasterIdleFlag, and USB_OTG_ReadCoreSoftResetFlag.
USB_HostInit()
void USB_HostInit (void)
USB Host initialization.
Parameters
None
Return values
None
< ULPI PHY
< UTMI PHY (OTG_HS_PHY_UTMI)
< USB_OTG_HS_CORE
< Disable all interrupt
< Clear OTG flag
< Clear global interrupt flag
Definition at line 159 of file usbh_init.c.
References CHANNEL_INT_ALL, HOST_CHANNEL_NUM, PHYCLK_30_60_MHZ, PHYCLK_48_MHZ, USB_Delay_us(), USB_HS_NP_TXH_FIFO_SIZE, USB_HS_P_TXH_FIFO_SIZE, USB_HS_RX_FIFO_SIZE, USB_INT_G_HCHAN, USB_INT_G_HPORT, USB_INT_G_IP_OUTTX, USB_INT_G_RWAKE, USB_INT_G_RXFNONE, USB_INT_G_USBSUS, USB_MODE_HOST, USB_OTG_ConfigMode(), USB_OTG_FlushRxFIFO(), USB_OTG_FlushTxFIFO(), USB_OTG_H_ClearChannelIntFlag, USB_OTG_H_ConfigHostClk, USB_OTG_H_DisableChannelInt, and USB_OTG_PortReset().
Referenced by USBH_Init().
USBD_CloseInEP()
void USBD_CloseInEP (uint8_t ep)
Close IN endpoint.
Parameters
ep IN endpoint Number
Return values
None
Definition at line 416 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, and USB_OTG_InEpDeactive().
USBD_CloseOutEP()
void USBD_CloseOutEP (uint8_t ep)
Close OUT endpoint.
Parameters
ep OUT endpoint Number
Return values
None
Definition at line 402 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, and USB_OTG_OutEpDeactive().
USBD_Init()
void USBD_Init (USBD_InitParam_T * param)
USB initialization.
USB init.
Parameters
param Initialization parameter
Return values
None
Definition at line 62 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References BIT_RESET, USBD_InitParam_T::classReqHandler, USBD_Info_T::classReqHandler, USBD_Info_T::configurationNum, g_usbDev, USBD_InitParam_T::inEpHandler, USBD_Info_T::inEpHandler, USBD_InitParam_T::intHandler, USBD_Info_T::intHandler, USBD_InitParam_T::outEpHandler, USBD_Info_T::outEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_Info_T::pConfigurationDesc, USBD_Descriptor_T::pDesc, USBD_InitParam_T::pDeviceDesc, USBD_Info_T::pDeviceDesc, USBD_InitParam_T::pHidReportDesc, USBD_Info_T::pHidReportDesc, USBD_InitParam_T::pQualifierDesc, USBD_Info_T::pQualifierDesc, USBD_InitParam_T::pStdReqCallback, USBD_Info_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, USBD_Info_T::pStringDesc, USBD_InitParam_T::resetHandler, USBD_Info_T::resetHandler, USBD_InitParam_T::rxStatusHandler, USBD_Info_T::rxStatusHandler, USBD_InitParam_T::stdReqExceptionHandler, USBD_Info_T::stdReqExceptionHandler, USBD_InitParam_T::txStatusHandler, USBD_Info_T::txStatusHandler, USB_HardwareInit(), USB_OTG_EnableAllGlobalInterrupt, USBD2_Disable, USBD_ConfigSerialString(), USBD_CONFIGURATION_NUM, USBD_HardWareInit(), USBD_PowerOn(), USBD_InitParam_T::vendorReqHandler, and USBD_Info_T::vendorReqHandler.
Referenced by CDC_Init(), HidMouse_Init(), MSC_Init(), USBD_HID_Init(), USBD_MSC_Init(), and USBD_VCP_Init().
USBD_InitParamStructInit()
void USBD_InitParamStructInit (USBD_InitParam_T * param)
Init parameter in param.
Parameters
param Initialization parameter
Return values
None
Definition at line 111 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References USBD_InitParam_T::classReqHandler, USBD_InitParam_T::inEpHandler, USBD_InitParam_T::intHandler, NULL, USBD_InitParam_T::outEpHandler, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::resetHandler, USBD_InitParam_T::rxStatusHandler, USBD_InitParam_T::stdReqExceptionHandler, USBD_InitParam_T::txStatusHandler, and USBD_InitParam_T::vendorReqHandler.
Referenced by CDC_Init(), HidMouse_Init(), MSC_Init(), USBD_HID_Init(), USBD_MSC_Init(), and USBD_VCP_Init().
USBD_OpenInEP()
void USBD_OpenInEP (uint8_t ep, USB_EP_TYPE_T epType, uint32_t packSize)
Open IN endpoint.
Parameters
ep IN endpoint number
epType IN endpoint type. This parameter can be one of the following value:
USB_EP_TYPE_CONTROL : Control endpoint
USB_EP_TYPE_ISO : Isochronous endpoint
USB_EP_TYPE_BULK : Bulk endpoint
USB_EP_TYPE_INTERRUPT : Interrupt endpoint
packSize endpoint max pack size
Return values
None
Definition at line 387 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, and USB_OTG_InEpActive().
USBD_OpenOutEP()
void USBD_OpenOutEP (uint8_t ep, USB_EP_TYPE_T epType, uint32_t packSize)
Open OUT endpoint.
Parameters
ep OUT endpoint number
epType OUT endpoint type. This parameter can be one of the following value:
USB_EP_TYPE_CONTROL : Control endpoint
USB_EP_TYPE_ISO : Isochronous endpoint
USB_EP_TYPE_BULK : Bulk endpoint
USB_EP_TYPE_INTERRUPT : Interrupt endpoint
packSize ep max pack size
Return values
None
Definition at line 365 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, and USB_OTG_OutEpActive().
USBH_DeInit()
void USBH_DeInit (void)
USB Host initialization.
Parameters
param point to USBH_InitParam_T structure
Return values
None
Definition at line 93 of file usbh_init.c.
References USBH_Info_T::classDeInitHandler, USBH_Info_T::control, USBH_Control_T::ctrlState, USB_UserCallBack_T::deInitHandler, g_usbHost, g_userCallback, USBH_Control_T::inChannelNum, USBH_Control_T::maxPackSize, USBH_Control_T::outChannelNum, USB_EP0_PACKET_SIZE, USBH_CH_FreeChannel(), USBH_ConfigDeviceAddr, USBH_ConfigEnumState, USBH_ConfigHostState, USBH_CTRL_SETUP, USBH_DEVICE_DEFAULT_ADDRESS, USBH_ENUM_IDLE, USBH_HOST_IDLE, USBH_XFER_START, and USBH_Control_T::xferState.
USBH_Init()
void USBH_Init (USBH_InitParam_T * param)
USB Host initialization.
Parameters
param point to USBH_InitParam_T structure
Return values
None
Definition at line 57 of file usbh_init.c.
References USBH_InitParam_T::classCoreHandler, USBH_Info_T::classCoreHandler, USBH_InitParam_T::classDeInitHandler, USBH_Info_T::classDeInitHandler, USBH_InitParam_T::classInitHandler, USBH_Info_T::classInitHandler, USBH_InitParam_T::classReqHandler, USBH_Info_T::classReqHandler, USBH_Info_T::control, USBH_Info_T::devAddress, g_usbHost, g_userCallback, USB_UserCallBack_T::initHandler, USBH_InitParam_T::intHandler, USBH_Info_T::intHandler, USBH_Control_T::maxPackSize, USBH_InitParam_T::suspendHandler, USBH_Info_T::suspendHandler, USB_EP0_PACKET_SIZE, USB_HardwareInit(), USB_HostInit(), USB_OTG_EnableAllGlobalInterrupt, USBH_DEVICE_DEFAULT_ADDRESS, USBH_InitParam_T::wakeUpHandler, and USBH_Info_T::wakeUpHandler.
Referenced by USBH_CDC_Init(), USBH_HID_Init(), and USBH_MSC_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU