APM32F10x_SDK: Functions
Functions
Examples » ADC_ContinuousConversion
Functions
void ADC1_Isr (void)
ADC1 Isr.
void ADC_Init (void)
ADC Init.
void Delay (uint32_t count)
Delay.
int main (void)
Main program.
Detailed Description
Function Documentation
ADC1_Isr()
void ADC1_Isr (void)
ADC1 Isr.
Parameters
None
Return values
None
Note
This function need to put into ADC1_2_IRQHandler in apm32f10x_int.c
Definition at line 157 of file ADC/ADC_ContinuousConversion/Source/main.c.
References ADC1, ADC_ClearIntFlag(), ADC_INT_EOC, ADC_ReadConversionValue(), ADC_ReadIntFlag(), adcData, and SET.
Referenced by ADC1_2_IRQHandler().
ADC_Init()
void ADC_Init (void)
ADC Init.
Parameters
None
Return values
None
Definition at line 90 of file ADC/ADC_ContinuousConversion/Source/main.c.
References ADC1, ADC_CHANNEL_0, ADC_Config(), ADC_ConfigRegularChannel(), ADC_ConfigStructInit(), ADC_DATA_ALIGN_RIGHT, ADC_Enable(), ADC_EnableInterrupt(), ADC_EnableSoftwareStartConv(), ADC_EXT_TRIG_CONV_None, ADC_INT_EOC, ADC_MODE_INDEPENDENT, ADC_ReadCalibrationStartFlag(), ADC_ReadResetCalibrationStatus(), ADC_Reset(), ADC_ResetCalibration(), ADC_SAMPLETIME_13CYCLES5, ADC_StartCalibration(), ADC_Config_T::continuosConvMode, ADC_Config_T::dataAlign, DISABLE, ENABLE, ADC_Config_T::externalTrigConv, GPIO_Config(), GPIO_ConfigStructInit(), GPIO_MODE_ANALOG, GPIO_PIN_0, GPIOA, ADC_Config_T::mode, GPIO_Config_T::mode, ADC_Config_T::nbrOfChannel, NVIC_EnableIRQRequest(), GPIO_Config_T::pin, RCM_APB2_PERIPH_ADC1, RCM_APB2_PERIPH_GPIOA, RCM_ConfigADCCLK(), RCM_EnableAPB2PeriphClock(), RCM_PCLK2_DIV_4, and ADC_Config_T::scanConvMode.
Referenced by main().
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 180 of file ADC/ADC_ContinuousConversion/Source/main.c.
References count.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 61 of file ADC/ADC_ContinuousConversion/Source/main.c.
References ADC_Init(), APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, USART_Config_T::hardwareFlow, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU