APM32F10x_SDK: APM32F103_MINI_Functions
APM32F103_MINI_Functions
Board | Board » Board_APM32F103_MINI
Functions
void APM_MINI_LEDInit (Led_TypeDef Led)
Configures LED GPIO.
void APM_MINI_LEDOn (Led_TypeDef Led)
Turns selected LED On.
void APM_MINI_LEDOff (Led_TypeDef Led)
Turns selected LED Off.
void APM_MINI_LEDToggle (Led_TypeDef Led)
Toggles the selected LED.
void APM_MINI_PBInit (Button_TypeDef Button, ButtonMode_TypeDef Button_Mode)
Configures Button GPIO and EINT Line.
uint32_t APM_MINI_PBGetState (Button_TypeDef Button)
Returns the selected Button state.
void APM_MINI_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
void Delay_Init (void)
Update SystemCoreClock variable according to Clock Register Values The SystemCoreClock variable contains the core clock (HCLK)
void Delay_ms (__IO u32 nms)
Configures Delay ms.
void Delay_us (__IO u32 nus)
Configures Delay us.
Detailed Description
Function Documentation
APM_MINI_COMInit()
void APM_MINI_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 223 of file Board_APM32F103_MINI.c.
References COM1, COM_RX_PIN, COM_RX_PORT, COM_RX_PORT_CLK, COM_TX_PIN, COM_TX_PORT, COM_TX_PORT_CLK, COM_USART, COM_USART_CLK, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_SPEED_50MHz, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config(), and USART_Enable().
Referenced by APM_BOARD_COMInit(), main(), USART_Init(), and Usart_Init().
APM_MINI_LEDInit()
void APM_MINI_LEDInit (Led_TypeDef Led)
Configures LED GPIO.
Parameters
Led Specifies the Led to be configured. This parameter can be one of following parameters:
LED2
LED3
Return values
None
Definition at line 92 of file Board_APM32F103_MINI.c.
References GPIO_T::BC, GPIO_CLK, GPIO_Config(), GPIO_MODE_OUT_PP, GPIO_PIN, GPIO_PORT, GPIO_SPEED_50MHz, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by main(), and UserTaskInit().
APM_MINI_LEDOff()
void APM_MINI_LEDOff (Led_TypeDef Led)
Turns selected LED Off.
Parameters
Led Specifies the Led to be configured. This parameter can be one of following parameters:
LED2
LED3
Return values
None
Definition at line 133 of file Board_APM32F103_MINI.c.
References GPIO_T::BSC, GPIO_PIN, and GPIO_PORT.
Referenced by ADC_Isr(), APM_MINI_PB2_Isr(), DataAnalyze(), Eint0_Isr(), Eint1_Isr(), main(), TAMPER_IRQHandler(), and vTaskUsartTest().
APM_MINI_LEDOn()
void APM_MINI_LEDOn (Led_TypeDef Led)
Turns selected LED On.
Parameters
Led Specifies the Led to be configured. This parameter can be one of following parameters:
LED2
LED3
Return values
None
Definition at line 118 of file Board_APM32F103_MINI.c.
References GPIO_T::BC, GPIO_PIN, and GPIO_PORT.
Referenced by ADC1_2_IRQHandler(), ADC_Isr(), CAN1_RX0_ISR(), CAN2_RX0_ISR(), DataAnalyze(), EINT1_IRQHandler(), Eint1_Isr(), main(), RTC_Init(), and vTaskUsartTest().
APM_MINI_LEDToggle()
void APM_MINI_LEDToggle (Led_TypeDef Led)
Toggles the selected LED.
Parameters
Led Specifies the Led to be configured. This parameter can be one of following parameters:
LED2
LED3
Return values
None
Definition at line 148 of file Board_APM32F103_MINI.c.
References GPIO_PIN, GPIO_PORT, and GPIO_T::ODATA.
Referenced by APM_MINI_PB1_Isr(), APM_MINI_PB2_Isr(), EINT0_IRQHandler(), EINT1_IRQHandler(), main(), RTC_IRQHandler(), SysTick_Handler(), USART1_Isr(), USART2_Isr(), and vTaskLedToggle().
APM_MINI_PBGetState()
uint32_t APM_MINI_PBGetState (Button_TypeDef Button)
Returns the selected Button state.
Parameters
Button Specifies the Button to be configured. This parameter can be one of following parameters:
BUTTON_KEY1: Key1 Push Button
BUTTON_KEY2: Key2 Push Button
Return values
The Button GPIO pin value.
Definition at line 208 of file Board_APM32F103_MINI.c.
References BUTTON_PIN, BUTTON_PORT, and GPIO_ReadInputBit().
Referenced by main(), and USBD_HID_ReadKey().
APM_MINI_PBInit()
void APM_MINI_PBInit (Button_TypeDef Button, ButtonMode_TypeDef Button_Mode)
Configures Button GPIO and EINT Line.
Parameters
Button Specifies the Button to be configured. This parameter can be one of following parameters:
BUTTON_KEY1: Key1 Push Button
BUTTON_KEY2: Key2 Push Button
Button_Mode Specifies Button mode. This parameter can be one of following parameters:
BUTTON_MODE_GPIO: Button will be used as simple IO
BUTTON_MODE_EINT: Button will be connected to EINT line with interrupt generation capability
Return values
None
Definition at line 168 of file Board_APM32F103_MINI.c.
References BUTTON_CLK, BUTTON_EINT_LINE, BUTTON_IRQn, BUTTON_MODE_EINT, BUTTON_PIN, BUTTON_PIN_SOURCE, BUTTON_PORT, BUTTON_PORT_SOURCE, EINT_Config(), EINT_MODE_INTERRUPT, EINT_TRIGGER_FALLING, ENABLE, GPIO_Config(), GPIO_ConfigEINTLine(), GPIO_MODE_IN_PU, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, GPIO_Config_T::mode, NVIC_EnableIRQRequest(), GPIO_Config_T::pin, RCM_APB2_PERIPH_AFIO, RCM_EnableAPB2PeriphClock(), and EINT_Config_T::trigger.
Referenced by main(), and USBD_HID_GPIOInit().
Delay_Init()
void Delay_Init (void)
Update SystemCoreClock variable according to Clock Register Values The SystemCoreClock variable contains the core clock (HCLK)
Parameters
None
Return values
None
Definition at line 64 of file bsp_delay.c.
References SystemCoreClockUpdate().
Referenced by main().
Delay_ms()
void Delay_ms (__IO u32 nms)
Configures Delay ms.
Parameters
nms Specifies the delay to be configured. This parameter can be one of following parameters:
nms
Return values
None
Definition at line 79 of file bsp_delay.c.
References cntMs, and SystemCoreClock.
Referenced by AT24CXX_WriteOneByte(), and main().
Delay_us()
void Delay_us (__IO u32 nus)
Configures Delay us.
Parameters
nus Specifies the delay to be configured. This parameter can be one of following parameters:
nus
Return values
None
Definition at line 97 of file bsp_delay.c.
References cntUs, and SystemCoreClock.
Referenced by IIC_Ack(), IIC_NAck(), IIC_Read_Byte(), IIC_Send_Byte(), IIC_Start(), IIC_Stop(), and IIC_Wait_Ack().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU