APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device | USB OTG Library » Core Host » Class » MSC
Typedefs
typedef void(* MSC_Handler_T) (void)
Functions
void USBD_MSC_ClassHandler (USBD_DevReqData_T *reqData)
handler Class
void USBH_MSC_ClassInitHandler (void)
USB host MSC configuration.
void USBH_MSC_ClassDeInitHandler (void)
USB host MSC Class Reset.
void USBH_MSC_ClassReqHandler (void)
USB host MSC Class reguest handler.
void USBH_MSC_CoreHandler (void)
USB host MSC handler.
Detailed Description
Typedef Documentation
MSC_Handler_T
typedef void(* MSC_Handler_T) (void)
Definition at line 179 of file usbh_class_msc.h.
Function Documentation
USBD_MSC_ClassHandler()
void USBD_MSC_ClassHandler (USBD_DevReqData_T * reqData)
handler Class
USB MSC Class request handler.
Parameters
reqData USB device request data
Return values
None
Reset
Definition at line 66 of file USB_OTG_Lib/Core_Device/Class/src/usbd_class_msc.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, BOT_GET_MAX_LUN, BOT_RESET, USBD_DevReqData_T::bRequest, USBD_DevReqData_T::byte, USBD_REQ_TYPE_T::dir, USBD_DevReqData_T::domain, NULL, STORAGE_MAX_LUN, USB_EP_0, USB_OTG_SetStall(), USBD_CtrlInData(), USBD_EP_0, USBD_EP_STATUS_STALL, USBD_MSC_BOT_Reset(), USBD_SetEPTxRxStatus(), USBD_DevReqData_T::wLength, and USBD_DevReqData_T::wValue.
Referenced by MSC_Init(), and USBD_MSC_Init().
USBH_MSC_ClassDeInitHandler()
void USBH_MSC_ClassDeInitHandler (void)
USB host MSC Class Reset.
Parameters
None
Return values
None
Definition at line 171 of file usbh_class_msc.c.
References USBH_MSC_StorageInfo_T::blockSize, USBH_MSC_StorageInfo_T::capacity, USBH_MSC_Info_T::curClassReqState, USBH_MSC_Info_T::curMSCState, USBH_MSC_Info_T::errorCnt, g_MSCInfo, USBH_MSC_StorageInfo_T::maxLun, USBH_MSC_Info_T::preClassReqState, USBH_MSC_Info_T::preMSCState, USBH_MSC_StorageInfo_T::sectorSize, USBH_MSC_Info_T::stallCnt, USBH_MSC_Info_T::storageInfo, USBH_MSC_REQ_GET_MAX_LUN, and USBH_MSC_RESET_BOT.
Referenced by USBH_MSC_Init().
USBH_MSC_ClassInitHandler()
void USBH_MSC_ClassInitHandler (void)
USB host MSC configuration.
Parameters
None
Return values
None
Definition at line 105 of file usbh_class_msc.c.
References USBH_MSC_StorageInfo_T::blockSize, USBH_Info_T::devAddress, USB_UserCallBack_T::deviceNotSupportedHandler, g_BOTInfo, g_MSCInfo, g_usbHost, g_userCallback, USBH_MSC_StorageInfo_T::maxLun, USBH_MSC_StorageInfo_T::sectorSize, USBH_MSC_Info_T::stallCnt, USBH_MSC_Info_T::storageInfo, USB_EP_TYPE_BULK, USBH_CH_AllocChannel(), USBH_CH_OpenChannel(), USBH_CLASS_MSC, USBH_ConfigClassCoreState, USBH_ConfigHostState, USBH_HOST_CLASS, USBH_MSC_PROTOCOL_BBB, USBH_MSC_RESET_BOT, USBH_ReadConfigurationItfNum, USBH_ReadEndpointAddress, USBH_ReadEndpointMPS, USBH_ReadInterfaceClass, USBH_ReadInterfaceEpNum, and USBH_ReadInterfaceProtocol.
Referenced by USBH_MSC_Init().
USBH_MSC_ClassReqHandler()
void USBH_MSC_ClassReqHandler (void)
USB host MSC Class reguest handler.
Parameters
None
Return values
None
Definition at line 195 of file usbh_class_msc.c.
References USBH_MSC_Info_T::curClassReqState, g_MSCInfo, USBH_MSC_REQ_BOT_RESET, USBH_MSC_REQ_CTRL_ERROR, and USBH_MSC_REQ_GET_MAX_LUN.
Referenced by USBH_MSC_Init().
USBH_MSC_CoreHandler()
void USBH_MSC_CoreHandler (void)
USB host MSC handler.
Parameters
None
Return values
None
Definition at line 220 of file usbh_class_msc.c.
References USBH_MSC_Info_T::curMSCState, g_MSCInfo, and MSC_Handler.
Referenced by USBH_MSC_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU