APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » SPI Driver
Functions
void SPI_I2S_Reset (SPI_T *spi)
Reset the specified SPIx peripheral.
void SPI_Config (SPI_T *spi, SPI_Config_T *spiConfig)
Configures the SPI peripheral according to the specified parameters in the spiConfig.
void I2S_Config (SPI_T *spi, I2S_Config_T *i2sConfig)
Configures the I2S peripheral according to the specified parameters in the spiConfig.
void SPI_ConfigStructInit (SPI_Config_T *spiConfig)
Fills each SPI_Config_T member with its default value.
void I2S_ConfigStructInit (I2S_Config_T *i2sConfig)
Fills each I2S_Config_T member with its default value.
void SPI_Enable (SPI_T *spi)
Enable the specified SPI peripheral.
void SPI_Disable (SPI_T *spi)
Disable the specified SPI peripheral.
void I2S_Enable (SPI_T *spi)
Enable the specified I2S peripheral.
void I2S_Disable (SPI_T *spi)
Disable the specified I2S peripheral.
void SPI_I2S_TxData (SPI_T *spi, uint16_t data)
Transmit a Data through the SPIx/I2Sx peripheral.
uint16_t SPI_I2S_RxData (SPI_T *spi)
Return the most recent received data by the SPIx/I2Sx peripheral.
void SPI_SetSoftwareNSS (SPI_T *spi)
Set the SPI NSS internal by Software.
void SPI_ResetSoftwareNSS (SPI_T *spi)
Reset the SPI NSS internal by Software.
void SPI_EnableSSOutput (SPI_T *spi)
Enable the specified SPI SS output.
void SPI_DisableSSOutput (SPI_T *spi)
Disable the specified SPI SS output.
void SPI_ConfigDataSize (SPI_T *spi, SPI_DATA_LENGTH_T length)
Configures the specified SPI data size.
void SPI_I2S_EnableDMA (SPI_T *spi, SPI_I2S_DMA_REQ_T dmaReq)
Enable the SPIx/I2Sx DMA interface.
void SPI_I2S_DisableDMA (SPI_T *spi, SPI_I2S_DMA_REQ_T dmaReq)
Disable the SPIx/I2Sx DMA interface.
void SPI_TxCRC (SPI_T *spi)
Transmit CRC value.
void SPI_EnableCRC (SPI_T *spi)
Enable the specified SPI CRC value calculation of the transferred bytes.
void SPI_DisableCRC (SPI_T *spi)
Disable the specified SPI CRC value calculation of the transferred bytes.
uint16_t SPI_ReadTxCRC (SPI_T *spi)
Read the specified SPI transmit CRC register value.
uint16_t SPI_ReadRxCRC (SPI_T *spi)
Read the specified SPI receive CRC register value.
uint16_t SPI_ReadCRCPolynomial (SPI_T *spi)
Read the specified SPI CRC Polynomial register value.
void SPI_ConfigBiDirectionalLine (SPI_T *spi, SPI_DIRECTION_SELECT_T direction)
Configures the specified SPI data transfer direction.
void SPI_I2S_EnableInterrupt (SPI_T *spi, SPI_I2S_INT_T interrupt)
Enable the specified SPI/I2S interrupts.
void SPI_I2S_DisableInterrupt (SPI_T *spi, SPI_I2S_INT_T interrupt)
Disable the specified SPI/I2S interrupts.
uint8_t SPI_I2S_ReadStatusFlag (SPI_T *spi, SPI_FLAG_T flag)
Check whether the specified SPI/I2S flag is set or not.
void SPI_I2S_ClearStatusFlag (SPI_T *spi, SPI_FLAG_T flag)
Clear the SPIx CRC Error flag.
uint8_t SPI_I2S_ReadIntFlag (SPI_T *spi, SPI_I2S_INT_T flag)
Check whether the specified SPI/I2S interrupt has occurred or not.
void SPI_I2S_ClearIntFlag (SPI_T *spi, SPI_I2S_INT_T flag)
Clear the SPIx CRC Error interrupt flag.
Detailed Description
Function Documentation
I2S_Config()
void I2S_Config (SPI_T * spi, I2S_Config_T * i2sConfig)
Configures the I2S peripheral according to the specified parameters in the spiConfig.
Parameters
spi The SPIx can be 2,3
i2sConfig pointer to a I2S_Config_T structure
Return values
None
Definition at line 96 of file apm32f10x_spi.c.
References I2S_Config_T::audioDiv, BIT_SET, I2S_AUDIO_DIV_DEFAULT, I2S_DATA_LENGHT_16B, I2S_MCLK_OUTPUT_ENABLE, SPI_T::I2SCFG, SPI_T::I2SCFG_B, SPI_T::I2SPSC, SPI_T::I2SPSC_B, I2S_Config_T::length, I2S_Config_T::MCLKOutput, I2S_Config_T::mode, SPI_T::MODESEL, SPI_T::ODDPSC, I2S_Config_T::polarity, RCM_ReadSYSCLKFreq(), and I2S_Config_T::standard.
Referenced by main().
I2S_ConfigStructInit()
void I2S_ConfigStructInit (I2S_Config_T * i2sConfig)
Fills each I2S_Config_T member with its default value.
Parameters
i2sConfig pointer to a I2S_Config_T structure
Return values
None
Definition at line 184 of file apm32f10x_spi.c.
References I2S_Config_T::audioDiv, I2S_AUDIO_DIV_DEFAULT, I2S_CLKPOL_LOW, I2S_DATA_LENGHT_16B, I2S_MCLK_OUTPUT_DISABLE, I2S_MODE_SLAVE_TX, I2S_STANDARD_PHILLIPS, I2S_Config_T::length, I2S_Config_T::MCLKOutput, I2S_Config_T::mode, I2S_Config_T::polarity, and I2S_Config_T::standard.
I2S_Disable()
void I2S_Disable (SPI_T * spi)
Disable the specified I2S peripheral.
Parameters
spi The I2S can be SPI2,SPI3
Return values
None
Definition at line 236 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::I2SCFG_B, and SPI_T::I2SEN.
I2S_Enable()
void I2S_Enable (SPI_T * spi)
Enable the specified I2S peripheral.
Parameters
spi The I2S can be SPI2,SPI3
Return values
None
Definition at line 224 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::I2SCFG_B, and SPI_T::I2SEN.
Referenced by main().
SPI_Config()
void SPI_Config (SPI_T * spi, SPI_Config_T * spiConfig)
Configures the SPI peripheral according to the specified parameters in the spiConfig.
Parameters
spi The SPIx can be 1,2,3
spiConfig pointer to a SPI_Config_T structure
Return values
None
Definition at line 77 of file apm32f10x_spi.c.
References SPI_Config_T::baudrateDiv, SPI_T::CRCPOLY, SPI_Config_T::crcPolynomial, SPI_T::CTRL1, SPI_Config_T::direction, SPI_Config_T::firstBit, SPI_Config_T::length, SPI_Config_T::mode, SPI_Config_T::nss, SPI_Config_T::phase, and SPI_Config_T::polarity.
Referenced by SPI_FullDuplex_Init().
SPI_ConfigBiDirectionalLine()
void SPI_ConfigBiDirectionalLine (SPI_T * spi, SPI_DIRECTION_SELECT_T direction)
Configures the specified SPI data transfer direction.
Parameters
spi The SPIx can be 1,2,3
direction Select the SPI data transfer direction The parameter can be one of following values:
SPI_DIRECTION_RX: Selects Rx receive direction
SPI_DIRECTION_TX: Selects Tx transmission direction
Return values
None
Definition at line 463 of file apm32f10x_spi.c.
References SPI_T::CTRL1, SPI_DIRECTION_RX, and SPI_DIRECTION_TX.
SPI_ConfigDataSize()
void SPI_ConfigDataSize (SPI_T * spi, SPI_DATA_LENGTH_T length)
Configures the specified SPI data size.
Parameters
spi The SPIx can be 1,2,3
length specifies the SPI data size. This parameter can be one of the following values:
SPI_DATA_LENGTH_16B: Set data frame format to 16bit
SPI_DATA_LENGTH_8B : Set data frame format to 8bit
Return values
None
Definition at line 375 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CTRL1, SPI_T::CTRL1_B, and SPI_T::DFLSEL.
Referenced by SPI_FullDuplex_Init().
SPI_ConfigStructInit()
void SPI_ConfigStructInit (SPI_Config_T * spiConfig)
Fills each SPI_Config_T member with its default value.
Parameters
spiConfig pointer to a SPI_Config_T structure
Return values
None
Definition at line 164 of file apm32f10x_spi.c.
References SPI_Config_T::baudrateDiv, SPI_Config_T::crcPolynomial, SPI_Config_T::direction, SPI_Config_T::firstBit, SPI_Config_T::length, SPI_Config_T::mode, SPI_Config_T::nss, SPI_Config_T::phase, SPI_Config_T::polarity, SPI_BAUDRATE_DIV_2, SPI_CLKPHA_1EDGE, SPI_CLKPOL_LOW, SPI_DATA_LENGTH_8B, SPI_DIRECTION_2LINES_FULLDUPLEX, SPI_FIRSTBIT_MSB, SPI_MODE_SLAVE, and SPI_NSS_HARD.
Referenced by SPI_FullDuplex_Init().
SPI_Disable()
void SPI_Disable (SPI_T * spi)
Disable the specified SPI peripheral.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 212 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CTRL1_B, and SPI_T::SPIEN.
SPI_DisableCRC()
void SPI_DisableCRC (SPI_T * spi)
Disable the specified SPI CRC value calculation of the transferred bytes.
Parameters
spi The SPIx can be 1,2,3
Definition at line 411 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CRCEN, and SPI_T::CTRL1_B.
SPI_DisableSSOutput()
void SPI_DisableSSOutput (SPI_T * spi)
Disable the specified SPI SS output.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 358 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CTRL2_B, and SPI_T::SSOEN.
SPI_Enable()
void SPI_Enable (SPI_T * spi)
Enable the specified SPI peripheral.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 200 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::CTRL1_B, and SPI_T::SPIEN.
Referenced by SPI_FullDuplex_Init().
SPI_EnableCRC()
void SPI_EnableCRC (SPI_T * spi)
Enable the specified SPI CRC value calculation of the transferred bytes.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 400 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::CRCEN, and SPI_T::CTRL1_B.
SPI_EnableSSOutput()
void SPI_EnableSSOutput (SPI_T * spi)
Enable the specified SPI SS output.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 346 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::CTRL2_B, and SPI_T::SSOEN.
SPI_I2S_ClearIntFlag()
void SPI_I2S_ClearIntFlag (SPI_T * spi, SPI_I2S_INT_T flag)
Clear the SPIx CRC Error interrupt flag.
Parameters
spi The SPIx can be 1,2,3
flag only Clear SPI_INT_CRCE(CRC Error interrupt flag)
Return values
None
Note
1)SPI_I2S_INT_OVR: (OverRun interrupt error) flag is cleared by software sequence: a read operation to SPI_DATA register (SPI_I2S_RxData()) followed by a read operation to SPI_STS register (SPI_I2S_ReadIntFlag()). 2)I2S_INT_UDR: (UnderRun interrupt error) flag is cleared: a read operation to SPI_STS register (SPI_I2S_ReadIntFlag()). 3)SPI_INT_ME: (Mode interrupt Fault) flag is cleared by software sequence: a read/write operation to SPI_STS register (SPI_I2S_ReadIntFlag()) followed by a write operation to SPI_CTRL1 register (SPI_Enable()).
Definition at line 612 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CRCEFLG, and SPI_T::STS_B.
SPI_I2S_ClearStatusFlag()
void SPI_I2S_ClearStatusFlag (SPI_T * spi, SPI_FLAG_T flag)
Clear the SPIx CRC Error flag.
Parameters
spi The SPIx can be 1,2,3
flag only Clear SPI_FLAG_CRCE(CRC Error flag)
Return values
None
Note
1)SPI_FLAG_OVR: (OverRun error) flag is cleared by software sequence: a read operation to SPI_DATA register (SPI_I2S_RxData()) followed by a read operation to SPI_STS register (SPI_I2S_ReadStatusFlag()). 2)I2S_FLAG_UDR: (UnderRun error) flag is cleared: a read operation to SPI_STS register (SPI_I2S_ReadStatusFlag()). 3)SPI_FLAG_ME: (Mode Fault) flag is cleared by software sequence: a read/write operation to SPI_STS register (SPI_I2S_ReadStatusFlag()) followed by a write operation to SPI_CTRL1 register (SPI_Enable()).
Definition at line 557 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CRCEFLG, and SPI_T::STS_B.
SPI_I2S_DisableDMA()
void SPI_I2S_DisableDMA (SPI_T * spi, SPI_I2S_DMA_REQ_T dmaReq)
Disable the SPIx/I2Sx DMA interface.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
dmaReq specifies the SPI/I2S DMA transfer request The parameter can be one of following values:
SPI_I2S_DMA_REQ_TX: Tx buffer DMA transfer request
SPI_I2S_DMA_REQ_RX: Rx buffer DMA transfer request
Return values
None
Definition at line 275 of file apm32f10x_spi.c.
References SPI_T::CTRL2_B, DISABLE, SPI_T::RXDEN, SPI_I2S_DMA_REQ_TX, and SPI_T::TXDEN.
SPI_I2S_DisableInterrupt()
void SPI_I2S_DisableInterrupt (SPI_T * spi, SPI_I2S_INT_T interrupt)
Disable the specified SPI/I2S interrupts.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
interrupt specifies the TMR interrupts sources The parameter can be one of following values:
SPI_I2S_INT_TXBE: Tx buffer empty interrupt
SPI_I2S_INT_RXBNE: Rx buffer not empty interrupt
SPI_I2S_INT_ERR: Error interrupt
Return values
None
Definition at line 504 of file apm32f10x_spi.c.
References SPI_T::CTRL2.
Referenced by SPI3_IRQHandler().
SPI_I2S_EnableDMA()
void SPI_I2S_EnableDMA (SPI_T * spi, SPI_I2S_DMA_REQ_T dmaReq)
Enable the SPIx/I2Sx DMA interface.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
dmaReq specifies the SPI/I2S DMA transfer request The parameter can be one of following values:
SPI_I2S_DMA_REQ_TX: Tx buffer DMA transfer request
SPI_I2S_DMA_REQ_RX: Rx buffer DMA transfer request
Return values
None
Definition at line 252 of file apm32f10x_spi.c.
References SPI_T::CTRL2_B, ENABLE, SPI_T::RXDEN, SPI_I2S_DMA_REQ_TX, and SPI_T::TXDEN.
SPI_I2S_EnableInterrupt()
void SPI_I2S_EnableInterrupt (SPI_T * spi, SPI_I2S_INT_T interrupt)
Enable the specified SPI/I2S interrupts.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
interrupt specifies the TMR interrupts sources The parameter can be one of following values:
SPI_I2S_INT_TXBE: Tx buffer empty interrupt
SPI_I2S_INT_RXBNE: Rx buffer not empty interrupt
SPI_I2S_INT_ERR: Error interrupt
Return values
None
Definition at line 487 of file apm32f10x_spi.c.
References SPI_T::CTRL2.
Referenced by main().
SPI_I2S_ReadIntFlag()
uint8_t SPI_I2S_ReadIntFlag (SPI_T * spi, SPI_I2S_INT_T flag)
Check whether the specified SPI/I2S interrupt has occurred or not.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
flag specifies the SPI/I2S interrupt flag to check. The parameter can be one of following values:
SPI_I2S_INT_RXBNE: Receive buffer not empty interrupt flag
SPI_I2S_INT_TXBE: Transmit buffer empty interrupt flag
SPI_I2S_INT_OVR: Overrun interrupt flag
SPI_INT_CRCE: CRC Error interrupt flag
SPI_INT_ME: Mode Error interrupt flag
I2S_INT_UDR: Underrun Error interrupt flag
Return values
SET or RESET
Definition at line 578 of file apm32f10x_spi.c.
References SPI_T::CTRL2, intStatus, RESET, SET, and SPI_T::STS.
Referenced by SPI2_IRQHandler(), and SPI3_IRQHandler().
SPI_I2S_ReadStatusFlag()
uint8_t SPI_I2S_ReadStatusFlag (SPI_T * spi, SPI_FLAG_T flag)
Check whether the specified SPI/I2S flag is set or not.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
flag specifies the SPI/I2S flag to check The parameter can be one of following values:
SPI_FLAG_RXBNE: Receive buffer not empty flag
SPI_FLAG_TXBE: Transmit buffer empty flag
I2S_FLAG_SCHDIR: Side Channel flag
I2S_FLAG_UDR: Underrun Error flag
SPI_FLAG_CRCE: CRC Error flag
SPI_FLAG_ME: Mode Error flag
SPI_FLAG_OVR: Overrun flag
SPI_FLAG_BSY: Busy flag
Return values
SET or RESET
Definition at line 527 of file apm32f10x_spi.c.
References RESET, SET, and SPI_T::STS.
Referenced by main(), and SPI_WriteByte().
SPI_I2S_Reset()
void SPI_I2S_Reset (SPI_T * spi)
Reset the specified SPIx peripheral.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 49 of file apm32f10x_spi.c.
References RCM_APB1_PERIPH_SPI2, RCM_APB1_PERIPH_SPI3, RCM_APB2_PERIPH_SPI1, RCM_DisableAPB1PeriphReset(), RCM_DisableAPB2PeriphReset(), RCM_EnableAPB1PeriphReset(), RCM_EnableAPB2PeriphReset(), SPI1, SPI2, and SPI3.
Referenced by main().
SPI_I2S_RxData()
uint16_t SPI_I2S_RxData (SPI_T * spi)
Return the most recent received data by the SPIx/I2Sx peripheral.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
Return values
data :The value of the received data
None
Definition at line 310 of file apm32f10x_spi.c.
References SPI_T::DATA.
Referenced by main(), and SPI2_IRQHandler().
SPI_I2S_TxData()
void SPI_I2S_TxData (SPI_T * spi, uint16_t data)
Transmit a Data through the SPIx/I2Sx peripheral.
Parameters
spi The SPIx can be 1,2,3, When the I2S can be 2,3
data Data to be transmitted
Return values
None
Definition at line 296 of file apm32f10x_spi.c.
References data, and SPI_T::DATA.
Referenced by SPI3_IRQHandler(), and SPI_WriteByte().
SPI_ReadCRCPolynomial()
uint16_t SPI_ReadCRCPolynomial (SPI_T * spi)
Read the specified SPI CRC Polynomial register value.
Parameters
spi The SPIx can be 1,2,3
Return values
The SPI CRC Polynomial register value
Definition at line 447 of file apm32f10x_spi.c.
References SPI_T::CRCPOLY, and SPI_T::CRCPOLY_B.
SPI_ReadRxCRC()
uint16_t SPI_ReadRxCRC (SPI_T * spi)
Read the specified SPI receive CRC register value.
Parameters
spi The SPIx can be 1,2,3
Return values
The SPI receive CRC register value
Definition at line 435 of file apm32f10x_spi.c.
References SPI_T::RXCRC, and SPI_T::RXCRC_B.
SPI_ReadTxCRC()
uint16_t SPI_ReadTxCRC (SPI_T * spi)
Read the specified SPI transmit CRC register value.
Parameters
spi The SPIx can be 1,2,3
Return values
The SPI transmit CRC register value
Definition at line 423 of file apm32f10x_spi.c.
References SPI_T::TXCRC, and SPI_T::TXCRC_B.
SPI_ResetSoftwareNSS()
void SPI_ResetSoftwareNSS (SPI_T * spi)
Reset the SPI NSS internal by Software.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 334 of file apm32f10x_spi.c.
References BIT_RESET, SPI_T::CTRL1_B, and SPI_T::ISSEL.
SPI_SetSoftwareNSS()
void SPI_SetSoftwareNSS (SPI_T * spi)
Set the SPI NSS internal by Software.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 322 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::CTRL1_B, and SPI_T::ISSEL.
SPI_TxCRC()
void SPI_TxCRC (SPI_T * spi)
Transmit CRC value.
Parameters
spi The SPIx can be 1,2,3
Return values
None
Definition at line 388 of file apm32f10x_spi.c.
References BIT_SET, SPI_T::CRCNXT, and SPI_T::CTRL1_B.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU