APM32F10x_SDK: Fuctions
Fuctions
Standard Peripheral Library » USBD Driver
Macros
#define USBD_SetRegCTRL(val) (USBD->CTRL = val)
Set CTRL register.
#define USBD_SetRegINTSTS(val) (USBD->INTSTS = val)
Set INTSTS register.
#define USBD_SetForceReset() (USBD->CTRL_B.FORRST = BIT_SET)
Set force reset.
#define USBD_ResetForceReset() (USBD->CTRL_B.FORRST = BIT_RESET)
Reset force reset.
#define USBD_SetPowerDown() (USBD->CTRL_B.PWRDOWN = BIT_SET)
Set power down.
#define USBD_ResetPowerDown() (USBD->CTRL_B.PWRDOWN = BIT_RESET)
Reset power down.
#define USBD_SetLowerPowerMode() (USBD->CTRL_B.LPWREN = BIT_SET)
Set low power mode.
#define USBD_ResetLowerPowerMode() (USBD->CTRL_B.LPWREN = BIT_RESET)
Ret low power mode.
#define USBD_SetForceSuspend() (USBD->CTRL_B.FORSUS = BIT_SET)
Set force suspend.
#define USBD_ResetForceSuspend() (USBD->CTRL_B.FORSUS = BIT_RESET)
Reset force suspend.
#define USBD_ReadForceSuspend() (USBD->CTRL_B.FORSUS)
Read force suspend status.
#define USBD_SetResume() (USBD->CTRL_B.WUPREQ = BIT_SET)
Set resume.
#define USBD_ResetResume() (USBD->CTRL_B.WUPREQ = BIT_RESET)
Reset resume.
#define USBD_EnableInterrupt(int) (USBD->CTRL |= int)
Enable interrupt.
#define USBD_DisableInterrupt(int) (USBD->CTRL &= (uint32_t)~int)
Disable interrupt.
#define USBD_ReadIntFlag(int) (USBD->INTSTS & int)
Read the specified interrupt flag status.
#define USBD_ClearIntFlag(int) (USBD->INTSTS &= (uint32_t)~int)
Clear the specified interrupt flag status.
#define USBD_ReadDir() (USBD->INTSTS_B.DOT)
Read DOT field value in INTSTS rigister.
#define USBD_ReadEP() ((USBD_EP_T)(USBD->INTSTS_B.EPID))
Read EPID field value in INTSTS rigister.
#define USBD_ReadEPType(ep) (USBD->EP[ep].EP_B.TYPE)
Read EP type.
#define USBD_ReadEPTxStatus(ep) ((USBD_EP_STATUS_T)(USBD->EP[ep].EP_B.TXSTS))
Read EP Tx status.
#define USBD_ReadEPRxStatus(ep) ((USBD_EP_STATUS_T)(USBD->EP[ep].EP_B.RXSTS))
Read EP Rx status.
#define USBD_ReadEPSetup(ep) (USBD->EP[ep].EP_B.SETUP)
Read SETUP field value in EP register.
#define USBD_SetBufferTable(tab) (USBD->BUFFTB_B.BUFFTB = tab)
Set buffer table value.
#define USBD_SetDeviceAddr(addr) (USBD->ADDR_B.ADDR = addr)
Set device address.
#define USBD_ReadEPRxFlag(ep) (USBD->EP[ep].EP_B.CTFR)
Read CTFR field value in EP register.
#define USBD_ReadEPTxFlag(ep) (USBD->EP[ep].EP_B.CTFT)
Read CTFT field value in EP register.
#define USBD_Enable() (USBD->ADDR_B.USBDEN = BIT_SET)
Enable USBD peripheral.
#define USBD_Disable() (USBD->ADDR_B.USBDEN = BIT_RESET)
Disable USBD peripheral.
#define USBD2_Enable() (USBD->SWITCH = BIT_SET)
Enable USBD2 peripheral.
#define USBD2_Disable() (USBD->SWITCH = BIT_RESET)
Disable USBD2 peripheral.
#define USBD_ReadRDPS() (USBD->FRANUM_B.RXDPSTS)
Read RXDPSTS field value in FRANUM register.
#define USBD_ReadRDMS() (USBD->FRANUM_B.RXDMSTS)
Read RXDMSTS field value in FRANUM register.
#define USBD_ReadLOCK() (USBD->FRANUM_B.LOCK)
Read LOCK field value in FRANUM register.
#define USBD_ReadLSOF() (USBD->FRANUM_B.LSOFNUM)
Read LSOFNUM field value in FRANUM register.
#define USBD_ReadFRANUM() (USBD->FRANUM_B.FRANUM)
Read FRANUM field value in FRANUM register.
#define USBD_ReadEPTxAddrPointer(ep) (uint16_t *)((USBD->BUFFTB + ep * 8) * 2 + USBD_PMA_ADDR)
Read EP Tx address pointer.
#define USBD_ReadEPTxCntPointer(ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 2) * 2 + USBD_PMA_ADDR)
Read EP Tx count pointer.
#define USBD_ReadEPRxAddrPointer(ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 4) * 2 + USBD_PMA_ADDR)
Read EP Rx address pointer.
#define USBD_ReadEPRxCntPointer(ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 6) * 2 + USBD_PMA_ADDR)
Read EP Rx count pointer.
#define USBD_SetEPTxAddr(ep, addr) (*USBD_ReadEPTxAddrPointer(ep) = (addr >> 1) << 1)
Set EP Tx addr.
#define USBD_SetEPRxAddr(ep, addr) (*USBD_ReadEPRxAddrPointer(ep) = (addr >> 1) << 1)
Set EP Rx addr.
#define USBD_ReadEPTxAddr(ep) ((uint16_t)*USBD_ReadEPTxAddrPointer(ep))
Read EP Tx addr.
#define USBD_ReadEPRxAddr(ep) ((uint16_t)*USBD_ReadEPRxAddrPointer(ep))
Read EP Rx addr.
#define USBD_ReadEPTxBufferPointer(ep) (uint32_t *)(((uint32_t)USBD_ReadEPTxAddr(ep) << 1) + USBD_PMA_ADDR)
Read EP Tx Buffer Pointer.
#define USBD_ReadEPRxBufferPointer(ep) (uint32_t *)(((uint32_t)USBD_ReadEPRxAddr(ep) << 1) + USBD_PMA_ADDR)
Read EP Rx Buffer Pointer.
#define USBD_SetEPTxCnt(ep, cnt) (*USBD_ReadEPTxCntPointer(ep) = cnt)
Set EP Tx Count.
#define USBD_ReadEPTxCnt(ep) ((uint16_t)*USBD_ReadEPTxCntPointer(ep) & 0x3ff)
Read EP Tx count.
#define USBD_ReadEPRxCnt(ep) ((uint16_t)*USBD_ReadEPRxCntPointer(ep) & 0x3ff)
Read EP Rx count.
Functions
void USBD_SetEPType (uint8_t ep, USBD_REG_EP_TYPE_T type)
Set Endpoint type.
void USBD_SetEPKind (uint8_t ep)
Set EP kind.
void USBD_ResetEPKind (uint8_t ep)
Reset EP kind.
void USBD_ResetEPRxFlag (uint8_t ep)
Reset EP CTFR bit.
void USBD_ResetEPTxFlag (uint8_t ep)
Reset EP CTFT bit.
void USBD_ToggleTx (uint8_t ep)
Toggle Tx DTOG.
void USBD_ToggleRx (uint8_t ep)
Toggle Rx DTOG.
void USBD_ResetTxToggle (uint8_t ep)
Reset Toggle Tx DTOG.
void USBD_ResetRxToggle (uint8_t ep)
Reset Toggle Rx DTOG.
void USBD_SetEpAddr (uint8_t ep, uint8_t addr)
Set EP address.
void USBD_SetEPTxStatus (uint8_t ep, USBD_EP_STATUS_T status)
Set EP Tx status.
void USBD_SetEPRxStatus (uint8_t ep, USBD_EP_STATUS_T status)
Set EP Rx status.
void USBD_SetEPTxRxStatus (uint8_t ep, USBD_EP_STATUS_T txStatus, USBD_EP_STATUS_T rxStatus)
Set EP Tx and Rx status.
void USBD_SetEPRxCnt (uint8_t ep, uint32_t cnt)
Set EP Rx Count.
void USBD_WriteDataToEP (uint8_t ep, uint8_t *wBuf, uint32_t wLen)
Write a buffer of data to a selected endpoint.
void USBD_ReadDataFromEP (uint8_t ep, uint8_t *rBuf, uint32_t rLen)
Read a buffer of data to a selected endpoint.
Detailed Description
Macro Definition Documentation
USBD2_Disable
#define USBD2_Disable () (USBD->SWITCH = BIT_RESET)
Disable USBD2 peripheral.
Parameters
None
Return values
None
Definition at line 434 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD2_Enable
#define USBD2_Enable () (USBD->SWITCH = BIT_SET)
Enable USBD2 peripheral.
Parameters
None
Return values
None
Definition at line 425 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ClearIntFlag
#define USBD_ClearIntFlag (int) (USBD->INTSTS &= (uint32_t)~int)
Clear the specified interrupt flag status.
Parameters
int Interrupt source
Return values
None
Definition at line 308 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_Disable
#define USBD_Disable () (USBD->ADDR_B.USBDEN = BIT_RESET)
Disable USBD peripheral.
Parameters
None
Return values
None
Definition at line 416 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_DisableInterrupt
#define USBD_DisableInterrupt (int) (USBD->CTRL &= (uint32_t)~int)
Disable interrupt.
Parameters
int Interrupt source
Return values
None
Definition at line 290 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_Enable
#define USBD_Enable () (USBD->ADDR_B.USBDEN = BIT_SET)
Enable USBD peripheral.
Parameters
None
Return values
None
Definition at line 407 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_EnableInterrupt
#define USBD_EnableInterrupt (int) (USBD->CTRL |= int)
Enable interrupt.
Parameters
int Interrupt source
Return values
None
Definition at line 281 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadDir
#define USBD_ReadDir () (USBD->INTSTS_B.DOT)
Read DOT field value in INTSTS rigister.
Parameters
None
Return values
DOT field value
Definition at line 317 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEP
#define USBD_ReadEP () ((USBD_EP_T)(USBD->INTSTS_B.EPID))
Read EPID field value in INTSTS rigister.
Parameters
None
Return values
EPIDfield value
Definition at line 326 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxAddr
#define USBD_ReadEPRxAddr (ep) ((uint16_t)*USBD_ReadEPRxAddrPointer(ep))
Read EP Rx addr.
Parameters
ep EP number
Return values
EP Rx addr
Definition at line 1166 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxAddrPointer
#define USBD_ReadEPRxAddrPointer (ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 4) * 2 + USBD_PMA_ADDR)
Read EP Rx address pointer.
Parameters
ep EP number
Return values
EP Rx address pointer
Definition at line 1117 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxBufferPointer
#define USBD_ReadEPRxBufferPointer (ep) (uint32_t *)(((uint32_t)USBD_ReadEPRxAddr(ep) << 1) + USBD_PMA_ADDR)
Read EP Rx Buffer Pointer.
Parameters
ep EP number
Return values
EP Rx Buffer Pointer
Definition at line 1184 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxCnt
#define USBD_ReadEPRxCnt (ep) ((uint16_t)*USBD_ReadEPRxCntPointer(ep) & 0x3ff)
Read EP Rx count.
Parameters
ep EP number
Return values
EP Rx count
Definition at line 1213 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxCntPointer
#define USBD_ReadEPRxCntPointer (ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 6) * 2 + USBD_PMA_ADDR)
Read EP Rx count pointer.
Parameters
ep EP number
Return values
EP Rx count pointer
Definition at line 1126 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxFlag
#define USBD_ReadEPRxFlag (ep) (USBD->EP[ep].EP_B.CTFR)
Read CTFR field value in EP register.
Parameters
ep Endpoint number
Return values
CTFR field value
Definition at line 389 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPRxStatus
#define USBD_ReadEPRxStatus (ep) ((USBD_EP_STATUS_T)(USBD->EP[ep].EP_B.RXSTS))
Read EP Rx status.
Parameters
ep EP number
Return values
EP Rx status
Definition at line 353 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPSetup
#define USBD_ReadEPSetup (ep) (USBD->EP[ep].EP_B.SETUP)
Read SETUP field value in EP register.
Parameters
ep EP number
Return values
SETUP field value
Definition at line 362 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxAddr
#define USBD_ReadEPTxAddr (ep) ((uint16_t)*USBD_ReadEPTxAddrPointer(ep))
Read EP Tx addr.
Parameters
ep EP number
Return values
EP Tx addr
Definition at line 1157 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxAddrPointer
#define USBD_ReadEPTxAddrPointer (ep) (uint16_t *)((USBD->BUFFTB + ep * 8) * 2 + USBD_PMA_ADDR)
Read EP Tx address pointer.
Parameters
ep EP number
Return values
EP Tx address pointer
Definition at line 1099 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxBufferPointer
#define USBD_ReadEPTxBufferPointer (ep) (uint32_t *)(((uint32_t)USBD_ReadEPTxAddr(ep) << 1) + USBD_PMA_ADDR)
Read EP Tx Buffer Pointer.
Parameters
ep EP number
Return values
EP Tx Buffer Pointer
Definition at line 1175 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxCnt
#define USBD_ReadEPTxCnt (ep) ((uint16_t)*USBD_ReadEPTxCntPointer(ep) & 0x3ff)
Read EP Tx count.
Parameters
ep EP number
Return values
EP Tx count
Definition at line 1204 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxCntPointer
#define USBD_ReadEPTxCntPointer (ep) (uint16_t *)((USBD->BUFFTB + ep * 8 + 2) * 2 + USBD_PMA_ADDR)
Read EP Tx count pointer.
Parameters
ep EP number
Return values
EP Tx count pointer
Definition at line 1108 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxFlag
#define USBD_ReadEPTxFlag (ep) (USBD->EP[ep].EP_B.CTFT)
Read CTFT field value in EP register.
Parameters
ep Endpoint number
Return values
CTFT field value
Definition at line 398 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPTxStatus
#define USBD_ReadEPTxStatus (ep) ((USBD_EP_STATUS_T)(USBD->EP[ep].EP_B.TXSTS))
Read EP Tx status.
Parameters
ep EP number
Return values
EP Tx status
Definition at line 344 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadEPType
#define USBD_ReadEPType (ep) (USBD->EP[ep].EP_B.TYPE)
Read EP type.
Parameters
ep EP number
Return values
EP type
Definition at line 335 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadForceSuspend
#define USBD_ReadForceSuspend () (USBD->CTRL_B.FORSUS)
Read force suspend status.
Parameters
None
Return values
None
Definition at line 254 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadFRANUM
#define USBD_ReadFRANUM () (USBD->FRANUM_B.FRANUM)
Read FRANUM field value in FRANUM register.
Parameters
None
Return values
FRANUM field value APM32F10x_USB
Definition at line 1091 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadIntFlag
#define USBD_ReadIntFlag (int) (USBD->INTSTS & int)
Read the specified interrupt flag status.
Parameters
int Interrupt source
Return values
Flag status.0 or not 0
Definition at line 299 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadLOCK
#define USBD_ReadLOCK () (USBD->FRANUM_B.LOCK)
Read LOCK field value in FRANUM register.
Parameters
None
Return values
LOCK field value
Definition at line 461 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadLSOF
#define USBD_ReadLSOF () (USBD->FRANUM_B.LSOFNUM)
Read LSOFNUM field value in FRANUM register.
Parameters
None
Return values
LSOFNUM field value
Definition at line 470 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadRDMS
#define USBD_ReadRDMS () (USBD->FRANUM_B.RXDMSTS)
Read RXDMSTS field value in FRANUM register.
Parameters
None
Return values
RXDMSTS field value
Definition at line 452 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ReadRDPS
#define USBD_ReadRDPS () (USBD->FRANUM_B.RXDPSTS)
Read RXDPSTS field value in FRANUM register.
Parameters
None
Return values
RXDPSTS field value
Definition at line 443 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ResetForceReset
#define USBD_ResetForceReset () (USBD->CTRL_B.FORRST = BIT_RESET)
Reset force reset.
Parameters
None
Return values
None
Definition at line 191 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ResetForceSuspend
#define USBD_ResetForceSuspend () (USBD->CTRL_B.FORSUS = BIT_RESET)
Reset force suspend.
Parameters
None
Return values
None
Definition at line 245 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ResetLowerPowerMode
#define USBD_ResetLowerPowerMode () (USBD->CTRL_B.LPWREN = BIT_RESET)
Ret low power mode.
Parameters
None
Return values
None
Definition at line 227 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ResetPowerDown
#define USBD_ResetPowerDown () (USBD->CTRL_B.PWRDOWN = BIT_RESET)
Reset power down.
Parameters
None
Return values
None
Definition at line 209 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_ResetResume
#define USBD_ResetResume () (USBD->CTRL_B.WUPREQ = BIT_RESET)
Reset resume.
Parameters
None
Return values
None
Definition at line 272 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetBufferTable
#define USBD_SetBufferTable (tab) (USBD->BUFFTB_B.BUFFTB = tab)
Set buffer table value.
Parameters
tab Buffer table value
Return values
None
Definition at line 371 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetDeviceAddr
#define USBD_SetDeviceAddr (addr) (USBD->ADDR_B.ADDR = addr)
Set device address.
Parameters
addr Device address
Return values
None
Definition at line 380 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetEPRxAddr
#define USBD_SetEPRxAddr (ep, addr) (*USBD_ReadEPRxAddrPointer(ep) = (addr >> 1) << 1)
Set EP Rx addr.
Parameters
ep EP number
addr Rx addr
Return values
None
Definition at line 1148 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetEPTxAddr
#define USBD_SetEPTxAddr (ep, addr) (*USBD_ReadEPTxAddrPointer(ep) = (addr >> 1) << 1)
Set EP Tx addr.
Parameters
ep EP number
addr Tx addr
Return values
None
Definition at line 1137 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetEPTxCnt
#define USBD_SetEPTxCnt (ep, cnt) (*USBD_ReadEPTxCntPointer(ep) = cnt)
Set EP Tx Count.
Parameters
ep EP number
cnt Tx count
Return values
None
Definition at line 1195 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetForceReset
#define USBD_SetForceReset () (USBD->CTRL_B.FORRST = BIT_SET)
Set force reset.
Parameters
None
Return values
None
Definition at line 182 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetForceSuspend
#define USBD_SetForceSuspend () (USBD->CTRL_B.FORSUS = BIT_SET)
Set force suspend.
Parameters
None
Return values
None
Definition at line 236 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetLowerPowerMode
#define USBD_SetLowerPowerMode () (USBD->CTRL_B.LPWREN = BIT_SET)
Set low power mode.
Parameters
None
Return values
None
Definition at line 218 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetPowerDown
#define USBD_SetPowerDown () (USBD->CTRL_B.PWRDOWN = BIT_SET)
Set power down.
Parameters
None
Return values
None
Definition at line 200 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetRegCTRL
#define USBD_SetRegCTRL (val) (USBD->CTRL = val)
Set CTRL register.
Parameters
val Register value
Return values
None
Definition at line 164 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetRegINTSTS
#define USBD_SetRegINTSTS (val) (USBD->INTSTS = val)
Set INTSTS register.
Parameters
val Register value
Return values
None
Definition at line 173 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
USBD_SetResume
#define USBD_SetResume () (USBD->CTRL_B.WUPREQ = BIT_SET)
Set resume.
Parameters
None
Return values
None
Definition at line 263 of file USB_Device_Lib/Driver/inc/drv_usb_device.h.
Function Documentation
USBD_ReadDataFromEP()
void USBD_ReadDataFromEP (uint8_t ep, uint8_t * rBuf, uint32_t rLen)
Read a buffer of data to a selected endpoint.
Parameters
ep Endpoint number
Return values
wBuf The pointer to the buffer of data to be read to the endpoint
Parameters
wLen Number of data to be read (in bytes)
Return values
None
Definition at line 378 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References USBD_ReadEPRxBufferPointer.
Referenced by USBD_CtrlOutProcess(), USBD_DataOutProcess(), and USBD_SetupProcess().
USBD_ResetEPKind()
void USBD_ResetEPKind (uint8_t ep)
Reset EP kind.
Parameters
ep Endpoint number
Return values
None
Definition at line 76 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_OpenInEP(), and USBD_OpenOutEP().
USBD_ResetEPRxFlag()
void USBD_ResetEPRxFlag (uint8_t ep)
Reset EP CTFR bit.
Parameters
ep Endpoint number
Return values
None
Definition at line 96 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, and USBD_EP_MASK_DEFAULT.
USBD_ResetEPTxFlag()
void USBD_ResetEPTxFlag (uint8_t ep)
Reset EP CTFT bit.
Parameters
ep Endpoint number
Return values
None
Definition at line 115 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, and USBD_EP_MASK_DEFAULT.
USBD_ResetRxToggle()
void USBD_ResetRxToggle (uint8_t ep)
Reset Toggle Rx DTOG.
Parameters
ep Endpoint number
Return values
None
Definition at line 187 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References USBD, and USBD_ToggleRx().
USBD_ResetTxToggle()
void USBD_ResetTxToggle (uint8_t ep)
Reset Toggle Tx DTOG.
Parameters
ep Endpoint number
Return values
None
Definition at line 172 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References USBD, and USBD_ToggleTx().
USBD_SetEpAddr()
void USBD_SetEpAddr (uint8_t ep, uint8_t addr)
Set EP address.
Parameters
ep Endpoint number
addr Address
Return values
None
Definition at line 204 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, and USBD_EP_MASK_DEFAULT.
USBD_SetEPKind()
void USBD_SetEPKind (uint8_t ep)
Set EP kind.
Parameters
ep Endpoint number
Return values
None
Definition at line 57 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_KIND, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_OpenInEP(), and USBD_OpenOutEP().
USBD_SetEPRxCnt()
void USBD_SetEPRxCnt (uint8_t ep, uint32_t cnt)
Set EP Rx Count.
Parameters
ep Endpoint number
cnt Rx count
Return values
None
Definition at line 301 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, and USBD_ReadEPRxCntPointer.
Referenced by USBD_OpenOutEP(), and USBD_RxData().
USBD_SetEPRxStatus()
void USBD_SetEPRxStatus (uint8_t ep, USBD_EP_STATUS_T status)
Set EP Rx status.
Parameters
ep Endpoint number
status status
Return values
None
Definition at line 249 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_RXSTS, and USBD_EP_MASK_DEFAULT.
Referenced by HidMouse_Reset(), USBD_CloseOutEP(), USBD_DataOutProcess(), USBD_OpenOutEP(), and USBD_RxData().
USBD_SetEPTxRxStatus()
void USBD_SetEPTxRxStatus (uint8_t ep, USBD_EP_STATUS_T txStatus, USBD_EP_STATUS_T rxStatus)
Set EP Tx and Rx status.
Parameters
ep Endpoint number
status status
Return values
None
Definition at line 274 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_RXSTS, USBD_EP_BIT_TXSTS, and USBD_EP_MASK_DEFAULT.
Referenced by HidMouse_ReportDescriptor(), USBD_CtrlInData(), USBD_CtrlInProcess(), USBD_CtrlOutData(), USBD_MSC_ClassHandler(), USBD_SetupProcess(), and USBD_StandardReqeust().
USBD_SetEPTxStatus()
void USBD_SetEPTxStatus (uint8_t ep, USBD_EP_STATUS_T status)
Set EP Tx status.
Parameters
ep Endpoint number
status status
Return values
None
Definition at line 226 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_TXSTS, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_CloseInEP(), USBD_CtrlInData(), USBD_CtrlInProcess(), USBD_DataInProcess(), USBD_MSV_BOT_ClearFeatureHandler(), USBD_OpenInEP(), and USBD_TxData().
USBD_SetEPType()
void USBD_SetEPType (uint8_t ep, USBD_REG_EP_TYPE_T type)
Set Endpoint type.
Parameters
ep Endpoint number
type Endpoint type
Return values
None
Definition at line 37 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_OpenInEP(), and USBD_OpenOutEP().
USBD_ToggleRx()
void USBD_ToggleRx (uint8_t ep)
Toggle Rx DTOG.
Parameters
ep Endpoint number
Return values
None
Definition at line 153 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_RXDTOG, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_ResetRxToggle().
USBD_ToggleTx()
void USBD_ToggleTx (uint8_t ep)
Toggle Tx DTOG.
Parameters
ep Endpoint number
Return values
None
Definition at line 134 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References __IOM, USBD, USBD_EP_BIT_TXDTOG, and USBD_EP_MASK_DEFAULT.
Referenced by USBD_ResetTxToggle().
USBD_WriteDataToEP()
void USBD_WriteDataToEP (uint8_t ep, uint8_t * wBuf, uint32_t wLen)
Write a buffer of data to a selected endpoint.
Parameters
ep Endpoint number
Return values
wBuf The pointer to the buffer of data to be written to the endpoint
Parameters
wLen Number of data to be written (in bytes)
Return values
None
Definition at line 343 of file USB_Device_Lib/Driver/src/drv_usb_device.c.
References USBD_ReadEPTxBufferPointer.
Referenced by USBD_CtrlInData(), USBD_CtrlInProcess(), USBD_DataInProcess(), and USBD_TxData().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU