APM32F10x_SDK: Functions
Functions
Examples » TMR_SinglePulse
Functions
int main (void)
Main program.
Detailed Description
Function Documentation
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 50 of file TMR/TMR_SinglePulse/Source/main.c.
References TMR_ICConfig_T::channel, TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_BaseConfig_T::division, TMR_ICConfig_T::filter, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_PIN_8, GPIO_PIN_9, GPIO_SPEED_50MHz, GPIOA, TMR_OCConfig_T::idleState, GPIO_Config_T::mode, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_BaseConfig_T::period, GPIO_Config_T::pin, TMR_OCConfig_T::polarity, TMR_ICConfig_T::polarity, TMR_ICConfig_T::prescaler, TMR_OCConfig_T::pulse, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_TMR1, RCM_EnableAPB2PeriphClock(), TMR_BaseConfig_T::repetitionCounter, TMR_ICConfig_T::selection, GPIO_Config_T::speed, TMR1, TMR_CHANNEL_2, TMR_CLOCK_DIV_1, TMR_ConfigIC(), TMR_ConfigOC1(), TMR_ConfigOCStructInit(), TMR_ConfigSinglePulseMode(), TMR_ConfigTimeBase(), TMR_COUNTER_MODE_UP, TMR_Enable(), TMR_EnablePWMOutputs(), TMR_IC_POLARITY_RISING, TMR_IC_PSC_1, TMR_IC_SELECTION_DIRECT_TI, TMR_OC_IDLE_STATE_SET, TMR_OC_MODE_PWM2, TMR_OC_NIDLE_STATE_RESET, TMR_OC_NPOLARITY_HIGH, TMR_OC_NSTATE_DISABLE, TMR_OC_POLARITY_HIGH, TMR_OC_STATE_ENABLE, TMR_SelectInputTrigger(), TMR_SelectSlaveMode(), TMR_SLAVE_MODE_TRIGGER, TMR_SPM_SINGLE, and TMR_TRIGGER_SOURCE_TI2FP2.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU