APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » DMA Driver
Functions
void DMA_Reset (DMA_Channel_T *channel)
Reset specified DMA Channel registers to their default reset.
void DMA_Config (DMA_Channel_T *channel, DMA_Config_T *dmaConfig)
Configs specified DMA Channel through a structure.
void DMA_ConfigStructInit (DMA_Config_T *dmaConfig)
Populate the structure with default values.
void DMA_Enable (DMA_Channel_T *channel)
Enable the specified DMA Channel.
void DMA_Disable (DMA_Channel_T *channel)
Disable the specified DMA Channel.
void DMA_ConfigDataNumber (DMA_Channel_T *channel, uint16_t dataNumber)
Configs the number of data units in the channel.
uint16_t DMA_ReadDataNumber (DMA_Channel_T *channel)
Read the number of data units in the channel.
void DMA_EnableInterrupt (DMA_Channel_T *channel, uint32_t interrupt)
Enables the specified DMA Channel interrupts.
void DMA_DisableInterrupt (DMA_Channel_T *channel, uint32_t interrupt)
Disable the specified DMA Channel interrupts.
uint8_t DMA_ReadStatusFlag (DMA_FLAG_T flag)
Read whether the specifie DMA Channel flag is set or not.
void DMA_ClearStatusFlag (uint32_t flag)
Clears the specifie DMA Channel's flags.
uint8_t DMA_ReadIntFlag (DMA_INT_FLAG_T flag)
Read whether the specified DMA Channel interrupts is set or not.
void DMA_ClearIntFlag (uint32_t flag)
Clears the specified DMA Channel's interrupts.
Detailed Description
Function Documentation
DMA_ClearIntFlag()
void DMA_ClearIntFlag (uint32_t flag)
Clears the specified DMA Channel's interrupts.
Parameters
flag the interrupt flag to Clear. This parameter can be any combination of the following values:
DMA1_INT_FLAG_GINT1 : DMA1 Channel 1 global interrupt.
DMA1_INT_FLAG_TC1 : DMA1 Channel 1 transfer complete interrupt.
DMA1_INT_FLAG_HT1 : DMA1 Channel 1 half transfer interrupt.
DMA1_INT_FLAG_TERR1 : DMA1 Channel 1 transfer error interrupt.
DMA1_INT_FLAG_GINT2 : DMA1 Channel2 global interrupt.
DMA1_INT_FLAG_TC2 : DMA1 Channel2 transfer complete interrupt.
DMA1_INT_FLAG_HT2 : DMA1 Channel2 half transfer interrupt.
DMA1_INT_FLAG_TERR2 : DMA1 Channel2 transfer error interrupt.
DMA1_INT_FLAG_GINT3 : DMA1 Channel3 global interrupt.
DMA1_INT_FLAG_TC3 : DMA1 Channel3 transfer complete interrupt.
DMA1_INT_FLAG_HT3 : DMA1 Channel3 half transfer interrupt.
DMA1_INT_FLAG_TERR3 : DMA1 Channel3 transfer error interrupt.
DMA1_INT_FLAG_GINT4 : DMA1 Channel4 global interrupt.
DMA1_INT_FLAG_TC4 : DMA1 Channel4 transfer complete interrupt.
DMA1_INT_FLAG_HT4 : DMA1 Channel4 half transfer interrupt.
DMA1_INT_FLAG_TERR4 : DMA1 Channel4 transfer error interrupt.
DMA1_INT_FLAG_GINT5 : DMA1 Channel5 global interrupt.
DMA1_INT_FLAG_TC5 DMA1 Channel5 transfer complete interrupt.
DMA1_INT_FLAG_HT5 DMA1 Channel5 half transfer interrupt.
DMA1_INT_FLAG_TERR5 : DMA1 Channel5 transfer error interrupt.
DMA1_INT_FLAG_GINT6 : DMA1 Channel6 global interrupt.
DMA1_INT_FLAG_TC6 : DMA1 Channel6 transfer complete interrupt.
DMA1_INT_FLAG_HT6 : DMA1 Channel6 half transfer interrupt.
DMA1_INT_FLAG_TERR6 : DMA1 Channel6 transfer error interrupt.
DMA1_INT_FLAG_GINT7 : DMA1 Channel7 global interrupt.
DMA1_INT_FLAG_TC7 : DMA1 Channel7 transfer complete interrupt.
DMA1_INT_FLAG_HT7 : DMA1 Channel7 half transfer interrupt.
DMA1_INT_FLAG_TERR7 : DMA1 Channel7 transfer error interrupt.
DMA2_INT_FLAG_GINT1 : DMA2 Channel 1 global interrupt.
DMA2_INT_FLAG_TC1 : DMA2 Channel 1 transfer complete interrupt.
DMA2_INT_FLAG_HT1 : DMA2 Channel 1 half transfer interrupt.
DMA2_INT_FLAG_TERR1 : DMA2 Channel 1 transfer error interrupt.
DMA2_INT_FLAG_GINT2 : DMA2 Channel 2 global interrupt.
DMA2_INT_FLAG_TC2 : DMA2 Channel 2 transfer complete interrupt.
DMA2_INT_FLAG_HT2 : DMA2 Channel 2 half transfer interrupt.
DMA2_INT_FLAG_TERR2 : DMA2 Channel 2 transfer error interrupt.
DMA2_INT_FLAG_GINT3 : DMA2 Channel 3 global interrupt.
DMA2_INT_FLAG_TC3 : DMA2 Channel 3 transfer complete interrupt.
DMA2_INT_FLAG_HT3 : DMA2 Channel 3 half transfer interrupt.
DMA2_INT_FLAG_TERR3 : DMA2 Channel 3 transfer error interrupt.
DMA2_INT_FLAG_GINT4 : DMA2 Channel 4 global interrupt.
DMA2_INT_FLAG_TC4 : DMA2 Channel 4 transfer complete interrupt.
DMA2_INT_FLAG_HT4 : DMA2 Channel 4 half transfer interrupt.
DMA2_INT_FLAG_TERR4 : DMA2 Channel 4 transfer error interrupt.
DMA2_INT_FLAG_GINT5 : DMA2 Channel 5 global interrupt.
DMA2_INT_FLAG_TC5 : DMA2 Channel 5 transfer complete interrupt.
DMA2_INT_FLAG_HT5 : DMA2 Channel 5 half transfer interrupt.
DMA2_INT_FLAG_TERR5 : DMA2 Channel 5 transfer error interrupt.
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 555 of file apm32f10x_dma.c.
References DMA1, DMA2, and RESET.
Referenced by DMA1_Channel6_IRQHandler().
DMA_ClearStatusFlag()
void DMA_ClearStatusFlag (uint32_t flag)
Clears the specifie DMA Channel's flags.
Parameters
flag:the flag to Clear. This parameter can be any combination of the following values:
DMA1_FLAG_GINT1: DMA1 Channel 1 global flag.
DMA1_FLAG_TC1: DMA1 Channel 1 transfer complete flag.
DMA1_FLAG_HT1: DMA1 Channel 1 half transfer flag.
DMA1_FLAG_TERR1: DMA1 Channel 1 transfer error flag.
DMA1_FLAG_GINT2: DMA1 Channel2 global flag.
DMA1_FLAG_TC2: DMA1 Channel2 transfer complete flag.
DMA1_FLAG_HT2: DMA1 Channel2 half transfer flag.
DMA1_FLAG_TERR2: DMA1 Channel2 transfer error flag.
DMA1_FLAG_GINT3: DMA1 Channel3 global flag.
DMA1_FLAG_TC3: DMA1 Channel3 transfer complete flag.
DMA1_FLAG_HT3: DMA1 Channel3 half transfer flag.
DMA1_FLAG_TERR3: DMA1 Channel3 transfer error flag.
DMA1_FLAG_GINT4: DMA1 Channel4 global flag.
DMA1_FLAG_TC4: DMA1 Channel4 transfer complete flag.
DMA1_FLAG_HT4: DMA1 Channel4 half transfer flag.
DMA1_FLAG_TERR4: DMA1 Channel4 transfer error flag.
DMA1_FLAG_GINT5: DMA1 Channel5 global flag.
DMA1_FLAG_TC5: DMA1 Channel5 transfer complete flag.
DMA1_FLAG_HT5: DMA1 Channel5 half transfer flag.
DMA1_FLAG_TERR5: DMA1 Channel5 transfer error flag.
DMA1_FLAG_GINT6: DMA1 Channel6 global flag.
DMA1_FLAG_TC6: DMA1 Channel6 transfer complete flag.
DMA1_FLAG_HT6: DMA1 Channel6 half transfer flag.
DMA1_FLAG_TERR6: DMA1 Channel6 transfer error flag.
DMA1_FLAG_GINT7: DMA1 Channel7 global flag.
DMA1_FLAG_TC7: DMA1 Channel7 transfer complete flag.
DMA1_FLAG_HT7: DMA1 Channel7 half transfer flag.
DMA1_FLAG_TERR7: DMA1 Channel7 transfer error flag.
DMA2_FLAG_GINT1: DMA2 Channel 1 global flag.
DMA2_FLAG_TC1: DMA2 Channel 1 transfer complete flag.
DMA2_FLAG_HT1: DMA2 Channel 1 half transfer flag.
DMA2_FLAG_TERR1: DMA2 Channel 1 transfer error flag.
DMA2_FLAG_GINT2: DMA2 Channel 2 global flag.
DMA2_FLAG_TC2: DMA2 Channel 2 transfer complete flag.
DMA2_FLAG_HT2: DMA2 Channel 2 half transfer flag.
DMA2_FLAG_TERR2: DMA2 Channel 2 transfer error flag.
DMA2_FLAG_GINT3: DMA2 Channel 3 global flag.
DMA2_FLAG_TC3: DMA2 Channel 3 transfer complete flag.
DMA2_FLAG_HT3: DMA2 Channel 3 half transfer flag.
DMA2_FLAG_TERR3: DMA2 Channel 3 transfer error flag.
DMA2_FLAG_GINT4: DMA2 Channel 4 global flag.
DMA2_FLAG_TC4: DMA2 Channel 4 transfer complete flag.
DMA2_FLAG_HT4: DMA2 Channel 4 half transfer flag.
DMA2_FLAG_TERR4: DMA2 Channel 4 transfer error flag.
DMA2_FLAG_GINT5: DMA2 Channel 5 global flag.
DMA2_FLAG_TC5: DMA2 Channel 5 transfer complete flag.
DMA2_FLAG_HT5: DMA2 Channel 5 half transfer flag.
DMA2_FLAG_TERR5: DMA2 Channel 5 transfer error flag.
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 399 of file apm32f10x_dma.c.
References DMA1, DMA2, and RESET.
Referenced by main().
DMA_Config()
void DMA_Config (DMA_Channel_T * channel, DMA_Config_T * dmaConfig)
Configs specified DMA Channel through a structure.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
dmaConfig Point to a DMA_Config_T structure
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 119 of file apm32f10x_dma.c.
References DMA_Config_T::bufferSize, DMA_Channel_T::CHCFG_B, DMA_Channel_T::CHMADDR, DMA_Channel_T::CHNDATA, DMA_Channel_T::CHPADDR, DMA_Channel_T::CHPL, DMA_Channel_T::CIRMODE, DMA_Config_T::dir, DMA_Channel_T::DIRCFG, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Channel_T::M2MMODE, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Channel_T::MEMSIZE, DMA_Channel_T::MIMODE, DMA_Channel_T::PERIMODE, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Channel_T::PERSIZE, and DMA_Config_T::priority.
Referenced by DMA_Init(), DMA_Init(), main(), USART1_RX_DMA_Init(), and USART2_TX_DMA_Init().
DMA_ConfigDataNumber()
void DMA_ConfigDataNumber (DMA_Channel_T * channel, uint16_t dataNumber)
Configs the number of data units in the channel.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
dataNumber:The number of data units in the current DMA Channel transfer.
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 196 of file apm32f10x_dma.c.
References DMA_Channel_T::CHNDATA.
DMA_ConfigStructInit()
void DMA_ConfigStructInit (DMA_Config_T * dmaConfig)
Populate the structure with default values.
Parameters
dmaConfig Point to a DMA_Config_T structure.
Return values
None
Definition at line 142 of file apm32f10x_dma.c.
References DMA_Config_T::bufferSize, DMA_Config_T::dir, DMA_DIR_PERIPHERAL_SRC, DMA_M2MEN_DISABLE, DMA_MEMORY_DATA_SIZE_BYTE, DMA_MEMORY_INC_DISABLE, DMA_MODE_NORMAL, DMA_PERIPHERAL_DATA_SIZE_BYTE, DMA_PERIPHERAL_INC_DISABLE, DMA_PRIORITY_LOW, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, and DMA_Config_T::priority.
DMA_Disable()
void DMA_Disable (DMA_Channel_T * channel)
Disable the specified DMA Channel.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 180 of file apm32f10x_dma.c.
References DMA_Channel_T::CHCFG_B, DMA_Channel_T::CHEN, and DISABLE.
DMA_DisableInterrupt()
void DMA_DisableInterrupt (DMA_Channel_T * channel, uint32_t interrupt)
Disable the specified DMA Channel interrupts.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
interrupt DMA interrupts sources to selsct This parameter can be any combination of the following values:
DMA_INT_TC : All Transfer Complete Interrupt
DMA_INT_HT : Half Transfer Complete Interrupt
DMA_INT_TERR : Transfer Error Occur Interrupt
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 250 of file apm32f10x_dma.c.
References DMA_Channel_T::CHCFG.
DMA_Enable()
void DMA_Enable (DMA_Channel_T * channel)
Enable the specified DMA Channel.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 166 of file apm32f10x_dma.c.
References DMA_Channel_T::CHCFG_B, DMA_Channel_T::CHEN, and ENABLE.
Referenced by DMA_Init(), DMA_Init(), main(), USART1_RX_DMA_Init(), and USART2_TX_DMA_Init().
DMA_EnableInterrupt()
void DMA_EnableInterrupt (DMA_Channel_T * channel, uint32_t interrupt)
Enables the specified DMA Channel interrupts.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
interrupt DMA interrupts sources to selsct This parameter can be any combination of the following values:
DMA_INT_TC : All Transfer Complete Interrupt
DMA_INT_HT : Half Transfer Complete Interrupt
DMA_INT_TERR : Transfer Error Occur Interrupt
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 230 of file apm32f10x_dma.c.
References DMA_Channel_T::CHCFG.
Referenced by DMA_Init(), and main().
DMA_ReadDataNumber()
uint16_t DMA_ReadDataNumber (DMA_Channel_T * channel)
Read the number of data units in the channel.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5)
Return values
The number of CHNDATA value
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 210 of file apm32f10x_dma.c.
References DMA_Channel_T::CHNDATA.
Referenced by DMA1_Channel6_IRQHandler(), and main().
DMA_ReadIntFlag()
uint8_t DMA_ReadIntFlag (DMA_INT_FLAG_T flag)
Read whether the specified DMA Channel interrupts is set or not.
Parameters
interrupt interrupt source to check. This parameter can be one of the following values:
DMA1_INT_FLAG_GINT1 : DMA1 Channel 1 global interrupt.
DMA1_INT_FLAG_TC1 : DMA1 Channel 1 transfer complete interrupt.
DMA1_INT_FLAG_HT1 : DMA1 Channel 1 half transfer interrupt.
DMA1_INT_FLAG_TERR1 : DMA1 Channel 1 transfer error interrupt.
DMA1_INT_FLAG_GINT2 : DMA1 Channel2 global interrupt.
DMA1_INT_FLAG_TC2 : DMA1 Channel2 transfer complete interrupt.
DMA1_INT_FLAG_HT2 : DMA1 Channel2 half transfer interrupt.
DMA1_INT_FLAG_TERR2 : DMA1 Channel2 transfer error interrupt.
DMA1_INT_FLAG_GINT3 : DMA1 Channel3 global interrupt.
DMA1_INT_FLAG_TC3 : DMA1 Channel3 transfer complete interrupt.
DMA1_INT_FLAG_HT3 : DMA1 Channel3 half transfer interrupt.
DMA1_INT_FLAG_TERR3 : DMA1 Channel3 transfer error interrupt.
DMA1_INT_FLAG_GINT4 : DMA1 Channel4 global interrupt.
DMA1_INT_FLAG_TC4 : DMA1 Channel4 transfer complete interrupt.
DMA1_INT_FLAG_HT4 : DMA1 Channel4 half transfer interrupt.
DMA1_INT_FLAG_TERR4 : DMA1 Channel4 transfer error interrupt.
DMA1_INT_FLAG_GINT5 : DMA1 Channel5 global interrupt.
DMA1_INT_FLAG_TC5 DMA1 Channel5 transfer complete interrupt.
DMA1_INT_FLAG_HT5 DMA1 Channel5 half transfer interrupt.
DMA1_INT_FLAG_TERR5 : DMA1 Channel5 transfer error interrupt.
DMA1_INT_FLAG_GINT6 : DMA1 Channel6 global interrupt.
DMA1_INT_FLAG_TC6 : DMA1 Channel6 transfer complete interrupt.
DMA1_INT_FLAG_HT6 : DMA1 Channel6 half transfer interrupt.
DMA1_INT_FLAG_TERR6 : DMA1 Channel6 transfer error interrupt.
DMA1_INT_FLAG_GINT7 : DMA1 Channel7 global interrupt.
DMA1_INT_FLAG_TC7 : DMA1 Channel7 transfer complete interrupt.
DMA1_INT_FLAG_HT7 : DMA1 Channel7 half transfer interrupt.
DMA1_INT_FLAG_TERR7 : DMA1 Channel7 transfer error interrupt.
DMA2_INT_FLAG_GINT1 : DMA2 Channel 1 global interrupt.
DMA2_INT_FLAG_TC1 : DMA2 Channel 1 transfer complete interrupt.
DMA2_INT_FLAG_HT1 : DMA2 Channel 1 half transfer interrupt.
DMA2_INT_FLAG_TERR1 : DMA2 Channel 1 transfer error interrupt.
DMA2_INT_FLAG_GINT2 : DMA2 Channel 2 global interrupt.
DMA2_INT_FLAG_TC2 : DMA2 Channel 2 transfer complete interrupt.
DMA2_INT_FLAG_HT2 : DMA2 Channel 2 half transfer interrupt.
DMA2_INT_FLAG_TERR2 : DMA2 Channel 2 transfer error interrupt.
DMA2_INT_FLAG_GINT3 : DMA2 Channel 3 global interrupt.
DMA2_INT_FLAG_TC3 : DMA2 Channel 3 transfer complete interrupt.
DMA2_INT_FLAG_HT3 : DMA2 Channel 3 half transfer interrupt.
DMA2_INT_FLAG_TERR3 : DMA2 Channel 3 transfer error interrupt.
DMA2_INT_FLAG_GINT4 : DMA2 Channel 4 global interrupt.
DMA2_INT_FLAG_TC4 : DMA2 Channel 4 transfer complete interrupt.
DMA2_INT_FLAG_HT4 : DMA2 Channel 4 half transfer interrupt.
DMA2_INT_FLAG_TERR4 : DMA2 Channel 4 transfer error interrupt.
DMA2_INT_FLAG_GINT5 : DMA2 Channel 5 global interrupt.
DMA2_INT_FLAG_TC5 : DMA2 Channel 5 transfer complete interrupt.
DMA2_INT_FLAG_HT5 : DMA2 Channel 5 half transfer interrupt.
DMA2_INT_FLAG_TERR5 : DMA2 Channel 5 transfer error interrupt.
Return values
interrupt State
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 470 of file apm32f10x_dma.c.
References DMA1, DMA2, RESET, and SET.
Referenced by DMA1_Channel6_IRQHandler().
DMA_ReadStatusFlag()
uint8_t DMA_ReadStatusFlag (DMA_FLAG_T flag)
Read whether the specifie DMA Channel flag is set or not.
Parameters
flag the flag to check. This parameter can be one of the following values:
DMA1_FLAG_GINT1: DMA1 Channel 1 global flag.
DMA1_FLAG_TC1: DMA1 Channel 1 transfer complete flag.
DMA1_FLAG_HT1: DMA1 Channel 1 half transfer flag.
DMA1_FLAG_TERR1: DMA1 Channel 1 transfer error flag.
DMA1_FLAG_GINT2: DMA1 Channel2 global flag.
DMA1_FLAG_TC2: DMA1 Channel2 transfer complete flag.
DMA1_FLAG_HT2: DMA1 Channel2 half transfer flag.
DMA1_FLAG_TERR2: DMA1 Channel2 transfer error flag.
DMA1_FLAG_GINT3: DMA1 Channel3 global flag.
DMA1_FLAG_TC3: DMA1 Channel3 transfer complete flag.
DMA1_FLAG_HT3: DMA1 Channel3 half transfer flag.
DMA1_FLAG_TERR3: DMA1 Channel3 transfer error flag.
DMA1_FLAG_GINT4: DMA1 Channel4 global flag.
DMA1_FLAG_TC4: DMA1 Channel4 transfer complete flag.
DMA1_FLAG_HT4: DMA1 Channel4 half transfer flag.
DMA1_FLAG_TERR4: DMA1 Channel4 transfer error flag.
DMA1_FLAG_GINT5: DMA1 Channel5 global flag.
DMA1_FLAG_TC5: DMA1 Channel5 transfer complete flag.
DMA1_FLAG_HT5: DMA1 Channel5 half transfer flag.
DMA1_FLAG_TERR5: DMA1 Channel5 transfer error flag.
DMA1_FLAG_GINT6: DMA1 Channel6 global flag.
DMA1_FLAG_TC6: DMA1 Channel6 transfer complete flag.
DMA1_FLAG_HT6: DMA1 Channel6 half transfer flag.
DMA1_FLAG_TERR6: DMA1 Channel6 transfer error flag.
DMA1_FLAG_GINT7: DMA1 Channel7 global flag.
DMA1_FLAG_TC7: DMA1 Channel7 transfer complete flag.
DMA1_FLAG_HT7: DMA1 Channel7 half transfer flag.
DMA1_FLAG_TERR7: DMA1 Channel7 transfer error flag.
DMA2_FLAG_GINT1: DMA2 Channel 1 global flag.
DMA2_FLAG_TC1: DMA2 Channel 1 transfer complete flag.
DMA2_FLAG_HT1: DMA2 Channel 1 half transfer flag.
DMA2_FLAG_TERR1: DMA2 Channel 1 transfer error flag.
DMA2_FLAG_GINT2: DMA2 Channel 2 global flag.
DMA2_FLAG_TC2: DMA2 Channel 2 transfer complete flag.
DMA2_FLAG_HT2: DMA2 Channel 2 half transfer flag.
DMA2_FLAG_TERR2: DMA2 Channel 2 transfer error flag.
DMA2_FLAG_GINT3: DMA2 Channel 3 global flag.
DMA2_FLAG_TC3: DMA2 Channel 3 transfer complete flag.
DMA2_FLAG_HT3: DMA2 Channel 3 half transfer flag.
DMA2_FLAG_TERR3: DMA2 Channel 3 transfer error flag.
DMA2_FLAG_GINT4: DMA2 Channel 4 global flag.
DMA2_FLAG_TC4: DMA2 Channel 4 transfer complete flag.
DMA2_FLAG_HT4: DMA2 Channel 4 half transfer flag.
DMA2_FLAG_TERR4: DMA2 Channel 4 transfer error flag.
DMA2_FLAG_GINT5: DMA2 Channel 5 global flag.
DMA2_FLAG_TC5: DMA2 Channel 5 transfer complete flag.
DMA2_FLAG_HT5: DMA2 Channel 5 half transfer flag.
DMA2_FLAG_TERR5: DMA2 Channel 5 transfer error flag.
Return values
Flag State
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 314 of file apm32f10x_dma.c.
References DMA1, DMA2, RESET, and SET.
Referenced by main().
DMA_Reset()
void DMA_Reset (DMA_Channel_T * channel)
Reset specified DMA Channel registers to their default reset.
Parameters
channel:DMA1_channelx(x can be from 1 to 7) or DMA2_channely(y can be from 1 to 5).
Return values
None
Note
DMA2 Channel only for APM32 High density devices.
Definition at line 50 of file apm32f10x_dma.c.
References BIT_RESET, DMA_Channel_T::CHCFG, DMA_Channel_T::CHCFG_B, DMA_Channel_T::CHEN, DMA_Channel_T::CHMADDR, DMA_Channel_T::CHNDATA, DMA_Channel_T::CHPADDR, DMA1, DMA1_Channel1, DMA1_Channel2, DMA1_Channel3, DMA1_Channel4, DMA1_Channel5, DMA1_Channel6, DMA1_Channel7, DMA2, DMA2_Channel1, DMA2_Channel2, DMA2_Channel3, DMA2_Channel4, and DMA2_Channel5.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU