APM32F10x_SDK: Functions
Functions
Examples » FreeRTOS
Enumerations
enum BOOL { FALSE , TRUE }
Functions
void USART_Write (USART_T *usart, uint8_t *dat)
void USART_Init (void)
USARTS Initialization.
void Delay (uint32_t count)
Delay.
BOOL BufferCompare (uint8_t *buf1, uint8_t *buf2, uint8_t size)
Compares two buffers.
void vTaskLedToggle (void *pvParameters)
Led toggle task.
void vTaskUsartTest (void *pvParameters)
Led toggle task.
int main (void)
Main program.
Variables
uint8_t rxDataBufUSART1 [DATA_BUF_SIZE] = {0}
uint8_t txDataBufUSART1 [DATA_BUF_SIZE] = {0}
uint8_t rxDataBufUSART2 [DATA_BUF_SIZE] = {0}
uint8_t txDataBufUSART2 [DATA_BUF_SIZE] = {0}
Detailed Description
Enumeration Type Documentation
BOOL
enum BOOL
Enumerator
FALSE
TRUE
Definition at line 56 of file RTOS/FreeRTOS/Source/main.c.
Function Documentation
BufferCompare()
BOOL BufferCompare (uint8_t * buf1, uint8_t * buf2, uint8_t size)
Compares two buffers.
Parameters
buf1 First buffer to be compared
buf1 Second buffer to be compared
size Buffer size
Return values
Return SET if buf1 = buf2. If not then return RESET
Definition at line 284 of file RTOS/FreeRTOS/Source/main.c.
References FALSE, size, and TRUE.
Referenced by vTaskUsartTest().
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 338 of file RTOS/FreeRTOS/Source/main.c.
References count.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 97 of file RTOS/FreeRTOS/Source/main.c.
References APM_MINI_LEDInit(), LED2, LED3, and USART_Init().
USART_Init()
void USART_Init (void)
USARTS Initialization.
Parameters
None
Return values
None
Definition at line 306 of file RTOS/FreeRTOS/Source/main.c.
References APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, COM2, Delay(), USART_Config_T::hardwareFlow, MINI_COM1, MINI_COM2, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_ClearStatusFlag(), USART_DisableInterrupt(), USART_FLAG_RXBNE, USART_HARDWARE_FLOW_NONE, USART_INT_RXBNE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by main().
USART_Write()
void USART_Write (USART_T * usart, uint8_t * dat)
vTaskLedToggle()
void vTaskLedToggle (void * pvParameters)
Led toggle task.
Parameters
pvParameters - passed into the task function as the function parameters
Return values
None
Definition at line 145 of file RTOS/FreeRTOS/Source/main.c.
References APM_MINI_LEDToggle(), and LED2.
vTaskUsartTest()
void vTaskUsartTest (void * pvParameters)
Led toggle task.
Parameters
pvParameters - passed into the task function as the function parameters
Return values
None
Definition at line 163 of file RTOS/FreeRTOS/Source/main.c.
References APM_MINI_LEDOff(), APM_MINI_LEDOn(), BufferCompare(), DATA_BUF_SIZE, LED3, MINI_COM1, MINI_COM2, RESET, rxDataBufUSART1, rxDataBufUSART2, TRUE, txDataBufUSART1, txDataBufUSART2, USART_FLAG_RXBNE, USART_FLAG_TXBE, USART_ReadStatusFlag(), USART_RxData(), and USART_TxData().
Variable Documentation
rxDataBufUSART1
uint8_t rxDataBufUSART1[DATA_BUF_SIZE] = {0}
Definition at line 59 of file RTOS/FreeRTOS/Source/main.c.
Referenced by vTaskUsartTest().
rxDataBufUSART2
uint8_t rxDataBufUSART2[DATA_BUF_SIZE] = {0}
Definition at line 64 of file RTOS/FreeRTOS/Source/main.c.
Referenced by vTaskUsartTest().
txDataBufUSART1
uint8_t txDataBufUSART1[DATA_BUF_SIZE] = {0}
Definition at line 61 of file RTOS/FreeRTOS/Source/main.c.
Referenced by vTaskUsartTest().
txDataBufUSART2
uint8_t txDataBufUSART2[DATA_BUF_SIZE] = {0}
Definition at line 66 of file RTOS/FreeRTOS/Source/main.c.
Referenced by vTaskUsartTest().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU