APM32F10x_SDK: Functions
Functions
Examples » USBH_MSC
Functions
void USB_HardwareInit (void)
USB hardware Init.
void USB_Timer_IRQHandler (void)
Handle USB Timer interrupt.
void USB_usDelay (uint32_t delayTime)
microseconds delay function
void USB_msDelay (uint32_t delayTime)
milliseconds delay function
void ConfigDelayTimer (void)
Config Delay Timer 1ms Timer.
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
void USBH_MSC_Init (void)
Init USB host MSC.
uint8_t USBH_DeviceStatus (void)
Get the device connection status.
uint8_t USB_DiskRead (uint8_t *buffer, uint32_t sector, uint32_t cnt)
USB_DiskRead.
uint8_t USB_DiskWrite (uint8_t *buffer, uint32_t sector, uint32_t cnt)
USB_DiskWrite.
FRESULT FATFS_ScanFiles (char *path)
Traverse files of FatFs.
void FATFS_WriteReadFile (FIL *file)
Write a file to fatfs and read it.
void USBH_MSC_BOT_Init (void)
Init BOT of USB host MSC.
void USBH_MSC_BOTXferHandler (void)
BOT transmission handler.
void USBH_MSC_BOT_ConfigCBW (uint32_t xferLen, USBH_BOT_DIR_T dir, uint8_t *CBBuf, uint8_t CBLen)
uint8_t MSC_SCSI_TestUnitReady (void)
function declaration
uint8_t MSC_SCSI_ReadCapacity10 (void)
Read Capacity 10 command.
uint8_t MSC_SCSI_ModeSense6 (void)
Mode Sense 6 command.
uint8_t MSC_SCSI_RequestSense (void)
Request Sense command.
uint8_t MSC_SCSI_Write10 (uint8_t *dataBuffer, uint32_t address, uint32_t sectorCnt)
Write 10 command.
uint8_t MSC_SCSI_Read10 (uint8_t *dataBuffer, uint32_t address, uint32_t sectorCnt)
Read 10 command.
int main (void)
Main program.
Variables
uint32_t test = 0
Detailed Description
Function Documentation
APM_BOARD_COMInit()
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 380 of file OTG_Host/USBH_MSC/Source/usb_board.c.
References APM_MINI_COMInit().
ConfigDelayTimer()
void ConfigDelayTimer (void)
Config Delay Timer 1ms Timer.
Parameters
None
Return values
None
Definition at line 286 of file OTG_Host/USBH_MSC/Source/usb_board.c.
References TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_BaseConfig_T::division, NVIC_EnableIRQRequest(), TMR_BaseConfig_T::period, RCM_APB1_PERIPH_TMR2, RCM_EnableAPB1PeriphClock(), RCM_ReadPCLKFreq(), TMR2, tmr2Clk, TMR_CLOCK_DIV_1, TMR_ConfigTimeBase(), TMR_COUNTER_MODE_UP, TMR_Enable(), TMR_EnableAutoReload(), TMR_EnableInterrupt(), and TMR_INT_UPDATE.
FATFS_ScanFiles()
FRESULT FATFS_ScanFiles (char * path)
Traverse files of FatFs.
Parameters
path init scan path
Return values
File function return code
Note
This function is assuming non-Unicode cfg
Definition at line 168 of file usbh_msc.c.
References FATFS_ScanFiles().
Referenced by FATFS_ScanFiles().
FATFS_WriteReadFile()
void FATFS_WriteReadFile (FIL * file)
Write a file to fatfs and read it.
Parameters
file point to the file.
Return values
None
Definition at line 243 of file usbh_msc.c.
References byteReadWriteNum, readBuffer, and writeBuffer.
main()
int main (void)
Main program.
Parameters
None
Return values
int
Definition at line 48 of file OTG/OTG_Host/USBH_MSC/Source/main.c.
References USBH_MSC_Init(), and USBH_PollingProcess().
MSC_SCSI_ModeSense6()
uint8_t MSC_SCSI_ModeSense6 (void)
Mode Sense 6 command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 147 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_CBW_T::dDataXferLen, g_BOTInfo, g_MSCInfo, LEN_CBW, LEN_XFER_MODE_SENSE6, MODE_SENSE_PAGE_CODE, MODE_SENSE_PAGE_CONTROL_FIELD, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_MODE_SENSE_6, USBH_MSC_Info_T::SCSIStates, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_IN.
MSC_SCSI_Read10()
uint8_t MSC_SCSI_Read10 (uint8_t * dataBuffer, uint32_t address, uint32_t sectorCnt)
Read 10 command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 302 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, USBH_MSC_StorageInfo_T::blockSize, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_CBW_T::dDataXferLen, g_BOTInfo, g_MSCInfo, LEN_CBW, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_READ_10, USBH_MSC_Info_T::SCSIStates, USBH_MSC_Info_T::storageInfo, test, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_IN.
Referenced by USB_DiskRead().
MSC_SCSI_ReadCapacity10()
uint8_t MSC_SCSI_ReadCapacity10 (void)
Read Capacity 10 command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 99 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_CBW_T::dDataXferLen, g_BOTInfo, g_MSCInfo, LEN_CBW, LEN_CSW_MAX, LEN_XFER_READ_CAPACITY10, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_READ_CAPACITY_10, USBH_MSC_Info_T::SCSIStates, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_IN.
MSC_SCSI_RequestSense()
uint8_t MSC_SCSI_RequestSense (void)
Request Sense command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 195 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_CBW_T::dDataXferLen, DESC_REQUEST_SENSE, g_BOTInfo, g_MSCInfo, LEN_CBW, LEN_XFER_REQUEST_SENSE, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_REQUEST_SENSE, USBH_MSC_Info_T::SCSIStates, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_IN.
MSC_SCSI_TestUnitReady()
uint8_t MSC_SCSI_TestUnitReady (void)
function declaration
Test Unit Ready command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 52 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_Info_T::CSW, BOT_CBW_T::dDataXferLen, g_BOTInfo, g_MSCInfo, LEN_CBW_TEST_UNIT_READY, LEN_CSW_MAX, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_TEST_UNIT_READY, USBH_MSC_Info_T::SCSIStates, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_OUT.
MSC_SCSI_Write10()
uint8_t MSC_SCSI_Write10 (uint8_t * dataBuffer, uint32_t address, uint32_t sectorCnt)
Write 10 command.
Parameters
None
Return values
BOT SCSI transmission status
Definition at line 243 of file usbh_msc_scsi.c.
References BOT_CBW_T::bCBLen, USBH_MSC_StorageInfo_T::blockSize, BOT_CBW_T::bmFlags, BOT_CBW_CB_LEN, BOT_CBW_T::CB, BOT_Info_T::CBW, BOT_CBW_T::dDataXferLen, g_BOTInfo, g_MSCInfo, LEN_CBW, MSC_SCSI_BUSY, MSC_SCSI_SEND, SCSI_CMD_WRITE10, USBH_MSC_Info_T::SCSIStates, USBH_MSC_Info_T::storageInfo, USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_BOT_OK, USBH_BOT_PHASE_ERROR, USBH_BOT_SEND_CBW, USBH_ConfigClassCoreState, USBH_MSC_BOT_TRANSFER, and USBH_REQ_DIR_OUT.
Referenced by USB_DiskWrite().
USB_DiskRead()
uint8_t USB_DiskRead (uint8_t * buffer, uint32_t sector, uint32_t cnt)
USB_DiskRead.
Parameters
buffer:U-disk data buffer
sector:read sector
cnt:total number of sector
Return values
Status
Definition at line 109 of file usbh_msc.c.
References MSC_SCSI_Read10(), USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_DeviceStatus(), and USBH_MSC_BOTXferHandler().
USB_DiskWrite()
uint8_t USB_DiskWrite (uint8_t * buffer, uint32_t sector, uint32_t cnt)
USB_DiskWrite.
Parameters
buffer:U-disk data buffer
sector:read sector
cnt:total number of sector
Return values
Status
Definition at line 140 of file usbh_msc.c.
References MSC_SCSI_Write10(), USBH_BOT_BUSY, USBH_BOT_FAIL, USBH_DeviceStatus(), and USBH_MSC_BOTXferHandler().
USB_HardwareInit()
void USB_HardwareInit (void)
USB hardware Init.
Parameters
None
Return values
None
Definition at line 64 of file OTG_Host/USBH_MSC/Source/usb_board.c.
References BIT10, BIT12, BIT8, BIT9, BIT_SET, ConfigDelayTimer(), FMC, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_9, GPIO_PIN_SOURCE_0, GPIO_PIN_SOURCE_1, GPIO_PIN_SOURCE_10, GPIO_PIN_SOURCE_11, GPIO_PIN_SOURCE_12, GPIO_PIN_SOURCE_13, GPIO_PIN_SOURCE_14, GPIO_PIN_SOURCE_15, GPIO_PIN_SOURCE_3, GPIO_PIN_SOURCE_4, GPIO_PIN_SOURCE_5, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIOC, GPIO_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_1, GPIO_Config_T::pin, RCM, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, and USB_OTG_DisableAllGlobalInterrupt.
USB_msDelay()
void USB_msDelay (uint32_t delayTime)
milliseconds delay function
Parameters
delayTime : set the number of milliseconds to delay
Return values
None
Definition at line 270 of file OTG_Host/USBH_MSC/Source/usb_board.c.
References USB_usDelay().
USB_Timer_IRQHandler()
void USB_Timer_IRQHandler (void)
Handle USB Timer interrupt.
Parameters
None
Return values
None
Definition at line 219 of file OTG_Host/USBH_MSC/Source/usb_board.c.
References TMR2, TMR_ClearIntFlag(), TMR_delayCnt, TMR_Disable(), TMR_INT_UPDATE, and TMR_ReadIntFlag().
USB_usDelay()
void USB_usDelay (uint32_t delayTime)
microseconds delay function
Parameters
delayTime : set the number of microseconds to delay
Return values
None
Definition at line 244 of file OTG_Host/USBH_MSC/Source/usb_board.c.
USBH_DeviceStatus()
uint8_t USBH_DeviceStatus (void)
Get the device connection status.
Parameters
None
Return values
Device connection status. 1 -> connected 0 -> disconnected
Definition at line 93 of file usbh_msc.c.
References USBH_Info_T::connectedFlag, and g_usbHost.
Referenced by USB_DiskRead(), and USB_DiskWrite().
USBH_MSC_BOT_ConfigCBW()
void USBH_MSC_BOT_ConfigCBW (uint32_t xferLen, USBH_BOT_DIR_T dir, uint8_t * CBBuf, uint8_t CBLen)
USBH_MSC_BOT_Init()
void USBH_MSC_BOT_Init (void)
Init BOT of USB host MSC.
Parameters
None
Return values
None
Definition at line 93 of file usbh_msc_bot.c.
References USBH_BOT_CBW_T::bLUN, USBH_BOT_CmdPack_T::CBW, USBH_BOT_Info_T::cmdPack, USBH_BOT_CBW_T::dSignature, USBH_BOT_CBW_T::dTag, USBH_MSC_Info_T::errorCnt, USBH_BOT_CBW_T::field, g_BOTInfo, g_errorCntBOTStall, g_MSCInfo, MSC_BOT_CBW_SIGNATURE, MSC_BOT_CBW_TAG, MSC_SCSI_SEND, and USBH_MSC_Info_T::SCSIStates.
USBH_MSC_BOTXferHandler()
void USBH_MSC_BOTXferHandler (void)
BOT transmission handler.
Parameters
None
Return values
None
Definition at line 154 of file usbh_msc_bot.c.
References USBH_BOT_Info_T::curBOTState, g_BOTInfo, and MSC_BOT_Handler.
Referenced by USB_DiskRead(), and USB_DiskWrite().
USBH_MSC_Init()
void USBH_MSC_Init (void)
Init USB host MSC.
Parameters
None
Return values
None
Definition at line 69 of file usbh_msc.c.
References USBH_InitParam_T::classCoreHandler, USBH_InitParam_T::classDeInitHandler, USBH_InitParam_T::classInitHandler, USBH_InitParam_T::classReqHandler, USBH_InitParam_T::intHandler, NULL, USBH_InitParam_T::suspendHandler, USBH_Init(), USBH_MSC_ClassDeInitHandler(), USBH_MSC_ClassInitHandler(), USBH_MSC_ClassReqHandler(), USBH_MSC_CoreHandler(), and USBH_InitParam_T::wakeUpHandler.
Referenced by main().
Variable Documentation
test
uint32_t test = 0
Definition at line 294 of file usbh_msc_scsi.c.
Referenced by MSC_SCSI_Read10().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU