APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » FMC Driver
Functions
void FMC_ConfigLatency (FMC_LATENCY_T latency)
Configs the code latency value.
void FMC_EnableHalfCycleAccess (void)
Enables the Half cycle flash access.
void FMC_DisableHalfCycleAccess (void)
Disable the Half cycle flash access.
void FMC_EnablePrefetchBuffer (void)
Enables the Prefetch Buffer.
void FMC_DisablePrefetchBuffer (void)
Disables the Prefetch Buffer.
void FMC_Unlock (void)
Unlocks the FMC Program Erase Controller.
void FMC_Lock (void)
Locks the FMC Program Erase Controller.
FMC_STATUS_T FMC_ErasePage (uint32_t pageAddr)
Erases a specified FMC page.
FMC_STATUS_T FMC_EraseAllPage (void)
Erases all FMC pages.
FMC_STATUS_T FMC_EraseOptionBytes (void)
Erases the FMC option bytes.
FMC_STATUS_T FMC_ProgramWord (uint32_t address, uint32_t data)
Programs a word at a specified address.
FMC_STATUS_T FMC_ProgramHalfWord (uint32_t address, uint16_t data)
Programs a half word at a specified address.
FMC_STATUS_T FMC_ProgramOptionByteData (uint32_t address, uint8_t data)
Programs a half word at a specified Option Byte Data address.
FMC_STATUS_T FMC_EnableWriteProtection (uint32_t page)
Write protects the desired pages.
FMC_STATUS_T FMC_EnableReadOutProtection (void)
Enables the read out protection.
FMC_STATUS_T FMC_DisableReadOutProtection (void)
Disables the read out protection.
FMC_STATUS_T FMC_ConfigUserOptionByte (FMC_UserConfig_T *userConfig)
Programs the FMC User Option Byte.
uint32_t FMC_ReadUserOptionByte (void)
Read the FMC User Option Bytes values.
uint32_t FMC_ReadOptionByteWriteProtection (void)
Read the FMC Write Protection Option Bytes Register value.
uint8_t FMC_GetReadProtectionStatus (void)
Get the FMC Read Out Protection Status is set or not.
uint8_t FMC_ReadPrefetchBufferStatus (void)
FMC Prefetch Buffer status is set or not.
void FMC_EnableInterrupt (FMC_INT_T interrupt)
Enables the specified FMC interrupts.
void FMC_DisableInterrupt (FMC_INT_T interrupt)
Disable the specified FMC interrupts.
uint8_t FMC_ReadStatusFlag (FMC_FLAG_T flag)
Read FMC flag is set or not.
void FMC_ClearStatusFlag (uint32_t flag)
Clears the FMC's flag.
FMC_STATUS_T FMC_ReadStatus (void)
Read the FMC Status.
FMC_STATUS_T FMC_WaitForLastOperation (uint32_t timeOut)
Waits for a Flash operation to complete or a TIMEOUT to occur.
Detailed Description
Function Documentation
FMC_ClearStatusFlag()
void FMC_ClearStatusFlag (uint32_t flag)
Clears the FMC's flag.
Parameters
flag status flag of FMC This parameter can be any combination of the following values:
FMC_FLAG_OC : FMC Operation Complete flag
FMC_FLAG_PE : FMC Program error flag
FMC_FLAG_WPE : FMC Write protected error flag
Return values
None
Definition at line 697 of file apm32f10x_fmc.c.
References FMC.
Referenced by FLASH_IAP_Init(), and main().
FMC_ConfigLatency()
void FMC_ConfigLatency (FMC_LATENCY_T latency)
Configs the code latency value.
Parameters
latency the FMC Latency value.
Return values
None
Definition at line 49 of file apm32f10x_fmc.c.
References FMC.
Referenced by RCM_Configuration(), and SetSysClock().
FMC_ConfigUserOptionByte()
FMC_STATUS_T FMC_ConfigUserOptionByte (FMC_UserConfig_T * userConfig)
Programs the FMC User Option Byte.
Parameters
userConfig Point to a FMC_UserConfig_T structure.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 533 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, FMC_WaitForLastOperation(), FMC_UserConfig_T::iwdtSet, OB, FMC_UserConfig_T::stdbySet, and FMC_UserConfig_T::stopSet.
FMC_DisableHalfCycleAccess()
void FMC_DisableHalfCycleAccess (void)
Disable the Half cycle flash access.
Parameters
None
Return values
None
Definition at line 73 of file apm32f10x_fmc.c.
References BIT_RESET, and FMC.
FMC_DisableInterrupt()
void FMC_DisableInterrupt (FMC_INT_T interrupt)
Disable the specified FMC interrupts.
Parameters
interrupt Select the FMC interrupt sources This parameter can be one of the following values:
FMC_INT_ERR : Error Interrupt
FMC_INT_OC : Operation Complete Interrupt
Return values
None
Definition at line 647 of file apm32f10x_fmc.c.
References DISABLE, FMC, and FMC_INT_ERR.
FMC_DisablePrefetchBuffer()
void FMC_DisablePrefetchBuffer (void)
Disables the Prefetch Buffer.
Parameters
None
Return values
None
Definition at line 97 of file apm32f10x_fmc.c.
References DISABLE, and FMC.
FMC_DisableReadOutProtection()
FMC_STATUS_T FMC_DisableReadOutProtection (void)
Disables the read out protection.
Parameters
None
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 486 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, FMC_WaitForLastOperation(), and OB.
FMC_EnableHalfCycleAccess()
void FMC_EnableHalfCycleAccess (void)
Enables the Half cycle flash access.
Parameters
None
Return values
None
Definition at line 61 of file apm32f10x_fmc.c.
References BIT_SET, and FMC.
FMC_EnableInterrupt()
void FMC_EnableInterrupt (FMC_INT_T interrupt)
Enables the specified FMC interrupts.
Parameters
interrupt Select the FMC interrupt sources This parameter can be one of the following values:
FMC_INT_ERR : Error Interrupt
FMC_INT_OC : Operation Complete Interrupt
Return values
None
Definition at line 625 of file apm32f10x_fmc.c.
References ENABLE, FMC, and FMC_INT_ERR.
FMC_EnablePrefetchBuffer()
void FMC_EnablePrefetchBuffer (void)
Enables the Prefetch Buffer.
Parameters
None
Return values
None
Definition at line 85 of file apm32f10x_fmc.c.
References ENABLE, and FMC.
Referenced by RCM_Configuration(), and SetSysClock().
FMC_EnableReadOutProtection()
FMC_STATUS_T FMC_EnableReadOutProtection (void)
Enables the read out protection.
Parameters
None
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 438 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, FMC_WaitForLastOperation(), and OB.
FMC_EnableWriteProtection()
FMC_STATUS_T FMC_EnableWriteProtection (uint32_t page)
Write protects the desired pages.
Parameters
page:the address of the pages to be write protection This parameter can be any combination of the following values: for APM32F10X_LD :
FLASH_WRP_PAGE_0_3 to FLASH_WRP_PAGE_28_31 for APM32F10X_MD :
FLASH_WRP_PAGE_0_3 to FLASH_WRP_PAGE_124_127 for APM32F10X_HD :
FLASH_WRP_PAGE_0_1 to FLASH_WRP_PAGE_60_61 or FLASH_WRP_PAGE_62_127
FMC_WRP_PAGE_ALL
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 379 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, FMC_WaitForLastOperation(), and OB.
Referenced by main().
FMC_EraseAllPage()
FMC_STATUS_T FMC_EraseAllPage (void)
Erases all FMC pages.
Parameters
None
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 167 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, and FMC_WaitForLastOperation().
FMC_EraseOptionBytes()
FMC_STATUS_T FMC_EraseOptionBytes (void)
Erases the FMC option bytes.
Parameters
None
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 194 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_GetReadProtectionStatus(), FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, FMC_WaitForLastOperation(), OB, and RESET.
Referenced by main().
FMC_ErasePage()
FMC_STATUS_T FMC_ErasePage (uint32_t pageAddr)
Erases a specified FMC page.
Parameters
pageAddr The page address to be erased.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_BUSY
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 139 of file apm32f10x_fmc.c.
References BIT_RESET, BIT_SET, FMC, FMC_STATUS_COMPLETE, and FMC_WaitForLastOperation().
Referenced by FLASH_IAP_Erase(), and main().
FMC_GetReadProtectionStatus()
uint8_t FMC_GetReadProtectionStatus (void)
Get the FMC Read Out Protection Status is set or not.
Parameters
None
Return values
status : set or reset.
Definition at line 588 of file apm32f10x_fmc.c.
References FMC, RESET, and SET.
Referenced by FMC_EraseOptionBytes().
FMC_Lock()
void FMC_Lock (void)
Locks the FMC Program Erase Controller.
Parameters
None
Return values
None
Definition at line 122 of file apm32f10x_fmc.c.
References BIT_SET, and FMC.
Referenced by Jump_to_App(), and main().
FMC_ProgramHalfWord()
FMC_STATUS_T FMC_ProgramHalfWord (uint32_t address, uint16_t data)
Programs a half word at a specified address.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 300 of file apm32f10x_fmc.c.
References __IOM, BIT_RESET, BIT_SET, data, FMC, FMC_STATUS_COMPLETE, and FMC_WaitForLastOperation().
FMC_ProgramOptionByteData()
FMC_STATUS_T FMC_ProgramOptionByteData (uint32_t address, uint8_t data)
Programs a half word at a specified Option Byte Data address.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 338 of file apm32f10x_fmc.c.
References __IOM, BIT_RESET, BIT_SET, data, FMC, FMC_STATUS_COMPLETE, FMC_STATUS_TIMEOUT, and FMC_WaitForLastOperation().
FMC_ProgramWord()
FMC_STATUS_T FMC_ProgramWord (uint32_t address, uint32_t data)
Programs a word at a specified address.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Definition at line 246 of file apm32f10x_fmc.c.
References __IOM, BIT_RESET, BIT_SET, data, FMC, FMC_STATUS_COMPLETE, and FMC_WaitForLastOperation().
Referenced by FLASH_IAP_Write(), and main().
FMC_ReadOptionByteWriteProtection()
uint32_t FMC_ReadOptionByteWriteProtection (void)
Read the FMC Write Protection Option Bytes Register value.
Parameters
None
Return values
Returns the value of Option Bytes Write Protection Register.
Definition at line 576 of file apm32f10x_fmc.c.
References FMC.
Referenced by main(), and Select_Menu().
FMC_ReadPrefetchBufferStatus()
uint8_t FMC_ReadPrefetchBufferStatus (void)
FMC Prefetch Buffer status is set or not.
Parameters
None
Return values
status : set or reset.
Definition at line 610 of file apm32f10x_fmc.c.
References FMC.
FMC_ReadStatus()
FMC_STATUS_T FMC_ReadStatus (void)
Read the FMC Status.
Parameters
None
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_BUSY
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
Definition at line 713 of file apm32f10x_fmc.c.
References BIT_SET, FMC, FMC_STATUS_BUSY, FMC_STATUS_COMPLETE, FMC_STATUS_ERROR_PG, and FMC_STATUS_ERROR_WRP.
Referenced by FMC_WaitForLastOperation().
FMC_ReadStatusFlag()
uint8_t FMC_ReadStatusFlag (FMC_FLAG_T flag)
Read FMC flag is set or not.
Parameters
flag status flag of FMC This parameter can be one of the following values:
FMC_FLAG_BUSY : FMC Busy flag
FMC_FLAG_OC : FMC Operation Complete flag
FMC_FLAG_PE : FMC Program error flag
FMC_FLAG_WPE : FMC Write protected error flag
FMC_FLAG_OBE : FMC Option Byte error flag
Return values
flag status : set or reset
Definition at line 672 of file apm32f10x_fmc.c.
References FMC, FMC_FLAG_OBE, RESET, and SET.
FMC_ReadUserOptionByte()
uint32_t FMC_ReadUserOptionByte (void)
Read the FMC User Option Bytes values.
Parameters
None
Return values
Returns User Option Bytes values
Definition at line 564 of file apm32f10x_fmc.c.
References FMC.
FMC_Unlock()
void FMC_Unlock (void)
Unlocks the FMC Program Erase Controller.
Parameters
None
Return values
None
Definition at line 109 of file apm32f10x_fmc.c.
References FMC.
Referenced by FLASH_IAP_Init(), and main().
FMC_WaitForLastOperation()
FMC_STATUS_T FMC_WaitForLastOperation (uint32_t timeOut)
Waits for a Flash operation to complete or a TIMEOUT to occur.
Parameters
timeOut:FMC programming timeout value.
Return values
Returns the flash state.It can be one of value:
FMC_STATUS_ERROR_PG
FMC_STATUS_ERROR_WRP
FMC_STATUS_COMPLETE
FMC_STATUS_TIMEOUT
Check for the Flash Status
Wait for a Flash operation to complete or a TIMEOUT to occur
Definition at line 747 of file apm32f10x_fmc.c.
References FMC_ReadStatus(), FMC_STATUS_BUSY, FMC_STATUS_COMPLETE, and FMC_STATUS_TIMEOUT.
Referenced by FMC_ConfigUserOptionByte(), FMC_DisableReadOutProtection(), FMC_EnableReadOutProtection(), FMC_EnableWriteProtection(), FMC_EraseAllPage(), FMC_EraseOptionBytes(), FMC_ErasePage(), FMC_ProgramHalfWord(), FMC_ProgramOptionByteData(), and FMC_ProgramWord().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU