APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » ADC Driver
Functions
void ADC_Reset (ADC_T *adc)
Reset ADC peripheral registers to their default reset values.
void ADC_Config (ADC_T *adc, ADC_Config_T *adcConfig)
Config the ADC peripheral according to the specified parameters in the adcConfig.
void ADC_ConfigStructInit (ADC_Config_T *adcConfig)
Fills each ADC_Config_T member with its default value.
void ADC_ConfigRegularChannel (ADC_T *adc, uint8_t channel, uint8_t rank, uint8_t sampleTime)
Configures the specified ADC regular channel.
void ADC_Enable (ADC_T *adc)
Enables the specified ADC peripheral.
void ADC_Disable (ADC_T *adc)
Disable the specified ADC peripheral.
void ADC_EnableDMA (ADC_T *adc)
Disable the specified ADC DMA request.
void ADC_DisableDMA (ADC_T *adc)
Disable the specified ADC DMA request.
void ADC_ResetCalibration (ADC_T *adc)
Reset the specified ADC calibration registers.
uint8_t ADC_ReadResetCalibrationStatus (ADC_T *adc)
Reads the specified ADC calibration reset status.
void ADC_StartCalibration (ADC_T *adc)
Starts the specified ADC calibration.
uint8_t ADC_ReadCalibrationStartFlag (ADC_T *adc)
Reads the specified ADC calibration start flag.
void ADC_EnableSoftwareStartConv (ADC_T *adc)
Enables the specified ADC software start conversion.
void ADC_DisableSoftwareStartConv (ADC_T *adc)
Disable the specified ADC software start conversion.
uint8_t ADC_ReadSoftwareStartConvStatus (ADC_T *adc)
Reads the specified ADC Software start conversion Status.
void ADC_ConfigDiscMode (ADC_T *adc, uint8_t number)
Configures the specified ADC regular discontinuous mode.
void ADC_EnableDiscMode (ADC_T *adc)
Enable the specified ADC regular discontinuous mode.
void ADC_DisableDiscMode (ADC_T *adc)
Disable the specified ADC regular discontinuous mode.
void ADC_EnableExternalTrigConv (ADC_T *adc)
Enable the specified ADC regular channel external trigger.
void ADC_DisableExternalTrigConv (ADC_T *adc)
Disable the specified ADC regular channel external trigger.
uint16_t ADC_ReadConversionValue (ADC_T *adc)
Reads the specified ADC conversion result data.
uint32_t ADC_ReadDualModeConversionValue (ADC_T *adc)
Reads the specified ADC conversion result data in dual mode.
void ADC_EnableAutoInjectedConv (ADC_T *adc)
Enable the specified ADC automatic injected group.
void ADC_DisableAutoInjectedConv (ADC_T *adc)
Disable the specified ADC automatic injected group.
void ADC_EnableInjectedDiscMode (ADC_T *adc)
Enable the specified ADC discontinuous mode for injected group.
void ADC_DisableInjectedDiscMode (ADC_T *adc)
Disable the specified ADC discontinuous mode for injected group.
void ADC_ConfigExternalTrigInjectedConv (ADC_T *adc, ADC_EXT_TRIG_INJEC_CONV_T extTrigInjecConv)
Configures the specified ADC external trigger for injected channels conversion.
void ADC_EnableExternalTrigInjectedConv (ADC_T *adc)
Ensable the specified ADC injected channels conversion through.
void ADC_DisableExternalTrigInjectedConv (ADC_T *adc)
Disable the specified ADC injected channels conversion through.
void ADC_EnableSoftwareStartInjectedConv (ADC_T *adc)
Enable the specified ADC start of the injected.
void ADC_DisableSoftwareStartInjectedConv (ADC_T *adc)
Disable the specified ADC start of the injected.
uint8_t ADC_ReadSoftwareStartInjectedConvStatus (ADC_T *adc)
Reads the specified ADC Software start injected conversion Status.
void ADC_ConfigInjectedChannel (ADC_T *adc, uint8_t channel, uint8_t rank, uint8_t sampleTime)
Configures the specified ADC injected channel.
void ADC_ConfigInjectedSequencerLength (ADC_T *adc, uint8_t length)
Configures the specified ADC injected channel.
void ADC_ConfigInjectedOffset (ADC_T *adc, ADC_INJEC_CHANNEL_T channel, uint16_t offSet)
Configures the specified ADC injected channel conversion value offset.
uint16_t ADC_ReadInjectedConversionValue (ADC_T *adc, ADC_INJEC_CHANNEL_T channel)
Reads the ADC injected channel conversion value.
void ADC_EnableAnalogWatchdog (ADC_T *adc, uint32_t analogWatchdog)
Enable the specified ADC analog watchdog.
void ADC_DisableAnalogWatchdog (ADC_T *adc)
Disable the specified ADC analog watchdog.
void ADC_ConfigAnalogWatchdogThresholds (ADC_T *adc, uint16_t highThreshold, uint16_t lowThreshold)
Configures the specified ADC high and low thresholds of the analog watchdog.
void ADC_ConfigAnalogWatchdogSingleChannel (ADC_T *adc, uint8_t channel)
Configures the specified ADC analog watchdog guarded single channel.
void ADC_EnableTempSensorVrefint (ADC_T *adc)
Enable the specified ADC temperature sensor and Vrefint channel.
void ADC_DisableTempSensorVrefint (ADC_T *adc)
Disable the specified ADC temperature sensor and Vrefint channel.
void ADC_EnableInterrupt (ADC_T *adc, uint16_t interrupt)
Enable the specified ADC interrupt.
void ADC_DisableInterrupt (ADC_T *adc, uint16_t interrupt)
Disable the specified ADC interrupt.
uint8_t ADC_ReadStatusFlag (ADC_T *adc, ADC_FLAG_T flag)
Reads the specified ADC flag.
void ADC_ClearStatusFlag (ADC_T *adc, uint8_t flag)
Clears the specified ADC flag.
uint8_t ADC_ReadIntFlag (ADC_T *adc, ADC_INT_T flag)
Reads the specified ADC Interrupt flag.
void ADC_ClearIntFlag (ADC_T *adc, uint16_t flag)
Clears the specified ADC Interrupt pending bits.
Variables
ADC_MODE_T mode
uint8_t scanConvMode
This parameter can be ENABLE or DISABLE.
uint8_t continuosConvMode
This parameter can be ENABLE or DISABLE.
ADC_EXT_TRIG_CONV_T externalTrigConv
ADC_DATA_ALIGN_T dataAlign
uint8_t nbrOfChannel
This parameter must range from 1 to 16.
Detailed Description
Function Documentation
ADC_ClearIntFlag()
void ADC_ClearIntFlag (ADC_T * adc, uint16_t flag)
Clears the specified ADC Interrupt pending bits.
Parameters
adc Select the ADC peripheral.
interrupt Select the ADC interrupt source. This parameter can be any combination of the following values:
ADC_INT_AWD : Enable Analog watchdog interrupt
ADC_INT_EOC : Enable End of conversion interrupt
ADC_INT_INJEOC : Enable End of injected conversion interrupt
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 1055 of file apm32f10x_adc.c.
References ADC_T::STS.
Referenced by ADC1_2_IRQHandler(), and ADC1_Isr().
ADC_ClearStatusFlag()
void ADC_ClearStatusFlag (ADC_T * adc, uint8_t flag)
Clears the specified ADC flag.
Parameters
adc Select the ADC peripheral
flag Select the flag to clear This parameter can be any combination of the following values:
ADC_FLAG_AWD : Analog watchdog flag
ADC_FLAG_EOC : End of conversion flag
ADC_FLAG_INJEOC: End of injected group conversion flag
ADC_FLAG_INJCS : Injected group conversion Start flag
ADC_FLAG_REGCS : Regular group conversion Start flag
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 1000 of file apm32f10x_adc.c.
References ADC_T::STS.
Referenced by ADC_Isr().
ADC_Config()
void ADC_Config (ADC_T * adc, ADC_Config_T * adcConfig)
Config the ADC peripheral according to the specified parameters in the adcConfig.
Parameters
adc Select ADC peripheral.
adcConfig pointer to a ADC_Config_T structure.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 81 of file apm32f10x_adc.c.
References ADC_Config_T::continuosConvMode, ADC_T::CTRL1, ADC_T::CTRL2, ADC_Config_T::dataAlign, ADC_Config_T::externalTrigConv, ADC_Config_T::mode, ADC_Config_T::nbrOfChannel, ADC_T::REGSEQ1, and ADC_Config_T::scanConvMode.
Referenced by ADC_Init(), and main().
ADC_ConfigAnalogWatchdogSingleChannel()
void ADC_ConfigAnalogWatchdogSingleChannel (ADC_T * adc, uint8_t channel)
Configures the specified ADC analog watchdog guarded single channel.
Parameters
adc Select the ADC peripheral
channel Select the ADC channel This parameter can be one of the following values:
ADC_Channel_0: Select ADC Channel 0
ADC_Channel_1: Select ADC Channel 1
ADC_Channel_2: Select ADC Channel 2
ADC_Channel_3: Select ADC Channel 3
ADC_Channel_4: Select ADC Channel 4
ADC_Channel_5: Select ADC Channel 5
ADC_Channel_6: Select ADC Channel 6
ADC_Channel_7: Select ADC Channel 7
ADC_Channel_8: Select ADC Channel 8
ADC_Channel_9: Select ADC Channel 9
ADC_Channel_10: Select ADC Channel 10
ADC_Channel_11: Select ADC Channel 11
ADC_Channel_12: Select ADC Channel 12
ADC_Channel_13: Select ADC Channel 13
ADC_Channel_14: Select ADC Channel 14
ADC_Channel_15: Select ADC Channel 15
ADC_Channel_16: Select ADC Channel 16 which is connected to TempSensor
ADC_Channel_17: Select ADC Channel 17 which is connected to Vrefint
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 881 of file apm32f10x_adc.c.
References ADC_T::AWDCHSEL, BIT_RESET, ADC_T::CTRL1, and ADC_T::CTRL1_B.
Referenced by main().
ADC_ConfigAnalogWatchdogThresholds()
void ADC_ConfigAnalogWatchdogThresholds (ADC_T * adc, uint16_t highThreshold, uint16_t lowThreshold)
Configures the specified ADC high and low thresholds of the analog watchdog.
Parameters
adc Select the ADC peripheral.
highThreshold The ADC analog watchdog High threshold value. This parameter must be a 12bit value.
lowThreshold The ADC analog watchdog Low threshold value. This parameter must be a 12bit value.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 845 of file apm32f10x_adc.c.
References ADC_T::AWDHT, and ADC_T::AWDLT.
Referenced by main().
ADC_ConfigDiscMode()
void ADC_ConfigDiscMode (ADC_T * adc, uint8_t number)
Configures the specified ADC regular discontinuous mode.
Parameters
adc Select the ADC peripheral.
number The number of the discontinuous mode regular channels. This parameter can be between 1 and 8.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 293 of file apm32f10x_adc.c.
References ADC_T::CTRL1_B, and ADC_T::DISCNUMCFG.
ADC_ConfigExternalTrigInjectedConv()
void ADC_ConfigExternalTrigInjectedConv (ADC_T * adc, ADC_EXT_TRIG_INJEC_CONV_T extTrigInjecConv)
Configures the specified ADC external trigger for injected channels conversion.
Parameters
adc Select the ADC peripheral
extTrigInjecConv Select the ADC trigger to start injected conversion This parameter can be one of the following values:
ADC_EXT_TRIG_INJEC_CONV_TMR1_TRGO : Select Timer1 TRGO event (for ADC1, ADC2 and ADC3)
ADC_EXT_TRIG_INJEC_CONV_TMR1_CC4 : Select Timer1 capture compare4 (for ADC1, ADC2 and ADC3)
ADC_EXT_TRIG_INJEC_CONV_TMR2_TRGO : Select Timer2 TRGO event (for ADC1 and ADC2)
ADC_EXT_TRIG_INJEC_CONV_TMR2_CC1 : Select Timer2 capture compare1 (for ADC1 and ADC2)
ADC_EXT_TRIG_INJEC_CONV_TMR3_CC4 : Select Timer3 capture compare4 (for ADC1 and ADC2)
ADC_EXT_TRIG_INJEC_CONV_TMR4_TRGO : Select Timer4 TRGO event selected (for ADC1 and ADC2)
ADC_EXT_TRIG_INJEC_CONV_EINT15_T8_CC4: External interrupt line 15 or Timer8 capture compare4 event (for ADC1 and ADC2)
ADC_EXT_TRIG_INJEC_CONV_TMR4_CC3 : Timer4 capture compare3 selected (for ADC3 only)
ADC_EXT_TRIG_INJEC_CONV_TMR8_CC2 : Timer8 capture compare2 selected (for ADC3 only)
ADC_EXT_TRIG_INJEC_CONV_TMR8_CC4 : Timer8 capture compare4 selected (for ADC3 only)
ADC_EXT_TRIG_INJEC_CONV_TMR5_TRGO: Timer5 TRGO event selected (for ADC3 only)
ADC_EXT_TRIG_INJEC_CONV_TMR5_CC4 : Timer5 capture compare4 selected (for ADC3 only)
ADC_EXT_TRIG_INJEC_CONV_NONE : Injected conversion started by software instead of external trigger (for ADC1, ADC2 and ADC3)
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 562 of file apm32f10x_adc.c.
References ADC_T::CTRL2_B, ADC_T::INJGEXTTRGSEL, and RESET.
ADC_ConfigInjectedChannel()
void ADC_ConfigInjectedChannel (ADC_T * adc, uint8_t channel, uint8_t rank, uint8_t sampleTime)
Configures the specified ADC injected channel.
Parameters
adc Select the ADC peripheral.
channel Select the ADC injected channel. This parameter can be one of the following values:
ADC_CHANNEL_0: ADC channel 0
ADC_CHANNEL_1: ADC channel 1
ADC_CHANNEL_2: ADC channel 2
ADC_CHANNEL_3: ADC channel 3
ADC_CHANNEL_4: ADC channel 4
ADC_CHANNEL_5: ADC channel 5
ADC_CHANNEL_6: ADC channel 6
ADC_CHANNEL_7: ADC channel 7
ADC_CHANNEL_8: ADC channel 8
ADC_CHANNEL_9: ADC channel 9
ADC_CHANNEL_10: ADC channel 10
ADC_CHANNEL_11: ADC channel 11
ADC_CHANNEL_12: ADC channel 12
ADC_CHANNEL_13: ADC channel 13
ADC_CHANNEL_14: ADC channel 14
ADC_CHANNEL_15: ADC channel 15
ADC_CHANNEL_16: ADC channel 16 which is connected to TempSensor
ADC_CHANNEL_17: ADC channel 17 which is connected to Vrefint
rank The rank in the injected group sequencer. This parameter must be between 1 to 4.
sampleTime the specified ADC channel SampleTime The parameter can be one of following values:
ADC_SAMPLETIME_1CYCLES5: ADC 1.5 clock cycles
ADC_SAMPLETIME_7CYCLES5: ADC 7.5 clock cycles
ADC_SAMPLETIME_13CYCLES5: ADC 13.5 clock cycles
ADC_SAMPLETIME_28CYCLES5: ADC 28.5 clock cycles
ADC_SAMPLETIME_41CYCLES5: ADC 41.5 clock cycles
ADC_SAMPLETIME_55CYCLES5: ADC 55.5 clock cycles
ADC_SAMPLETIME_71CYCLES5: ADC 71.5 clock cycles
ADC_SAMPLETIME_239CYCLES5: ADC 239.5 clock cycles
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 686 of file apm32f10x_adc.c.
References ADC_CHANNEL_9, ADC_T::INJSEQ, INJSEQ_SET_INJSEQC, INJSEQ_SET_INJSEQLEN, SMPCYCCFG_SET_SMPTIM1, SMPCYCCFG_SET_SMPTIM2, ADC_T::SMPTIM1, and ADC_T::SMPTIM2.
ADC_ConfigInjectedOffset()
void ADC_ConfigInjectedOffset (ADC_T * adc, ADC_INJEC_CHANNEL_T channel, uint16_t offSet)
Configures the specified ADC injected channel conversion value offset.
Parameters
adc Select the ADC peripheral.
channel Select the ADC injected channel. This parameter can be one of the following values:
ADC_INJEC_CHANNEL_1: select Injected Channel 1
ADC_INJEC_CHANNEL_2: select Injected Channel 2
ADC_INJEC_CHANNEL_3: select Injected Channel 3
ADC_INJEC_CHANNEL_4: select Injected Channel 4
offSet The specified ADC injected channel offset. This parameter must be a 12bit value.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 755 of file apm32f10x_adc.c.
References __IOM.
ADC_ConfigInjectedSequencerLength()
void ADC_ConfigInjectedSequencerLength (ADC_T * adc, uint8_t length)
Configures the specified ADC injected channel.
Parameters
adc Select the ADC peripheral.
length The sequencer length. This parameter must be a number between 1 to 4.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 730 of file apm32f10x_adc.c.
References ADC_T::INJSEQ_B, ADC_T::INJSEQLEN, and RESET.
ADC_ConfigRegularChannel()
void ADC_ConfigRegularChannel (ADC_T * adc, uint8_t channel, uint8_t rank, uint8_t sampleTime)
Configures the specified ADC regular channel.
Parameters
adc Select the ADC peripheral.
channel Select the ADC channel. This parameter can be one of the following values:
ADC_CHANNEL_0: ADC channel 0
ADC_CHANNEL_1: ADC channel 1
ADC_CHANNEL_2: ADC channel 2
ADC_CHANNEL_3: ADC channel 3
ADC_CHANNEL_4: ADC channel 4
ADC_CHANNEL_5: ADC channel 5
ADC_CHANNEL_6: ADC channel 6
ADC_CHANNEL_7: ADC channel 7
ADC_CHANNEL_8: ADC channel 8
ADC_CHANNEL_9: ADC channel 9
ADC_CHANNEL_10: ADC channel 10
ADC_CHANNEL_11: ADC channel 11
ADC_CHANNEL_12: ADC channel 12
ADC_CHANNEL_13: ADC channel 13
ADC_CHANNEL_14: ADC channel 14
ADC_CHANNEL_15: ADC channel 15
ADC_CHANNEL_16: ADC channel 16 which is connected to TempSensor
ADC_CHANNEL_17: ADC channel 17 which is connected to Vrefint
rank The rank in the regular group sequencer This parameter must be between 1 to 16.
sampleTime the specified ADC channel SampleTime The parameter can be one of following values:
ADC_SAMPLETIME_1CYCLES5: ADC 1.5 clock cycles
ADC_SAMPLETIME_7CYCLES5: ADC 7.5 clock cycles
ADC_SAMPLETIME_13CYCLES5: ADC 13.5 clock cycles
ADC_SAMPLETIME_28CYCLES5: ADC 28.5 clock cycles
ADC_SAMPLETIME_41CYCLES5: ADC 41.5 clock cycles
ADC_SAMPLETIME_55CYCLES5: ADC 55.5 clock cycles
ADC_SAMPLETIME_71CYCLES5: ADC 71.5 clock cycles
ADC_SAMPLETIME_239CYCLES5: ADC 239.5 clock cycles
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 370 of file apm32f10x_adc.c.
References ADC_CHANNEL_9, ADC_T::REGSEQ1, ADC_T::REGSEQ2, ADC_T::REGSEQ3, REGSEQC_SET_REGSEQ1, REGSEQC_SET_REGSEQ2, REGSEQC_SET_REGSEQ3, SMPCYCCFG_SET_SMPTIM1, SMPCYCCFG_SET_SMPTIM2, ADC_T::SMPTIM1, and ADC_T::SMPTIM2.
Referenced by ADC_Init(), and main().
ADC_ConfigStructInit()
void ADC_ConfigStructInit (ADC_Config_T * adcConfig)
Fills each ADC_Config_T member with its default value.
Parameters
adcConfig pointer to a ADC_Config_T structure which will be initialized.
Return values
None
Definition at line 111 of file apm32f10x_adc.c.
References ADC_DATA_ALIGN_RIGHT, ADC_EXT_TRIG_CONV_TMR1_CC1, ADC_MODE_INDEPENDENT, ADC_Config_T::continuosConvMode, ADC_Config_T::dataAlign, DISABLE, ADC_Config_T::externalTrigConv, ADC_Config_T::mode, ADC_Config_T::nbrOfChannel, and ADC_Config_T::scanConvMode.
Referenced by ADC_Init().
ADC_Disable()
void ADC_Disable (ADC_T * adc)
Disable the specified ADC peripheral.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 144 of file apm32f10x_adc.c.
References ADC_T::ADCEN, BIT_RESET, and ADC_T::CTRL2_B.
ADC_DisableAnalogWatchdog()
void ADC_DisableAnalogWatchdog (ADC_T * adc)
Disable the specified ADC analog watchdog.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 825 of file apm32f10x_adc.c.
References ADC_T::CTRL1.
ADC_DisableAutoInjectedConv()
void ADC_DisableAutoInjectedConv (ADC_T * adc)
Disable the specified ADC automatic injected group.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 501 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL1_B, and ADC_T::INJGACEN.
ADC_DisableDiscMode()
void ADC_DisableDiscMode (ADC_T * adc)
Disable the specified ADC regular discontinuous mode.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 321 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL1_B, and ADC_T::REGDISCEN.
ADC_DisableDMA()
void ADC_DisableDMA (ADC_T * adc)
Disable the specified ADC DMA request.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 172 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL2_B, and ADC_T::DMAEN.
ADC_DisableExternalTrigConv()
void ADC_DisableExternalTrigConv (ADC_T * adc)
Disable the specified ADC regular channel external trigger.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 445 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL2_B, and ADC_T::REGEXTTRGEN.
ADC_DisableExternalTrigInjectedConv()
void ADC_DisableExternalTrigInjectedConv (ADC_T * adc)
Disable the specified ADC injected channels conversion through.
Parameters
adc Select the ADC peripheral
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 591 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL2_B, and ADC_T::INJEXTTRGEN.
ADC_DisableInjectedDiscMode()
void ADC_DisableInjectedDiscMode (ADC_T * adc)
Disable the specified ADC discontinuous mode for injected group.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 529 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL1_B, and ADC_T::INJDISCEN.
ADC_DisableInterrupt()
void ADC_DisableInterrupt (ADC_T * adc, uint16_t interrupt)
Disable the specified ADC interrupt.
Parameters
adc Select the ADC peripheral.
interrupt Select the ADC interrupt sources This parameter can be any combination of the following values:
ADC_INT_AWD : Disable Analog watchdog interrupt
ADC_INT_EOC : Disable End of conversion interrupt
ADC_INT_INJEOC : Disable End of injected conversion interrupt
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 953 of file apm32f10x_adc.c.
References ADC_T::CTRL1.
ADC_DisableSoftwareStartConv()
void ADC_DisableSoftwareStartConv (ADC_T * adc)
Disable the specified ADC software start conversion.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 260 of file apm32f10x_adc.c.
References ADC_T::CTRL2.
ADC_DisableSoftwareStartInjectedConv()
void ADC_DisableSoftwareStartInjectedConv (ADC_T * adc)
Disable the specified ADC start of the injected.
Parameters
adc Select the ADC peripheral
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 620 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL2_B, ADC_T::INJEXTTRGEN, and ADC_T::INJSWSC.
ADC_DisableTempSensorVrefint()
void ADC_DisableTempSensorVrefint (ADC_T * adc)
Disable the specified ADC temperature sensor and Vrefint channel.
Parameters
adc Select the ADC peripheral
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 910 of file apm32f10x_adc.c.
References BIT_RESET, ADC_T::CTRL2_B, and ADC_T::TSVREFEN.
ADC_Enable()
void ADC_Enable (ADC_T * adc)
Enables the specified ADC peripheral.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 130 of file apm32f10x_adc.c.
References ADC_T::ADCEN, BIT_SET, and ADC_T::CTRL2_B.
Referenced by ADC_Init(), and main().
ADC_EnableAnalogWatchdog()
void ADC_EnableAnalogWatchdog (ADC_T * adc, uint32_t analogWatchdog)
Enable the specified ADC analog watchdog.
Parameters
adc Select the ADC peripheral.
analogWatchdog The ADC analog watchdog configuration This parameter can be one of the following values:
ADC_ANALOG_WATCHDOG_SINGLE_REG : Analog watchdog on a single regular channel
ADC_ANALOG_WATCHDOG_SINGLE_INJEC : Analog watchdog on a single injected channel
ADC_ANALOG_WATCHDOG_SINGLE_REG_INJEC : Analog watchdog on a single regular or injected channel
ADC_ANALOG_WATCHDOG_ALL_REG : Analog watchdog on all regular channel
ADC_ANALOG_WATCHDOG_ALL_INJEC : Analog watchdog on all injected channel
ADC_ANALOG_WATCHDOG_ALL_REG_ALL_INJEC : Analog watchdog on all regular and injected channels
ADC_ANALOG_WATCHDOG_NONE : No channel guarded by the analog watchdog
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 810 of file apm32f10x_adc.c.
References ADC_T::CTRL1.
Referenced by main().
ADC_EnableAutoInjectedConv()
void ADC_EnableAutoInjectedConv (ADC_T * adc)
Enable the specified ADC automatic injected group.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 487 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL1_B, and ADC_T::INJGACEN.
ADC_EnableDiscMode()
void ADC_EnableDiscMode (ADC_T * adc)
Enable the specified ADC regular discontinuous mode.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 307 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL1_B, and ADC_T::REGDISCEN.
ADC_EnableDMA()
void ADC_EnableDMA (ADC_T * adc)
Disable the specified ADC DMA request.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 158 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL2_B, and ADC_T::DMAEN.
Referenced by ADC_Init().
ADC_EnableExternalTrigConv()
void ADC_EnableExternalTrigConv (ADC_T * adc)
Enable the specified ADC regular channel external trigger.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 431 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL2_B, and ADC_T::REGEXTTRGEN.
ADC_EnableExternalTrigInjectedConv()
void ADC_EnableExternalTrigInjectedConv (ADC_T * adc)
Ensable the specified ADC injected channels conversion through.
Parameters
adc Select the ADC peripheral
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 577 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL2_B, and ADC_T::INJEXTTRGEN.
ADC_EnableInjectedDiscMode()
void ADC_EnableInjectedDiscMode (ADC_T * adc)
Enable the specified ADC discontinuous mode for injected group.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 515 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL1_B, and ADC_T::INJDISCEN.
ADC_EnableInterrupt()
void ADC_EnableInterrupt (ADC_T * adc, uint16_t interrupt)
Enable the specified ADC interrupt.
Parameters
adc Select the ADC peripheral.
interrupt Select the ADC interrupt sources This parameter can be any combination of the following values:
ADC_INT_AWD : Enable Analog watchdog interrupt
ADC_INT_EOC : Enable End of conversion interrupt
ADC_INT_INJEOC : Enable End of injected conversion interrupt
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 930 of file apm32f10x_adc.c.
References ADC_T::CTRL1.
Referenced by ADC_Init(), and main().
ADC_EnableSoftwareStartConv()
void ADC_EnableSoftwareStartConv (ADC_T * adc)
Enables the specified ADC software start conversion.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 246 of file apm32f10x_adc.c.
References ADC_T::CTRL2.
Referenced by ADC_Init(), and main().
ADC_EnableSoftwareStartInjectedConv()
void ADC_EnableSoftwareStartInjectedConv (ADC_T * adc)
Enable the specified ADC start of the injected.
Parameters
adc Select the ADC peripheral
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 605 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL2_B, ADC_T::INJEXTTRGEN, and ADC_T::INJSWSC.
ADC_EnableTempSensorVrefint()
void ADC_EnableTempSensorVrefint (ADC_T * adc)
Enable the specified ADC temperature sensor and Vrefint channel.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 896 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CTRL2_B, and ADC_T::TSVREFEN.
ADC_ReadCalibrationStartFlag()
uint8_t ADC_ReadCalibrationStartFlag (ADC_T * adc)
Reads the specified ADC calibration start flag.
Parameters
adc Select the ADC peripheral.
Return values
The status of ADC calibration start.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 230 of file apm32f10x_adc.c.
References BIT_RESET, BIT_SET, ADC_T::CAL, and ADC_T::CTRL2_B.
Referenced by ADC_Init(), and main().
ADC_ReadConversionValue()
uint16_t ADC_ReadConversionValue (ADC_T * adc)
Reads the specified ADC conversion result data.
Parameters
adc Select the ADC peripheral.
Return values
The Data conversion value.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 459 of file apm32f10x_adc.c.
References ADC_T::REGDATA.
Referenced by ADC1_Isr(), and ADC_Isr().
ADC_ReadDualModeConversionValue()
uint32_t ADC_ReadDualModeConversionValue (ADC_T * adc)
Reads the specified ADC conversion result data in dual mode.
Parameters
adc Select the ADC peripheral.
Return values
The Data conversion value.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 473 of file apm32f10x_adc.c.
References __IOM, and RDG_ADDRESS.
ADC_ReadInjectedConversionValue()
uint16_t ADC_ReadInjectedConversionValue (ADC_T * adc, ADC_INJEC_CHANNEL_T channel)
Reads the ADC injected channel conversion value.
Parameters
adc Select the ADC peripheral.
channel Select the ADC injected channel. This parameter can be one of the following values:
ADC_INJEC_CHANNEL_1: select Injected Channel 1
ADC_INJEC_CHANNEL_2: select Injected Channel 2
ADC_INJEC_CHANNEL_3: select Injected Channel 3
ADC_INJEC_CHANNEL_4: select Injected Channel 4
Return values
The Data of conversion value.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 781 of file apm32f10x_adc.c.
References __IOM, and INJDATA_OFFSET.
ADC_ReadIntFlag()
uint8_t ADC_ReadIntFlag (ADC_T * adc, ADC_INT_T flag)
Reads the specified ADC Interrupt flag.
Parameters
adc Select the ADC peripheral.
interrupt Select the ADC interrupt source. This parameter can be one of the following values:
ADC_INT_AWD : Enable Analog watchdog interrupt
ADC_INT_EOC : Enable End of conversion interrupt
ADC_INT_INJEOC : Enable End of injected conversion interrupt
Return values
The status of ADC interrupt
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 1020 of file apm32f10x_adc.c.
References ADC_T::CTRL1, RESET, SET, and ADC_T::STS.
Referenced by ADC1_Isr().
ADC_ReadResetCalibrationStatus()
uint8_t ADC_ReadResetCalibrationStatus (ADC_T * adc)
Reads the specified ADC calibration reset status.
Parameters
adc Select the ADC peripheral.
Return values
The status of ADC calibration reset.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 200 of file apm32f10x_adc.c.
References BIT_RESET, BIT_SET, ADC_T::CALRST, and ADC_T::CTRL2_B.
Referenced by ADC_Init(), and main().
ADC_ReadSoftwareStartConvStatus()
uint8_t ADC_ReadSoftwareStartConvStatus (ADC_T * adc)
Reads the specified ADC Software start conversion Status.
Parameters
adc Select the ADC peripheral.
Return values
The status of ADC Software start conversion registers.
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 274 of file apm32f10x_adc.c.
References BIT_RESET, BIT_SET, ADC_T::CTRL2_B, and ADC_T::REGSWSC.
ADC_ReadSoftwareStartInjectedConvStatus()
uint8_t ADC_ReadSoftwareStartInjectedConvStatus (ADC_T * adc)
Reads the specified ADC Software start injected conversion Status.
Parameters
adc Select the ADC peripheral
Return values
The status of ADC Software start injected conversion
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 635 of file apm32f10x_adc.c.
References BIT_RESET, BIT_SET, ADC_T::CTRL2_B, and ADC_T::INJSWSC.
ADC_ReadStatusFlag()
uint8_t ADC_ReadStatusFlag (ADC_T * adc, ADC_FLAG_T flag)
Reads the specified ADC flag.
Parameters
adc Select the ADC peripheral
flag Select the flag to check This parameter can be one of the following values:
ADC_FLAG_AWD : Analog watchdog flag
ADC_FLAG_EOC : End of conversion flag
ADC_FLAG_INJEOC: End of injected group conversion flag
ADC_FLAG_INJCS : Injected group conversion Start flag
ADC_FLAG_REGCS : Regular group conversion Start flag
Return values
The status of ADC flag
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 978 of file apm32f10x_adc.c.
References RESET, SET, and ADC_T::STS.
Referenced by ADC_Isr().
ADC_Reset()
void ADC_Reset (ADC_T * adc)
Reset ADC peripheral registers to their default reset values.
Parameters
adc Select ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 51 of file apm32f10x_adc.c.
References ADC1, ADC2, ADC3, RCM_APB2_PERIPH_ADC1, RCM_APB2_PERIPH_ADC2, RCM_APB2_PERIPH_ADC3, RCM_DisableAPB2PeriphReset(), and RCM_EnableAPB2PeriphReset().
Referenced by ADC_Init().
ADC_ResetCalibration()
void ADC_ResetCalibration (ADC_T * adc)
Reset the specified ADC calibration registers.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 186 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CALRST, and ADC_T::CTRL2_B.
Referenced by ADC_Init(), and main().
ADC_StartCalibration()
void ADC_StartCalibration (ADC_T * adc)
Starts the specified ADC calibration.
Parameters
adc Select the ADC peripheral.
Return values
None
Note
adc can be ADC1, ADC2 or ADC3.
Definition at line 216 of file apm32f10x_adc.c.
References BIT_SET, ADC_T::CAL, and ADC_T::CTRL2_B.
Referenced by ADC_Init(), and main().
Variable Documentation
continuosConvMode
uint8_t continuosConvMode
This parameter can be ENABLE or DISABLE.
Definition at line 249 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
dataAlign
ADC_DATA_ALIGN_T dataAlign
Definition at line 251 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
externalTrigConv
ADC_EXT_TRIG_CONV_T externalTrigConv
Definition at line 250 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
mode
ADC_MODE_T mode
Definition at line 247 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
nbrOfChannel
uint8_t nbrOfChannel
This parameter must range from 1 to 16.
Definition at line 252 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
scanConvMode
uint8_t scanConvMode
This parameter can be ENABLE or DISABLE.
Definition at line 248 of file apm32f10x_adc.h.
Referenced by ADC_Config(), ADC_ConfigStructInit(), ADC_Init(), and main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU