APM32F10x_SDK: Functions
Functions
Examples » IAP_Application2
Functions
int main (void)
Main program.
void Delay (void)
Delay.
Detailed Description
Function Documentation
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 79 of file IAP/IAP_Application2/Source/main.c.
References tick.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 57 of file IAP/IAP_Application2/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDToggle(), Delay(), FMC_BASE, LED3, and SystemCoreClock.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU