APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device | USB OTG Library » Core Host » Class » HID
Typedefs
typedef void(* HID_REQ_Handler_T) (void)
typedef void(* HID_Handler_T) (void)
Functions
void USBD_ClassHandler (USBD_DevReqData_T *reqData)
USB HID Class request handler.
void USBH_HID_InitHandler (void)
USB Host Class Initialization.
void USBH_HID_DeInitHandler (void)
USB Host Class Re-Initialization.
void USBH_HID_ReqHandler (void)
USB Host Class Request handler.
void USBH_HID_CoreHandler (void)
USB Host Class Core handler.
void ParseMouseData (uint8_t *rBuf)
Parse Mouse Data.
Detailed Description
Typedef Documentation
HID_Handler_T
typedef void(* HID_Handler_T) (void)
Definition at line 98 of file usbh_class_hid.h.
HID_REQ_Handler_T
typedef void(* HID_REQ_Handler_T) (void)
Definition at line 97 of file usbh_class_hid.h.
Function Documentation
ParseMouseData()
void ParseMouseData (uint8_t * rBuf)
Parse Mouse Data.
Parameters
rBuf : Buffer to be Parsed.
Return values
None
Definition at line 539 of file usbh_class_hid.c.
References HID_MOUSE_Data_T::button, mouseData, mouseSeat, printMouse, HID_MOUSE_Data_T::x, and HID_MOUSE_Data_T::y.
USBD_ClassHandler()
void USBD_ClassHandler (USBD_DevReqData_T * reqData)
USB HID Class request handler.
USB CDC Class request handler.
Parameters
reqData : point to USBD_DevReqData_T structure
Return values
None
Definition at line 66 of file USB_OTG_Lib/Core_Device/Class/src/usbd_class_hid.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, USBD_DevReqData_T::bRequest, USBD_DevReqData_T::byte, USBD_REQ_TYPE_T::dir, USBD_DevReqData_T::domain, HID_CLASS_REQ_GET_IDLE, HID_CLASS_REQ_GET_PROTOCOL, HID_CLASS_REQ_SET_IDLE, HID_CLASS_REQ_SET_PROTOCOL, USB_EP_0, USB_OTG_SetStall(), USBD_CtrlInData(), USBD_CtrlOutData(), USBD_CtrlRxStatus, USBD_CtrlTxStatus, USBD_DevReqData_T::wLength, and USBD_DevReqData_T::wValue.
Referenced by CDC_Init(), HidMouse_Init(), USBD_HID_Init(), and USBD_VCP_Init().
USBH_HID_CoreHandler()
void USBH_HID_CoreHandler (void)
USB Host Class Core handler.
Parameters
None
Return values
None
Definition at line 174 of file usbh_class_hid.c.
References USB_UserCallBack_T::applicationHandler, g_userCallback, HID_Handler, and s_classState.
Referenced by USBH_HID_Init().
USBH_HID_DeInitHandler()
void USBH_HID_DeInitHandler (void)
USB Host Class Re-Initialization.
Parameters
None
Return values
None
Definition at line 141 of file usbh_class_hid.c.
References HID_IDLE, HID_REQ_IDLE, s_classReqState, and s_classState.
Referenced by USBH_HID_Init().
USBH_HID_InitHandler()
void USBH_HID_InitHandler (void)
USB Host Class Initialization.
Parameters
None
Return values
None
Definition at line 119 of file usbh_class_hid.c.
References USBH_Info_T::curHostState, g_usbHost, hidDataInChannel, USBH_Info_T::preHostState, USB_EP_TYPE_INTERRUPT, USBH_CH_AllocChannel(), USBH_CH_OpenChannel(), USBH_DEVICE_CONFIGURED_ADDRESS, and USBH_HOST_CLASS_REQ.
Referenced by USBH_HID_Init().
USBH_HID_ReqHandler()
void USBH_HID_ReqHandler (void)
USB Host Class Request handler.
Parameters
None
Return values
None
Definition at line 154 of file usbh_class_hid.c.
References USBH_Info_T::curHostState, g_usbHost, HID_REQ_CONFIGURED_OK, HID_REQ_Handler, HID_REQ_IDLE, s_classReqState, and USBH_HOST_CLASS.
Referenced by USBH_HID_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU