APM32F10x_SDK: Functions
Functions
Examples » USART_LIN
Functions
void Delay (void)
Delay.
void LIN_MasterISR (void)
Transmits Sync Segment.
void LIN_SlaveISR (void)
Transmits Sync Segment.
void LINInit (void)
USART2 and USART3 LIN mode initializes functions.
void LIN_MasterSendSlave (void)
The master sends data to the slave test function.
void LIN_MasterReadSlave (void)
Master read slave data test function.
uint8_t LIN_CheckPID (uint8_t id)
ID check.
uint8_t LIN_Checksum (uint8_t id, uint8_t *data)
Transmits Sync Segment.
void LIN_SendHead (USART_T *usart, LIN_Message_T LINMessage)
The master header frame sending function.
void LIN_SendAnswer (USART_T *usart, LIN_Message_T LINMessage)
Transmits Sync Segment.
uint8_t LIN_SlaveReceivedProces (void)
Transmits Sync Segment.
uint8_t LIN_MasterReceivedProces (void)
Transmits Sync Segment.
int main (void)
Main program.
void LIN_SendBreak (USART_T *usart)
Transmits break characters.
void LIN_SendSyncSegment (USART_T *usart)
Transmits Sync Segment.
void LIN_TxData (USART_T *usart, uint8_t *data)
Transmits Sync Segment.
Detailed Description
Function Documentation
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 709 of file USART/USART_LIN/Source/main.c.
References tick.
LIN_CheckPID()
uint8_t LIN_CheckPID (uint8_t id)
ID check.
Parameters
id frame ID
Return values
None
Definition at line 421 of file USART/USART_LIN/Source/main.c.
Referenced by LIN_Checksum(), and LIN_SendHead().
LIN_Checksum()
uint8_t LIN_Checksum (uint8_t id, uint8_t * data)
Transmits Sync Segment.
Parameters
id frame ID
data frame data
Return values
None
Definition at line 445 of file USART/USART_LIN/Source/main.c.
References data, and LIN_CheckPID().
Referenced by LIN_MasterReadSlave(), LIN_MasterReceivedProces(), LIN_MasterSendSlave(), LIN_SendAnswer(), LIN_SlaveISR(), and LIN_SlaveReceivedProces().
LIN_MasterISR()
void LIN_MasterISR (void)
Transmits Sync Segment.
Parameters
None
Return values
None
Definition at line 595 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, MasterReceived, MasterReceiveDataProces, MasterReceivedOverFlag, MasterReceivedProces, SET, USART2, USART_INT_RXBNE, USART_ReadIntFlag(), and USART_RxData().
Referenced by USART2_IRQHandler().
LIN_MasterReadSlave()
void LIN_MasterReadSlave (void)
Master read slave data test function.
Parameters
None
Return values
None
Definition at line 314 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, LIN_Message_T::ID, LIN_Checksum(), LIN_MasterReceivedProces(), LIN_SendHead(), MasterReceived, MasterReceivedOverFlag, MasterSend, SlaveReceived, SlaveSend, SUCCESS, and USART2.
Referenced by main().
LIN_MasterReceivedProces()
uint8_t LIN_MasterReceivedProces (void)
Transmits Sync Segment.
Parameters
None
Return values
ERROR/SUCCESS data verify is failed/successful.
Definition at line 563 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, ERROR, LIN_Message_T::ID, LIN_Checksum(), MasterReceived, MasterSend, SlaveReceived, SlaveSend, and SUCCESS.
Referenced by LIN_MasterReadSlave().
LIN_MasterSendSlave()
void LIN_MasterSendSlave (void)
The master sends data to the slave test function.
Parameters
None
Return values
None
Definition at line 254 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, Delay(), LIN_Message_T::ID, LIN_Checksum(), LIN_SendAnswer(), LIN_SendHead(), LIN_SlaveReceivedProces(), MasterSend, SlaveReceived, SlaveReceivedOverFlag, SUCCESS, and USART2.
Referenced by main().
LIN_SendAnswer()
void LIN_SendAnswer (USART_T * usart, LIN_Message_T LINMessage)
Transmits Sync Segment.
Parameters
usart Select the USART or the UART peripheral
LINMessage LIN Message strucstruct @LIN_Message_T
Return values
None
Definition at line 514 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::data, LIN_Message_T::ID, LIN_Checksum(), LIN_TxData(), RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
Referenced by LIN_MasterSendSlave().
LIN_SendBreak()
void LIN_SendBreak (USART_T * usart)
Transmits break characters.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Definition at line 372 of file USART/USART_LIN/Source/main.c.
References USART_TxBreak().
Referenced by LIN_SendHead().
LIN_SendHead()
void LIN_SendHead (USART_T * usart, LIN_Message_T LINMessage)
The master header frame sending function.
Parameters
usart Select the USART or the UART peripheral
LINMessage LIN Message strucstruct @LIN_Message_T
Return values
None
Definition at line 403 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::ID, LIN_CheckPID(), LIN_SendBreak(), LIN_SendSyncSegment(), RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
Referenced by LIN_MasterReadSlave(), and LIN_MasterSendSlave().
LIN_SendSyncSegment()
void LIN_SendSyncSegment (USART_T * usart)
Transmits Sync Segment.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Definition at line 385 of file USART/USART_LIN/Source/main.c.
References RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
Referenced by LIN_SendHead().
LIN_SlaveISR()
void LIN_SlaveISR (void)
Transmits Sync Segment.
Parameters
None
Return values
None
Definition at line 636 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, LIN_Message_T::ID, LIN_Checksum(), LIN_TxData(), RESET, SET, SlaveReceived, SlaveReceivedDataProces, SlaveReceivedflag, SlaveReceivedOverFlag, SlaveReceivedProces, SlaveSend, USART3, USART_FLAG_TXBE, USART_INT_RXBNE, USART_ReadIntFlag(), USART_ReadStatusFlag(), USART_RxData(), and USART_TxData().
Referenced by USART3_IRQHandler().
LIN_SlaveReceivedProces()
uint8_t LIN_SlaveReceivedProces (void)
Transmits Sync Segment.
Parameters
None
Return values
ERROR/SUCCESS data verify is failed/successful.
Definition at line 531 of file USART/USART_LIN/Source/main.c.
References LIN_Message_T::CheckSum, LIN_Message_T::data, ERROR, LIN_Message_T::ID, LIN_Checksum(), MasterSend, SlaveReceived, and SUCCESS.
Referenced by LIN_MasterSendSlave().
LIN_TxData()
void LIN_TxData (USART_T * usart, uint8_t * data)
Transmits Sync Segment.
Parameters
usart Select the USART or the UART peripheral
data frame data
Return values
None
Definition at line 489 of file USART/USART_LIN/Source/main.c.
References data, RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
Referenced by LIN_SendAnswer(), and LIN_SlaveISR().
LINInit()
void LINInit (void)
USART2 and USART3 LIN mode initializes functions.
Parameters
None
Return values
None
Note
Definition at line 167 of file USART/USART_LIN/Source/main.c.
References USART_Config_T::baudRate, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_2, GPIO_PIN_3, GPIO_SPEED_50MHz, GPIOA, GPIOB, USART_Config_T::hardwareFlow, GPIO_Config_T::mode, USART_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_2, USART_Config_T::parity, GPIO_Config_T::pin, RCM_APB1_PERIPH_USART2, RCM_APB1_PERIPH_USART3, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART2, USART3, USART_Config(), USART_ConfigLINBreakDetectLength(), USART_Enable(), USART_EnableInterrupt(), USART_EnableLIN(), USART_HARDWARE_FLOW_NONE, USART_INT_RXBNE, USART_LBDL_10B, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 110 of file USART/USART_LIN/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDToggle(), USART_Config_T::baudRate, COM1, Delay(), USART_Config_T::hardwareFlow, LED2, LED3, LIN_MasterReadSlave(), LIN_MasterSendSlave(), LINInit(), USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, SystemCoreClock, SystemCoreClockUpdate(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU