APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » USART Driver
Functions
void USART_Reset (USART_T *usart)
Reset usart peripheral registers to their default reset values.
void USART_Config (USART_T *uart, USART_Config_T *usartConfig)
Configures the USART peripheral according to the specified parameters in the usartConfig.
void USART_ConfigStructInit (USART_Config_T *usartConfig)
Fills each USART_InitStruct member with its default value.
void USART_Address (USART_T *usart, uint8_t address)
Configures the address of the USART node.
void USART_Enable (USART_T *usart)
Enable the specified USART peripheral.
void USART_Disable (USART_T *usart)
Disable the specified USART peripheral.
void USART_ConfigClock (USART_T *usart, USART_ClockConfig_T *clockConfig)
Configures communication clock.
void USART_ConfigClockStructInit (USART_ClockConfig_T *clockConfig)
Fills each clockConfig member with its default value.
void USART_EnableDMA (USART_T *usart, USART_DMA_T dmaReq)
Enable the USART DMA interface.
void USART_DisableDMA (USART_T *usart, USART_DMA_T dmaReq)
Disable the USART DMA interface.
void USART_ConfigWakeUp (USART_T *usart, USART_WAKEUP_T wakeup)
Selects the USART WakeUp method.
void USART_EnableMuteMode (USART_T *usart)
Enable USART Receiver in mute mode.
void USART_DisableMuteMode (USART_T *usart)
Disable USART Receiver in active mode.
void USART_ConfigLINBreakDetectLength (USART_T *usart, USART_LBDL_T length)
Set the USART LIN Break detection length.
void USART_EnableLIN (USART_T *usart)
Enable the USART LIN MODE.
void USART_DisableLIN (USART_T *usart)
Disable the USART LIN MODE.
void USART_EnableTx (USART_T *usart)
Transmitter enable.
void USART_DisableTx (USART_T *usart)
Transmitter disable.
void USART_EnableRx (USART_T *usart)
Receiver enable.
void USART_DisableRx (USART_T *usart)
Receiver disable.
void USART_TxData (USART_T *usart, uint16_t data)
Transmits single data.
uint16_t USART_RxData (USART_T *usart)
Return the most recent received data.
void USART_TxBreak (USART_T *usart)
Transmits break characters.
void USART_ConfigGuardTime (USART_T *usart, uint8_t guardTime)
Set the specified USART guard time.
void USART_ConfigPrescaler (USART_T *usart, uint8_t div)
Set the system clock divider number.
void USART_EnableSmartCard (USART_T *usart)
Enable the USART Smart Card mode.
void USART_DisableSmartCard (USART_T *usart)
Disable the USART Smart Card mode.
void USART_EnableSmartCardNACK (USART_T *usart)
Enable NACK transmission.
void USART_DisableSmartCardNACK (USART_T *usart)
Disable NACK transmission.
void USART_EnableHalfDuplex (USART_T *usart)
Enable USART Half Duplex communication.
void USART_DisableHalfDuplex (USART_T *usart)
Disable USART Half Duplex communication.
void USART_ConfigIrDA (USART_T *usart, USART_IRDALP_T IrDAMode)
Configures the USART's IrDA interface.
void USART_EnableIrDA (USART_T *usart)
Enable the USART's IrDA interface.
void USART_DisableIrDA (USART_T *usart)
Disable the USART's IrDA interface.
void USART_EnableInterrupt (USART_T *usart, USART_INT_T interrupt)
Enable the specified USART interrupts.
void USART_DisableInterrupt (USART_T *usart, USART_INT_T interrupt)
Disable the specified USART interrupts.
uint8_t USART_ReadStatusFlag (USART_T *usart, USART_FLAG_T flag)
Read the specified USART flag.
void USART_ClearStatusFlag (USART_T *usart, USART_FLAG_T flag)
Clear the USARTx's pending flags.
uint8_t USART_ReadIntFlag (USART_T *usart, USART_INT_T flag)
Read the specified USART interrupt flag.
void USART_ClearIntFlag (USART_T *usart, USART_INT_T flag)
Clear the USART interrupt pending bits.
Detailed Description
Function Documentation
USART_Address()
void USART_Address (USART_T * usart, uint8_t address)
Configures the address of the USART node.
Parameters
usart Select the USART or the UART peripheral
address Indicates the address of the USART node
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 260 of file apm32f10x_usart.c.
References USART_T::ADDR, and USART_T::CTRL2_B.
USART_ClearIntFlag()
void USART_ClearIntFlag (USART_T * usart, USART_INT_T flag)
Clear the USART interrupt pending bits.
Parameters
usart Select the USART or the UART peripheral
flag Specifies the interrupt pending bit to clear The parameter can be one of following values:
USART_INT_RXBNE: Receive data buffer not empty interrupt
USART_INT_TXC: Transmission complete interrupt
USART_INT_LBD: LIN break detection interrupt
USART_INT_CTS: CTS change interrupt
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 820 of file apm32f10x_usart.c.
References USART_T::STS.
USART_ClearStatusFlag()
void USART_ClearStatusFlag (USART_T * usart, USART_FLAG_T flag)
Clear the USARTx's pending flags.
Parameters
usart Select the USART or the UART peripheral
flag Specifies the flag to clear The parameter can be one of following values:
USART_FLAG_CTS: CTS Change flag (not available for UART4 and UART5)
USART_FLAG_LBD: LIN Break detection flag
USART_FLAG_TXC: Transmission Complete flag
USART_FLAG_RXBNE: Receive data buffer not empty flag
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 748 of file apm32f10x_usart.c.
References USART_T::STS.
Referenced by main(), rt_hw_console_getchar(), and USART_Init().
USART_Config()
void USART_Config (USART_T * uart, USART_Config_T * usartConfig)
Configures the USART peripheral according to the specified parameters in the usartConfig.
Parameters
uart Select the USART or the UART peripheral
usartConfig pointer to a USART_Config_T structure
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 91 of file apm32f10x_usart.c.
References USART_Config_T::baudRate, USART_T::BR, USART_T::CTRL1, USART_T::CTRL2, USART_T::CTRL3, USART_Config_T::hardwareFlow, USART_Config_T::mode, NULL, USART_Config_T::parity, RCM_ReadPCLKFreq(), USART_Config_T::stopBits, USART1, and USART_Config_T::wordLength.
Referenced by APM_MINI_COMInit(), IrDAInit(), LINInit(), main(), SmartcardInit(), USART_FullDuplex_Init(), and USART_Init().
USART_ConfigClock()
void USART_ConfigClock (USART_T * usart, USART_ClockConfig_T * clockConfig)
Configures communication clock.
Parameters
usart Select the USART or the UART peripheral
clockConfig Pointer to a USART_clockConfig_T structure
Return values
None
Note
The usart can be USART1, USART2, USART3
Definition at line 157 of file apm32f10x_usart.c.
References USART_T::CLKEN, USART_ClockConfig_T::clock, USART_T::CPHA, USART_T::CPOL, USART_T::CTRL2_B, USART_ClockConfig_T::lastBit, USART_T::LBCPOEN, USART_ClockConfig_T::phase, and USART_ClockConfig_T::polarity.
Referenced by SmartcardInit(), and USART_FullDuplex_Init().
USART_ConfigClockStructInit()
void USART_ConfigClockStructInit (USART_ClockConfig_T * clockConfig)
Fills each clockConfig member with its default value.
Parameters
clockConfig Pointer to a USART_clockConfig_T structure
Return values
None
Definition at line 173 of file apm32f10x_usart.c.
References USART_ClockConfig_T::clock, USART_ClockConfig_T::lastBit, USART_ClockConfig_T::phase, USART_ClockConfig_T::polarity, USART_CLKEN_DISABLE, USART_CLKPHA_1EDGE, USART_CLKPOL_LOW, and USART_LBCP_DISABLE.
USART_ConfigGuardTime()
void USART_ConfigGuardTime (USART_T * usart, uint8_t guardTime)
Set the specified USART guard time.
Parameters
usart Select the USART or the UART peripheral
guardTime Specifies the guard time
Return values
None
Note
The usart can be USART1, USART2, USART3
Definition at line 470 of file apm32f10x_usart.c.
References USART_T::GRDT, and USART_T::GTPSC_B.
Referenced by SmartcardInit().
USART_ConfigIrDA()
void USART_ConfigIrDA (USART_T * usart, USART_IRDALP_T IrDAMode)
Configures the USART's IrDA interface.
Parameters
usart Select the USART or the UART peripheral
IrDAMode Specifies the IrDA mode This parameter can be one of the following values:
USART_IRDALP_NORMAL: Normal
USART_IRDALP_LOWPOWER: Low-Power
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 588 of file apm32f10x_usart.c.
References USART_T::CTRL3_B, and USART_T::IRLPEN.
Referenced by IrDAInit().
USART_ConfigLINBreakDetectLength()
void USART_ConfigLINBreakDetectLength (USART_T * usart, USART_LBDL_T length)
Set the USART LIN Break detection length.
Parameters
usart Select the USART or the UART peripheral
length Specifies the LIN break detection length This parameter can be one of the following values:
USART_LBDL_10B: 10-bit break detection
USART_LBDL_10B: 11-bit break detection
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 326 of file apm32f10x_usart.c.
References USART_T::CTRL2_B, and USART_T::LBDLCFG.
Referenced by LINInit().
USART_ConfigPrescaler()
void USART_ConfigPrescaler (USART_T * usart, uint8_t div)
Set the system clock divider number.
Parameters
usart Select the USART or the UART peripheral
div specifies the divider number
Return values
None
Note
The usart can be USART1, USART2, USART3
Definition at line 486 of file apm32f10x_usart.c.
References USART_T::GTPSC_B, and USART_T::PSC.
Referenced by IrDAInit(), and SmartcardInit().
USART_ConfigStructInit()
void USART_ConfigStructInit (USART_Config_T * usartConfig)
Fills each USART_InitStruct member with its default value.
Parameters
usartConfig pointer to a USART_Config_T structure which will be initialized
Return values
None
Definition at line 136 of file apm32f10x_usart.c.
References USART_Config_T::baudRate, USART_Config_T::hardwareFlow, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by main().
USART_ConfigWakeUp()
void USART_ConfigWakeUp (USART_T * usart, USART_WAKEUP_T wakeup)
Selects the USART WakeUp method.
Parameters
usart Select the USART or the UART peripheral
wakeup Specifies the selected USART auto baud rate method This parameter can be one of the following values:
USART_WAKEUP_IDLE_LINE: WakeUp by an idle line detection
USART_WAKEUP_ADDRESS_MARK: WakeUp by an address mark
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 279 of file apm32f10x_usart.c.
References USART_T::CTRL1_B, and USART_T::WUPMCFG.
USART_Disable()
void USART_Disable (USART_T * usart)
Disable the specified USART peripheral.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 204 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL1_B, and USART_T::UEN.
USART_DisableDMA()
void USART_DisableDMA (USART_T * usart, USART_DMA_T dmaReq)
Disable the USART DMA interface.
Parameters
usart Select the USART or the UART peripheral
dmaReq Specifies the DMA request This parameter can be one of the following values:
USART_DMA_TX: USART DMA receive request
USART_DMA_RX: USART DMA transmit request
USART_DMA_TX_RX: USART DMA transmit/receive request
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 244 of file apm32f10x_usart.c.
References USART_T::CTRL3.
USART_DisableHalfDuplex()
void USART_DisableHalfDuplex (USART_T * usart)
Disable USART Half Duplex communication.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 570 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL3_B, and USART_T::HDEN.
USART_DisableInterrupt()
void USART_DisableInterrupt (USART_T * usart, USART_INT_T interrupt)
Disable the specified USART interrupts.
Parameters
usart Select the USART or the UART peripheral
interrupt Specifies the USART interrupts sources The parameter can be one of following values:
USART_INT_PE: Parity error interrupt
USART_INT_TXBE: Tansmit data buffer empty interrupt
USART_INT_TXC: Transmission complete interrupt
USART_INT_RXBNE: Receive data buffer not empty interrupt
USART_INT_IDLE: Idle line detection interrupt
USART_INT_LBD: LIN break detection interrupt
USART_INT_CTS: CTS change interrupt
USART_INT_ERR: Error interrupt(Frame error, noise error, overrun error)
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 683 of file apm32f10x_usart.c.
References USART_T::CTRL1, USART_T::CTRL2, and USART_T::CTRL3.
Referenced by SmartcardIRQHandler(), and USART_Init().
USART_DisableIrDA()
void USART_DisableIrDA (USART_T * usart)
Disable the USART's IrDA interface.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 616 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL3_B, and USART_T::IREN.
USART_DisableLIN()
void USART_DisableLIN (USART_T * usart)
Disable the USART LIN MODE.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 354 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL2_B, and USART_T::LINMEN.
USART_DisableMuteMode()
void USART_DisableMuteMode (USART_T * usart)
Disable USART Receiver in active mode.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 307 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL1_B, and USART_T::RXMUTEEN.
USART_DisableRx()
void USART_DisableRx (USART_T * usart)
Receiver disable.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 410 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL1_B, and USART_T::RXEN.
USART_DisableSmartCard()
void USART_DisableSmartCard (USART_T * usart)
Disable the USART Smart Card mode.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The Smart Card mode is not available for UART4 and UART5
Definition at line 514 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL3_B, and USART_T::SCEN.
USART_DisableSmartCardNACK()
void USART_DisableSmartCardNACK (USART_T * usart)
Disable NACK transmission.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The Smart Card mode is not available for UART4 and UART5
Definition at line 542 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL3_B, and USART_T::SCNACKEN.
USART_DisableTx()
void USART_DisableTx (USART_T * usart)
Transmitter disable.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 382 of file apm32f10x_usart.c.
References BIT_RESET, USART_T::CTRL1_B, and USART_T::TXEN.
USART_Enable()
void USART_Enable (USART_T * usart)
Enable the specified USART peripheral.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 190 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL1_B, and USART_T::UEN.
Referenced by APM_MINI_COMInit(), IrDAInit(), LINInit(), main(), SmartcardInit(), USART_FullDuplex_Init(), and USART_Init().
USART_EnableDMA()
void USART_EnableDMA (USART_T * usart, USART_DMA_T dmaReq)
Enable the USART DMA interface.
Parameters
usart Select the USART or the UART peripheral
dmaReq Specifies the DMA request This parameter can be one of the following values:
USART_DMA_TX: USART DMA receive request
USART_DMA_RX: USART DMA transmit request
USART_DMA_TX_RX: USART DMA transmit/receive request
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 224 of file apm32f10x_usart.c.
References USART_T::CTRL3.
Referenced by main().
USART_EnableHalfDuplex()
void USART_EnableHalfDuplex (USART_T * usart)
Enable USART Half Duplex communication.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 556 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL3_B, and USART_T::HDEN.
USART_EnableInterrupt()
void USART_EnableInterrupt (USART_T * usart, USART_INT_T interrupt)
Enable the specified USART interrupts.
Parameters
usart Select the USART or the UART peripheral
interrupt Specifies the USART interrupts sources The parameter can be one of following values:
USART_INT_PE: Parity error interrupt
USART_INT_TXBE: Tansmit data buffer empty interrupt
USART_INT_TXC: Transmission complete interrupt
USART_INT_RXBNE: Receive data buffer not empty interrupt
USART_INT_IDLE: Idle line detection interrupt
USART_INT_LBD: LIN break detection interrupt
USART_INT_CTS: CTS change interrupt
USART_INT_ERR: Error interrupt(Frame error, noise error, overrun error)
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 641 of file apm32f10x_usart.c.
References USART_T::CTRL1, USART_T::CTRL2, and USART_T::CTRL3.
Referenced by LINInit(), main(), SmartcardInit(), and SmartcardIRQHandler().
USART_EnableIrDA()
void USART_EnableIrDA (USART_T * usart)
Enable the USART's IrDA interface.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 602 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL3_B, and USART_T::IREN.
Referenced by IrDAInit().
USART_EnableLIN()
void USART_EnableLIN (USART_T * usart)
Enable the USART LIN MODE.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 340 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL2_B, and USART_T::LINMEN.
Referenced by LINInit().
USART_EnableMuteMode()
void USART_EnableMuteMode (USART_T * usart)
Enable USART Receiver in mute mode.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 293 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL1_B, and USART_T::RXMUTEEN.
USART_EnableRx()
void USART_EnableRx (USART_T * usart)
Receiver enable.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 396 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL1_B, and USART_T::RXEN.
USART_EnableSmartCard()
void USART_EnableSmartCard (USART_T * usart)
Enable the USART Smart Card mode.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The Smart Card mode is not available for UART4 and UART5
Definition at line 500 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL3_B, and USART_T::SCEN.
Referenced by SmartcardInit().
USART_EnableSmartCardNACK()
void USART_EnableSmartCardNACK (USART_T * usart)
Enable NACK transmission.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The Smart Card mode is not available for UART4 and UART5
Definition at line 528 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL3_B, and USART_T::SCNACKEN.
Referenced by SmartcardInit().
USART_EnableTx()
void USART_EnableTx (USART_T * usart)
Transmitter enable.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 368 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL1_B, and USART_T::TXEN.
USART_ReadIntFlag()
uint8_t USART_ReadIntFlag (USART_T * usart, USART_INT_T flag)
Read the specified USART interrupt flag.
Parameters
usart Select the USART or the UART peripheral
flag Specifies the USART interrupt source to check The parameter can be one of following values:
USART_INT_TXBE: Tansmit data buffer empty interrupt
USART_INT_TXC: Transmission complete interrupt
USART_INT_RXBNE: Receive data buffer not empty interrupt
USART_INT_IDLE: Idle line detection interrupt
USART_INT_LBD: LIN break detection interrupt
USART_INT_CTS: CTS change interrupt
USART_INT_OVRE: OverRun Error interruptpt
USART_INT_NE: Noise Error interrupt
USART_INT_FE: Framing Error interrupt
USART_INT_PE: Parity error interrupt
Return values
The new state of flag (SET or RESET)
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 775 of file apm32f10x_usart.c.
References USART_T::CTRL1, USART_T::CTRL2, USART_T::CTRL3, RESET, SET, and USART_T::STS.
Referenced by LIN_MasterISR(), LIN_SlaveISR(), SmartcardIRQHandler(), USART1_Isr(), and USART2_Isr().
USART_ReadStatusFlag()
uint8_t USART_ReadStatusFlag (USART_T * usart, USART_FLAG_T flag)
Read the specified USART flag.
Parameters
usart Select the USART or the UART peripheral
flag Specifies the flag to check The parameter can be one of following values:
USART_FLAG_CTS: CTS Change flag (not available for UART4 and UART5)
USART_FLAG_LBD: LIN Break detection flag
USART_FLAG_TXBE: Transmit data buffer empty flag
USART_FLAG_TXC: Transmission Complete flag
USART_FLAG_RXBNE: Receive data buffer not empty flag
USART_FLAG_IDLE: Idle Line detection flag
USART_FLAG_OVRE: OverRun Error flag
USART_FLAG_NE: Noise Error flag
USART_FLAG_FE: Framing Error flag
USART_FLAG_PE: Parity Error flag
Return values
The new state of flag (SET or RESET)
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 727 of file apm32f10x_usart.c.
References RESET, SET, and USART_T::STS.
Referenced by fputc(), IrDA_USART2_RxData(), IrDA_USART2_TxData(), IrDA_USART3_RxData(), IrDA_USART3_TxData(), LIN_SendAnswer(), LIN_SendHead(), LIN_SendSyncSegment(), LIN_SlaveISR(), LIN_TxData(), main(), rt_hw_console_getchar(), rt_hw_console_output(), SmartcardTest(), Usart_SendString(), and vTaskUsartTest().
USART_Reset()
void USART_Reset (USART_T * usart)
Reset usart peripheral registers to their default reset values.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 51 of file apm32f10x_usart.c.
References RCM_APB1_PERIPH_UART4, RCM_APB1_PERIPH_UART5, RCM_APB1_PERIPH_USART2, RCM_APB1_PERIPH_USART3, RCM_APB2_PERIPH_USART1, RCM_DisableAPB1PeriphReset(), RCM_DisableAPB2PeriphReset(), RCM_EnableAPB1PeriphReset(), RCM_EnableAPB2PeriphReset(), UART4, UART5, USART1, USART2, and USART3.
USART_RxData()
uint16_t USART_RxData (USART_T * usart)
Return the most recent received data.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 440 of file apm32f10x_usart.c.
References USART_T::DATA, and USART_T::DATA_B.
Referenced by IrDA_USART2_RxData(), IrDA_USART3_RxData(), LIN_MasterISR(), LIN_SlaveISR(), main(), rt_hw_console_getchar(), SmartcardIRQHandler(), SmartcardTest(), USART2_Isr(), and vTaskUsartTest().
USART_TxBreak()
void USART_TxBreak (USART_T * usart)
Transmits break characters.
Parameters
usart Select the USART or the UART peripheral
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 454 of file apm32f10x_usart.c.
References BIT_SET, USART_T::CTRL1_B, and USART_T::TXBF.
Referenced by LIN_SendBreak().
USART_TxData()
void USART_TxData (USART_T * usart, uint16_t data)
Transmits single data.
Parameters
usart Select the USART or the UART peripheral
data the data to transmit
Return values
None
Note
The usart can be USART1, USART2, USART3, UART4 and UART5
Definition at line 426 of file apm32f10x_usart.c.
References data, USART_T::DATA, and USART_T::DATA_B.
Referenced by fputc(), IrDA_USART2_TxData(), IrDA_USART3_TxData(), LIN_SendAnswer(), LIN_SendHead(), LIN_SendSyncSegment(), LIN_SlaveISR(), LIN_TxData(), main(), rt_hw_console_output(), USART1_Isr(), Usart_SendString(), and vTaskUsartTest().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU