APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader » BSP_FLASH
Functions
void FLASH_IAP_Init (void)
Unlocks Flash for write access.
uint32_t FLASH_IAP_Erase (APP_TypeDef Application)
Erase of all user flash area.
uint32_t FLASH_IAP_Write (__IO uint32_t *address, uint32_t *data, uint16_t length, APP_TypeDef Application)
Write the appoint data buffer in flash.
Detailed Description
Function Documentation
FLASH_IAP_Erase()
uint32_t FLASH_IAP_Erase (APP_TypeDef Application)
Erase of all user flash area.
Parameters
Application : APP1 or APP2
Return values
SUCCESS user flash area successfully erased ERROR: error occurred
Definition at line 79 of file bsp_flash.c.
References APP1, FLASH_PAGE_SIZE, FLASHStatus, FMC_ErasePage(), FMC_STATUS_COMPLETE, SUCCESS, USER_APP1_END_ADDRESS, USER_APP1_START_ADDRESS, USER_APP2_END_ADDRESS, and USER_APP2_START_ADDRESS.
Referenced by recceiveFile().
FLASH_IAP_Init()
void FLASH_IAP_Init (void)
Unlocks Flash for write access.
Parameters
None
Return values
None
Definition at line 61 of file bsp_flash.c.
References FMC_ClearStatusFlag(), FMC_FLAG_OBE, FMC_FLAG_OC, FMC_FLAG_PE, FMC_FLAG_WPE, and FMC_Unlock().
Referenced by main().
FLASH_IAP_Write()
uint32_t FLASH_IAP_Write (__IO uint32_t * address, uint32_t * data, uint16_t length, APP_TypeDef Application)
Write the appoint data buffer in flash.
Parameters
address start address for writing data buffer
data pointer on data buffer
length length of data buffer (unit is 32-bit word)
Application : APP1 or APP2
Return values
SUCCESS data successfully written to Flash memory ERROR: Error occurred while writing data in Flash memory
Note
buffer data are 32-bit aligned
Definition at line 120 of file bsp_flash.c.
References APP1, data, ERROR, FMC_ProgramWord(), FMC_STATUS_COMPLETE, SUCCESS, USER_APP1_END_ADDRESS, and USER_APP2_END_ADDRESS.
Referenced by recceiveFile().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU