APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » TMR Driver
Functions
void TMR_Reset (TMR_T *tmr)
Deinitialize the TMRx peripheral registers to their default reset values.
void TMR_ConfigTimeBase (TMR_T *tmr, TMR_BaseConfig_T *baseConfig)
Initialize the base timer through the structure.
void TMR_ConfigOC1 (TMR_T *tmr, TMR_OCConfig_T *OCConfig)
Configures channel 1 according to parameters.
void TMR_ConfigOC2 (TMR_T *tmr, TMR_OCConfig_T *OCConfig)
Configures channel 2 according to parameters.
void TMR_ConfigOC3 (TMR_T *tmr, TMR_OCConfig_T *OCConfig)
Configures channel 3 according to parameters.
void TMR_ConfigOC4 (TMR_T *tmr, TMR_OCConfig_T *OCConfig)
Configures channel 4 according to parameters.
void TMR_ConfigIC (TMR_T *tmr, TMR_ICConfig_T *ICConfig)
Configures Peripheral equipment.
void TMR_ConfigBDT (TMR_T *tmr, TMR_BDTConfig_T *BDTConfig)
Configures the: Break feature, dead time, Lock level, the IMOS.
void TMR_ConfigTimeBaseStructInit (TMR_BaseConfig_T *baseConfig)
Initialize the Base timer with its default value.
void TMR_ConfigOCStructInit (TMR_OCConfig_T *OCConfig)
Initialize the OC timer with its default value.
void TMR_ConfigICStructInit (TMR_ICConfig_T *ICConfig)
Initialize the IC timer with its default value.
void TMR_ConfigBDTStructInit (TMR_BDTConfig_T *BDTConfig)
Initialize the BDT timer with its default value.
void TMR_ConfigSinglePulseMode (TMR_T *tmr, TMR_SPM_T singlePulseMode)
Configures the Sing pulse Mode.
void TMR_ConfigClockDivision (TMR_T *tmr, TMR_CLOCK_DIV_T clockDivision)
Configures the Clock Division value.
void TMR_Enable (TMR_T *tmr)
Enable the specified TMR peripheral.
void TMR_Disable (TMR_T *tmr)
Disable the specified TMR peripheral.
void TMR_ConfigPWM (TMR_T *tmr, TMR_ICConfig_T *PWMConfig)
Configures of TMR to PWM input.
void TMR_EnablePWMOutputs (TMR_T *tmr)
Enable TMRx PWM output.
void TMR_DisablePWMOutputs (TMR_T *tmr)
Disable TMRx PWM output.
void TMR_ConfigDMA (TMR_T *tmr, TMR_DMA_BASE_T baseAddress, TMR_DMA_BURSTLENGTH_T burstLength)
Configures the TMRx's DMA interface.
void TMR_EnableDMASoure (TMR_T *tmr, uint16_t dmaSource)
Enable TMRx Requests.
void TMR_DisableDMASoure (TMR_T *tmr, uint16_t dmaSource)
Disable TMRx Requests.
void TMR_ConfigInternalClock (TMR_T *tmr)
Configures the TMRx internal Clock.
void TMR_ConfigIntTrigExternalClock (TMR_T *tmr, TMR_TRIGGER_SOURCE_T triggerSource)
Configures the TMRx Internal Trigger as External Clock.
void TMR_ConfigTrigExternalClock (TMR_T *tmr, TMR_TRIGGER_SOURCE_T triggerSource, TMR_IC_POLARITY_T ICpolarity, uint16_t ICfilter)
Configures the TMRx Trigger as External Clock.
void TMR_ConfigETRClockMode1 (TMR_T *tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the External clock Mode1.
void TMR_ConfigETRClockMode2 (TMR_T *tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the External clock Mode2.
void TMR_ConfigETR (TMR_T *tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the TMRx External Trigger (ETR).
void TMR_ConfigPrescaler (TMR_T *tmr, uint16_t prescaler, TMR_PSC_RELOAD_T pscReloadMode)
Configures the TMRx prescaler.
void TMR_ConfigCounterMode (TMR_T *tmr, TMR_COUNTER_MODE_T countMode)
Configures counter mode.
void TMR_SelectInputTrigger (TMR_T *tmr, TMR_TRIGGER_SOURCE_T triggerSource)
Selects the Input Trigger source.
void TMR_ConfigEncodeInterface (TMR_T *tmr, TMR_ENCODER_MODE_T encodeMode, TMR_IC_POLARITY_T IC1Polarity, TMR_IC_POLARITY_T IC2Polarity)
Configures the Encoder Interface.
void TMR_ConfigForcedOC1 (TMR_T *tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 1 waveform to active or inactive level.
void TMR_ConfigForcedOC2 (TMR_T *tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 2 waveform to active or inactive level.
void TMR_ConfigForcedOC3 (TMR_T *tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 3 waveform to active or inactive level.
void TMR_ConfigForcedOC4 (TMR_T *tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 4 waveform to active or inactive level.
void TMR_EnableAutoReload (TMR_T *tmr)
Enable peripheral Preload register on AUTORLD.
void TMR_DisableAutoReload (TMR_T *tmr)
Disable peripheral Preload register on AUTORLD.
void TMR_EnableSelectCOM (TMR_T *tmr)
Enable Clear the TMR peripheral Commutation event.
void TMR_DisableSelectCOM (TMR_T *tmr)
Disable Clear the TMR peripheral Commutation event.
void TMR_EnableCCDMA (TMR_T *tmr)
Enable Capture Compare DMA source.
void TMR_DisableCCDMA (TMR_T *tmr)
Disable Capture Compare DMA source.
void TMR_EnableCCPreload (TMR_T *tmr)
Enable Capture Compare Preload Control bit.
void TMR_DisableCCPreload (TMR_T *tmr)
Disable Capture Compare Preload Control bit.
void TMR_ConfigOC1Preload (TMR_T *tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM1.
void TMR_ConfigOC2Preload (TMR_T *tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM2.
void TMR_ConfigOC3Preload (TMR_T *tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM3.
void TMR_ConfigOC4Preload (TMR_T *tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM4.
void TMR_ConfigOC1Fast (TMR_T *tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 1 Fast feature.
void TMR_ConfigOC2Fast (TMR_T *tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 2 Fast feature.
void TMR_ConfigOC3Fast (TMR_T *tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 2 Fast feature.
void TMR_ConfigOC4Fast (TMR_T *tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 4 Fast feature.
void TMR_ClearOC1Ref (TMR_T *tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF1 signal on an external event.
void TMR_ClearOC2Ref (TMR_T *tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF2 signal on an external event.
void TMR_ClearOC3Ref (TMR_T *tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF3 signal on an external event.
void TMR_ClearOC4Ref (TMR_T *tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF4 signal on an external event.
void TMR_ConfigOC1Polarity (TMR_T *tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 1 polarity.
void TMR_ConfigOC1NPolarity (TMR_T *tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 1 nPolarity.
void TMR_ConfigOC2Polarity (TMR_T *tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 2 polarity.
void TMR_ConfigOC2NPolarity (TMR_T *tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 2 nPolarity.
void TMR_ConfigOC3Polarity (TMR_T *tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 3 polarity.
void TMR_ConfigOC3NPolarity (TMR_T *tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 3 nPolarity.
void TMR_ConfigOC4Polarity (TMR_T *tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 4 polarity.
void TMR_EnableCCxChannel (TMR_T *tmr, TMR_CHANNEL_T channel)
Enable the Capture Compare Channel x.
void TMR_DisableCCxChannel (TMR_T *tmr, TMR_CHANNEL_T channel)
Disable the Capture Compare Channel x.
void TMR_EnableCCxNChannel (TMR_T *tmr, TMR_CHANNEL_T channel)
Enable the Capture Compare Channelx N.
void TMR_DisableCCxNChannel (TMR_T *tmr, TMR_CHANNEL_T channel)
Disable the Capture Compare Channelx N.
void TMR_SelectOCxMode (TMR_T *tmr, TMR_CHANNEL_T channel, TMR_OC_MODE_T mode)
Selects the Output Compare Mode.
void TMR_EnableUpdate (TMR_T *tmr)
Enable the TMRx update event.
void TMR_DisableUpdate (TMR_T *tmr)
Disable the TMRx update event.
void TMR_ConfigUpdateRequest (TMR_T *tmr, TMR_UPDATE_SOURCE_T updateSource)
Configures the Update Request Interrupt source.
void TMR_EnableHallSensor (TMR_T *tmr)
Enable Hall sensor interface.
void TMR_DisableHallSensor (TMR_T *tmr)
Disable Hall sensor interface.
void TMR_SelectOutputTrigger (TMR_T *tmr, TMR_TRGO_SOURCE_T TRGOSource)
Selects the Trigger Output Mode.
void TMR_SelectSlaveMode (TMR_T *tmr, TMR_SLAVE_MODE_T slaveMode)
Selects the Slave Mode.
void TMR_EnableMasterSlaveMode (TMR_T *tmr)
Enable the Master Slave Mode.
void TMR_DisableMasterSlaveMode (TMR_T *tmr)
Disable the Master Slave Mode.
void TMR_ConfigCounter (TMR_T *tmr, uint16_t counter)
Configures the Counter Register value.
void TMR_ConfigAutoreload (TMR_T *tmr, uint16_t autoReload)
Configures the AutoReload Register value.
void TMR_ConfigCompare1 (TMR_T *tmr, uint16_t compare1)
Configures the Capture Compare1 Register value.
void TMR_ConfigCompare2 (TMR_T *tmr, uint16_t compare2)
Configures the Capture Compare2 Register value.
void TMR_ConfigCompare3 (TMR_T *tmr, uint16_t compare3)
Configures the Capture Compare3 Register value.
void TMR_ConfigCompare4 (TMR_T *tmr, uint16_t compare4)
Configures the Capture Compare4 Register value.
void TMR_ConfigIC1Prescal (TMR_T *tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 1 prescaler.
void TMR_ConfigIC2Prescal (TMR_T *tmr, TMR_IC_PSC_T prescaler)
Sets the TMRx Input Capture 2 prescaler.
void TMR_ConfigIC3Prescal (TMR_T *tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 3 prescaler.
void TMR_ConfigIC4Prescal (TMR_T *tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 4 prescaler.
uint16_t TMR_ReadCaputer1 (TMR_T *tmr)
Read Input Capture 1 value.
uint16_t TMR_ReadCaputer2 (TMR_T *tmr)
Read Input Capture 2 value.
uint16_t TMR_ReadCaputer3 (TMR_T *tmr)
Read Input Capture 3 value.
uint16_t TMR_ReadCaputer4 (TMR_T *tmr)
Read Input Capture 4 value.
uint16_t TMR_ReadCounter (TMR_T *tmr)
Read the TMRx Counter value.
uint16_t TMR_ReadPrescaler (TMR_T *tmr)
Read the TMRx Prescaler value.
void TMR_EnableInterrupt (TMR_T *tmr, uint16_t interrupt)
Enable intterupts.
void TMR_DisableInterrupt (TMR_T *tmr, uint16_t interrupt)
Disable intterupts.
void TMR_GenerateEvent (TMR_T *tmr, uint16_t eventSources)
Configures the TMRx event to be generate by software.
uint16_t TMR_ReadStatusFlag (TMR_T *tmr, TMR_FLAG_T flag)
Check whether the flag is set or reset.
void TMR_ClearStatusFlag (TMR_T *tmr, uint16_t flag)
Clear the TMR's pending flags.
uint16_t TMR_ReadIntFlag (TMR_T *tmr, TMR_INT_T flag)
Check whether the ITflag is set or reset.
void TMR_ClearIntFlag (TMR_T *tmr, uint16_t flag)
Clear the TMR's interrupt pending bits.
Detailed Description
Function Documentation
TMR_ClearIntFlag()
void TMR_ClearIntFlag (TMR_T * tmr, uint16_t flag)
Clear the TMR's interrupt pending bits.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be any combination following values:
TMR_INT_UPDATE: Timer update Interrupt source
TMR_INT_CC1: Timer Capture Compare 1 Interrupt source
TMR_INT_CC2: Timer Capture Compare 2 Interrupt source
TMR_INT_CC3: Timer Capture Compare 3 Interrupt source
TMR_INT_CC4: Timer Capture Compare 4 Interrupt source
TMR_INT_COM: Timer Commutation Interrupt source (Only for TMR1 and TMR8)
TMR_INT_TRG: Timer Trigger Interrupt source
TMR_INT_BRK: Timer Break Interrupt source (Only for TMR1 and TMR8)
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_INT_UPDATE.
Definition at line 1969 of file apm32f10x_tmr.c.
References TMR_T::STS.
Referenced by TMR1_TRG_COM_IRQHandler(), TMR1_UP_IRQHandler(), TMR2_IRQHandler(), TMR2_Isr(), TMR5_IRQHandler(), and USB_Timer_IRQHandler().
TMR_ClearOC1Ref()
void TMR_ClearOC1Ref (TMR_T * tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF1 signal on an external event.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCClear specifies the Output Compare Channel1 Clear The parameter can be one of following values:
TMR_OC_CLEAR_DISABLE
TMR_OC_CLEAR_ENABLE
Return values
None
Definition at line 1126 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC1CEN.
TMR_ClearOC2Ref()
void TMR_ClearOC2Ref (TMR_T * tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF2 signal on an external event.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCClear specifies the Output Compare Channel1 Clear The parameter can be one of following values:
TMR_OC_CLEAR_DISABLE
TMR_OC_CLEAR_ENABLE
Return values
None
Definition at line 1142 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC2CEN.
TMR_ClearOC3Ref()
void TMR_ClearOC3Ref (TMR_T * tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF3 signal on an external event.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCClear specifies the Output Compare Channel1 Clear The parameter can be one of following values:
TMR_OC_CLEAR_DISABLE
TMR_OC_CLEAR_ENABLE
Return values
None
Definition at line 1158 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC3CEN.
TMR_ClearOC4Ref()
void TMR_ClearOC4Ref (TMR_T * tmr, TMR_OC_CLEAR_T OCClear)
Clear or safeguards the OCREF4 signal on an external event.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCClear specifies the Output Compare Channel1 Clear The parameter can be one of following values:
TMR_OC_CLEAR_DISABLE
TMR_OC_CLEAR_ENABLE
Return values
None
Definition at line 1174 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC4CEN.
TMR_ClearStatusFlag()
void TMR_ClearStatusFlag (TMR_T * tmr, uint16_t flag)
Clear the TMR's pending flags.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be any combination of following values:
TMR_FLAG_UPDATE: Timer update Flag
TMR_FLAG_CC1: Timer Capture Compare 1 Flag
TMR_FLAG_CC2: Timer Capture Compare 2 Flag
TMR_FLAG_CC3: Timer Capture Compare 3 Flag
TMR_FLAG_CC4: Timer Capture Compare 4 Flag
TMR_FLAG_COM: Timer Commutation Flag (Only for TMR1 and TMR8)
TMR_FLAG_TRG: Timer Trigger Flag
TMR_FLAG_BRK: Timer Break Flag (Only for TMR1 and TMR8)
TMR_FLAG_CC1RC: Timer Capture Compare 1 Repetition Flag
TMR_FLAG_CC2RC: Timer Capture Compare 2 Repetition Flag
TMR_FLAG_CC3RC: Timer Capture Compare 3 Repetition Flag
TMR_FLAG_CC4RC: Timer Capture Compare 4 Repetition Flag
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_FLAG_UPDATE.
Definition at line 1914 of file apm32f10x_tmr.c.
References TMR_T::STS.
Referenced by main().
TMR_ConfigAutoreload()
void TMR_ConfigAutoreload (TMR_T * tmr, uint16_t autoReload)
Configures the AutoReload Register value.
Parameters
tmr The TMRx can be 1 to 8
autoReload autoReload register new value
Return values
None
Definition at line 1566 of file apm32f10x_tmr.c.
References TMR_T::AUTORLD.
TMR_ConfigBDT()
void TMR_ConfigBDT (TMR_T * tmr, TMR_BDTConfig_T * BDTConfig)
Configures the: Break feature, dead time, Lock level, the IMOS.
Parameters
tmr The TMRx it can be TMR1 and TMR8
BDTConfig Pointer to a TMR_BDTConfig_T structure
Return values
None
Definition at line 312 of file apm32f10x_tmr.c.
References TMR_BDTConfig_T::automaticOutput, TMR_T::BDT, TMR_BDTConfig_T::BRKPolarity, TMR_BDTConfig_T::BRKState, TMR_BDTConfig_T::deadTime, TMR_BDTConfig_T::IMOS, TMR_BDTConfig_T::lockLevel, and TMR_BDTConfig_T::RMOS.
Referenced by main().
TMR_ConfigBDTStructInit()
void TMR_ConfigBDTStructInit (TMR_BDTConfig_T * BDTConfig)
Initialize the BDT timer with its default value.
Parameters
BDTConfig pointer to a TMR_BDTConfig_T
Return values
None
Definition at line 381 of file apm32f10x_tmr.c.
References TMR_BDTConfig_T::automaticOutput, TMR_BDTConfig_T::BRKPolarity, TMR_BDTConfig_T::BRKState, TMR_BDTConfig_T::deadTime, TMR_BDTConfig_T::IMOS, TMR_BDTConfig_T::lockLevel, TMR_BDTConfig_T::RMOS, TMR_AUTOMATIC_OUTPUT_DISABLE, TMR_BRK_POLARITY_LOW, TMR_BRK_STATE_DISABLE, TMR_IMOS_STATE_DISABLE, TMR_LOCK_LEVEL_OFF, and TMR_RMOS_STATE_DISABLE.
TMR_ConfigClockDivision()
void TMR_ConfigClockDivision (TMR_T * tmr, TMR_CLOCK_DIV_T clockDivision)
Configures the Clock Division value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
clockDivision specifies the clock division value. The parameter can be one of following values:
TMR_CLOCK_DIV_1: TDTS = Tck_tim
TMR_CLOCK_DIV_2: TDTS = 2*Tck_tim
TMR_CLOCK_DIV_4: TDTS = 4*Tck_tim
Return values
None
Definition at line 1714 of file apm32f10x_tmr.c.
References TMR_T::CLKDIV, and TMR_T::CTRL1_B.
TMR_ConfigCompare1()
void TMR_ConfigCompare1 (TMR_T * tmr, uint16_t compare1)
Configures the Capture Compare1 Register value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
compare1 specifies the Capture Compare1 value.
Return values
None
Definition at line 1580 of file apm32f10x_tmr.c.
References TMR_T::CC1.
Referenced by TMR2_IRQHandler().
TMR_ConfigCompare2()
void TMR_ConfigCompare2 (TMR_T * tmr, uint16_t compare2)
Configures the Capture Compare2 Register value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
compare2 specifies the Capture Compare1 value.
Return values
None
Definition at line 1594 of file apm32f10x_tmr.c.
References TMR_T::CC2.
Referenced by TMR2_IRQHandler().
TMR_ConfigCompare3()
void TMR_ConfigCompare3 (TMR_T * tmr, uint16_t compare3)
Configures the Capture Compare3 Register value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
compare3 specifies the Capture Compare1 value.
Return values
None
Definition at line 1608 of file apm32f10x_tmr.c.
References TMR_T::CC3.
Referenced by TMR2_IRQHandler().
TMR_ConfigCompare4()
void TMR_ConfigCompare4 (TMR_T * tmr, uint16_t compare4)
Configures the Capture Compare4 Register value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
compare4 specifies the Capture Compare1 value.
Return values
None
Definition at line 1622 of file apm32f10x_tmr.c.
References TMR_T::CC4.
Referenced by TMR2_IRQHandler().
TMR_ConfigCounter()
void TMR_ConfigCounter (TMR_T * tmr, uint16_t counter)
Configures the Counter Register value.
Parameters
tmr The TMRx can be 1 to 8
counter Counter register new value
Return values
None
Definition at line 1552 of file apm32f10x_tmr.c.
References TMR_T::CNT.
Referenced by main(), and TMR1_UP_IRQHandler().
TMR_ConfigCounterMode()
void TMR_ConfigCounterMode (TMR_T * tmr, TMR_COUNTER_MODE_T countMode)
Configures counter mode.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
countMode specifies the Counter Mode to be used The parameter can be one of following values:
TMR_COUNTER_MODE_UP: Timer Up Counting Mode
TMR_COUNTER_MODE_DOWN: Timer Down Counting Mode
TMR_COUNTER_MODE_CENTERALIGNED1: Timer Center Aligned Mode1
TMR_COUNTER_MODE_CENTERALIGNED2: Timer Center Aligned Mode2
TMR_COUNTER_MODE_CENTERALIGNED3: Timer Center Aligned Mode3
Return values
None
Definition at line 752 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CAMSEL, TMR_T::CNTDIR, TMR_T::CTRL1, and TMR_T::CTRL1_B.
TMR_ConfigDMA()
void TMR_ConfigDMA (TMR_T * tmr, TMR_DMA_BASE_T baseAddress, TMR_DMA_BURSTLENGTH_T burstLength)
Configures the TMRx's DMA interface.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
baseAddress pointer to a TMR_DMA_BASE_T
burstLength pointer to a TMR_DMA_BURSTLENGTH_T
Return values
None
Definition at line 516 of file apm32f10x_tmr.c.
References TMR_T::DCTRL.
Referenced by main().
TMR_ConfigEncodeInterface()
void TMR_ConfigEncodeInterface (TMR_T * tmr, TMR_ENCODER_MODE_T encodeMode, TMR_IC_POLARITY_T IC1Polarity, TMR_IC_POLARITY_T IC2Polarity)
Configures the Encoder Interface.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
encodeMode specifies the Encoder Mode The parameter can be one of following values:
TMR_ENCODER_MODE_TI1: Counter counts on TI1FP1 edge depending on TI2FP2 level
TMR_ENCODER_MODE_TI2: Counter counts on TI2FP2 edge depending on TI1FP1 level
TMR_ENCODER_MODE_TI12: Counter counts on both TI1FP1 and TI2FP2 edges depending on the level of the other input
IC1Polarity specifies the TMR IC1 polarity The parameter can be one of following values:
TMR_IC_POLARITY_RISING: TMR IC polarity rising
TMR_IC_POLARITY_FALLING: TMR IC polarity falling
IC2Polarity specifies the TMR IC2 polarity The parameter can be one of following values:
TMR_IC_POLARITY_RISING: TMR IC polarity rising
TMR_IC_POLARITY_FALLING: TMR IC polarity falling
Return values
None
Definition at line 806 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CC1POL, TMR_T::CC1SEL, TMR_T::CC2POL, TMR_T::CC2SEL, TMR_T::CCEN, TMR_T::CCEN_B, TMR_T::CCM1_CAPTURE_B, TMR_T::SMCTRL_B, and TMR_T::SMFSEL.
Referenced by main().
TMR_ConfigETR()
void TMR_ConfigETR (TMR_T * tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the TMRx External Trigger (ETR).
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the external Trigger Prescaler The parameter can be one of following values:
TMR_EXTTRG_PSC_OFF: ETRP Prescaler OFF
TMR_EXTTRG_PSC_DIV2: ETRP frequency divided by 2
TMR_EXTTRG_PSC_DIV4: ETRP frequency divided by 4
TMR_EXTTRG_PSC_DIV8: ETRP frequency divided by 8
polarity specifies the TMR IC polarity The parameter can be one of following values:
TMR_EXTTRG_POL_INVERTED: Active low or falling edge active
TMR_EXTTGR_POL_NONINVERTED: Active high or rising edge active
filter This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 710 of file apm32f10x_tmr.c.
References TMR_T::ETFCFG, TMR_T::ETPCFG, TMR_T::ETPOL, TMR_T::SMCTRL, and TMR_T::SMCTRL_B.
Referenced by TMR_ConfigETRClockMode1(), and TMR_ConfigETRClockMode2().
TMR_ConfigETRClockMode1()
void TMR_ConfigETRClockMode1 (TMR_T * tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the External clock Mode1.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the external Trigger Prescaler The parameter can be one of following values:
TMR_EXTTRG_PSC_OFF: ETRP Prescaler OFF
TMR_EXTTRG_PSC_DIV2: ETRP frequency divided by 2
TMR_EXTTRG_PSC_DIV4: ETRP frequency divided by 4
TMR_EXTTRG_PSC_DIV8: ETRP frequency divided by 8
polarity specifies the TMR IC polarity The parameter can be one of following values:
TMR_EXTTRG_POL_INVERTED: Active low or falling edge active
TMR_EXTTGR_POL_NONINVERTED: Active high or rising edge active
filter This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 653 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::SMCTRL_B, TMR_T::SMFSEL, TMR_ConfigETR(), and TMR_T::TRGSEL.
TMR_ConfigETRClockMode2()
void TMR_ConfigETRClockMode2 (TMR_T * tmr, TMR_EXTTRG_PSC_T prescaler, TMR_EXTTRG_POL_T polarity, uint16_t filter)
Configures the External clock Mode2.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the external Trigger Prescaler The parameter can be one of following values:
TMR_EXTTRG_PSC_OFF: ETRP Prescaler OFF
TMR_EXTTRG_PSC_DIV2: ETRP frequency divided by 2
TMR_EXTTRG_PSC_DIV4: ETRP frequency divided by 4
TMR_EXTTRG_PSC_DIV8: ETRP frequency divided by 8
polarity specifies the TMR IC polarity The parameter can be one of following values:
TMR_EXTTRG_POL_INVERTED: Active low or falling edge active
TMR_EXTTGR_POL_NONINVERTED: Active high or rising edge active
filter This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 683 of file apm32f10x_tmr.c.
References TMR_T::ECEN, ENABLE, TMR_T::SMCTRL_B, and TMR_ConfigETR().
TMR_ConfigForcedOC1()
void TMR_ConfigForcedOC1 (TMR_T * tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 1 waveform to active or inactive level.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
forcesAction specifies the forced Action to be set to the output waveform The parameter can be one of following values:
TMR_FORCED_ACTION_ACTIVE: Force active level on OC1REF
TMR_FORCED_ACTION_INACTIVE: Force inactive level on OC1REF
Return values
None
Definition at line 833 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM1_COMPARE_B, and TMR_T::OC1MOD.
TMR_ConfigForcedOC2()
void TMR_ConfigForcedOC2 (TMR_T * tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 2 waveform to active or inactive level.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
forcesAction specifies the forced Action to be set to the output waveform The parameter can be one of following values:
TMR_FORCED_ACTION_ACTIVE: Force active level on OC1REF
TMR_FORCED_ACTION_INACTIVE: Force inactive level on OC1REF
Return values
None
Definition at line 850 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM1_COMPARE_B, and TMR_T::OC2MOD.
TMR_ConfigForcedOC3()
void TMR_ConfigForcedOC3 (TMR_T * tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 3 waveform to active or inactive level.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
forcesAction specifies the forced Action to be set to the output waveform The parameter can be one of following values:
TMR_FORCED_ACTION_ACTIVE: Force active level on OC1REF
TMR_FORCED_ACTION_INACTIVE: Force inactive level on OC1REF
Return values
None
Definition at line 868 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM2_COMPARE_B, and TMR_T::OC3MOD.
TMR_ConfigForcedOC4()
void TMR_ConfigForcedOC4 (TMR_T * tmr, TMR_FORCED_ACTION_T forcesAction)
Forces the output 4 waveform to active or inactive level.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
forcesAction specifies the forced Action to be set to the output waveform The parameter can be one of following values:
TMR_FORCED_ACTION_ACTIVE: Force active level on OC1REF
TMR_FORCED_ACTION_INACTIVE: Force inactive level on OC1REF
Return values
None
Definition at line 886 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM2_COMPARE_B, and TMR_T::OC4MOD.
TMR_ConfigIC()
void TMR_ConfigIC (TMR_T * tmr, TMR_ICConfig_T * ICConfig)
Configures Peripheral equipment.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
ICConfig Pointer to a TMR_ICConfig_T structure
Return values
None
Definition at line 279 of file apm32f10x_tmr.c.
References TMR_ICConfig_T::channel, TMR_ICConfig_T::filter, TMR_ICConfig_T::polarity, TMR_ICConfig_T::prescaler, TMR_ICConfig_T::selection, TMR_CHANNEL_1, TMR_CHANNEL_2, TMR_CHANNEL_3, TMR_CHANNEL_4, TMR_ConfigIC1Prescal(), TMR_ConfigIC2Prescal(), TMR_ConfigIC3Prescal(), and TMR_ConfigIC4Prescal().
Referenced by main().
TMR_ConfigIC1Prescal()
void TMR_ConfigIC1Prescal (TMR_T * tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 1 prescaler.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the Input Capture Channel1 Perscaler The parameter can be one of following values:
TMR_IC_PSC_1: no prescaler
TMR_IC_PSC_2: capture is done once every 2 events
TMR_IC_PSC_4: capture is done once every 4 events
TMR_IC_PSC_8: capture is done once every 8 events
Return values
None
Definition at line 1640 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM1_CAPTURE_B, and TMR_T::IC1PSC.
Referenced by TMR_ConfigIC(), and TMR_ConfigPWM().
TMR_ConfigIC2Prescal()
void TMR_ConfigIC2Prescal (TMR_T * tmr, TMR_IC_PSC_T prescaler)
Sets the TMRx Input Capture 2 prescaler.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the Input Capture Channel2 Perscaler The parameter can be one of following values:
TMR_IC_PSC_1: no prescaler
TMR_IC_PSC_2: capture is done once every 2 events
TMR_IC_PSC_4: capture is done once every 4 events
TMR_IC_PSC_8: capture is done once every 8 events
Return values
None
Definition at line 1658 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM1_CAPTURE_B, and TMR_T::IC2PSC.
Referenced by TMR_ConfigIC(), and TMR_ConfigPWM().
TMR_ConfigIC3Prescal()
void TMR_ConfigIC3Prescal (TMR_T * tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 3 prescaler.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the Input Capture Channel3 Perscaler The parameter can be one of following values:
TMR_IC_PSC_1: no prescaler
TMR_IC_PSC_2: capture is done once every 2 events
TMR_IC_PSC_4: capture is done once every 4 events
TMR_IC_PSC_8: capture is done once every 8 events
Return values
None
Definition at line 1677 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM2_CAPTURE_B, and TMR_T::IC3PSC.
Referenced by TMR_ConfigIC().
TMR_ConfigIC4Prescal()
void TMR_ConfigIC4Prescal (TMR_T * tmr, TMR_IC_PSC_T prescaler)
Configures the TMRx Input Capture 4 prescaler.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the Input Capture Channel4 Perscaler The parameter can be one of following values:
TMR_IC_PSC_1: no prescaler
TMR_IC_PSC_2: capture is done once every 2 events
TMR_IC_PSC_4: capture is done once every 4 events
TMR_IC_PSC_8: capture is done once every 8 events
Return values
None
Definition at line 1696 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCM2_CAPTURE_B, and TMR_T::IC4PSC.
Referenced by TMR_ConfigIC().
TMR_ConfigICStructInit()
void TMR_ConfigICStructInit (TMR_ICConfig_T * ICConfig)
Initialize the IC timer with its default value.
Parameters
ICConfig pointer to a TMR_ICConfig_T
Return values
None
Definition at line 365 of file apm32f10x_tmr.c.
References TMR_ICConfig_T::channel, TMR_ICConfig_T::filter, TMR_ICConfig_T::polarity, TMR_ICConfig_T::prescaler, TMR_ICConfig_T::selection, TMR_CHANNEL_1, TMR_IC_POLARITY_RISING, TMR_IC_PSC_1, and TMR_IC_SELECTION_DIRECT_TI.
TMR_ConfigInternalClock()
void TMR_ConfigInternalClock (TMR_T * tmr)
Configures the TMRx internal Clock.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 572 of file apm32f10x_tmr.c.
References DISABLE, TMR_T::SMCTRL_B, and TMR_T::SMFSEL.
TMR_ConfigIntTrigExternalClock()
void TMR_ConfigIntTrigExternalClock (TMR_T * tmr, TMR_TRIGGER_SOURCE_T triggerSource)
Configures the TMRx Internal Trigger as External Clock.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
triggerSource specifies the TMR trigger souces The parameter can be one of following values:
TMR_TRIGGER_SOURCE_ITR0: TMR Internal Trigger 0
TMR_TRIGGER_SOURCE_ITR1: TMR Internal Trigger 1
TMR_TRIGGER_SOURCE_ITR2: TMR Internal Trigger 2
TMR_TRIGGER_SOURCE_ITR3: TMR Internal Trigger 3
Return values
None
Definition at line 590 of file apm32f10x_tmr.c.
References TMR_T::SMCTRL_B, TMR_T::SMFSEL, and TMR_SelectInputTrigger().
TMR_ConfigOC1()
void TMR_ConfigOC1 (TMR_T * tmr, TMR_OCConfig_T * OCConfig)
Configures channel 1 according to parameters.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCConfig Pointer to a TMR_OCConfig_T structure
Return values
None
Definition at line 145 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CC1, TMR_T::CC1EN, TMR_T::CC1NEN, TMR_T::CC1NPOL, TMR_T::CC1POL, TMR_T::CC1SEL, TMR_T::CCEN_B, TMR_T::CCM1_COMPARE_B, TMR_T::CTRL2_B, TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_T::OC1MOD, TMR_T::OC1NOIS, TMR_T::OC1OIS, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, TMR1, and TMR8.
Referenced by main().
TMR_ConfigOC1Fast()
void TMR_ConfigOC1Fast (TMR_T * tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 1 Fast feature.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCFast specifies the Output Compare Channel Fast The parameter can be one of following values:
TMR_OC_FAST_DISABLE
TMR_OC_FAST_ENABLE
Return values
None
Definition at line 1062 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC1FEN.
TMR_ConfigOC1NPolarity()
void TMR_ConfigOC1NPolarity (TMR_T * tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 1 nPolarity.
Parameters
tmr The TMRx it can be TMR1 and TMR8
nPolarity specifies the OC1 nPolarity The parameter can be one of following values:
TMR_OC_NPOLARITY_HIGH: Output Compare active high
TMR_OC_NPOLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1206 of file apm32f10x_tmr.c.
References TMR_T::CC1NPOL, and TMR_T::CCEN_B.
TMR_ConfigOC1Polarity()
void TMR_ConfigOC1Polarity (TMR_T * tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 1 polarity.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
polarity specifies the OC1 Polarity The parameter can be one of following values:
TMR_OC_POLARITY_HIGH: Output Compare active high
TMR_OC_POLARITY_LOW: Output Compare active low
Return values
Nonee
Definition at line 1190 of file apm32f10x_tmr.c.
References TMR_T::CC1POL, and TMR_T::CCEN_B.
TMR_ConfigOC1Preload()
void TMR_ConfigOC1Preload (TMR_T * tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM1.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCPreload specifies the Output Compare Channel Preload The parameter can be one of following values:
TMR_OC_PRELOAD_DISABLE
TMR_OC_PRELOAD_ENABLE
Return values
None
Definition at line 998 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC1PEN.
Referenced by main().
TMR_ConfigOC2()
void TMR_ConfigOC2 (TMR_T * tmr, TMR_OCConfig_T * OCConfig)
Configures channel 2 according to parameters.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCConfig Pointer to a TMR_OCConfig_T structure
Return values
None
Definition at line 177 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CC2, TMR_T::CC2EN, TMR_T::CC2NEN, TMR_T::CC2NPOL, TMR_T::CC2POL, TMR_T::CC2SEL, TMR_T::CCEN_B, TMR_T::CCM1_COMPARE_B, TMR_T::CTRL2_B, TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_T::OC2MOD, TMR_T::OC2NOIS, TMR_T::OC2OIS, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, TMR1, and TMR8.
Referenced by main().
TMR_ConfigOC2Fast()
void TMR_ConfigOC2Fast (TMR_T * tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 2 Fast feature.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCFast specifies the Output Compare Channel Fast The parameter can be one of following values:
TMR_OC_FAST_DISABLE
TMR_OC_FAST_ENABLE
Return values
None
Definition at line 1078 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC2FEN.
TMR_ConfigOC2NPolarity()
void TMR_ConfigOC2NPolarity (TMR_T * tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 2 nPolarity.
Parameters
tmr The TMRx it can be TMR1 and TMR8
nPolarity specifies the OC2 nPolarity The parameter can be one of following values:
TMR_OC_NPOLARITY_HIGH: Output Compare active high
TMR_OC_NPOLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1238 of file apm32f10x_tmr.c.
References TMR_T::CC2NPOL, and TMR_T::CCEN_B.
TMR_ConfigOC2Polarity()
void TMR_ConfigOC2Polarity (TMR_T * tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 2 polarity.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
polarity specifies the OC2 Polarity The parameter can be one of following values:
TMR_OC_POLARITY_HIGH: Output Compare active high
TMR_OC_POLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1222 of file apm32f10x_tmr.c.
References TMR_T::CC2POL, and TMR_T::CCEN_B.
TMR_ConfigOC2Preload()
void TMR_ConfigOC2Preload (TMR_T * tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM2.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCPreload specifies the Output Compare Channel Preload The parameter can be one of following values:
TMR_OC_PRELOAD_DISABLE
TMR_OC_PRELOAD_ENABLE
Return values
None
Definition at line 1014 of file apm32f10x_tmr.c.
References TMR_T::CCM1_COMPARE_B, and TMR_T::OC2PEN.
Referenced by main().
TMR_ConfigOC3()
void TMR_ConfigOC3 (TMR_T * tmr, TMR_OCConfig_T * OCConfig)
Configures channel 3 according to parameters.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCConfig Pointer to a TMR_OCConfig_T structure
Return values
None
Definition at line 214 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CC3, TMR_T::CC3EN, TMR_T::CC3NEN, TMR_T::CC3NPOL, TMR_T::CC3POL, TMR_T::CC3SEL, TMR_T::CCEN_B, TMR_T::CCM2_COMPARE_B, TMR_T::CTRL2_B, TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_T::OC3MOD, TMR_T::OC3NOIS, TMR_T::OC3OIS, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, TMR1, and TMR8.
Referenced by main().
TMR_ConfigOC3Fast()
void TMR_ConfigOC3Fast (TMR_T * tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 2 Fast feature.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCFast specifies the Output Compare Channel Fast The parameter can be one of following values:
TMR_OC_FAST_DISABLE
TMR_OC_FAST_ENABLE
Return values
None
Definition at line 1094 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC3FEN.
TMR_ConfigOC3NPolarity()
void TMR_ConfigOC3NPolarity (TMR_T * tmr, TMR_OC_NPOLARITY_T nPolarity)
Configures the channel 3 nPolarity.
Parameters
tmr The TMRx it can be TMR1 and TMR8
nPolarity specifies the OC3 nPolarity The parameter can be one of following values:
TMR_OC_NPOLARITY_HIGH: Output Compare active high
TMR_OC_NPOLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1270 of file apm32f10x_tmr.c.
References TMR_T::CC3NPOL, and TMR_T::CCEN_B.
TMR_ConfigOC3Polarity()
void TMR_ConfigOC3Polarity (TMR_T * tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 3 polarity.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
polarity specifies the OC3 Polarity The parameter can be one of following values:
TMR_OC_POLARITY_HIGH: Output Compare active high
TMR_OC_POLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1254 of file apm32f10x_tmr.c.
References TMR_T::CC3POL, and TMR_T::CCEN_B.
TMR_ConfigOC3Preload()
void TMR_ConfigOC3Preload (TMR_T * tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM3.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCPreload specifies the Output Compare Channel Preload The parameter can be one of following values:
TMR_OC_PRELOAD_DISABLE
TMR_OC_PRELOAD_ENABLE
Return values
None
Definition at line 1030 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC3PEN.
Referenced by main().
TMR_ConfigOC4()
void TMR_ConfigOC4 (TMR_T * tmr, TMR_OCConfig_T * OCConfig)
Configures channel 4 according to parameters.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCConfig Pointer to a TMR_OCConfig_T structure
Return values
None
Definition at line 250 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CC4, TMR_T::CC4EN, TMR_T::CC4POL, TMR_T::CC4SEL, TMR_T::CCEN_B, TMR_T::CCM2_COMPARE_B, TMR_T::CTRL2_B, TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_T::OC4MOD, TMR_T::OC4OIS, TMR_OCConfig_T::outputState, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, TMR1, and TMR8.
Referenced by main().
TMR_ConfigOC4Fast()
void TMR_ConfigOC4Fast (TMR_T * tmr, TMR_OC_FAST_T OCFast)
Configures the Output Compare 4 Fast feature.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCFast specifies the Output Compare Channel Fast The parameter can be one of following values:
TMR_OC_FAST_DISABLE
TMR_OC_FAST_ENABLE
Return values
None
Definition at line 1110 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC4FEN.
TMR_ConfigOC4Polarity()
void TMR_ConfigOC4Polarity (TMR_T * tmr, TMR_OC_POLARITY_T polarity)
Configures the channel 4 polarity.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
polarity specifies the OC4 Polarity The parameter can be one of following values:
TMR_OC_POLARITY_HIGH: Output Compare active high
TMR_OC_POLARITY_LOW: Output Compare active low
Return values
None
Definition at line 1286 of file apm32f10x_tmr.c.
References TMR_T::CC4POL, and TMR_T::CCEN_B.
TMR_ConfigOC4Preload()
void TMR_ConfigOC4Preload (TMR_T * tmr, TMR_OC_PRELOAD_T OCPreload)
Enable or disable the peripheral Preload register on CCM4.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
OCPreload specifies the Output Compare Channel Preload The parameter can be one of following values:
TMR_OC_PRELOAD_DISABLE
TMR_OC_PRELOAD_ENABLE
Return values
Nonee
Definition at line 1046 of file apm32f10x_tmr.c.
References TMR_T::CCM2_COMPARE_B, and TMR_T::OC4PEN.
Referenced by main().
TMR_ConfigOCStructInit()
void TMR_ConfigOCStructInit (TMR_OCConfig_T * OCConfig)
Initialize the OC timer with its default value.
Parameters
OCConfig pointer to a TMR_OCConfig_T
Return values
None
Definition at line 346 of file apm32f10x_tmr.c.
References TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, TMR_OC_IDLE_STATE_RESET, TMR_OC_MODE_TMRING, TMR_OC_NIDLE_STATE_RESET, TMR_OC_NPOLARITY_HIGH, TMR_OC_NSTATE_DISABLE, TMR_OC_POLARITY_HIGH, and TMR_OC_STATE_DISABLE.
Referenced by main().
TMR_ConfigPrescaler()
void TMR_ConfigPrescaler (TMR_T * tmr, uint16_t prescaler, TMR_PSC_RELOAD_T pscReloadMode)
Configures the TMRx prescaler.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
prescaler specifies the prescaler Register value
pscReloadMode specifies the TMR prescaler Reload mode The parameter can be one of following values:
TMR_PSC_RELOAD_UPDATE: The Prescaler is loaded at the update event
TMR_PSC_RELOAD_IMMEDIATE: The Prescaler is loaded immediately
Return values
None
Definition at line 732 of file apm32f10x_tmr.c.
References TMR_T::CEG_B, TMR_T::PSC, and TMR_T::UEG.
Referenced by main().
TMR_ConfigPWM()
void TMR_ConfigPWM (TMR_T * tmr, TMR_ICConfig_T * PWMConfig)
Configures of TMR to PWM input.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
PWMConfig pointer to a TMR_ICConfig_T
Return values
None
Definition at line 442 of file apm32f10x_tmr.c.
References TMR_ICConfig_T::channel, TMR_ICConfig_T::filter, TMR_ICConfig_T::polarity, TMR_ICConfig_T::prescaler, TMR_ICConfig_T::selection, TMR_CHANNEL_1, TMR_ConfigIC1Prescal(), TMR_ConfigIC2Prescal(), TMR_IC_POLARITY_FALLING, TMR_IC_POLARITY_RISING, TMR_IC_SELECTION_DIRECT_TI, and TMR_IC_SELECTION_INDIRECT_TI.
Referenced by main().
TMR_ConfigSinglePulseMode()
void TMR_ConfigSinglePulseMode (TMR_T * tmr, TMR_SPM_T singlePulseMode)
Configures the Sing pulse Mode.
Parameters
tmr The TMRx can be 1 to 8
singlePulseMode specifies the Single Pulse Mode The parameter can be one of following values:
TMR_SPM_REPETITIVE
TMR_SPM_SINGLE
Return values
None
Definition at line 404 of file apm32f10x_tmr.c.
References TMR_T::CTRL1_B, and TMR_T::SPMEN.
Referenced by main().
TMR_ConfigTimeBase()
void TMR_ConfigTimeBase (TMR_T * tmr, TMR_BaseConfig_T * baseConfig)
Initialize the base timer through the structure.
Parameters
tmr Clear TMRx peripheral, The x can be 1 to 8
baseConfig Pointer to a TMR_BaseConfig_T structure
Return values
None
Definition at line 108 of file apm32f10x_tmr.c.
References TMR_T::AUTORLD, TMR_T::CEG_B, TMR_T::CLKDIV, TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_T::CTRL1, TMR_T::CTRL1_B, TMR_BaseConfig_T::division, TMR_BaseConfig_T::period, TMR_T::PSC, TMR_T::REPCNT, TMR_BaseConfig_T::repetitionCounter, TMR1, TMR2, TMR3, TMR4, TMR5, TMR6, TMR7, TMR8, and TMR_T::UEG.
Referenced by ConfigDelayTimer(), and main().
TMR_ConfigTimeBaseStructInit()
void TMR_ConfigTimeBaseStructInit (TMR_BaseConfig_T * baseConfig)
Initialize the Base timer with its default value.
Parameters
baseConfig pointer to a TMR_BaseConfig_T
Return values
None
Definition at line 330 of file apm32f10x_tmr.c.
References TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_BaseConfig_T::division, TMR_BaseConfig_T::period, TMR_BaseConfig_T::repetitionCounter, TMR_CLOCK_DIV_1, and TMR_COUNTER_MODE_UP.
TMR_ConfigTrigExternalClock()
void TMR_ConfigTrigExternalClock (TMR_T * tmr, TMR_TRIGGER_SOURCE_T triggerSource, TMR_IC_POLARITY_T ICpolarity, uint16_t ICfilter)
Configures the TMRx Trigger as External Clock.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
triggerSource specifies the TMR trigger souces The parameter can be one of following values:
TMR_TRIGGER_SOURCE_TI1F_ED: TI1 Edge Detector
TMR_TRIGGER_SOURCE_TI1FP1: Filtered Timer Input 1
TMR_TRIGGER_SOURCE_TI2FP2: Filtered Timer Input 2
ICpolarity specifies the TMR IC polarity The parameter can be one of following values:
TMR_IC_POLARITY_RISING: TMR IC polarity rising
TMR_IC_POLARITY_FALLING: TMR IC polarity falling
ICfilter This parameter must be a value between 0x00 and 0x0F.
Return values
None
Definition at line 616 of file apm32f10x_tmr.c.
References TMR_T::SMCTRL_B, TMR_T::SMFSEL, TMR_IC_SELECTION_DIRECT_TI, and TMR_SelectInputTrigger().
TMR_ConfigUpdateRequest()
void TMR_ConfigUpdateRequest (TMR_T * tmr, TMR_UPDATE_SOURCE_T updateSource)
Configures the Update Request Interrupt source.
Parameters
tmr The TMRx can be 1 to 8
updateSource Config the Update source The parameter can be one of following values:
TMR_UPDATE_SOURCE_GLOBAL
TMR_UPDATE_SOURCE_REGULAR
Return values
None
Definition at line 1442 of file apm32f10x_tmr.c.
References BIT_RESET, BIT_SET, TMR_T::CTRL1_B, TMR_UPDATE_SOURCE_GLOBAL, and TMR_T::URSSEL.
Referenced by main().
TMR_Disable()
void TMR_Disable (TMR_T * tmr)
Disable the specified TMR peripheral.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 428 of file apm32f10x_tmr.c.
References TMR_T::CNTEN, TMR_T::CTRL1_B, and DISABLE.
Referenced by USB_Timer_IRQHandler().
TMR_DisableAutoReload()
void TMR_DisableAutoReload (TMR_T * tmr)
Disable peripheral Preload register on AUTORLD.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 911 of file apm32f10x_tmr.c.
References TMR_T::ARPEN, TMR_T::CTRL1_B, and DISABLE.
Referenced by main().
TMR_DisableCCDMA()
void TMR_DisableCCDMA (TMR_T * tmr)
Disable Capture Compare DMA source.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 958 of file apm32f10x_tmr.c.
References TMR_T::CCDSEL, TMR_T::CTRL2_B, and DISABLE.
TMR_DisableCCPreload()
void TMR_DisableCCPreload (TMR_T * tmr)
Disable Capture Compare Preload Control bit.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 982 of file apm32f10x_tmr.c.
References TMR_T::CCPEN, TMR_T::CTRL2_B, and DISABLE.
TMR_DisableCCxChannel()
void TMR_DisableCCxChannel (TMR_T * tmr, TMR_CHANNEL_T channel)
Disable the Capture Compare Channel x.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
channel specifies the Channel The parameter can be one of following values:
TMR_CHANNEL_1: Timer Channel 1
TMR_CHANNEL_2: Timer Channel 2
TMR_CHANNEL_3: Timer Channel 3
TMR_CHANNEL_4: Timer Channel 4
Return values
None
Definition at line 1322 of file apm32f10x_tmr.c.
References BIT_SET, and TMR_T::CCEN.
Referenced by TMR1_TRG_COM_IRQHandler().
TMR_DisableCCxNChannel()
void TMR_DisableCCxNChannel (TMR_T * tmr, TMR_CHANNEL_T channel)
Disable the Capture Compare Channelx N.
Parameters
tmr The TMRx it can be TMR1 and TMR8
channel specifies the Channel The parameter can be one of following values:
TMR_CHANNEL_1: Timer Channel 1
TMR_CHANNEL_2: Timer Channel 2
TMR_CHANNEL_3: Timer Channel 3
Return values
None
Definition at line 1356 of file apm32f10x_tmr.c.
References TMR_T::CCEN.
Referenced by TMR1_TRG_COM_IRQHandler().
TMR_DisableDMASoure()
void TMR_DisableDMASoure (TMR_T * tmr, uint16_t dmaSource)
Disable TMRx Requests.
Parameters
tmr The TMRx can be 1 to 8
souces specifies the TMR DMA souces The parameter can be any combination of following values:
TMR_DMA_SOURCE_UPDATE: TMR update DMA souces
TMR_DMA_SOURCE_CC1: TMR Capture Compare 1 DMA souces
TMR_DMA_SOURCE_CC2: TMR Capture Compare 2 DMA souces
TMR_DMA_SOURCE_CC3: TMR Capture Compare 3 DMA souces
TMR_DMA_SOURCE_CC4: TMR Capture Compare 4 DMA souces
TMR_DMA_SOURCE_COM: TMR Commutation DMA souces
TMR_DMA_SOURCE_TRG: TMR Trigger DMA souces
Return values
None
Definition at line 560 of file apm32f10x_tmr.c.
References TMR_T::DIEN.
TMR_DisableHallSensor()
void TMR_DisableHallSensor (TMR_T * tmr)
Disable Hall sensor interface.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 1473 of file apm32f10x_tmr.c.
References TMR_T::CTRL2_B, DISABLE, and TMR_T::TI1SEL.
TMR_DisableInterrupt()
void TMR_DisableInterrupt (TMR_T * tmr, uint16_t interrupt)
Disable intterupts.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be any combination of following values:
TMR_INT_UPDATE: Timer update Interrupt source
TMR_INT_CC1: Timer Capture Compare 1 Interrupt source
TMR_INT_CC2: Timer Capture Compare 2 Interrupt source
TMR_INT_CC3: Timer Capture Compare 3 Interrupt source
TMR_INT_CC4: Timer Capture Compare 4 Interrupt source
TMR_INT_COM: Timer Commutation Interrupt source (Only for TMR1 and TMR8)
TMR_INT_TRG: Timer Trigger Interrupt source
TMR_INT_BRK: Timer Break Interrupt source (Only for TMR1 and TMR8)
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_INT_UPDATE.
Definition at line 1834 of file apm32f10x_tmr.c.
References TMR_T::DIEN.
TMR_DisableMasterSlaveMode()
void TMR_DisableMasterSlaveMode (TMR_T * tmr)
Disable the Master Slave Mode.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 1538 of file apm32f10x_tmr.c.
References DISABLE, TMR_T::MSMEN, and TMR_T::SMCTRL_B.
TMR_DisablePWMOutputs()
void TMR_DisablePWMOutputs (TMR_T * tmr)
Disable TMRx PWM output.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 500 of file apm32f10x_tmr.c.
References TMR_T::BDT_B, DISABLE, and TMR_T::MOEN.
TMR_DisableSelectCOM()
void TMR_DisableSelectCOM (TMR_T * tmr)
Disable Clear the TMR peripheral Commutation event.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 934 of file apm32f10x_tmr.c.
References TMR_T::CCUSEL, TMR_T::CTRL2_B, and DISABLE.
TMR_DisableUpdate()
void TMR_DisableUpdate (TMR_T * tmr)
Disable the TMRx update event.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 1426 of file apm32f10x_tmr.c.
References TMR_T::CTRL1_B, ENABLE, and TMR_T::UD.
TMR_Enable()
void TMR_Enable (TMR_T * tmr)
Enable the specified TMR peripheral.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 416 of file apm32f10x_tmr.c.
References TMR_T::CNTEN, TMR_T::CTRL1_B, and ENABLE.
Referenced by ConfigDelayTimer(), and main().
TMR_EnableAutoReload()
void TMR_EnableAutoReload (TMR_T * tmr)
Enable peripheral Preload register on AUTORLD.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 899 of file apm32f10x_tmr.c.
References TMR_T::ARPEN, TMR_T::CTRL1_B, and ENABLE.
Referenced by ConfigDelayTimer(), and main().
TMR_EnableCCDMA()
void TMR_EnableCCDMA (TMR_T * tmr)
Enable Capture Compare DMA source.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 946 of file apm32f10x_tmr.c.
References TMR_T::CCDSEL, TMR_T::CTRL2_B, and ENABLE.
TMR_EnableCCPreload()
void TMR_EnableCCPreload (TMR_T * tmr)
Enable Capture Compare Preload Control bit.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 970 of file apm32f10x_tmr.c.
References TMR_T::CCPEN, TMR_T::CTRL2_B, and ENABLE.
Referenced by main().
TMR_EnableCCxChannel()
void TMR_EnableCCxChannel (TMR_T * tmr, TMR_CHANNEL_T channel)
Enable the Capture Compare Channel x.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
channel specifies the Channel The parameter can be one of following values:
TMR_CHANNEL_1: Timer Channel 1
TMR_CHANNEL_2: Timer Channel 2
TMR_CHANNEL_3: Timer Channel 3
TMR_CHANNEL_4: Timer Channel 4
Return values
None
Definition at line 1304 of file apm32f10x_tmr.c.
References BIT_SET, and TMR_T::CCEN.
Referenced by TMR1_TRG_COM_IRQHandler().
TMR_EnableCCxNChannel()
void TMR_EnableCCxNChannel (TMR_T * tmr, TMR_CHANNEL_T channel)
Enable the Capture Compare Channelx N.
Parameters
tmr The TMRx it can be TMR1 and TMR8
channel specifies the Channel The parameter can be one of following values:
TMR_CHANNEL_1: Timer Channel 1
TMR_CHANNEL_2: Timer Channel 2
TMR_CHANNEL_3: Timer Channel 3
Return values
None
Definition at line 1339 of file apm32f10x_tmr.c.
References TMR_T::CCEN.
Referenced by TMR1_TRG_COM_IRQHandler().
TMR_EnableDMASoure()
void TMR_EnableDMASoure (TMR_T * tmr, uint16_t dmaSource)
Enable TMRx Requests.
Parameters
tmr The TMRx can be 1 to 8
souces specifies the TMR DMA souces The parameter can be any combination of following values:
TMR_DMA_SOURCE_UPDATE: TMR update DMA souces
TMR_DMA_SOURCE_CC1: TMR Capture Compare 1 DMA souces
TMR_DMA_SOURCE_CC2: TMR Capture Compare 2 DMA souces
TMR_DMA_SOURCE_CC3: TMR Capture Compare 3 DMA souces
TMR_DMA_SOURCE_CC4: TMR Capture Compare 4 DMA souces
TMR_DMA_SOURCE_COM: TMR Commutation DMA souces
TMR_DMA_SOURCE_TRG: TMR Trigger DMA souces
Return values
None
Definition at line 538 of file apm32f10x_tmr.c.
References TMR_T::DIEN.
Referenced by main().
TMR_EnableHallSensor()
void TMR_EnableHallSensor (TMR_T * tmr)
Enable Hall sensor interface.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 1461 of file apm32f10x_tmr.c.
References TMR_T::CTRL2_B, ENABLE, and TMR_T::TI1SEL.
TMR_EnableInterrupt()
void TMR_EnableInterrupt (TMR_T * tmr, uint16_t interrupt)
Enable intterupts.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be any combination of following values:
TMR_INT_UPDATE: Timer update Interrupt source
TMR_INT_CC1: Timer Capture Compare 1 Interrupt source
TMR_INT_CC2: Timer Capture Compare 2 Interrupt source
TMR_INT_CC3: Timer Capture Compare 3 Interrupt source
TMR_INT_CC4: Timer Capture Compare 4 Interrupt source
TMR_INT_COM: Timer Commutation Interrupt source (Only for TMR1 and TMR8)
TMR_INT_TRG: Timer Trigger Interrupt source
TMR_INT_BRK: Timer Break Interrupt source (Only for TMR1 and TMR8)
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_INT_UPDATE.
Definition at line 1810 of file apm32f10x_tmr.c.
References TMR_T::DIEN.
Referenced by ConfigDelayTimer(), and main().
TMR_EnableMasterSlaveMode()
void TMR_EnableMasterSlaveMode (TMR_T * tmr)
Enable the Master Slave Mode.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
None
Definition at line 1526 of file apm32f10x_tmr.c.
References ENABLE, TMR_T::MSMEN, and TMR_T::SMCTRL_B.
Referenced by main().
TMR_EnablePWMOutputs()
void TMR_EnablePWMOutputs (TMR_T * tmr)
Enable TMRx PWM output.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 488 of file apm32f10x_tmr.c.
References TMR_T::BDT_B, ENABLE, and TMR_T::MOEN.
Referenced by main().
TMR_EnableSelectCOM()
void TMR_EnableSelectCOM (TMR_T * tmr)
Enable Clear the TMR peripheral Commutation event.
Parameters
tmr The TMRx it can be TMR1 and TMR8
Return values
None
Definition at line 923 of file apm32f10x_tmr.c.
References TMR_T::CCUSEL, TMR_T::CTRL2_B, and ENABLE.
TMR_EnableUpdate()
void TMR_EnableUpdate (TMR_T * tmr)
Enable the TMRx update event.
Parameters
tmr The TMRx can be 1 to 8
Return values
None
Definition at line 1414 of file apm32f10x_tmr.c.
References TMR_T::CTRL1_B, DISABLE, and TMR_T::UD.
Referenced by main().
TMR_GenerateEvent()
void TMR_GenerateEvent (TMR_T * tmr, uint16_t eventSources)
Configures the TMRx event to be generate by software.
Parameters
tmr The TMRx can be 1 to 8
eventSources specifies the TMR event sources The parameter can be any combination of following values:
TMR_EVENT_UPDATE: Timer update Interrupt source
TMR_EVENT_CC1: Timer Capture Compare 1 Event source
TMR_EVENT_CC2: Timer Capture Compare 2 Event source
TMR_EVENT_CC3: Timer Capture Compare 3 Event source
TMR_EVENT_CC4: Timer Capture Compare 4 Event source
TMR_EVENT_COM: Timer Commutation Event source (Only for TMR1 and TMR8)
TMR_EVENT_TRG: Timer Trigger Event source
TMR_EVENT_BRK: Timer Break Event source (Only for TMR1 and TMR8)
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_EVENT_UPDATE.
Definition at line 1858 of file apm32f10x_tmr.c.
References TMR_T::CEG.
Referenced by main().
TMR_ReadCaputer1()
uint16_t TMR_ReadCaputer1 (TMR_T * tmr)
Read Input Capture 1 value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
Capture Compare 1 Register value.
Definition at line 1726 of file apm32f10x_tmr.c.
References TMR_T::CC1.
Referenced by TMR2_IRQHandler(), and TMR5_IRQHandler().
TMR_ReadCaputer2()
uint16_t TMR_ReadCaputer2 (TMR_T * tmr)
Read Input Capture 2 value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
Capture Compare 2 Register value.
Definition at line 1738 of file apm32f10x_tmr.c.
References TMR_T::CC2.
Referenced by TMR2_IRQHandler(), and TMR5_IRQHandler().
TMR_ReadCaputer3()
uint16_t TMR_ReadCaputer3 (TMR_T * tmr)
Read Input Capture 3 value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
Capture Compare 3 Register value.
Definition at line 1750 of file apm32f10x_tmr.c.
References TMR_T::CC3.
Referenced by TMR2_IRQHandler().
TMR_ReadCaputer4()
uint16_t TMR_ReadCaputer4 (TMR_T * tmr)
Read Input Capture 4 value.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
Return values
Capture Compare 4 Register value.
Definition at line 1762 of file apm32f10x_tmr.c.
References TMR_T::CC4.
Referenced by TMR2_IRQHandler().
TMR_ReadCounter()
uint16_t TMR_ReadCounter (TMR_T * tmr)
Read the TMRx Counter value.
Parameters
tmr The TMRx can be 1 to 8
Return values
Counter Register value.
Definition at line 1774 of file apm32f10x_tmr.c.
References TMR_T::CNT.
TMR_ReadIntFlag()
uint16_t TMR_ReadIntFlag (TMR_T * tmr, TMR_INT_T flag)
Check whether the ITflag is set or reset.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be one of following values:
TMR_INT_UPDATE: Timer update Interrupt source
TMR_INT_CC1: Timer Capture Compare 1 Interrupt source
TMR_INT_CC2: Timer Capture Compare 2 Interrupt source
TMR_INT_CC3: Timer Capture Compare 3 Interrupt source
TMR_INT_CC4: Timer Capture Compare 4 Interrupt source
TMR_INT_COM: Timer Commutation Interrupt source (Only for TMR1 and TMR8)
TMR_INT_TRG: Timer Trigger Interrupt source
TMR_INT_BRK: Timer Break Interrupt source (Only for TMR1 and TMR8)
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_INT_UPDATE.
Definition at line 1938 of file apm32f10x_tmr.c.
References TMR_T::DIEN, RESET, SET, and TMR_T::STS.
Referenced by TMR1_UP_IRQHandler(), TMR2_IRQHandler(), TMR2_Isr(), and USB_Timer_IRQHandler().
TMR_ReadPrescaler()
uint16_t TMR_ReadPrescaler (TMR_T * tmr)
Read the TMRx Prescaler value.
Parameters
tmr The TMRx can be 1 to 8
Return values
Prescaler Register value.
Definition at line 1786 of file apm32f10x_tmr.c.
References TMR_T::PSC.
TMR_ReadStatusFlag()
uint16_t TMR_ReadStatusFlag (TMR_T * tmr, TMR_FLAG_T flag)
Check whether the flag is set or reset.
Parameters
tmr The TMRx can be 1 to 8
interrupt specifies the TMR interrupts sources The parameter can be any combination of following values:
TMR_FLAG_UPDATE: Timer update Flag
TMR_FLAG_CC1: Timer Capture Compare 1 Flag
TMR_FLAG_CC2: Timer Capture Compare 2 Flag
TMR_FLAG_CC3: Timer Capture Compare 3 Flag
TMR_FLAG_CC4: Timer Capture Compare 4 Flag
TMR_FLAG_COM: Timer Commutation Flag (Only for TMR1 and TMR8)
TMR_FLAG_TRG: Timer Trigger Flag
TMR_FLAG_BRK: Timer Break Flag (Only for TMR1 and TMR8)
TMR_FLAG_CC1RC: Timer Capture Compare 1 Repetition Flag
TMR_FLAG_CC2RC: Timer Capture Compare 2 Repetition Flag
TMR_FLAG_CC3RC: Timer Capture Compare 3 Repetition Flag
TMR_FLAG_CC4RC: Timer Capture Compare 4 Repetition Flag
Return values
None
Note
TMR6 and TMR7 can only generate an TMR_FLAG_UPDATE.
Definition at line 1886 of file apm32f10x_tmr.c.
References RESET, SET, and TMR_T::STS.
TMR_Reset()
void TMR_Reset (TMR_T * tmr)
Deinitialize the TMRx peripheral registers to their default reset values.
Parameters
tmr Clear TMRx peripheral, The x can be 1 to 8
Return values
None
Definition at line 55 of file apm32f10x_tmr.c.
References RCM_APB1_PERIPH_TMR2, RCM_APB1_PERIPH_TMR3, RCM_APB1_PERIPH_TMR4, RCM_APB1_PERIPH_TMR5, RCM_APB1_PERIPH_TMR6, RCM_APB1_PERIPH_TMR7, RCM_APB2_PERIPH_TMR1, RCM_APB2_PERIPH_TMR8, RCM_DisableAPB1PeriphReset(), RCM_DisableAPB2PeriphReset(), RCM_EnableAPB1PeriphReset(), RCM_EnableAPB2PeriphReset(), TMR1, TMR2, TMR3, TMR4, TMR5, TMR6, TMR7, and TMR8.
TMR_SelectInputTrigger()
void TMR_SelectInputTrigger (TMR_T * tmr, TMR_TRIGGER_SOURCE_T triggerSource)
Selects the Input Trigger source.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
triggerSource specifies the Input Trigger source The parameter can be one of following values:
TMR_TRIGGER_SOURCE_ITR0: Internal Trigger 0
TMR_TRIGGER_SOURCE_ITR1: Internal Trigger 1
TMR_TRIGGER_SOURCE_ITR2: Internal Trigger 2
TMR_TRIGGER_SOURCE_ITR3: Internal Trigger 3
TMR_TRIGGER_SOURCE_TI1F_ED: TI1 Edge Detector
TMR_TRIGGER_SOURCE_TI1FP1: Filtered Timer Input 1
TMR_TRIGGER_SOURCE_TI2FP2: Filtered Timer Input 2
TMR_TRIGGER_SOURCE_ETRF: External Trigger input
Return values
None
Definition at line 777 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::SMCTRL_B, and TMR_T::TRGSEL.
Referenced by main(), TMR_ConfigIntTrigExternalClock(), and TMR_ConfigTrigExternalClock().
TMR_SelectOCxMode()
void TMR_SelectOCxMode (TMR_T * tmr, TMR_CHANNEL_T channel, TMR_OC_MODE_T mode)
Selects the Output Compare Mode.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
channel specifies the Channel The parameter can be one of following values:
TMR_CHANNEL_1: Timer Channel 1
TMR_CHANNEL_2: Timer Channel 2
TMR_CHANNEL_3: Timer Channel 3
TMR_CHANNEL_4: Timer Channel 4
mode specifies the Output Compare Mode The parameter can be one of following values:
TMR_OC_MODE_TMRING
TMR_OC_MODE_ACTIVE
TMR_OC_MODE_INACTIVE
TMR_OC_MODE_TOGGEL
TMR_OC_MODE_LOWLEVEL
TMR_OC_MODE_HIGHLEVEL
TMR_OC_MODE_PWM1
TMR_OC_MODE_PWM2
Return values
None
Definition at line 1385 of file apm32f10x_tmr.c.
References BIT_RESET, TMR_T::CCEN, TMR_T::CCM1_COMPARE_B, TMR_T::CCM2_COMPARE_B, TMR_T::OC1MOD, TMR_T::OC2MOD, TMR_T::OC3MOD, TMR_T::OC4MOD, TMR_CHANNEL_1, TMR_CHANNEL_2, TMR_CHANNEL_3, and TMR_CHANNEL_4.
Referenced by TMR1_TRG_COM_IRQHandler().
TMR_SelectOutputTrigger()
void TMR_SelectOutputTrigger (TMR_T * tmr, TMR_TRGO_SOURCE_T TRGOSource)
Selects the Trigger Output Mode.
Parameters
tmr The TMRx can be 1 to 8
TRGOSource specifies the Trigger Output source The parameter can be one of following values:
TMR_TRGO_SOURCE_RESET
TMR_TRGO_SOURCE_ENABLE
TMR_TRGO_SOURCE_UPDATE The under is not for TMR6 and TMR7
TMR_TRGO_SOURCE_OC1
TMR_TRGO_SOURCE_OC1REF
TMR_TRGO_SOURCE_OC2REF
TMR_TRGO_SOURCE_OC3REF
TMR_TRGO_SOURCE_OC4REF
Return values
None
Definition at line 1496 of file apm32f10x_tmr.c.
References TMR_T::CTRL2_B, and TMR_T::MMSEL.
Referenced by main().
TMR_SelectSlaveMode()
void TMR_SelectSlaveMode (TMR_T * tmr, TMR_SLAVE_MODE_T slaveMode)
Selects the Slave Mode.
Parameters
tmr The TMRx can be 1 to 8 except 6 and 7
slaveMode specifies the Timer Slave Mode. The parameter can be one of following values:
TMR_SLAVE_MODE_RESET
TMR_SLAVE_MODE_GATED
TMR_SLAVE_MODE_TRIGGER
TMR_SLAVE_MODE_EXTERNAL1
Return values
None
Definition at line 1514 of file apm32f10x_tmr.c.
References TMR_T::SMCTRL_B, and TMR_T::SMFSEL.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU