APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » GPIO Driver
Functions
void GPIO_Reset (GPIO_T *port)
Reset GPIO peripheral registers to their default reset values.
void GPIO_AFIOReset (void)
Reset Alternate Functions registers to their default reset values.
void GPIO_Config (GPIO_T *port, GPIO_Config_T *gpioConfig)
Config the GPIO peripheral according to the specified parameters in the gpioConfig.
void GPIO_ConfigStructInit (GPIO_Config_T *gpioConfig)
Fills each gpioConfig member with its default value.
uint8_t GPIO_ReadInputBit (GPIO_T *port, uint16_t pin)
Reads the specified input port pin.
uint16_t GPIO_ReadInputPort (GPIO_T *port)
Reads the specified GPIO input data port.
uint8_t GPIO_ReadOutputBit (GPIO_T *port, uint16_t pin)
Reads the specified output data port bit.
uint16_t GPIO_ReadOutputPort (GPIO_T *port)
Reads the specified GPIO output data port.
void GPIO_SetBit (GPIO_T *port, uint16_t pin)
Sets the selected data port bits.
void GPIO_ResetBit (GPIO_T *port, uint16_t pin)
Clears the selected data port bits.
void GPIO_WriteOutputPort (GPIO_T *port, uint16_t portValue)
Writes data to the specified GPIO data port.
void GPIO_WriteBitValue (GPIO_T *port, uint16_t pin, uint8_t bitVal)
Writes data to the specified GPIO data port bit.
void GPIO_ConfigPinLock (GPIO_T *port, uint16_t pin)
Locks GPIO Pins configuration registers.
void GPIO_ConfigEventOutput (GPIO_PORT_SOURCE_T portSource, GPIO_PIN_SOURCE_T pinSource)
Selects the GPIO pin used as Event output.
void GPIO_EnableEventOutput (void)
Enables the Event Output.
void GPIO_DisableEventOutput (void)
Disable the Event Output.
void GPIO_ConfigPinRemap (GPIO_REMAP_T remap)
Changes the mapping of the specified pin.
void GPIO_ConfigEINTLine (GPIO_PORT_SOURCE_T portSource, GPIO_PIN_SOURCE_T pinSource)
Selects the GPIO pin used as EINT Line.
Detailed Description
Function Documentation
GPIO_AFIOReset()
void GPIO_AFIOReset (void)
Reset Alternate Functions registers to their default reset values.
Parameters
None
Return values
None
Definition at line 94 of file apm32f10x_gpio.c.
References RCM_APB2_PERIPH_AFIO, RCM_DisableAPB2PeriphReset(), and RCM_EnableAPB2PeriphReset().
GPIO_Config()
void GPIO_Config (GPIO_T * port, GPIO_Config_T * gpioConfig)
Config the GPIO peripheral according to the specified parameters in the gpioConfig.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
gpioConfig pointer to a GPIO_Config_T structure
Return values
None
Definition at line 110 of file apm32f10x_gpio.c.
References GPIO_T::BC, GPIO_T::BSC, GPIO_T::CFGHIG, GPIO_T::CFGLOW, GPIO_MODE_IN_PD, GPIO_MODE_IN_PU, GPIO_Config_T::mode, GPIO_Config_T::pin, and GPIO_Config_T::speed.
Referenced by ADC_Init(), APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_PBInit(), CAN_GPIO_Init(), DAC_Init(), GPIO_Configuration(), GPIO_Init(), HidMouse_GPIOInit(), I2C_Init(), IIC_Init(), IrDAInit(), LINInit(), main(), SmartcardInit(), SPI_FullDuplex_Init(), USART_FullDuplex_Init(), USART_Init(), and USB_HardwareInit().
GPIO_ConfigEINTLine()
void GPIO_ConfigEINTLine (GPIO_PORT_SOURCE_T portSource, GPIO_PIN_SOURCE_T pinSource)
Selects the GPIO pin used as EINT Line.
Parameters
portSource : selects the GPIO port to be used as source for EINT line. This parameter can be one of GPIO_PORT_SOURCE_x(x can be from A to G).
pinSource : Specifies the EINT line to be configured. This parameter can be GPIO_PIN_SOURCE_x(x can be from 0 to 15).
Return values
None
Definition at line 529 of file apm32f10x_gpio.c.
References AFIO, GPIO_PIN_SOURCE_11, GPIO_PIN_SOURCE_12, GPIO_PIN_SOURCE_15, GPIO_PIN_SOURCE_3, GPIO_PIN_SOURCE_4, GPIO_PIN_SOURCE_7, and GPIO_PIN_SOURCE_8.
Referenced by APM_MINI_PBInit().
GPIO_ConfigEventOutput()
void GPIO_ConfigEventOutput (GPIO_PORT_SOURCE_T portSource, GPIO_PIN_SOURCE_T pinSource)
Selects the GPIO pin used as Event output.
Parameters
portSource : selects the GPIO port to be used as source for Event output. This parameter can be one of GPIO_PORT_SOURCE_x(x can be from A to E).
pinSource specifies the pin for the Event output This parameter can be GPIO_PIN_SOURCE_x(x can be from 0 to 15).
Return values
None
Definition at line 374 of file apm32f10x_gpio.c.
References AFIO.
Referenced by main().
GPIO_ConfigPinLock()
void GPIO_ConfigPinLock (GPIO_T * port, uint16_t pin)
Locks GPIO Pins configuration registers.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : Select specifies pin. This parameter can be any combination of GPIO_PIN_x(x can be from 0 to 15).
Return values
None
Definition at line 346 of file apm32f10x_gpio.c.
References GPIO_T::LOCK.
GPIO_ConfigPinRemap()
void GPIO_ConfigPinRemap (GPIO_REMAP_T remap)
Changes the mapping of the specified pin.
Parameters
remap : selects the pin to remap This parameter can be one of the following values:
GPIO_NO_REMAP_SPI1 : No SPI1 Alternate Function mapping
GPIO_REMAP_SPI1 : SPI1 Alternate Function mapping
GPIO_NO_REMAP_I2C1 : No I2C1 Alternate Function mapping
GPIO_REMAP_I2C1 : I2C1 Alternate Function mapping
GPIO_NO_REMAP_USART1 : No USART1 Alternate Function mapping
GPIO_REMAP_USART1 : USART1 Alternate Function mapping
GPIO_NO_REMAP_USART2 : No USART2 Alternate Function mapping
GPIO_REMAP_USART2 : USART2 Alternate Function mapping
GPIO_NO_REMAP_USART3 : No USART3 Partial Alternate Function mapping
GPIO_PARTIAL_REMAP_USART3 : USART3 Partial Alternate Function mapping
GPIO_FULL_REMAP_USART3 : USART3 Full Alternate Function mapping
GPIO_NO_REMAP_TMR1 : No TIM1 Partial Alternate Function mapping
GPIO_PARTIAL_REMAP_TMR1 : TIM1 Partial Alternate Function mapping
GPIO_FULL_REMAP_TMR1 : TIM1 Full Alternate Function mapping
GPIO_NO_REMAP1_TMR2 : No TIM2 Partial1 Alternate Function mapping
GPIO_PARTIAL_REMAP1_TMR2 : TIM2 Partial1 Alternate Function mapping
GPIO_PARTIAL_REMAP2_TMR2 : TIM2 Partial2 Alternate Function mapping
GPIO_FULL_REMAP_TMR2 : TIM2 Full Alternate Function mapping
GPIO_NO_REMAP_TMR3 : No TIM3 Partial Alternate Function mapping
GPIO_PARTIAL_REMAP_TMR3 : TIM3 Partial Alternate Function mapping
GPIO_FULL_REMAP_TMR3 : TIM3 Full Alternate Function mapping
GPIO_NO_REMAP_TMR4 : No TIM4 Alternate Function mapping
GPIO_REMAP_TMR4 : TIM4 Alternate Function mapping
GPIO_NO_REMAP_CAN1 : No CAN1 Alternate Function mapping
GPIO_REMAP1_CAN1 : CAN1 Alternate Function mapping
GPIO_REMAP2_CAN1 : CAN1 Alternate Function mapping
GPIO_NO_REMAP_PD01 : No PD01 Alternate Function mapping
GPIO_REMAP_PD01 : PD01 Alternate Function mapping
GPIO_NO_REMAP_TMR5CH4_LSI : No LSI connected to TIM5 Channel4 input capture for calibration
GPIO_REMAP_TMR5CH4_LSI : LSI connected to TIM5 Channel4 input capture for calibration Only For APM32F10X_CL devices(APM32F107xx and APM32F105xx):
GPIO_NO_REMAP_ETH_MAC : No Ethernet MAC Alternate remapping
GPIO_REMAP_ETH_MAC : Ethernet MAC Alternate remapping
GPIO_NO_REMAP_CAN2 : No CAN2 Alternate Function mapping
GPIO_REMAP_CAN2 : CAN2 Alternate Function mapping
GPIO_REMAP_MACEISEL_MII : Ethernet MAC External Interface Select MII Interface
GPIO_REMAP_MACEISEL_RMII : Ethernet MAC External Interface Select RMII Interface
GPIO_NO_REMAP_SPI3 : No SPI3 Alternate Function mapping
GPIO_REMAP_SPI3 : SPI3 Alternate Function mapping
GPIO_NO_REMAP_SWJ : Full SWJ Enabled (JTAG-DP + SW-DP)
GPIO_REMAP_SWJ_NOJTRST : Full SWJ Enabled (JTAG-DP + SW-DP) but without JTRST
GPIO_REMAP_SWJ_JTAGDISABLE : JTAG-DP Disabled and SW-DP Enabled
GPIO_REMAP_SWJ_DISABLE : Full SWJ Disabled (JTAG-DP + SW-DP)
GPIO_NO_REMAP_TMR2ITR1 : No TMR2 ITR1 Alternate Function mapping
GPIO_REMAP_TMR2ITR1 : TMR2 ITR1 Alternate Function mapping
GPIO_NO_REMAP_PTP_PPS : No Ethernet MAC PTP_PPS Alternate Function mapping
GPIO_REMAP_PTP_PPS : Ethernet MAC PTP_PPS Alternate Function mapping For Other APM32F10X_HD/MD/LD devices:
GPIO_NO_REMAP_ADC1_ETRGINJ : No ADC1 External Trigger Injected Conversion remapping
GPIO_REMAP_ADC1_ETRGINJ : ADC1 External Trigger Injected Conversion remapping
GPIO_NO_REMAP_ADC1_ETRGREG : No ADC1 External Trigger Regular Conversion remapping
GPIO_REMAP_ADC1_ETRGREG : ADC1 External Trigger Regular Conversion remapping
GPIO_NO_REMAP_ADC2_ETRGINJ : No ADC2 External Trigger Injected Conversion remapping
GPIO_REMAP_ADC2_ETRGINJ : ADC2 External Trigger Injected Conversion remapping
GPIO_NO_REMAP_ADC2_ETRGREG : No ADC2 External Trigger Regular Conversion remapping
GPIO_REMAP_ADC2_ETRGREG : ADC2 External Trigger Regular Conversion remapping
GPIO_NO_REMAP_CAN2 : No CAN2 Alternate Function mapping
GPIO_REMAP_CAN2 : CAN2 Alternate Function mapping
GPIO_NO_REMAP_SWJ : Full SWJ Enabled (JTAG-DP + SW-DP)
GPIO_REMAP_SWJ_NOJTRST : Full SWJ Enabled (JTAG-DP + SW-DP) but without JTRST
GPIO_REMAP_SWJ_JTAGDISABLE : JTAG-DP Disabled and SW-DP Enabled
GPIO_REMAP_SWJ_DISABLE : Full SWJ Disabled (JTAG-DP + SW-DP)
Return values
When you use GPIO_REMAP_CAN2, you must put this function last of all other ConfigPinRemap Function.
Definition at line 474 of file apm32f10x_gpio.c.
References AFIO.
Referenced by CAN_GPIO_Init(), GPIO_Configuration(), and main().
GPIO_ConfigStructInit()
void GPIO_ConfigStructInit (GPIO_Config_T * gpioConfig)
Fills each gpioConfig member with its default value.
Parameters
gpioConfig : pointer to a GPIO_Config_T structure which will be initialized.
Return values
None
Definition at line 185 of file apm32f10x_gpio.c.
References GPIO_MODE_IN_FLOATING, GPIO_PIN_ALL, GPIO_SPEED_2MHz, GPIO_Config_T::mode, GPIO_Config_T::pin, and GPIO_Config_T::speed.
Referenced by ADC_Init(), and DAC_Init().
GPIO_DisableEventOutput()
void GPIO_DisableEventOutput (void)
Disable the Event Output.
Parameters
None
Return values
None
Definition at line 399 of file apm32f10x_gpio.c.
References AFIO, and BIT_RESET.
GPIO_EnableEventOutput()
void GPIO_EnableEventOutput (void)
Enables the Event Output.
Parameters
None
Return values
None
Definition at line 387 of file apm32f10x_gpio.c.
References AFIO, and BIT_SET.
GPIO_ReadInputBit()
uint8_t GPIO_ReadInputBit (GPIO_T * port, uint16_t pin)
Reads the specified input port pin.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : specifies pin to read. This parameter can be one of GPIO_PIN_x(x can be from 0 to 15).
Return values
The input port pin value
Definition at line 203 of file apm32f10x_gpio.c.
References BIT_RESET, BIT_SET, and GPIO_T::IDATA.
Referenced by APM_MINI_PBGetState(), EINT0_IRQHandler(), EINT1_IRQHandler(), and HidMouse_ReadKey().
GPIO_ReadInputPort()
uint16_t GPIO_ReadInputPort (GPIO_T * port)
Reads the specified GPIO input data port.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
Return values
GPIO input data port value
Definition at line 220 of file apm32f10x_gpio.c.
References GPIO_T::IDATA.
GPIO_ReadOutputBit()
uint8_t GPIO_ReadOutputBit (GPIO_T * port, uint16_t pin)
Reads the specified output data port bit.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : specifies pin to read. This parameter can be one of GPIO_PIN_x(x can be from 0 to 15).
Return values
The output port pin value
Definition at line 236 of file apm32f10x_gpio.c.
References BIT_RESET, BIT_SET, and GPIO_T::ODATA.
GPIO_ReadOutputPort()
uint16_t GPIO_ReadOutputPort (GPIO_T * port)
Reads the specified GPIO output data port.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
Return values
output data port value
Definition at line 254 of file apm32f10x_gpio.c.
References GPIO_T::ODATA.
GPIO_Reset()
void GPIO_Reset (GPIO_T * port)
Reset GPIO peripheral registers to their default reset values.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
Return values
None
Definition at line 50 of file apm32f10x_gpio.c.
References GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF, GPIOG, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_GPIOB, RCM_APB2_PERIPH_GPIOC, RCM_APB2_PERIPH_GPIOD, RCM_APB2_PERIPH_GPIOE, RCM_APB2_PERIPH_GPIOF, RCM_APB2_PERIPH_GPIOG, RCM_DisableAPB2PeriphReset(), and RCM_EnableAPB2PeriphReset().
GPIO_ResetBit()
void GPIO_ResetBit (GPIO_T * port, uint16_t pin)
Clears the selected data port bits.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : specifies pin to be cleared. This parameter can be any combination of GPIO_PIN_x(x can be from 0 to 15).
Return values
None
Definition at line 286 of file apm32f10x_gpio.c.
References GPIO_T::BC.
Referenced by SmartcardTest().
GPIO_SetBit()
void GPIO_SetBit (GPIO_T * port, uint16_t pin)
Sets the selected data port bits.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : specifies pin to be written. This parameter can be any combination of GPIO_PIN_x(x can be from 0 to 15).
Return values
None
Definition at line 270 of file apm32f10x_gpio.c.
References GPIO_T::BSC.
Referenced by IIC_Init(), SmartcardInit(), and SmartcardTest().
GPIO_WriteBitValue()
void GPIO_WriteBitValue (GPIO_T * port, uint16_t pin, uint8_t bitVal)
Writes data to the specified GPIO data port bit.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
pin : Select specifies pin. This parameter can be one of GPIO_PIN_x(x can be from 0 to 15).
bitVal : specifies the value to be written to the port output data register This parameter can be one of the following values:
BIT_RESET: Reset the port pin
BIT_SET : Set the port pin
Return values
None
Definition at line 308 of file apm32f10x_gpio.c.
References GPIO_T::BC, BIT_RESET, and GPIO_T::BSC.
Referenced by main(), and TMR2_Isr().
GPIO_WriteOutputPort()
void GPIO_WriteOutputPort (GPIO_T * port, uint16_t portValue)
Writes data to the specified GPIO data port.
Parameters
port Select the GPIO port. This parameter can be one of GPIOx(x can be from A to G).
portValue : specifies the value to be written to the port output data register.
Return values
None
Definition at line 330 of file apm32f10x_gpio.c.
References GPIO_T::ODATA.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU