APM32F10x_SDK: Functions
Functions
Examples » USART_Smartcard
Functions
void Delay (void)
Delay.
uint32_t SmartcardTest (void)
Test the inserted card is ISO7816-3 T=0.
void SmartcardInit (void)
USART3 Smartcard mode initializes functions.
void SmartcardIRQHandler (void)
This function handles Smartcard USART global interrupt request.
uint8_t Smartcard_decode_Answer2reset (__IO uint8_t *cardBuff)
Decode the Card ATR Response.
int main (void)
Main program.
Detailed Description
Function Documentation
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 161 of file USART/USART_Smartcard/Source/main.c.
References tick.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 101 of file USART/USART_Smartcard/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), APM_MINI_LEDToggle(), USART_Config_T::baudRate, COM1, Delay(), USART_Config_T::hardwareFlow, LED2, LED3, USART_Config_T::mode, USART_Config_T::parity, SmartcardInit(), SmartcardTest(), USART_Config_T::stopBits, SUCCESS, SystemCoreClock, SystemCoreClockUpdate(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Smartcard_decode_Answer2reset()
uint8_t Smartcard_decode_Answer2reset (__IO uint8_t * cardBuff)
Decode the Card ATR Response.
Parameters
card pointer to the buffer containing the Card ATR.
Return values
Card protocol
Definition at line 335 of file USART/USART_Smartcard/Source/main.c.
References Smartcard_ATR_T::H, Smartcard_ATR_T::Hlenght, Smartcard_A2RStruct, Smartcard_Hist_Lenght, Smartcard_Setup_Lenght, Smartcard_ATR_T::T, Smartcard_ATR_T::T0, Smartcard_ATR_T::Tlenght, and Smartcard_ATR_T::TS.
Referenced by SmartcardTest().
SmartcardInit()
void SmartcardInit (void)
USART3 Smartcard mode initializes functions.
Parameters
None
Return values
None
Definition at line 239 of file USART/USART_Smartcard/Source/main.c.
References USART_Config_T::baudRate, USART_ClockConfig_T::clock, GPIO_Config(), GPIO_MODE_AF_OD, GPIO_MODE_AF_PP, GPIO_MODE_OUT_OD, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_SetBit(), GPIO_SPEED_50MHz, GPIOB, USART_Config_T::hardwareFlow, USART_ClockConfig_T::lastBit, GPIO_Config_T::mode, USART_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_1, USART_Config_T::parity, USART_ClockConfig_T::phase, GPIO_Config_T::pin, USART_ClockConfig_T::polarity, RCM_APB1_PERIPH_USART3, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART3, USART_CLKEN_ENABLE, USART_CLKPHA_1EDGE, USART_CLKPOL_LOW, USART_Config(), USART_ConfigClock(), USART_ConfigGuardTime(), USART_ConfigPrescaler(), USART_Enable(), USART_EnableInterrupt(), USART_EnableSmartCard(), USART_EnableSmartCardNACK(), USART_HARDWARE_FLOW_NONE, USART_INT_PE, USART_LBCP_ENABLE, USART_MODE_TX_RX, USART_PARITY_EVEN, USART_STOP_BIT_1_5, USART_WORD_LEN_9B, and USART_Config_T::wordLength.
Referenced by main().
SmartcardIRQHandler()
void SmartcardIRQHandler (void)
This function handles Smartcard USART global interrupt request.
Parameters
None
Return values
None
Definition at line 422 of file USART/USART_Smartcard/Source/main.c.
References RESET, USART3, USART_DisableInterrupt(), USART_EnableInterrupt(), USART_INT_PE, USART_INT_RXBNE, USART_ReadIntFlag(), and USART_RxData().
Referenced by USART3_IRQHandler().
SmartcardTest()
uint32_t SmartcardTest (void)
Test the inserted card is ISO7816-3 T=0.
Parameters
None
Return values
None
Note
Definition at line 177 of file USART/USART_Smartcard/Source/main.c.
References ERROR, GPIO_PIN_11, GPIO_ResetBit(), GPIO_SetBit(), GPIOB, ReceivedBuffer, RESET, Smartcard_decode_Answer2reset(), Smartcard_Receive_Timeout, SUCCESS, USART3, USART_FLAG_RXBNE, USART_ReadStatusFlag(), and USART_RxData().
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU