APM32F10x_SDK: usbd_core.h File Reference
usbd_core.h File Reference
USB protocol core handler head file.
#include "drv_usb_device.h"
Data Structures
union USBD_REQ_TYPE_T
USB request type.
struct USBD_DevReqData_T
USB device request data.
struct USBD_Descriptor_T
Descriptor structure.
struct USBD_StdReqCallback_T
USB Class Request handler.
struct USBD_CtrlBuf_T
Control transfer buffer.
struct USBD_InitParam_T
USB init parameter.
struct USBD_Info_T
USB infomation.
Macros
#define USB_MIN(a, b) (a >= b ? b : a)
Get minimum value.
#define USB_MAX(a, b) (a >= b ? a : b)
Get maximum value.
#define USBD_CtrlTxStatus() USBD_CtrlInData(NULL, 0);
control status function
#define USBD_CtrlRxStatus() USBD_CtrlOutData(NULL, 0)
Typedefs
typedef void(* USBD_StdReqHandler_T) (void)
USB standard request callback handler.
typedef void(* USBD_ReqHandler_T) (USBD_DevReqData_T *)
USB request handler.
typedef void(* USBD_CtrlTxStatusHandler_T) (void)
Ctrl Tx Status handler function define.
typedef void(* USBD_CtrlRxStatusHandler_T) (void)
Ctrl Rx Status handler function define.
typedef void(* USBD_EPHandler_T) (uint8_t ep)
Endpoint handler.
typedef void(* USBD_ResetHandler_T) (void)
Reset handler.
typedef void(* USBD_InterruptHandler_T) (void)
Interrupt handler function define.
Enumerations
enum { USBD_REQ_TYPE_STANDARD = 0 , USBD_REQ_TYPE_CLASS = 1 , USBD_REQ_TYPE_VENDOR = 2 , USBD_REQ_TYPE_RESERVED = 3 }
USB request type.
enum { USBD_RECIPIENT_DEVICE = 0 , USBD_RECIPIENT_INTERFACE = 1 , USBD_RECIPIENT_ENDPOINT = 2 , USBD_RECIPIENT_OTHER = 3 }
USB recipient.
enum {
USBD_GET_STATUS = 0 , USBD_CLEAR_FEATURE = 1 , USBD_SET_FEATURE = 3 , USBD_SET_ADDRESS = 5 ,
USBD_GET_DESCRIPTOR = 6 , USBD_SET_DESCRIPTOR = 7 , USBD_GET_CONFIGURATION = 8 , USBD_SET_CONFIGURATION = 9 ,
USBD_GET_INTERFACE = 10 , USBD_SET_INTERFACE = 11 , USBD_SYNCH_FRAME = 12
}
USB standard device requests.
enum {
USBD_DESC_DEVICE = 1 , USBD_DESC_CONFIGURATION = 2 , USBD_DESC_STRING = 3 , USBD_DESC_INTERFACE = 4 ,
USBD_DESC_ENDPOINT = 5 , USBD_DESC_DEVICE_QUALIFIER = 6 , USBD_DESC_OTHER_SPEED = 7 , USBD_INTERFACE_POWER = 8
}
USB descriptor types.
enum { USBD_FEATURE_ENDPOINT_HALT = 0 , USBD_FEATURE_REMOTE_WAKEUP = 1 , USBD_FEATURE_TEST_MODE = 2 }
USB standard feature.
enum USBD_CTRL_STATE_T {
USBD_CTRL_STATE_WAIT_SETUP , USBD_CTRL_STATE_DATA_IN , USBD_CTRL_STATE_DATA_OUT , USBD_CTRL_STATE_WAIT_STATUS_IN ,
USBD_CTRL_STATE_WAIT_STATUS_OUT , USBD_CTRL_STATE_STALLED
}
USB internal state machine.
enum USBD_EP_TYPE_T { USBD_EP_TYPE_CONTROL , USBD_EP_TYPE_ISO , USBD_EP_TYPE_BULK , USBD_EP_TYPE_INTERRUPT }
USBD Endpoint type for USB protocol.
Functions
void USBD_SetupProcess (void)
Handler Endpoint 0 control transfer.
void USBD_CtrlInProcess (void)
Endpoint 0 USB Control in process.
void USBD_CtrlOutProcess (void)
Endpoint 0 USB Control out process.
void USBD_CtrlOutData (uint8_t *buf, uint32_t len)
Read data or status in control out transation.
void USBD_CtrlInData (uint8_t *buf, uint32_t len)
Send data or status in control in transation.
void USBD_DataInProcess (USBD_EP_T ep)
Handler other Endpoint data transfer.
void USBD_DataOutProcess (USBD_EP_T ep)
USB Data out process except endpoint 0.
void USBD_TxData (uint8_t ep, uint8_t *buf, uint32_t len)
Transfer data to host(except endpoint 0)
void USBD_RxData (uint8_t ep, uint8_t *buf, uint32_t len)
Receive data from host(except endpoint 0)
Variables
USBD_Info_T g_usbDev
USB information.
Detailed Description
USB protocol core handler head file.
Version
V1.0.0
Date
2021-12-06
Attention
Copyright (C) 2020-2022 Geehy Semiconductor
You may not use this file except in compliance with the GEEHY COPYRIGHT NOTICE (GEEHY SOFTWARE PACKAGE LICENSE).
The program is only for reference, which is distributed in the hope that it will be useful and instructional for customers to develop their software. Unless required by applicable law or agreed to in writing, the program is distributed on an "AS IS" BASIS, WITHOUT ANY WARRANTY OR CONDITIONS OF ANY KIND, either express or implied. See the GEEHY SOFTWARE PACKAGE LICENSE for the governing permissions and limitations under the License.
Definition in file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
Macro Definition Documentation
USB_MAX
#define USB_MAX (a, b) (a >= b ? a : b)
Get maximum value.
Definition at line 35 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USB_MIN
#define USB_MIN (a, b) (a >= b ? b : a)
Get minimum value.
Definition at line 32 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_CtrlRxStatus
#define USBD_CtrlRxStatus (void) USBD_CtrlOutData(NULL, 0)
Definition at line 297 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_CtrlTxStatus
#define USBD_CtrlTxStatus (void) USBD_CtrlInData(NULL, 0);
control status function
Definition at line 296 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
Typedef Documentation
USBD_CtrlRxStatusHandler_T
typedef void(* USBD_CtrlRxStatusHandler_T) (void)
Ctrl Rx Status handler function define.
Definition at line 180 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_CtrlTxStatusHandler_T
typedef void(* USBD_CtrlTxStatusHandler_T) (void)
Ctrl Tx Status handler function define.
Definition at line 177 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_EPHandler_T
typedef void(* USBD_EPHandler_T) (uint8_t ep)
Endpoint handler.
Definition at line 183 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_InterruptHandler_T
typedef void(* USBD_InterruptHandler_T) (void)
Interrupt handler function define.
Definition at line 189 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_ReqHandler_T
typedef void(* USBD_ReqHandler_T) (USBD_DevReqData_T *)
USB request handler.
Definition at line 174 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_ResetHandler_T
typedef void(* USBD_ResetHandler_T) (void)
Reset handler.
Definition at line 186 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_StdReqHandler_T
typedef void(* USBD_StdReqHandler_T) (void)
USB standard request callback handler.
Definition at line 171 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
USB request type.
Enumerator
USBD_REQ_TYPE_STANDARD
USBD_REQ_TYPE_CLASS
USBD_REQ_TYPE_VENDOR
USBD_REQ_TYPE_RESERVED
Definition at line 40 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
anonymous enum
anonymous enum
USB recipient.
Enumerator
USBD_RECIPIENT_DEVICE
USBD_RECIPIENT_INTERFACE
USBD_RECIPIENT_ENDPOINT
USBD_RECIPIENT_OTHER
Definition at line 51 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
anonymous enum
anonymous enum
USB standard device requests.
Enumerator
USBD_GET_STATUS
USBD_CLEAR_FEATURE
USBD_SET_FEATURE
USBD_SET_ADDRESS
USBD_GET_DESCRIPTOR
USBD_SET_DESCRIPTOR
USBD_GET_CONFIGURATION
USBD_SET_CONFIGURATION
USBD_GET_INTERFACE
USBD_SET_INTERFACE
USBD_SYNCH_FRAME
Definition at line 62 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
anonymous enum
anonymous enum
USB descriptor types.
Enumerator
USBD_DESC_DEVICE
USBD_DESC_CONFIGURATION
USBD_DESC_STRING
USBD_DESC_INTERFACE
USBD_DESC_ENDPOINT
USBD_DESC_DEVICE_QUALIFIER
USBD_DESC_OTHER_SPEED
USBD_INTERFACE_POWER
Definition at line 80 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
anonymous enum
anonymous enum
USB standard feature.
Enumerator
USBD_FEATURE_ENDPOINT_HALT
USBD_FEATURE_REMOTE_WAKEUP
USBD_FEATURE_TEST_MODE
Definition at line 95 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_CTRL_STATE_T
enum USBD_CTRL_STATE_T
USB internal state machine.
Enumerator
USBD_CTRL_STATE_WAIT_SETUP
USBD_CTRL_STATE_DATA_IN
USBD_CTRL_STATE_DATA_OUT
USBD_CTRL_STATE_WAIT_STATUS_IN
USBD_CTRL_STATE_WAIT_STATUS_OUT
USBD_CTRL_STATE_STALLED
Definition at line 105 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
USBD_EP_TYPE_T
enum USBD_EP_TYPE_T
USBD Endpoint type for USB protocol.
Enumerator
USBD_EP_TYPE_CONTROL
USBD_EP_TYPE_ISO
USBD_EP_TYPE_BULK
USBD_EP_TYPE_INTERRUPT
Definition at line 118 of file USB_Device_Lib/Core_Device/Standard/inc/usbd_core.h.
Function Documentation
USBD_DataInProcess()
void USBD_DataInProcess (USBD_EP_T ep)
Handler other Endpoint data transfer.
Handler other Endpoint data transfer.
Parameters
ep : endpoint Number except endpoint 0
Return values
None
Definition at line 287 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, USBD_Info_T::inBuf, USBD_Info_T::inEpHandler, USBD_CtrlBuf_T::maxPackSize, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_EP_STATUS_VALID, USBD_SetEPTxCnt, USBD_SetEPTxStatus(), and USBD_WriteDataToEP().
USBD_DataOutProcess()
void USBD_DataOutProcess (USBD_EP_T ep)
USB Data out process except endpoint 0.
Parameters
ep : endpoint Number except endpoint 0
Return values
None
Definition at line 321 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, NULL, USBD_Info_T::outBuf, USBD_Info_T::outEpHandler, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_EP_STATUS_VALID, USBD_ReadDataFromEP(), USBD_ReadEPRxCnt, USBD_SetEPRxStatus(), and USBD_CtrlBuf_T::xferCnt.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU