APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device | USB OTG Library » Core Host » Class » CDC
Typedefs
typedef void(* CDC_REQ_Handler_T) (void)
typedef void(* CDC_Handler_T) (void)
Functions
void USBD_ClassHandler (USBD_DevReqData_T *reqData)
Class Request handler.
void USBH_CDC_ClassInitHandler (void)
USB Host Class Initialization.
void USBH_CDC_ClassDeInitHandler (void)
USB Host Class Re-Initialization.
void USBH_CDC_ClassReqHandler (void)
Class request handler.
void USBH_CDC_CoreHandler (void)
CDC Class handler.
uint8_t USBH_CDCProcessSend (void)
CDC Process Send data.
uint8_t USBH_CDCProcessGet (void)
CDC Process Get data.
void CDC_EnableSend (void)
CDC Enable send flag.
void CDC_EnableGet (void)
CDC Enable to get data.
void CDC_DisableSend (void)
CDC Disable send flag.
void CDC_DisableGet (void)
CDC Disable get data.
uint8_t CDC_SendData (uint8_t *data, uint16_t length)
CDC send data handler.
void CDC_ReceiveData (void)
CDC data Receive handler.
void CDC_DEMO (void)
CDC tranfer data demo.
Detailed Description
Typedef Documentation
CDC_Handler_T
typedef void(* CDC_Handler_T) (void)
Definition at line 117 of file usbh_class_cdc.h.
CDC_REQ_Handler_T
typedef void(* CDC_REQ_Handler_T) (void)
Definition at line 116 of file usbh_class_cdc.h.
Function Documentation
CDC_DEMO()
void CDC_DEMO (void)
CDC tranfer data demo.
Parameters
None
Return values
None
Definition at line 669 of file usbh_class_cdc.c.
References CDC_DisableSend(), CDC_Rx, CDC_Tx, CDC_Xfer_T::cdcState, CDC_Xfer_T::pEmptyBuff, USB_OTG_FlushTxFIFO(), and USBH_CDC_COMPLETE.
CDC_DisableGet()
void CDC_DisableGet (void)
CDC Disable get data.
Parameters
None
Return values
None
Definition at line 612 of file usbh_class_cdc.c.
References CDC_Rx, CDC_Xfer_T::cdcState, CDC_Xfer_T::chNum, flagEnableGet, USB_OTG_HaltChannel(), and USBH_CDC_IDIE.
Referenced by EINT1_IRQHandler(), and USBH_CDCProcessGet().
CDC_DisableSend()
void CDC_DisableSend (void)
CDC Disable send flag.
Parameters
None
Return values
None
Definition at line 583 of file usbh_class_cdc.c.
References CDC_Tx, CDC_Xfer_T::cdcState, flagEnableSend, and USBH_CDC_IDIE.
Referenced by CDC_DEMO().
CDC_EnableGet()
void CDC_EnableGet (void)
CDC Enable to get data.
Parameters
None
Return values
None
Definition at line 596 of file usbh_class_cdc.c.
References CDC_Rx, CDC_Xfer_T::cdcState, flagEnableGet, USBH_CDC_GET_DATA, and USBH_CDC_IDIE.
Referenced by EINT1_IRQHandler(), and USBH_CDC_ClassInitHandler().
CDC_EnableSend()
void CDC_EnableSend (void)
CDC Enable send flag.
Parameters
None
Return values
None
Definition at line 569 of file usbh_class_cdc.c.
References CDC_Tx, CDC_Xfer_T::cdcState, flagEnableSend, and USBH_CDC_SEND_DATA.
Referenced by CDC_SendData().
CDC_ReceiveData()
void CDC_ReceiveData (void)
CDC data Receive handler.
Parameters
None
Return values
None
Definition at line 627 of file usbh_class_cdc.c.
References CDC_Rx, CDC_Xfer_T::dataLen, CDC_Xfer_T::pEmptyBuff, and CDC_Xfer_T::pFillBuff.
Referenced by USBH_CDCProcessGet().
CDC_SendData()
uint8_t CDC_SendData (uint8_t * data, uint16_t length)
CDC send data handler.
Parameters
None
Return values
None
Definition at line 650 of file usbh_class_cdc.c.
References CDC_Xfer_T::buff, CDC_EnableSend(), CDC_Tx, CDC_Xfer_T::cdcState, data, CDC_Xfer_T::dataLen, and USBH_CDC_IDIE.
Referenced by EINT0_IRQHandler().
USBD_ClassHandler()
void USBD_ClassHandler (USBD_DevReqData_T * reqData)
Class Request handler.
USB CDC Class request handler.
Parameters
reqData : point to setup request
Return values
None
Definition at line 67 of file USB_OTG_Lib/Core_Device/Class/src/usbd_class_cdc.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, USBD_REQ_TYPE_T::dir, USBD_DevReqData_T::domain, USBD_CtrlInData(), USBD_CtrlOutData(), USBD_CtrlTxStatus, and USBD_DevReqData_T::wLength.
USBH_CDC_ClassDeInitHandler()
void USBH_CDC_ClassDeInitHandler (void)
USB Host Class Re-Initialization.
Parameters
None
Return values
None
Definition at line 181 of file usbh_class_cdc.c.
References CDC_Xfer_T::buff, CDC_Rx, CDC_Tx, CDC_Xfer_T::cdcState, CDC_Xfer_T::dataLen, rxBuf, txBuf, and USBH_CDC_IDIE.
Referenced by USBH_CDC_Init().
USBH_CDC_ClassInitHandler()
void USBH_CDC_ClassInitHandler (void)
USB Host Class Initialization.
Parameters
None
Return values
None
Definition at line 105 of file usbh_class_cdc.c.
References CDC_Xfer_T::buff, CDC_Xfer_T::buffLen, CDC_BUFFER_SIZE, CDC_EnableGet(), CDC_Rx, CDC_Tx, CDC_Xfer_T::cdcState, CDC_Xfer_T::chNum, USBH_Info_T::curHostState, CDC_Xfer_T::dataLen, USB_UserCallBack_T::deviceNotSupportedHandler, g_usbHost, g_userCallback, CDC_Xfer_T::maxPackSize, CDC_Xfer_T::pEmptyBuff, CDC_Xfer_T::pFillBuff, USBH_Info_T::preHostState, rxBuf, txBuf, USB_EP_TYPE_BULK, USBH_CDC_IDIE, USBH_CH_AllocChannel(), USBH_CH_OpenChannel(), USBH_CLASS_CDCC, USBH_CLASS_CDCD, USBH_DEVICE_CONFIGURED_ADDRESS, USBH_HOST_CLASS_REQ, USBH_ReadConfigurationItfNum, USBH_ReadEndpointAddress, USBH_ReadEndpointMPS, USBH_ReadEndpointType, USBH_ReadInterfaceClass, and USBH_ReadInterfaceEpNum.
Referenced by USBH_CDC_Init().
USBH_CDC_ClassReqHandler()
void USBH_CDC_ClassReqHandler (void)
Class request handler.
Parameters
None
Return values
None
Definition at line 201 of file usbh_class_cdc.c.
References CDC_REQ_CONFIGURED_OK, CDC_REQ_Handler, CDC_REQ_SET_LINE_CODING, USBH_Info_T::curHostState, g_usbHost, s_classReqState, and USBH_HOST_CLASS.
Referenced by USBH_CDC_Init().
USBH_CDC_CoreHandler()
void USBH_CDC_CoreHandler (void)
CDC Class handler.
Parameters
None
Return values
None
Definition at line 223 of file usbh_class_cdc.c.
References USB_UserCallBack_T::applicationHandler, and g_userCallback.
Referenced by USBH_CDC_Init().
USBH_CDCProcessGet()
uint8_t USBH_CDCProcessGet (void)
CDC Process Get data.
Parameters
None
Return values
None
< OUT data OK
Definition at line 418 of file usbh_class_cdc.c.
References USBH_XferPipe_T::bufCount, CDC_Xfer_T::buffLen, CDC_DisableGet(), CDC_ReceiveData(), CDC_Rx, CDC_Xfer_T::cdcState, CDC_Xfer_T::chNum, CDC_Xfer_T::dataLen, flagEnableGet, g_usbHost, USBH_XferPipe_T::maxPackSize, CDC_Xfer_T::pFillBuff, USBH_XferPipe_T::urbStatus, USBH_BulkInData(), USBH_CDC_COMPLETE, USBH_CDC_ERROR, USBH_CDC_GET_DATA, USBH_CDC_GET_WAIT, USBH_CDC_IDIE, USBH_URB_ERROR, USBH_URB_NOREADY, USBH_URB_OK, USBH_URB_STALL, and USBH_Info_T::xferPipe.
USBH_CDCProcessSend()
uint8_t USBH_CDCProcessSend (void)
CDC Process Send data.
Parameters
None
Return values
None
< OUT data OK
Definition at line 494 of file usbh_class_cdc.c.
References CDC_Xfer_T::buff, CDC_Tx, CDC_Xfer_T::cdcState, CDC_Xfer_T::chNum, CDC_Xfer_T::dataLen, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USBH_BulkOutData(), USBH_CDC_COMPLETE, USBH_CDC_ERROR, USBH_CDC_IDIE, USBH_CDC_SEND_DATA, USBH_CDC_SEND_WAIT, USBH_URB_ERROR, USBH_URB_NOREADY, USBH_URB_OK, USBH_URB_STALL, and USBH_Info_T::xferPipe.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU