APM32F10x_SDK: Functions
Functions
Examples » RTC_Alarm
Functions
void RTC_Isr (void)
RTC_IRQHandler.
void EINT1_Isr (void)
RTC_IRQHandler.
void Delay (uint32_t count)
Delay.
void RTC_Init (void)
Delay.
int main (void)
Main program.
Detailed Description
Function Documentation
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 196 of file RTC/RTC_Alarm/Source/main.c.
References count, and systick.
EINT1_Isr()
void EINT1_Isr (void)
RTC_IRQHandler.
Parameters
None
Return values
None
Definition at line 173 of file RTC/RTC_Alarm/Source/main.c.
References EINT_ClearIntFlag(), EINT_LINE_1, EINT_ReadIntFlag(), RTC_ConfigAlarm(), RTC_ReadCounter(), RTC_WaitForLastTask(), and SET.
Referenced by EINT1_IRQHandler().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 70 of file RTC/RTC_Alarm/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDToggle(), APM_MINI_PBInit(), USART_Config_T::baudRate, BUTTON_KEY1, BUTTON_MODE_EINT, COM1, Delay(), USART_Config_T::hardwareFlow, LED2, LED3, USART_Config_T::mode, USART_Config_T::parity, RTC_Init(), USART_Config_T::stopBits, SystemCoreClock, USART_ConfigStructInit(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
RTC_Init()
void RTC_Init (void)
Delay.
Parameters
count delay count
Return values
None
Definition at line 116 of file RTC/RTC_Alarm/Source/main.c.
References NVIC_EnableIRQRequest(), PMU_EnableBackupAccess(), RCM_APB1_PERIPH_PMU, RCM_ConfigRTCCLK(), RCM_EnableAPB1PeriphClock(), RCM_EnableLSI(), RCM_EnableRTCCLK(), RCM_FLAG_LSIRDY, RCM_ReadStatusFlag(), RCM_RTCCLK_LSI, RESET, RTC_ConfigAlarm(), RTC_ConfigCounter(), RTC_ConfigPrescaler(), RTC_EnableInterrupt(), RTC_INT_ALR, RTC_IRQn, RTC_WaitForLastTask(), and RTC_WaitForSynchro().
Referenced by main().
RTC_Isr()
void RTC_Isr (void)
RTC_IRQHandler.
Parameters
None
Return values
None
Definition at line 155 of file RTC/RTC_Alarm/Source/main.c.
References RTC_ClearIntFlag(), RTC_INT_ALR, and RTC_ReadCounter().
Referenced by RTC_IRQHandler().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU