APM32F10x_SDK: Functions
Functions
Examples » DMA_MemoryToMemory
Functions
void RCM_Configuration (void)
Configures the different system clocks.
void NVIC_Configuration (void)
Configure the nested vectored interrupt controller.
uint8_t Buffercmp (const uint32_t *pBuffer, uint32_t *pBuffer1, uint16_t BufferLength)
Compares two buffers.
int main (void)
Main program.
Detailed Description
Function Documentation
Buffercmp()
uint8_t Buffercmp (const uint32_t * pBuffer, uint32_t * pBuffer1, uint16_t BufferLength)
Compares two buffers.
Parameters
pBuffer
pBuffer
Return values
PASSED pBuffer identical to pBuffer1. FAILED: pBuffer differs from pBuffer1
Definition at line 165 of file DMA/DMA_MemoryToMemory/Source/main.c.
References FAILED, and PASSED.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 79 of file DMA/DMA_MemoryToMemory/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), BUF_SIZE, Buffercmp(), DMA_Config_T::bufferSize, CurrDataCounterBegin, CurrDataCounterEnd, DMA_Config_T::dir, DMA1_Channel6, DMA_Config(), DMA_DIR_PERIPHERAL_SRC, DMA_Enable(), DMA_EnableInterrupt(), DMA_INT_TC, DMA_M2MEN_ENABLE, DMA_MEMORY_DATA_SIZE_WOED, DMA_MEMORY_INC_ENABLE, DMA_MODE_NORMAL, DMA_PERIPHERAL_DATA_SIZE_WOED, DMA_PERIPHERAL_INC_ENABLE, DMA_PRIORITY_HIGH, DMA_ReadDataNumber(), DMA_Reset(), DST_Buffer, LED2, LED3, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, NVIC_Configuration(), DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Config_T::priority, RCM_Configuration(), and SRC_Const_Buffer.
NVIC_Configuration()
void NVIC_Configuration (void)
Configure the nested vectored interrupt controller.
Parameters
None
Return values
None
Definition at line 150 of file DMA/DMA_MemoryToMemory/Source/main.c.
References DMA1_Channel6_IRQn, and NVIC_EnableIRQRequest().
RCM_Configuration()
void RCM_Configuration (void)
Configures the different system clocks.
Parameters
None
Return values
None
Definition at line 137 of file DMA/DMA_MemoryToMemory/Source/main.c.
References RCM_AHB_PERIPH_DMA1, and RCM_EnableAHBPeriphClock().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU