APM32F10x_SDK: board.c File Reference
board.c File Reference
#include <rthw.h>
#include <rtthread.h>
#include "Board.h"
Macros
#define _SCB_BASE (0xE000E010UL)
#define _SYSTICK_CTRL (*(rt_uint32_t *)(_SCB_BASE + 0x0))
#define _SYSTICK_LOAD (*(rt_uint32_t *)(_SCB_BASE + 0x4))
#define _SYSTICK_VAL (*(rt_uint32_t *)(_SCB_BASE + 0x8))
#define _SYSTICK_CALIB (*(rt_uint32_t *)(_SCB_BASE + 0xC))
#define _SYSTICK_PRI (*(rt_uint8_t *)(0xE000ED23UL))
Functions
void SystemCoreClockUpdate (void)
Update SystemCoreClock variable according to Clock Register Values The SystemCoreClock variable contains the core clock (HCLK)
void rt_os_tick_callback (void)
void rt_hw_board_init (void)
This function will initial your board.
void SysTick_Handler (void)
This function handles SysTick Handler.
INIT_BOARD_EXPORT (uart_init)
void rt_hw_console_output (const char *str)
char rt_hw_console_getchar (void)
Variables
rt_uint32_t SystemCoreClock
Macro Definition Documentation
_SCB_BASE
#define _SCB_BASE (0xE000E010UL)
Definition at line 14 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
_SYSTICK_CALIB
#define _SYSTICK_CALIB (*(rt_uint32_t *)(_SCB_BASE + 0xC))
Definition at line 18 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
_SYSTICK_CTRL
#define _SYSTICK_CTRL (*(rt_uint32_t *)(_SCB_BASE + 0x0))
Definition at line 15 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
_SYSTICK_LOAD
#define _SYSTICK_LOAD (*(rt_uint32_t *)(_SCB_BASE + 0x4))
Definition at line 16 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
_SYSTICK_PRI
#define _SYSTICK_PRI (*(rt_uint8_t *)(0xE000ED23UL))
Definition at line 19 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
_SYSTICK_VAL
#define _SYSTICK_VAL (*(rt_uint32_t *)(_SCB_BASE + 0x8))
Definition at line 17 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
Function Documentation
INIT_BOARD_EXPORT()
INIT_BOARD_EXPORT (uart_init)
rt_hw_board_init()
void rt_hw_board_init (void)
This function will initial your board.
Definition at line 76 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
References RT_TICK_PER_SECOND, SystemCoreClock, and SystemCoreClockUpdate().
rt_hw_console_getchar()
char rt_hw_console_getchar (void)
Definition at line 170 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
References RESET, USART1, USART_ClearStatusFlag(), USART_FLAG_OVRE, USART_FLAG_RXBNE, USART_ReadStatusFlag(), and USART_RxData().
rt_hw_console_output()
void rt_hw_console_output (const char * str)
Definition at line 148 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
References RESET, USART1, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
rt_os_tick_callback()
void rt_os_tick_callback (void)
Definition at line 64 of file Examples/RTOS/RT-thread/Project/MDK/RTE/RTOS/Board.c.
Referenced by SysTick_Handler().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU