APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » I2C Driver
Functions
void I2C_Reset (I2C_T *i2c)
Reset I2C.
void I2C_Config (I2C_T *i2c, I2C_Config_T *i2cConfig)
Configure I2C by configuring the structure.
void I2C_ConfigStructInit (I2C_Config_T *i2cConfig)
Fills each I2C_InitStruct member with its default value.
void I2C_Enable (I2C_T *i2c)
Enable I2C.
void I2C_Disable (I2C_T *i2c)
Disable I2C.
void I2C_EnableGenerateStart (I2C_T *i2c)
Enable Generates i2c communication START condition.
void I2C_DisableGenerateStart (I2C_T *i2c)
Disable Generates i2c communication START condition.
void I2C_EnableGenerateStop (I2C_T *i2c)
Enable Generates i2c communication STOP condition.
void I2C_DisableGenerateStop (I2C_T *i2c)
Disable Generates i2c communication STOP condition.
void I2C_EnableAcknowledge (I2C_T *i2c)
Enables the specified I2C acknowledge feature.
void I2C_DisableAcknowledge (I2C_T *i2c)
Disables the specified I2C acknowledge feature.
void I2C_ConfigOwnAddress2 (I2C_T *i2c, uint8_t address)
Config the specified I2C own address2.
void I2C_EnableDualAddress (I2C_T *i2c)
Enables the specified I2C dual addressing mode.
void I2C_DisableDualAddress (I2C_T *i2c)
Disables the specified I2C dual addressing mode.
void I2C_EnableGeneralCall (I2C_T *i2c)
Enables the specified I2C general call feature.
void I2C_DisableGeneralCall (I2C_T *i2c)
Disables the specified I2C general call feature.
void I2C_TxData (I2C_T *i2c, uint8_t data)
Send one byte.
uint8_t I2C_RxData (I2C_T *i2c)
Returns the recevie data.
void I2C_Tx7BitAddress (I2C_T *i2c, uint8_t address, I2C_DIRECTION_T direction)
Transmits the address byte to select the slave device.
uint16_t I2C_ReadRegister (I2C_T *i2c, I2C_REGISTER_T i2cRegister)
Reads the I2C register and returns its value.
void I2C_EnableSoftwareReset (I2C_T *i2c)
Enables the I2C software reset.
void I2C_DisableSoftwareReset (I2C_T *i2c)
Disables the I2C software reset.
void I2C_ConfigNACKPosition (I2C_T *i2c, I2C_NACK_POSITION_T NACKPosition)
Selects the specified I2C NACK position in master receiver mode.
void I2C_ConfigSMBusAlert (I2C_T *i2c, I2C_SMBUSALER_T SMBusState)
Control the height of pin of SMBusAlert.
void I2C_EnablePECTransmit (I2C_T *i2c)
Enables the I2C PEC transfer.
void I2C_DisablePECTransmit (I2C_T *i2c)
Disables the I2C PEC transfer.
void I2C_ConfigPECPosition (I2C_T *i2c, I2C_PEC_POSITION_T PECPosition)
Selects the I2C PEC position.
void I2C_EnablePEC (I2C_T *i2c)
Enables the PEC value calculation of the transferred bytes.
void I2C_DisablePEC (I2C_T *i2c)
Disables the PEC value calculation of the transferred bytes.
uint8_t I2C_ReadPEC (I2C_T *i2c)
Read the PEC value for the I2C.
void I2C_EnableARP (I2C_T *i2c)
Enables the I2C ARP.
void I2C_DisableARP (I2C_T *i2c)
Disables the I2C ARP.
void I2C_EnableStretchClock (I2C_T *i2c)
Enables the I2C Clock stretching.
void I2C_DisableStretchClock (I2C_T *i2c)
Disables the I2C Clock stretching.
void I2C_ConfigFastModeDutyCycle (I2C_T *i2c, I2C_DUTYCYCLE_T dutyCycle)
Selects the specified I2C fast mode duty cycle.
void I2C_EnableDMA (I2C_T *i2c)
Enables the specified I2C DMA requests.
void I2C_DisableDMA (I2C_T *i2c)
Disable the specified I2C DMA requests.
void I2C_EnableDMALastTransfer (I2C_T *i2c)
Enable DMA to receive the last transfer.
void I2C_DisableDMALastTransfer (I2C_T *i2c)
Disable DMA to receive the last transfer.
void I2C_EnableInterrupt (I2C_T *i2c, uint16_t interrupt)
Enables the specified I2C interrupts.
void I2C_DisableInterrupt (I2C_T *i2c, uint16_t interrupt)
Disable the specified I2C interrupts.
uint8_t I2C_ReadEventStatus (I2C_T *i2c, I2C_EVENT_T i2cEvent)
Check that the last event is equal to the last passed event.
uint32_t I2C_ReadLastEvent (I2C_T *i2c)
Read the last i2c Event.
uint8_t I2C_ReadStatusFlag (I2C_T *i2c, I2C_FLAG_T flag)
Check whether the I2C flag is set.
void I2C_ClearStatusFlag (I2C_T *i2c, I2C_FLAG_T flag)
Clear the I2C flag.
uint8_t I2C_ReadIntFlag (I2C_T *i2c, I2C_INT_FLAG_T flag)
Check whether the I2C interrupts is set.
void I2C_ClearIntFlag (I2C_T *i2c, uint32_t flag)
Clears the I2C interrupt flag bits.
Detailed Description
Function Documentation
I2C_ClearIntFlag()
void I2C_ClearIntFlag (I2C_T * i2c, uint32_t flag)
Clears the I2C interrupt flag bits.
Parameters
i2c I2C selet 1 or 2
flag specifies the I2C flag The parameter can be any combination of the following values:
I2C_INT_FLAG_SMBALT: SMBus Alert flag
I2C_INT_FLAG_TTE: Timeout or Tlow error flag
I2C_INT_FLAG_PECE: PEC error in reception flag
I2C_INT_FLAG_OVRUR: Overrun/Underrun flag (Slave mode)
I2C_INT_FLAG_AE: Acknowledge error flag
I2C_INT_FLAG_AL: Arbitration lost flag (Master mode)
I2C_INT_FLAG_BERR: Bus error flag
Return values
None
Note
1)I2C_INT_FLAG_STOP: Stop detection flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadIntFlag()) followed by a write operation to I2C_CRTL1 register (I2C_Enable()). 2)I2C_INT_FLAG_ADDR10: 10-bit header sent flag is cleared by software sequence: a read operation to I2C_STS1 (I2C_ReadIntFlag()) followed by writing the second byte of the address in I2C_DATA register. 3)I2C_INT_FLAG_BTC: Byte transfer complete flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadIntFlag()) followed by a read/write to I2C_DATA register (I2C_TxData()). 4)I2C_INT_FLAG_ADDR: Address sent flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadIntFlag()) followed by a read operation to I2C_STS2 register ((void)(I2Cx->STS2)). 5)I2C_INT_FLAG_START: Start bit flag is cleared software sequence: a read operation to I2C_STS1 register (I2C_ReadIntFlag()) followed by a write operation to I2C_DATA register (I2C_TxData()).
Definition at line 1018 of file apm32f10x_i2c.c.
References I2C_T::STS1.
I2C_ClearStatusFlag()
void I2C_ClearStatusFlag (I2C_T * i2c, I2C_FLAG_T flag)
Clear the I2C flag.
Parameters
i2c I2C selet 1 or 2
flag specifies the I2C flag The parameter can be one of the following values:
I2C_FLAG_SMBALT: SMBus Alert flag
I2C_FLAG_TTE: Timeout or Tlow error flag
I2C_FLAG_PECE: PEC error in reception flag
I2C_FLAG_OVRUR: Overrun/Underrun flag (Slave mode)
I2C_FLAG_AE: Acknowledge error flag
I2C_FLAG_AL: Arbitration lost flag (Master mode)
I2C_FLAG_BERR: Bus error flag
Return values
None
Note
1)I2C_FLAG_STOP: Stop detection flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadStatusFlag()) followed by a write operation to I2C_CRTL1 register (I2C_Enable()). 2)I2C_FLAG_ADDR10: 10-bit header sent flag is cleared by software sequence: a read operation to I2C_STS1 (I2C_ReadStatusFlag()) followed by writing the second byte of the address in I2C_DATA register. 3)I2C_FLAG_BTC: Byte transfer complete flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadStatusFlag()) followed by a read/write to I2C_DATA register (I2C_TxData()). 4)I2C_FLAG_ADDR: Address sent flag is cleared by software sequence: a read operation to I2C_STS1 register (I2C_ReadStatusFlag()) followed by a read operation to I2C_STS2 register ((void)(I2Cx->STS2)). 5)I2C_FLAG_START: Start bit flag is cleared software sequence: a read operation to I2C_STS1 register (I2C_ReadStatusFlag()) followed by a write operation to I2C_DATA register (I2C_TxData()).
Definition at line 918 of file apm32f10x_i2c.c.
References I2C_T::AEFLG, I2C_T::ALFLG, I2C_T::BERRFLG, BIT_RESET, I2C_FLAG_AE, I2C_FLAG_AL, I2C_FLAG_BERR, I2C_FLAG_OVRUR, I2C_FLAG_PECE, I2C_FLAG_SMBALT, I2C_FLAG_TTE, I2C_T::OVRURFLG, I2C_T::PECEFLG, I2C_T::SMBALTFLG, I2C_T::STS1_B, and I2C_T::TTEFLG.
I2C_Config()
void I2C_Config (I2C_T * i2c, I2C_Config_T * i2cConfig)
Configure I2C by configuring the structure.
Parameters
i2c I2C selet 1 or 2
i2cConfig pointer to a I2C_Config_T structure
Return values
None
Definition at line 72 of file apm32f10x_i2c.c.
References I2C_Config_T::ack, I2C_Config_T::ackAddress, I2C_T::ACKEN, BIT_RESET, BIT_SET, I2C_T::CLKCTRL, I2C_T::CLKFCFG, I2C_Config_T::clockSpeed, I2C_T::CTRL1, I2C_T::CTRL1_B, I2C_T::CTRL2_B, I2C_Config_T::dutyCycle, I2C_DUTYCYCLE_16_9, I2C_DUTYCYCLE_2, I2C_T::I2CEN, I2C_Config_T::mode, I2C_Config_T::ownAddress1, RCM_ReadPCLKFreq(), I2C_T::RISETMAX, I2C_T::SADDR1, I2C_T::SMBEN, I2C_T::SMBTCFG, and I2C_T::SWITCH.
Referenced by I2C_Init().
I2C_ConfigFastModeDutyCycle()
void I2C_ConfigFastModeDutyCycle (I2C_T * i2c, I2C_DUTYCYCLE_T dutyCycle)
Selects the specified I2C fast mode duty cycle.
Parameters
i2c I2C selet 1 or 2
dutyCycle the fast mode duty cycle. The parameter can be one of following values:
I2C_DUTYCYCLE_16_9: I2C fast mode Tlow/Thigh = 16/9
I2C_DUTYCYCLE_2: I2C fast mode Tlow/Thigh = 2
Return values
None
Definition at line 618 of file apm32f10x_i2c.c.
References BIT_RESET, BIT_SET, I2C_T::CLKCTRL_B, I2C_T::FDUTYCFG, and I2C_DUTYCYCLE_16_9.
I2C_ConfigNACKPosition()
void I2C_ConfigNACKPosition (I2C_T * i2c, I2C_NACK_POSITION_T NACKPosition)
Selects the specified I2C NACK position in master receiver mode.
Parameters
i2c I2C selet 1 or 2
NACKPosition specifies the NACK position.
Return values
None
Definition at line 441 of file apm32f10x_i2c.c.
References I2C_T::ACKPOS, BIT_RESET, BIT_SET, I2C_T::CTRL1_B, and I2C_NACK_POSITION_NEXT.
I2C_ConfigOwnAddress2()
void I2C_ConfigOwnAddress2 (I2C_T * i2c, uint8_t address)
Config the specified I2C own address2.
Parameters
i2c I2C selet 1 or 2
address:specifies the 7bit I2C own address2.
Return values
None
Definition at line 255 of file apm32f10x_i2c.c.
References I2C_T::ADDR2, and I2C_T::SADDR2_B.
I2C_ConfigPECPosition()
void I2C_ConfigPECPosition (I2C_T * i2c, I2C_PEC_POSITION_T PECPosition)
Selects the I2C PEC position.
Parameters
i2c I2C selet 1 or 2
PECPosition PEC position The parameter can be one of following values:
I2C_PEC_POSITION_NEXT: indicates that the next byte is PEC
I2C_PEC_POSITION_CURRENT: indicates that current byte is PEC
Return values
None
Definition at line 511 of file apm32f10x_i2c.c.
References I2C_T::ACKPOS, BIT_RESET, BIT_SET, I2C_T::CTRL1_B, and I2C_PEC_POSITION_NEXT.
I2C_ConfigSMBusAlert()
void I2C_ConfigSMBusAlert (I2C_T * i2c, I2C_SMBUSALER_T SMBusState)
Control the height of pin of SMBusAlert.
Parameters
i2c I2C selet 1 or 2
SMBusState SMBAlert pin level. The parameter can be one of following values:
I2C_SMBUSALER_LOW: SMBus Alert pin low
I2C_SMBUSALER_HIGH: SMBus Alert pin high
Return values
None
Definition at line 464 of file apm32f10x_i2c.c.
References I2C_T::ALERTEN, BIT_RESET, BIT_SET, I2C_T::CTRL1_B, and I2C_SMBUSALER_LOW.
I2C_ConfigStructInit()
void I2C_ConfigStructInit (I2C_Config_T * i2cConfig)
Fills each I2C_InitStruct member with its default value.
Parameters
i2cConfig pointer to a I2C_Config_T structure
Return values
None
Definition at line 140 of file apm32f10x_i2c.c.
References I2C_Config_T::ack, I2C_Config_T::ackAddress, I2C_Config_T::clockSpeed, I2C_Config_T::dutyCycle, I2C_ACK_ADDRESS_7BIT, I2C_ACK_DISABLE, I2C_DUTYCYCLE_2, I2C_MODE_I2C, I2C_Config_T::mode, and I2C_Config_T::ownAddress1.
I2C_Disable()
void I2C_Disable (I2C_T * i2c)
Disable I2C.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 169 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, DISABLE, and I2C_T::I2CEN.
I2C_DisableAcknowledge()
void I2C_DisableAcknowledge (I2C_T * i2c)
Disables the specified I2C acknowledge feature.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 241 of file apm32f10x_i2c.c.
References I2C_T::ACKEN, I2C_T::CTRL1_B, and DISABLE.
I2C_DisableARP()
void I2C_DisableARP (I2C_T * i2c)
Disables the I2C ARP.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 578 of file apm32f10x_i2c.c.
References I2C_T::ARPEN, BIT_RESET, and I2C_T::CTRL1_B.
I2C_DisableDMA()
void I2C_DisableDMA (I2C_T * i2c)
Disable the specified I2C DMA requests.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 649 of file apm32f10x_i2c.c.
References I2C_T::CTRL2_B, DISABLE, and I2C_T::DMAEN.
I2C_DisableDMALastTransfer()
void I2C_DisableDMALastTransfer (I2C_T * i2c)
Disable DMA to receive the last transfer.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 673 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CTRL2_B, and I2C_T::LTCFG.
I2C_DisableDualAddress()
void I2C_DisableDualAddress (I2C_T * i2c)
Disables the specified I2C dual addressing mode.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 279 of file apm32f10x_i2c.c.
References I2C_T::ADDRNUM, DISABLE, and I2C_T::SADDR2_B.
I2C_DisableGeneralCall()
void I2C_DisableGeneralCall (I2C_T * i2c)
Disables the specified I2C general call feature.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 303 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, DISABLE, and I2C_T::SRBEN.
I2C_DisableGenerateStart()
void I2C_DisableGenerateStart (I2C_T * i2c)
Disable Generates i2c communication START condition.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 193 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CTRL1_B, and I2C_T::START.
I2C_DisableGenerateStop()
void I2C_DisableGenerateStop (I2C_T * i2c)
Disable Generates i2c communication STOP condition.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 217 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CTRL1_B, and I2C_T::STOP.
I2C_DisableInterrupt()
void I2C_DisableInterrupt (I2C_T * i2c, uint16_t interrupt)
Disable the specified I2C interrupts.
Parameters
i2c I2C selet 1 or 2
interrupt:I2C interrupts sources The parameter can be any combination of following values:
I2C_INT_BUF: Buffer interrupt
I2C_INT_EVT: Event interrupt
I2C_INT_ERR: Error interrupt
Return values
None
Definition at line 709 of file apm32f10x_i2c.c.
References I2C_T::CTRL2.
Referenced by I2C_Write().
I2C_DisablePEC()
void I2C_DisablePEC (I2C_T * i2c)
Disables the PEC value calculation of the transferred bytes.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 542 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CTRL1_B, and I2C_T::PECEN.
I2C_DisablePECTransmit()
void I2C_DisablePECTransmit (I2C_T * i2c)
Disables the I2C PEC transfer.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 495 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CTRL1_B, and I2C_T::PEC.
I2C_DisableSoftwareReset()
void I2C_DisableSoftwareReset (I2C_T * i2c)
Disables the I2C software reset.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 427 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, DISABLE, and I2C_T::SWRST.
I2C_DisableStretchClock()
void I2C_DisableStretchClock (I2C_T * i2c)
Disables the I2C Clock stretching.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 602 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CLKSTRETCHD, and I2C_T::CTRL1_B.
I2C_Enable()
void I2C_Enable (I2C_T * i2c)
Enable I2C.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 157 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, ENABLE, and I2C_T::I2CEN.
Referenced by I2C_Init().
I2C_EnableAcknowledge()
void I2C_EnableAcknowledge (I2C_T * i2c)
Enables the specified I2C acknowledge feature.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 229 of file apm32f10x_i2c.c.
References I2C_T::ACKEN, I2C_T::CTRL1_B, and ENABLE.
I2C_EnableARP()
void I2C_EnableARP (I2C_T * i2c)
Enables the I2C ARP.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 566 of file apm32f10x_i2c.c.
References I2C_T::ARPEN, BIT_SET, and I2C_T::CTRL1_B.
I2C_EnableDMA()
void I2C_EnableDMA (I2C_T * i2c)
Enables the specified I2C DMA requests.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 637 of file apm32f10x_i2c.c.
References I2C_T::CTRL2_B, I2C_T::DMAEN, and ENABLE.
I2C_EnableDMALastTransfer()
void I2C_EnableDMALastTransfer (I2C_T * i2c)
Enable DMA to receive the last transfer.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 661 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CTRL2_B, and I2C_T::LTCFG.
I2C_EnableDualAddress()
void I2C_EnableDualAddress (I2C_T * i2c)
Enables the specified I2C dual addressing mode.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 267 of file apm32f10x_i2c.c.
References I2C_T::ADDRNUM, ENABLE, and I2C_T::SADDR2_B.
I2C_EnableGeneralCall()
void I2C_EnableGeneralCall (I2C_T * i2c)
Enables the specified I2C general call feature.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 291 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, ENABLE, and I2C_T::SRBEN.
I2C_EnableGenerateStart()
void I2C_EnableGenerateStart (I2C_T * i2c)
Enable Generates i2c communication START condition.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 181 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CTRL1_B, and I2C_T::START.
Referenced by I2C_Write().
I2C_EnableGenerateStop()
void I2C_EnableGenerateStop (I2C_T * i2c)
Enable Generates i2c communication STOP condition.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 205 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CTRL1_B, and I2C_T::STOP.
I2C_EnableInterrupt()
void I2C_EnableInterrupt (I2C_T * i2c, uint16_t interrupt)
Enables the specified I2C interrupts.
Parameters
i2c I2C selet 1 or 2
interrupt:I2C interrupts sources The parameter can be any combination of following values:
I2C_INT_BUF: Buffer interrupt
I2C_INT_EVT: Event interrupt
I2C_INT_ERR: Error interrupt
Return values
None
Definition at line 691 of file apm32f10x_i2c.c.
References I2C_T::CTRL2.
Referenced by I2C_Init().
I2C_EnablePEC()
void I2C_EnablePEC (I2C_T * i2c)
Enables the PEC value calculation of the transferred bytes.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 530 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CTRL1_B, and I2C_T::PECEN.
I2C_EnablePECTransmit()
void I2C_EnablePECTransmit (I2C_T * i2c)
Enables the I2C PEC transfer.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 483 of file apm32f10x_i2c.c.
References BIT_SET, I2C_T::CTRL1_B, and I2C_T::PEC.
I2C_EnableSoftwareReset()
void I2C_EnableSoftwareReset (I2C_T * i2c)
Enables the I2C software reset.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 415 of file apm32f10x_i2c.c.
References I2C_T::CTRL1_B, ENABLE, and I2C_T::SWRST.
I2C_EnableStretchClock()
void I2C_EnableStretchClock (I2C_T * i2c)
Enables the I2C Clock stretching.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 590 of file apm32f10x_i2c.c.
References BIT_RESET, I2C_T::CLKSTRETCHD, and I2C_T::CTRL1_B.
I2C_ReadEventStatus()
uint8_t I2C_ReadEventStatus (I2C_T * i2c, I2C_EVENT_T i2cEvent)
Check that the last event is equal to the last passed event.
Parameters
i2c I2C selet 1 or 2
i2cEvent the event to be checked. The parameter can be one of the following values:
I2C_EVENT_SLAVE_TRANSMITTER_ADDRESS_MATCHED : EV1
I2C_EVENT_SLAVE_RECEIVER_ADDRESS_MATCHED : EV1
I2C_EVENT_SLAVE_TRANSMITTER_SECONDADDRESS_MATCHED : EV1
I2C_EVENT_SLAVE_RECEIVER_SECONDADDRESS_MATCHED : EV1
I2C_EVENT_SLAVE_GENERALCALLADDRESS_MATCHED : EV1
I2C_EVENT_SLAVE_BYTE_RECEIVED : EV2
I2C_EVENT_SLAVE_BYTE_TRANSMITTED : EV3
I2C_EVENT_SLAVE_ACK_FAILURE : EV3_2
I2C_EVENT_SLAVE_STOP_DETECTED : EV4
I2C_EVENT_MASTER_MODE_SELECT : EV5
I2C_EVENT_MASTER_TRANSMITTER_MODE_SELECTED : EV6
I2C_EVENT_MASTER_RECEIVER_MODE_SELECTED : EV6
I2C_EVENT_MASTER_BYTE_RECEIVED : EV7
I2C_EVENT_MASTER_BYTE_TRANSMITTING : EV8
I2C_EVENT_MASTER_BYTE_TRANSMITTED : EV8_2
I2C_EVENT_MASTER_MODE_ADDRESS10 : EV9
Return values
Status SUCCESS or ERROR
Definition at line 740 of file apm32f10x_i2c.c.
References ERROR, I2C_T::STS1, I2C_T::STS2, and SUCCESS.
Referenced by I2C_Write().
I2C_ReadIntFlag()
uint8_t I2C_ReadIntFlag (I2C_T * i2c, I2C_INT_FLAG_T flag)
Check whether the I2C interrupts is set.
Parameters
i2c I2C selet 1 or 2
flag specifies the I2C interrupts The parameter can be one of the following values:
I2C_INT_FLAG_SMBALT: SMBus Alert flag
I2C_INT_FLAG_TTE: Timeout or Tlow error flag
I2C_INT_FLAG_PECE: PEC error in reception flag
I2C_INT_FLAG_OVRUR: Overrun/Underrun flag (Slave mode)
I2C_INT_FLAG_AE: Acknowledge error flag
I2C_INT_FLAG_AL: Arbitration lost flag (Master mode)
I2C_INT_FLAG_BERR: Bus error flag
I2C_INT_FLAG_TXBE: Transmitter data register empty flag
I2C_INT_FLAG_RXBNE: Receiver data register not empty flag
I2C_INT_FLAG_STOP: Stop detection flag (Slave mode)
I2C_INT_FLAG_ADDR10: 10-bit header sent flag (Master mode)
I2C_INT_FLAG_BTC: Byte transfer complete flag
I2C_INT_FLAG_ADDR: Address sent flag (Master mode)
I2C_INT_FLAG_START: Start bit flag (Master mode)
Return values
Status flag SET or RESET
Definition at line 972 of file apm32f10x_i2c.c.
References I2C_T::CTRL2, RESET, SET, and I2C_T::STS1.
Referenced by I2C_Isr().
I2C_ReadLastEvent()
uint32_t I2C_ReadLastEvent (I2C_T * i2c)
Read the last i2c Event.
Parameters
i2c I2C selet 1 or 2
Return values
The last event
Definition at line 765 of file apm32f10x_i2c.c.
References I2C_T::STS1, and I2C_T::STS2.
I2C_ReadPEC()
uint8_t I2C_ReadPEC (I2C_T * i2c)
Read the PEC value for the I2C.
Parameters
i2c I2C selet 1 or 2
Return values
value of PEC
Definition at line 554 of file apm32f10x_i2c.c.
References I2C_T::PECVALUE, and I2C_T::STS2_B.
I2C_ReadRegister()
uint16_t I2C_ReadRegister (I2C_T * i2c, I2C_REGISTER_T i2cRegister)
Reads the I2C register and returns its value.
Parameters
i2c I2C selet 1 or 2
i2cRegister : register to read The parameter can be one of following values:
I2C_REGISTER_CTRL1: CTRL1 register
I2C_REGISTER_CTRL2: CTRL2 register
I2C_REGISTER_SADDR1: SADDR1 register
I2C_REGISTER_SADDR2: SADDR2 register
I2C_REGISTER_DATA: DATA register
I2C_REGISTER_STS1: STS1 register
I2C_REGISTER_STS2: STS2 register
I2C_REGISTER_CLKCTRL: CLKCTRL register
I2C_REGISTER_RISETMAX: RISETMAX register
I2C_REGISTER_SWITCH: SWITCH register
Return values
The value of the read register
Definition at line 379 of file apm32f10x_i2c.c.
References I2C_T::CLKCTRL, I2C_T::CTRL1, I2C_T::CTRL2, I2C_T::DATA, I2C_REGISTER_CLKCTRL, I2C_REGISTER_CTRL1, I2C_REGISTER_CTRL2, I2C_REGISTER_DATA, I2C_REGISTER_RISETMAX, I2C_REGISTER_SADDR1, I2C_REGISTER_SADDR2, I2C_REGISTER_STS1, I2C_REGISTER_STS2, I2C_REGISTER_SWITCH, I2C_T::RISETMAX, I2C_T::SADDR1, I2C_T::SADDR2, I2C_T::STS1, I2C_T::STS2, and I2C_T::SWITCH.
I2C_ReadStatusFlag()
uint8_t I2C_ReadStatusFlag (I2C_T * i2c, I2C_FLAG_T flag)
Check whether the I2C flag is set.
Parameters
i2c I2C selet 1 or 2
flag specifies the I2C flag The parameter can be one of the following values:
I2C_FLAG_DUALADDR: Dual flag (Slave mode)
I2C_FLAG_SMMHADDR: SMBus host header (Slave mode)
I2C_FLAG_SMBDADDR: SMBus default header (Slave mode)
I2C_FLAG_GENCALL: General call header flag (Slave mode)
I2C_FLAG_TR: Transmitter/Receiver flag
I2C_FLAG_BUSBSY: Bus busy flag
I2C_FLAG_MS: Master/Slave flag
I2C_FLAG_SMBALT: SMBus Alert flag
I2C_FLAG_TTE: Timeout or Tlow error flag
I2C_FLAG_PECE: PEC error in reception flag
I2C_FLAG_OVRUR: Overrun/Underrun flag (Slave mode)
I2C_FLAG_AE: Acknowledge error flag
I2C_FLAG_AL: Arbitration lost flag (Master mode)
I2C_FLAG_BERR: Bus error flag
I2C_FLAG_TXBE: Transmitter data register empty flag
I2C_FLAG_RXBNE: Receiver data register not empty flag
I2C_FLAG_STOP: Stop detection flag (Slave mode)
I2C_FLAG_ADDR10: 10-bit header sent flag (Master mode)
I2C_FLAG_BTC: Byte transfer complete flag
I2C_FLAG_ADDR: Address sent flag (Master mode)
I2C_FLAG_START: Start bit flag (Master mode)
Return values
Status flag SET or RESET
Definition at line 810 of file apm32f10x_i2c.c.
References I2C_T::ADDR10FLG, I2C_T::ADDRFLG, I2C_T::AEFLG, I2C_T::ALFLG, I2C_T::BERRFLG, I2C_T::BTCFLG, I2C_T::BUSBSYFLG, I2C_T::DUALADDRFLG, I2C_T::GENCALLFLG, I2C_FLAG_ADDR, I2C_FLAG_ADDR10, I2C_FLAG_AE, I2C_FLAG_AL, I2C_FLAG_BERR, I2C_FLAG_BTC, I2C_FLAG_BUSBSY, I2C_FLAG_DUALADDR, I2C_FLAG_GENCALL, I2C_FLAG_MS, I2C_FLAG_OVRUR, I2C_FLAG_PECE, I2C_FLAG_RXBNE, I2C_FLAG_SMBALT, I2C_FLAG_SMBDADDR, I2C_FLAG_SMMHADDR, I2C_FLAG_START, I2C_FLAG_STOP, I2C_FLAG_TR, I2C_FLAG_TTE, I2C_FLAG_TXBE, I2C_T::MSFLG, I2C_T::OVRURFLG, I2C_T::PECEFLG, I2C_T::RXBNEFLG, I2C_T::SMBALTFLG, I2C_T::SMBDADDRFLG, I2C_T::SMMHADDR, I2C_T::STARTFLG, I2C_T::STOPFLG, I2C_T::STS1_B, I2C_T::STS2_B, I2C_T::TRFLG, I2C_T::TTEFLG, and I2C_T::TXBEFLG.
Referenced by I2C_Isr(), and I2C_Write().
I2C_Reset()
void I2C_Reset (I2C_T * i2c)
Reset I2C.
Parameters
i2c I2C selet 1 or 2
Return values
None
Definition at line 49 of file apm32f10x_i2c.c.
References I2C1, RCM_APB1_PERIPH_I2C1, RCM_APB1_PERIPH_I2C2, RCM_DisableAPB1PeriphReset(), and RCM_EnableAPB1PeriphReset().
Referenced by I2C_Init().
I2C_RxData()
uint8_t I2C_RxData (I2C_T * i2c)
Returns the recevie data.
Parameters
i2c I2C selet 1 or 2
Return values
received data
Definition at line 329 of file apm32f10x_i2c.c.
References I2C_T::DATA, and I2C_T::DATA_B.
Referenced by I2C_Isr().
I2C_Tx7BitAddress()
void I2C_Tx7BitAddress (I2C_T * i2c, uint8_t address, I2C_DIRECTION_T direction)
Transmits the address byte to select the slave device.
Parameters
i2c I2C selet 1 or 2
address slave address which will be transmitted
direction Direction mode The parameter can be one of following values:
I2C_DIRECTION_TX: Transmitter mode
I2C_DIRECTION_RX: Receiver mode
Return values
None
Definition at line 347 of file apm32f10x_i2c.c.
References I2C_T::DATA, I2C_T::DATA_B, and I2C_DIRECTION_TX.
Referenced by I2C_Write().
I2C_TxData()
void I2C_TxData (I2C_T * i2c, uint8_t data)
Send one byte.
Parameters
i2c I2C selet 1 or 2
data data to send
Return values
None
Definition at line 317 of file apm32f10x_i2c.c.
References data, I2C_T::DATA, and I2C_T::DATA_B.
Referenced by I2C_Write().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU