APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device » Standrad | USB OTG Library » Core Host » Standard » StdReq
Functions
void USBD_StandardReqeust (void)
USB request standard request.
void USBH_StandardGetConfiguration (void)
void USBH_StandardGetDescriptor (USBH_DESC_TYPE_T descType, uint8_t descIndex, uint16_t len)
Config Standard Get Descriptor request.
void USBH_StandardGetInterface (uint16_t interface)
Config Standard Get Interface request.
void USBH_StandardGetStatus (USBH_RECIPIENT_T recipient, uint16_t index)
Config Standard Get Status request.
void USBH_StandardSetAddress (uint8_t devAddr)
Config Standard Set Address request.
void USBH_StandardSetConfiguration (uint8_t configuration)
Config Standard Set Configuration request.
void USBH_StandardSetDescriptor (USBH_DESC_TYPE_T descType, uint8_t descIndex, uint16_t len)
Config Standard Set Descriptor request.
void USBH_StandardSetInterface (uint16_t interface, uint16_t alternateSetting)
Config Standard Set Interface request.
void USBH_StandardSetFeature (USBH_RECIPIENT_T recipient, USBH_FEATURE_TEST_T feature, uint16_t index)
Config Standard Set Feature request.
void USBH_StandardClearFeature (USBH_RECIPIENT_T recipient, USBH_FEATURE_TEST_T feature, uint16_t index, uint8_t channelNum)
Config Standard Clear Feature request.
void USBH_ParseCfgDesc (uint8_t *parseBuf, USBH_ConfigurationDesc_T *cfgDescBuf, USBH_Interface_T *interface)
void USBH_ParseStrDescriptor (uint8_t *DescBuff, uint8_t *strBuff)
Parses the string descriptor.
void USBH_GetStandardConfiguration (void)
Config Standard Get Configuration request.
Detailed Description
Function Documentation
USBD_StandardReqeust()
void USBD_StandardReqeust (void)
USB request standard request.
Parameters
None
Return values
None
Definition at line 69 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_stdReq.c.
References USBD_DevReqData_T::bRequest, USBD_DevReqData_T::byte, USBD_DevReqData_T::domain, g_usbDev, NULL, USBD_Info_T::reqData, USBD_Info_T::stdReqExceptionHandler, USB_EP_0, USB_OTG_SetStall(), USBD_CLEAR_FEATURE, USBD_EP_0, USBD_EP_STATUS_STALL, USBD_GET_CONFIGURATION, USBD_GET_DESCRIPTOR, USBD_GET_INTERFACE, USBD_GET_STATUS, USBD_SET_ADDRESS, USBD_SET_CONFIGURATION, USBD_SET_DESCRIPTOR, USBD_SET_FEATURE, USBD_SET_INTERFACE, and USBD_SetEPTxRxStatus().
Referenced by USBD_SetupProcess().
USBH_GetStandardConfiguration()
void USBH_GetStandardConfiguration (void)
Config Standard Get Configuration request.
Parameters
None
Return values
None
Definition at line 59 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_IN, USBH_REQ_TYPE_STANDARD, USBH_STD_GET_CONFIGURATION, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_ParseCfgDesc()
void USBH_ParseCfgDesc (uint8_t * parseBuf, USBH_ConfigurationDesc_T * cfgDescBuf, USBH_Interface_T * interface)
Definition at line 410 of file usbh_stdReq.c.
References ENDPOINT_DESC_MAX_NUM, INTERFACE_DESC_MAX_NUM, NULL, STD_CFG_DESC_SIZE, STD_EP_DESC_SIZE, STD_INTERFACE_DESC_SIZE, USBH_DESC_ENDPOINT, and USBH_DESC_INTERFACE.
USBH_ParseStrDescriptor()
void USBH_ParseStrDescriptor (uint8_t * DescBuff, uint8_t * strBuff)
Parses the string descriptor.
Parameters
DescBuff point to descriptor data
strBuff Buffer to store the string descriptor
Return values
None
< String Type Descriptor
Definition at line 484 of file usbh_stdReq.c.
USBH_StandardClearFeature()
void USBH_StandardClearFeature (USBH_RECIPIENT_T recipient, USBH_FEATURE_TEST_T feature, uint16_t index, uint8_t channelNum)
Config Standard Clear Feature request.
Parameters
recipient : Select request recipient. This value can be one of the following values:
USBH_RECIPIENT_DEVICE
USBH_RECIPIENT_INTERFACE
USBH_RECIPIENT_ENDPOINT
USBH_RECIPIENT_OTHER
feature : Specifies the feature. This value can be one of the following values:
USBH_FEATURE_ENDPOINT_HALT
USBH_FEATURE_REMOTE_WAKEUP
USBH_FEATURE_TEST_MODE
index : index of interface or endpoint.
Return values
None
Definition at line 389 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_CLEAR_FEATURE, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardGetConfiguration()
void USBH_StandardGetConfiguration (void)
USBH_StandardGetDescriptor()
void USBH_StandardGetDescriptor (USBH_DESC_TYPE_T descType, uint8_t descIndex, uint16_t len)
Config Standard Get Descriptor request.
Parameters
descType : Select descriptor type. This value can be one of the following values:
USBH_DESC_DEVICE
USBH_DESC_CONFIGURATION
USBH_DESC_STRING
USBH_DESC_INTERFACE
USBH_DESC_ENDPOINT
USBH_DESC_DEVICE_QUALIFIER
USBH_DESC_OTHER_SPEED
USBH_INTERFACE_POWER
descIndex : Specifies descriptor index.
len : Specifies descriptor len of request.
Return values
None
Definition at line 100 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_DESC_STRING, USBH_LANG_ID, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_IN, USBH_REQ_TYPE_STANDARD, USBH_STD_GET_DESCRIPTOR, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardGetInterface()
void USBH_StandardGetInterface (uint16_t interface)
Config Standard Get Interface request.
Parameters
interface : Specifies interface number to get its alternative setting.
Return values
None
Definition at line 136 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_INTERFACE, USBH_REQ_DIR_IN, USBH_REQ_TYPE_STANDARD, USBH_STD_GET_INTERFACE, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardGetStatus()
void USBH_StandardGetStatus (USBH_RECIPIENT_T recipient, uint16_t index)
Config Standard Get Status request.
Parameters
recipient : Select request recipient. This value can be one of the following values:
USBH_RECIPIENT_DEVICE
USBH_RECIPIENT_INTERFACE
USBH_RECIPIENT_ENDPOINT
USBH_RECIPIENT_OTHER
index : Specifies index of interface or endpoint.
Return values
None
Definition at line 171 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_IN, USBH_REQ_TYPE_STANDARD, USBH_STD_GET_INTERFACE, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardSetAddress()
void USBH_StandardSetAddress (uint8_t devAddr)
Config Standard Set Address request.
Parameters
devAddr : Specifies the device address.
Return values
None
Definition at line 207 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_SET_ADDRESS, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardSetConfiguration()
void USBH_StandardSetConfiguration (uint8_t configuration)
Config Standard Set Configuration request.
Parameters
configuration : Specifies the configuration value.
Return values
None
Definition at line 235 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_SET_CONFIGURATION, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardSetDescriptor()
void USBH_StandardSetDescriptor (USBH_DESC_TYPE_T descType, uint8_t descIndex, uint16_t len)
Config Standard Set Descriptor request.
Parameters
descType : Select descriptor type. This value can be one of the following values:
USBH_DESC_DEVICE
USBH_DESC_CONFIGURATION
USBH_DESC_STRING
USBH_DESC_INTERFACE
USBH_DESC_ENDPOINT
USBH_DESC_DEVICE_QUALIFIER
USBH_DESC_OTHER_SPEED
USBH_INTERFACE_POWER
descIndex : Specifies descriptor index.
len : Specifies descriptor len of request.
Return values
None
Definition at line 277 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_DEVICE, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_SET_DESCRIPTOR, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardSetFeature()
void USBH_StandardSetFeature (USBH_RECIPIENT_T recipient, USBH_FEATURE_TEST_T feature, uint16_t index)
Config Standard Set Feature request.
Parameters
recipient : Select request recipient. This value can be one of the following values:
USBH_RECIPIENT_DEVICE
USBH_RECIPIENT_INTERFACE
USBH_RECIPIENT_ENDPOINT
USBH_RECIPIENT_OTHER
feature : Specifies the feature. This value can be one of the following values:
USBH_FEATURE_ENDPOINT_HALT
USBH_FEATURE_REMOTE_WAKEUP
USBH_FEATURE_TEST_MODE
index : index of interface or endpoint.
Return values
None
Definition at line 348 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_SET_FEATURE, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
USBH_StandardSetInterface()
void USBH_StandardSetInterface (uint16_t interface, uint16_t alternateSetting)
Config Standard Set Interface request.
Parameters
interface : Specifies interface number.
alternateSetting : Specifies the alternative setting.
Return values
None
Definition at line 307 of file usbh_stdReq.c.
References USBH_REQ_TYPE_T::bit, USBH_HostReqData_T::bmRequestType, USBH_HostReqData_T::bRequest, USBH_Info_T::control, USBH_Control_T::ctrlState, USBH_REQ_TYPE_T::dir, USBH_HostReqData_T::domain, g_usbHost, USBH_REQ_TYPE_T::recipient, USBH_Control_T::reqData, USBH_REQ_TYPE_T::type, USBH_CTRL_SETUP, USBH_RECIPIENT_INTERFACE, USBH_REQ_DIR_OUT, USBH_REQ_TYPE_STANDARD, USBH_STD_SET_INTERFACE, USBH_HostReqData_T::wIndex, USBH_HostReqData_T::wLength, and USBH_HostReqData_T::wValue.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU