APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » MISC Driver
Functions
void NVIC_ConfigPriorityGroup (NVIC_PRIORITY_GROUP_T priorityGroup)
Configures the priority grouping: pre-emption priority and subpriority.
void NVIC_EnableIRQRequest (IRQn_Type irq, uint8_t preemptionPriority, uint8_t subPriority)
Enable NVIC request.
void NVIC_DisableIRQRequest (IRQn_Type irq)
Disable NVIC request.
void NVIC_ConfigVectorTable (NVIC_VECT_TAB_T vectTab, uint32_t offset)
Configs the vector table location and Offset.
void NVIC_SetSystemLowPower (NVIC_LOWPOWER_T lowPowerMode)
set the state of the low power mode
void NVIC_ResetystemLowPower (NVIC_LOWPOWER_T lowPowerMode)
reset the state of the low power mode
void SysTick_ConfigCLKSource (SYSTICK_CLK_SOURCE_T clkSource)
Configures the SysTick clock source.
Detailed Description
Function Documentation
NVIC_ConfigPriorityGroup()
void NVIC_ConfigPriorityGroup (NVIC_PRIORITY_GROUP_T priorityGroup)
Configures the priority grouping: pre-emption priority and subpriority.
Parameters
priorityGroup : specifies the priority grouping bits length. This parameter can be one of the following values:
NVIC_PRIORITY_GROUP_0
NVIC_PRIORITY_GROUP_1
NVIC_PRIORITY_GROUP_2
NVIC_PRIORITY_GROUP_3
NVIC_PRIORITY_GROUP_4
Return values
None
Definition at line 64 of file apm32f10x_misc.c.
References AIRCR_VECTKEY_MASK.
Referenced by Ethernet_Config(), LINInit(), main(), NVIC_EnableIRQRequest(), SmartcardInit(), and USB_HardwareInit().
NVIC_ConfigVectorTable()
void NVIC_ConfigVectorTable (NVIC_VECT_TAB_T vectTab, uint32_t offset)
Configs the vector table location and Offset.
Parameters
vectTab specifies if the vector table is in RAM or FLASH memory This parameter can be one of the following values:
NVIC_VECT_TAB_RAM
NVIC_VECT_TAB_FLASH
Offset Vector Table base offset field. This value must be a multiple of 0x200
Return values
None
Definition at line 160 of file apm32f10x_misc.c.
NVIC_DisableIRQRequest()
void NVIC_DisableIRQRequest (IRQn_Type irq)
Disable NVIC request.
Parameters
irq the NVIC interrupt request, detailed in IRQn_Type
Return values
None
Definition at line 142 of file apm32f10x_misc.c.
NVIC_EnableIRQRequest()
void NVIC_EnableIRQRequest (IRQn_Type irq, uint8_t preemptionPriority, uint8_t subPriority)
Enable NVIC request.
Parameters
irq the NVIC interrupt request, detailed in IRQn_Type For the complete APM32 Devices IRQ Channels list,please refer to apm32f10x.h file
preemptionPriority the pre-emption priority needed to set
subPriority the subpriority needed to set
Return values
None
Definition at line 81 of file apm32f10x_misc.c.
References NVIC_ConfigPriorityGroup(), NVIC_PRIORITY_GROUP_0, NVIC_PRIORITY_GROUP_1, NVIC_PRIORITY_GROUP_2, NVIC_PRIORITY_GROUP_3, and NVIC_PRIORITY_GROUP_4.
Referenced by ADC_Init(), APM_MINI_PBInit(), ConfigDelayTimer(), Ethernet_Config(), I2C_Init(), LINInit(), main(), NVIC_Configuration(), RTC_Config(), RTC_Init(), SmartcardInit(), USB_HardwareInit(), and USBD_HardWareInit().
NVIC_ResetystemLowPower()
void NVIC_ResetystemLowPower (NVIC_LOWPOWER_T lowPowerMode)
reset the state of the low power mode
Parameters
lowPowerMode the low power mode state This parameter can be one of the following values:
NVIC_LOWPOWER_SEVONPEND
NVIC_LOWPOWER_SLEEPDEEP
NVIC_LOWPOWER_SLEEPONEXIT
Return values
None
Definition at line 192 of file apm32f10x_misc.c.
NVIC_SetSystemLowPower()
void NVIC_SetSystemLowPower (NVIC_LOWPOWER_T lowPowerMode)
set the state of the low power mode
Parameters
lowPowerMode the low power mode state This parameter can be one of the following values:
NVIC_LOWPOWER_SEVONPEND
NVIC_LOWPOWER_SLEEPDEEP
NVIC_LOWPOWER_SLEEPONEXIT
Return values
None
Definition at line 176 of file apm32f10x_misc.c.
SysTick_ConfigCLKSource()
void SysTick_ConfigCLKSource (SYSTICK_CLK_SOURCE_T clkSource)
Configures the SysTick clock source.
Parameters
clkSource specifies the SysTick clock source This parameter can be one of the following values:
SYSTICK_CLK_SOURCE_HCLK_DIV8: AHB clock divided by 8 selected as SysTick clock source.
SYSTICK_CLK_SOURCE_HCLK: AHB clock selected as SysTick clock source.
Return values
None
Definition at line 207 of file apm32f10x_misc.c.
References BIT2, and SYSTICK_CLK_SOURCE_HCLK.
Referenced by SysTick_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU