APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » EINT Driver
Functions
void EINT_Reset (void)
Reset the EINT peripheral registers to their default reset values.
void EINT_Config (EINT_Config_T *eintConfig)
Configure the EINT.
void EINT_ConfigStructInit (EINT_Config_T *eintConfig)
Fills each EINT_Config_T member with its reset value.
void EINT_SelectSWInterrupt (uint32_t line)
Select Software interrupt on EINT line.
uint8_t EINT_ReadStatusFlag (EINT_LINE_T line)
Read the specified EINT_Line flag.
void EINT_ClearStatusFlag (uint32_t line)
Clears the EINT_Line pending bits.
uint8_t EINT_ReadIntFlag (EINT_LINE_T line)
Read the specified EINT_Line Interrupt Flag.
void EINT_ClearIntFlag (uint32_t line)
Clears the EINT_Line pending bits.
Detailed Description
Function Documentation
EINT_ClearIntFlag()
void EINT_ClearIntFlag (uint32_t line)
Clears the EINT_Line pending bits.
Parameters
line Select the EINT_Line This parameter can be any combination of EINT_LINE_T(can be from 0 to 18)
Return values
None
Definition at line 199 of file apm32f10x_eint.c.
References EINT.
Referenced by EINT0_IRQHandler(), Eint0_Isr(), EINT1_IRQHandler(), Eint1_Isr(), EINT1_Isr(), and USBDWakeUp_IRQHandler().
EINT_ClearStatusFlag()
void EINT_ClearStatusFlag (uint32_t line)
Clears the EINT_Line pending bits.
Parameters
line Select the EINT_Line. This parameter can be any combination of EINT_LINE_T(can be from 0 to 18)
Return values
None
Definition at line 160 of file apm32f10x_eint.c.
References EINT.
Referenced by APM_MINI_PB1_Isr(), APM_MINI_PB2_Isr(), APM_MINI_PB_I2C_Isr(), and EINT0_IRQHandler().
EINT_Config()
void EINT_Config (EINT_Config_T * eintConfig)
Configure the EINT.
Parameters
eintConfig pointer to a EINT_Config_T structure.
Return values
None
Definition at line 64 of file apm32f10x_eint.c.
References __IOM, DISABLE, EINT, EINT_BASE, EINT_TRIGGER_RISING_FALLING, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, and EINT_Config_T::trigger.
Referenced by APM_MINI_PBInit(), and USBD_HardWareInit().
EINT_ConfigStructInit()
void EINT_ConfigStructInit (EINT_Config_T * eintConfig)
Fills each EINT_Config_T member with its reset value.
Parameters
eintConfig pointer to a EINT_Config_T structure
Return values
None
Definition at line 108 of file apm32f10x_eint.c.
References DISABLE, EINT_LINENONE, EINT_MODE_INTERRUPT, EINT_TRIGGER_FALLING, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, and EINT_Config_T::trigger.
EINT_ReadIntFlag()
uint8_t EINT_ReadIntFlag (EINT_LINE_T line)
Read the specified EINT_Line Interrupt Flag.
Parameters
line Select the EINT_Line. This parameter can be one of EINT_LINE_T(can be from 0 to 18)
Return values
None
Definition at line 173 of file apm32f10x_eint.c.
References EINT, RESET, and SET.
Referenced by EINT0_IRQHandler(), Eint0_Isr(), EINT1_IRQHandler(), Eint1_Isr(), and EINT1_Isr().
EINT_ReadStatusFlag()
uint8_t EINT_ReadStatusFlag (EINT_LINE_T line)
Read the specified EINT_Line flag.
Parameters
line Select the EINT_Line. This parameter can be one of EINT_LINE_T(can be from 0 to 18)
Return values
status The new state of flag (SET or RESET)
Definition at line 137 of file apm32f10x_eint.c.
References EINT, RESET, and SET.
Referenced by APM_MINI_PB1_Isr(), APM_MINI_PB2_Isr(), APM_MINI_PB_I2C_Isr(), and EINT0_IRQHandler().
EINT_Reset()
void EINT_Reset (void)
Reset the EINT peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 48 of file apm32f10x_eint.c.
References EINT.
EINT_SelectSWInterrupt()
void EINT_SelectSWInterrupt (uint32_t line)
Select Software interrupt on EINT line.
Parameters
line specifies the EINT lines. This parameter can be any combination of EINT_LINE_T(can be from 0 to 18)
Return values
None
Definition at line 124 of file apm32f10x_eint.c.
References EINT.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU