APM32F10x_SDK: Functions
Functions
Examples » ETH_RTT_TcpServer
Functions
void Ethernet_Config (void)
configurate Ethernet.
err_t ethernetif_init (struct netif *netif)
Should be called at the beginning of the program to set up the network interface.
void tcp_server_task_init (void)
Initialize Tcp Server task.
void ethernetif_input (void *pParams)
This function should be called when a packet is ready to be read from the interface.
ETH_Frame_T ETH_RxPacket (void)
received ethernet packet
int ETH_TxPacket (u16 Length)
Transmits a ethernet packet
void LwIP_Init (void)
This function initializes the lwIP stack.
int main (void)
Main program.
int fputc (int ch, FILE *f)
Redirect C Library function printf to serial port.
Detailed Description
Function Documentation
ETH_RxPacket()
ETH_Frame_T ETH_RxPacket (void)
received ethernet packet
Parameters
None
Return values
None
Note
Definition at line 399 of file ETH_RT-Thread_TcpServer/Source/ethernetif.c.
References BIT7, ETH_Frame_T::buffer, ETH_DMADescConfig_T::Buffer1Addr, ETH_DMADescConfig_T::Buffer2NextDescAddr, ETH_Frame_T::descriptor, DMARxDescToGet, ETH_DMARXDESC_ERRS, ETH_DMARXDESC_FDES, ETH_DMARXDESC_FL, ETH_DMARXDESC_LDES, ETH_DMARXDESC_OWN, ETH_ERROR, ETH_Frame_T::length, RESET, and ETH_DMADescConfig_T::Status.
ETH_TxPacket()
int ETH_TxPacket (u16 Length)
Transmits a ethernet packet
Parameters
FrameLength Transmits Packet size
Return values
ETH_ERROR in case of Tx desc owned by DMA ETH_SUCCESS: for correct transmission
Note
Check if the descriptor is owned by the ETHERNET DMA (when set) or CPU (when reset)
Return ERROR: OWN bit set
Setting the Frame Length: bits[12:0]
Setting the last segment and first segment bits
Set Own bit of the Tx descriptor Status: gives the buffer back to ETHERNET DMA
When Tx Buffer unavailable flag is set: clear it and resume transmission
Clear TBUS ETHERNET DMA flag
Resume DMA transmission
Update the ETHERNET DMA global Tx descriptor with next Tx decriptor
Chained Mode
Selects the next DMA Tx descriptor list for next buffer to send
Return SUCCESS
Definition at line 457 of file ETH_RT-Thread_TcpServer/Source/ethernetif.c.
References BIT2, ETH_DMADescConfig_T::Buffer2NextDescAddr, ETH_DMADescConfig_T::ControlBufferSize, DMATxDescToSet, ETH_DMATXDESC_FS, ETH_DMATXDESC_LS, ETH_DMATXDESC_OWN, ETH_DMATXDESC_TXBS1, ETH_ERROR, ETH_SUCCESS, RESET, and ETH_DMADescConfig_T::Status.
Ethernet_Config()
void Ethernet_Config (void)
configurate Ethernet.
Parameters
None
Return values
None
Note
Definition at line 70 of file ETH_RT-Thread_TcpServer/Source/board_DP83848.c.
References ETH_DMA_INT_NIS, ETH_DMA_INT_RX, ETH_EnableDMAInterrupt(), NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), and NVIC_PRIORITY_GROUP_4.
ethernetif_init()
err_t ethernetif_init (struct netif * netif)
Should be called at the beginning of the program to set up the network interface.
It calls the function low_level_init() to do the actual setup of the hardware.
This function should be passed as a parameter to netif_add().
Parameters
netif the lwip network interface structure for this ethernetif
Returns
ERR_OK if the loopif is initialized ERR_MEM if private data couldn't be allocated any other err_t on error
Definition at line 347 of file ETH_RT-Thread_TcpServer/Source/ethernetif.c.
References ethernetif::ethaddr, IFNAME0, IFNAME1, and NULL.
ethernetif_input()
void ethernetif_input (void * pParams)
This function should be called when a packet is ready to be read from the interface.
It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
Parameters
netif the lwip network interface structure for this ethernetif
Definition at line 302 of file ETH_RT-Thread_TcpServer/Source/ethernetif.c.
References eth_rx_sem, and NULL.
fputc()
int fputc (int ch, FILE * f)
Redirect C Library function printf to serial port.
After Redirection, you can use printf function.
Parameters
ch The characters that need to be send.
*f pointer to a FILE that can recording all information needed to control a stream
Return values
The characters that need to be send.
Definition at line 173 of file ETH/ETH_RT-Thread_TcpServer/Source/main.c.
References DEBUG_USART, RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
LwIP_Init()
void LwIP_Init (void)
This function initializes the lwIP stack.
Parameters
None
Return values
None
Definition at line 116 of file ETH/ETH_RT-Thread_TcpServer/Source/main.c.
References ETH_GATEWAY, ETH_IP_ADDR, ETH_NET_MASK, ethernetif_init(), NULL, and UserNetif.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 76 of file ETH/ETH_RT-Thread_TcpServer/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDToggle(), USART_Config_T::baudRate, COM1, Ethernet_Config(), USART_Config_T::hardwareFlow, LED2, LwIP_Init(), USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, tcp_server_task_init(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
tcp_server_task_init()
void tcp_server_task_init (void)
Initialize Tcp Server task.
Parameters
None
Return values
None
Note
Definition at line 189 of file ETH_RT-Thread_TcpServer/Source/tcp_server_test.c.
References NULL, sys_thread_new(), and TCPIP_THREAD_PRIO.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU