APM32F10x_SDK: Functions
Functions
Examples » ETH_Ping
Functions
void Ethernet_Config (void)
configurate Ethernet.
err_t ethernetif_init (struct netif *netif)
Should be called at the beginning of the program to set up the network interface.
err_t ethernetif_input (struct netif *netif)
This function should be called when a packet is ready to be read from the interface.
void LwIP_Init (void)
This function initializes the lwIP stack.
void LwIP_Pkt_Handle (void)
This function received ethernet packet.
void LwIP_Periodic_Handle (__IO uint32_t ETHTimer)
This function LwIP periodic tasks.
ETH_Frame_T ETH_RxPacket (void)
received ethernet packet
int ETH_TxPacket (u16 Length)
Transmits a ethernet packet
void ConfigSysTick (void)
Configure SysTick.
void UserRCMClockConfig (void)
User config the different system Clock.
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
int main (void)
Main program.
Detailed Description
Function Documentation
APM_BOARD_COMInit()
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 273 of file ETH/ETH_Ping/Source/main.c.
References APM_MINI_COMInit(), and COM1.
Referenced by main().
ConfigSysTick()
void ConfigSysTick (void)
Configure SysTick.
Parameters
None
Return values
None
Definition at line 147 of file ETH/ETH_Ping/Source/main.c.
References SystemCoreClock.
Referenced by main().
ETH_RxPacket()
ETH_Frame_T ETH_RxPacket (void)
received ethernet packet
Parameters
None
Return values
None
Note
Definition at line 355 of file ETH_Ping/Source/ethernetif.c.
References BIT7, ETH_Frame_T::buffer, ETH_DMADescConfig_T::Buffer1Addr, ETH_DMADescConfig_T::Buffer2NextDescAddr, ETH_Frame_T::descriptor, DMARxDescToGet, ETH_DMARXDESC_ERRS, ETH_DMARXDESC_FDES, ETH_DMARXDESC_FL, ETH_DMARXDESC_LDES, ETH_DMARXDESC_OWN, ETH_ERROR, ETH_Frame_T::length, RESET, and ETH_DMADescConfig_T::Status.
ETH_TxPacket()
int ETH_TxPacket (u16 Length)
Transmits a ethernet packet
Parameters
FrameLength Transmits Packet size
Return values
ETH_ERROR in case of Tx desc owned by DMA ETH_SUCCESS: for correct transmission
Note
Check if the descriptor is owned by the ETHERNET DMA (when set) or CPU (when reset)
Return ERROR: OWN bit set
Setting the Frame Length: bits[12:0]
Setting the last segment and first segment bits
Set Own bit of the Tx descriptor Status: gives the buffer back to ETHERNET DMA
When Tx Buffer unavailable flag is set: clear it and resume transmission
Clear TBUS ETHERNET DMA flag
Resume DMA transmission
Update the ETHERNET DMA global Tx descriptor with next Tx decriptor
Chained Mode
Selects the next DMA Tx descriptor list for next buffer to send
Return SUCCESS
Definition at line 413 of file ETH_Ping/Source/ethernetif.c.
References BIT2, ETH_DMADescConfig_T::Buffer2NextDescAddr, ETH_DMADescConfig_T::ControlBufferSize, DMATxDescToSet, ETH_DMATXDESC_FS, ETH_DMATXDESC_LS, ETH_DMATXDESC_OWN, ETH_DMATXDESC_TXBS1, ETH_ERROR, ETH_SUCCESS, RESET, and ETH_DMADescConfig_T::Status.
Ethernet_Config()
void Ethernet_Config (void)
configurate Ethernet.
Parameters
None
Return values
None
Note
Definition at line 72 of file ETH_Ping/Source/board_DP83848.c.
ethernetif_init()
err_t ethernetif_init (struct netif * netif)
Should be called at the beginning of the program to set up the network interface.
It calls the function low_level_init() to do the actual setup of the hardware.
This function should be passed as a parameter to netif_add().
Parameters
netif the lwip network interface structure for this ethernetif
Returns
ERR_OK if the loopif is initialized ERR_MEM if private data couldn't be allocated any other err_t on error
Definition at line 303 of file ETH_Ping/Source/ethernetif.c.
References ethernetif::ethaddr, IFNAME0, IFNAME1, and NULL.
ethernetif_input()
err_t ethernetif_input (struct netif * netif)
This function should be called when a packet is ready to be read from the interface.
It uses the function low_level_input() that should handle the actual reception of bytes from the network interface. Then the type of the received packet is determined and the appropriate input function is called.
Parameters
netif the lwip network interface structure for this ethernetif
Definition at line 268 of file ETH_Ping/Source/ethernetif.c.
References NULL.
LwIP_Init()
void LwIP_Init (void)
This function initializes the lwIP stack.
Parameters
None
Return values
None
Definition at line 163 of file ETH/ETH_Ping/Source/main.c.
References ETH_ConfigMACAddress(), ETH_GATEWAY, ETH_IP_ADDR, ETH_MAC_ADDRESS0, ETH_NET_MASK, ethernetif_init(), NULL, SetMACaddr, and UserNetif.
LwIP_Periodic_Handle()
void LwIP_Periodic_Handle (__IO uint32_t ETHTimer)
This function LwIP periodic tasks.
Parameters
ETHTimer the current Ethernet Timer value
Return values
None
Definition at line 230 of file ETH/ETH_Ping/Source/main.c.
References ARPTimer, ETHTimer, and TCPTimer.
Referenced by main().
LwIP_Pkt_Handle()
void LwIP_Pkt_Handle (void)
This function received ethernet packet.
Parameters
None
Return values
None
Definition at line 217 of file ETH/ETH_Ping/Source/main.c.
References ethernetif_input(), and UserNetif.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 92 of file ETH/ETH_Ping/Source/main.c.
References APM_BOARD_COMInit(), USART_Config_T::baudRate, COM1, ConfigSysTick(), DMARxDescToGet, ETH_ReadRxPacketSize(), Ethernet_Config(), ETHTimer, USART_Config_T::hardwareFlow, LwIP_Init(), LwIP_Periodic_Handle(), LwIP_Pkt_Handle(), USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, UserRCMClockConfig(), and USART_Config_T::wordLength.
UserRCMClockConfig()
void UserRCMClockConfig (void)
User config the different system Clock.
Parameters
None
Return values
None
Definition at line 258 of file ETH/ETH_Ping/Source/main.c.
References SystemInit().
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU