APM32F10x_SDK: Functions
Functions
USB OTG Library » Driver » USB » Macros
Functions
void USB_OTG_ConfigMode (USB_MODE_T mode)
Force USB to device ot host mode.
void USB_OTG_ConfigPHY (USB_OTG_PHY_T phy)
Config HS PHY or FS Serial Transceiver.
void USB_OTG_EnableVbusSensing (void)
Enale USB Vbus Sensing.
void USB_OTG_DisableVbusSensing (void)
Disale USB Vbus Sensing.
void USB_OTG_EnableDeviceVbus (USB_DEVICE_TYPE_T type)
Enale USB device Vbus Sensing.
void USB_OTG_DisableDeviceVbus (USB_DEVICE_TYPE_T type)
Disale USB device Vbus Sensing.
void USB_OTG_FlushTxFIFO (uint8_t num)
Flush specific TxFIFO.
void USB_OTG_FlushRxFIFO (void)
Flush RxFIFO.
void USB_Delay_us (uint32_t cnt)
Read the specified OTG interrupt flag.
Detailed Description
Function Documentation
USB_Delay_us()
void USB_Delay_us (uint32_t cnt)
Read the specified OTG interrupt flag.
Parameters
USB_INT_OTG_T :point to USB_INT_OTG_T enum typedef
Return values
Flag status. 1 to set and 0 to not set
Read the specified Global interrupt flag
Parameters
USB_INT_G_T Point to USB_INT_G_T enum typedef
Return values
Flag status. 1 to set and 0 to not set
USB delay
Parameters
cnt : delay counter
Return values
None
Definition at line 252 of file drv_usb.c.
References USB_UserCallBack_T::delay, and g_userCallback.
Referenced by USB_CoreSoftReset(), USB_HostInit(), USB_OTG_FlushRxFIFO(), USB_OTG_FlushTxFIFO(), and USB_OTG_PortReset().
USB_OTG_ConfigMode()
void USB_OTG_ConfigMode (USB_MODE_T mode)
Force USB to device ot host mode.
Parameters
mode : Select mode. This value can be one of the following values:
USB_MODE_DEVICE : Force device mode.
USB_MODE_HOST : Force host mode.
Return values
None
Definition at line 56 of file drv_usb.c.
References BIT_SET, and USB_MODE_HOST.
Referenced by USB_HostInit().
USB_OTG_ConfigPHY()
void USB_OTG_ConfigPHY (USB_OTG_PHY_T phy)
Config HS PHY or FS Serial Transceiver.
Parameters
phy : Select PHY. This value can be one of the following values:
USB_OTG_PHY_FS : FS Serial Transceiver
USB_OTG_PHY_HS : HS PHY
Return values
None
Definition at line 78 of file drv_usb.c.
USB_OTG_DisableDeviceVbus()
void USB_OTG_DisableDeviceVbus (USB_DEVICE_TYPE_T type)
Disale USB device Vbus Sensing.
Parameters
type : Select "A" device or "B" device This value can be one of the following values:
USB_DEVICE_A : "A" device
USB_DEVICE_B : "B" device
Return values
None
Definition at line 140 of file drv_usb.c.
References BIT_RESET, and USB_DEVICE_A.
USB_OTG_DisableVbusSensing()
void USB_OTG_DisableVbusSensing (void)
Disale USB Vbus Sensing.
Parameters
None
Return values
None
Definition at line 103 of file drv_usb.c.
References BIT_SET.
USB_OTG_EnableDeviceVbus()
void USB_OTG_EnableDeviceVbus (USB_DEVICE_TYPE_T type)
Enale USB device Vbus Sensing.
Parameters
type : Select "A" device or "B" device This value can be one of the following values:
USB_DEVICE_A : "A" device
USB_DEVICE_B : "B" device
Return values
None
Definition at line 118 of file drv_usb.c.
References BIT_SET, and USB_DEVICE_A.
USB_OTG_EnableVbusSensing()
void USB_OTG_EnableVbusSensing (void)
Enale USB Vbus Sensing.
Parameters
None
Return values
None
Definition at line 91 of file drv_usb.c.
References BIT_RESET.
USB_OTG_FlushRxFIFO()
void USB_OTG_FlushRxFIFO (void)
Flush RxFIFO.
Parameters
None
Return values
None
Definition at line 195 of file drv_usb.c.
References BIT_RESET, BIT_SET, and USB_Delay_us().
Referenced by USB_HostInit(), USB_OTG_StopHost(), and USBD_MSC_BOT_Init().
USB_OTG_FlushTxFIFO()
void USB_OTG_FlushTxFIFO (uint8_t num)
Flush specific TxFIFO.
Parameters
num TxFIFO number
Return values
None
Definition at line 159 of file drv_usb.c.
References BIT_RESET, BIT_SET, and USB_Delay_us().
Referenced by CDC_DEMO(), USB_HostInit(), USB_OTG_StopHost(), and USBD_MSC_BOT_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU