APM32F10x_SDK: APM32F103_MINI_Fuctions
APM32F103_MINI_Fuctions
Board » Board_APM32F103_MINI
Functions
void Delay_Init (void)
Update SystemCoreClock variable according to Clock Register Values The SystemCoreClock variable contains the core clock (HCLK)
void Delay_ms (__IO u32 nms)
Configures Delay ms.
void Delay_us (__IO u32 nus)
Configures Delay us.
Detailed Description
Function Documentation
Delay_Init()
void Delay_Init (void)
Update SystemCoreClock variable according to Clock Register Values The SystemCoreClock variable contains the core clock (HCLK)
Parameters
None
Return values
None
Definition at line 64 of file bsp_delay.c.
References SystemCoreClockUpdate().
Referenced by main().
Delay_ms()
void Delay_ms (__IO u32 nms)
Configures Delay ms.
Parameters
nms Specifies the delay to be configured. This parameter can be one of following parameters:
nms
Return values
None
Definition at line 79 of file bsp_delay.c.
References cntMs, and SystemCoreClock.
Referenced by AT24CXX_WriteOneByte(), and main().
Delay_us()
void Delay_us (__IO u32 nus)
Configures Delay us.
Parameters
nus Specifies the delay to be configured. This parameter can be one of following parameters:
nus
Return values
None
Definition at line 97 of file bsp_delay.c.
References cntUs, and SystemCoreClock.
Referenced by IIC_Ack(), IIC_NAck(), IIC_Read_Byte(), IIC_Send_Byte(), IIC_Start(), IIC_Stop(), and IIC_Wait_Ack().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU