APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader » YMODEM
Functions
int32_t recceiveFile (uint8_t *buffer, uint8_t Application)
Receive a file from sender using the Ymodem.
uint8_t transmitFile (uint8_t *buf, const uint8_t *name, uint32_t lenFile)
Transmit a file using the Ymodem.
uint16_t CRC16_Update (uint16_t value, uint8_t b)
Update CRC16 for input byte.
uint16_t CRC16_Sum (const uint8_t *data, uint32_t len)
Cal CRC16.
uint8_t Check_sum (const uint8_t *data, uint32_t len)
Cal Check sum for YModem Packet.
void PreFirstPack (uint8_t *data, const uint8_t *fileName, uint32_t *length)
!
void PrePack (uint8_t *sourceBuf, uint8_t *data, uint8_t packNo, uint32_t lenBlk)
Prepare the Ymodem data pack.
void Send_Packet (uint8_t *data, uint16_t length)
Transmit a data pack using the ymodem protocol.
Detailed Description
Function Documentation
Check_sum()
uint8_t Check_sum (const uint8_t * data, uint32_t len)
Cal Check sum for YModem Packet.
Parameters
data
len
Return values
checksum
Note
Definition at line 184 of file ymodem.c.
References data.
Referenced by transmitFile().
CRC16_Sum()
uint16_t CRC16_Sum (const uint8_t * data, uint32_t len)
Cal CRC16.
Parameters
data
len
Return values
CRC16 sum
Note
Definition at line 155 of file ymodem.c.
References CRC16_Update(), and data.
Referenced by transmitFile().
CRC16_Update()
uint16_t CRC16_Update (uint16_t value, uint8_t b)
Update CRC16 for input byte.
Parameters
value CRC input value
b input byte
Return values
returnTemp Updated CRC value
Note
Definition at line 116 of file ymodem.c.
References b.
Referenced by CRC16_Sum().
PreFirstPack()
void PreFirstPack (uint8_t * data, const uint8_t * fileName, uint32_t * length)
!
Prepare the Ymodem first packet
Parameters
data packet data
fileName file name
length file lenght
Return values
None
Note
Definition at line 482 of file ymodem.c.
References data, FILE_NAME_MAX, FRAME_SOH, IntConStr(), PACK_FRAME_HEADER, and PACKET_SIZE.
Referenced by transmitFile().
PrePack()
void PrePack (uint8_t * sourceBuf, uint8_t * data, uint8_t packNo, uint32_t lenBlk)
Prepare the Ymodem data pack.
Parameters
sourceBuf:source buffer
data:packet data
packNo:packet block number
lenBlk packet block lenght
Return values
None
Note
Definition at line 539 of file ymodem.c.
References data, FILE_FILL_VAL, FRAME_SOH, FRAME_STX, PACK_FRAME_HEADER, PACKET_1K_SIZE, and PACKET_SIZE.
Referenced by transmitFile().
recceiveFile()
int32_t recceiveFile (uint8_t * buffer, uint8_t Application)
Receive a file from sender using the Ymodem.
Parameters
buffer file buffer
Application : APP1 or APP2
Return values
The lenght of the file
Note
Definition at line 303 of file ymodem.c.
References APP1, ERRORS, FILE_NAME_MAX, FILE_SIZE_MAX, FileN, FLASH_IAP_Erase(), FLASH_IAP_Write(), FRAME_ACK, FRAME_CAN, FRAME_CRC16, FRAME_NACK, NAK_TIMEOUT, PACK_1K_FRAME_OVERHEAD_SIZE, PACK_FRAME_HEADER, PACK_FRAMENO_INDEX, StrConInt(), SUCCESS, USER_APP1_START_ADDRESS, USER_APP2_START_ADDRESS, and USER_FLASH_SIZE.
Referenced by Download().
Send_Packet()
void Send_Packet (uint8_t * data, uint16_t length)
Transmit a data pack using the ymodem protocol.
Parameters
data packet data
length : The length of packet data
Return values
None
Note
Definition at line 602 of file ymodem.c.
References data.
Referenced by transmitFile().
transmitFile()
uint8_t transmitFile (uint8_t * buf, const uint8_t * name, uint32_t lenFile)
Transmit a file using the Ymodem.
Parameters
buf File address of the first byte
name File name
lenFile The lenght of the file
Return values
The lenght of the file
Note
Definition at line 623 of file ymodem.c.
References Check_sum(), CRC16_Sum(), ERRORS, FILE_NAME_MAX, FileN, FRAME_ACK, FRAME_EOT, FRAME_SOH, PACK_FRAME_HEADER, PACK_FRAME_OVERHEAD, PACKET_1K_SIZE, PACKET_SIZE, PreFirstPack(), PrePack(), Send_Packet(), SUCCESS, USART_COM_CLEAR_OVREE, USART_COM_RXDATA, and USER_FLASH_SIZE.
Referenced by Upload().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU