APM32F10x_SDK: Functions
Functions
Examples » USB_CDC_VirtualCOMPort
Functions
void USBD_HardWareInit (void)
void CDC_Init (void)
USB cdc init.
void CDC_Proc (void)
void CDC_SetConfigCallBack (void)
int main (void)
Main program.
void VCP_Reset (void)
Reset.
void USBD_VCP_OutEpCallback (uint8_t ep)
OUT endpoint transfer done handler(except EP0)
void USBD_VCP_InEpCallback (uint8_t ep)
IN endpoint transfer done handler(except EP0)
Detailed Description
Function Documentation
CDC_Init()
void CDC_Init (void)
USB cdc init.
Parameters
None
Return values
None
Definition at line 150 of file usbd_cdc.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_stringDescriptor, USBD_InitParam_T::inEpHandler, USBD_InitParam_T::outEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, USBD_InitParam_T::resetHandler, stdReqCallback, USBD_ClassHandler(), USBD_Init(), USBD_InitParamStructInit(), USBD_VCP_InEpCallback(), USBD_VCP_OutEpCallback(), and VCP_Reset().
Referenced by main().
CDC_Proc()
void CDC_Proc (void)
CDC_SetConfigCallBack()
void CDC_SetConfigCallBack (void)
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 50 of file USB/USB_CDC_VirtualCOMPort/Source/main.c.
References CDC_Init().
USBD_HardWareInit()
void USBD_HardWareInit (void)
Definition at line 41 of file USB_CDC_VirtualCOMPort/Source/usb_bsp.c.
References EINT_Config(), EINT_LINE_18, EINT_MODE_INTERRUPT, EINT_TRIGGER_RISING, ENABLE, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, NVIC_EnableIRQRequest(), RCM_APB1_PERIPH_USB, RCM_ConfigUSBCLK(), RCM_EnableAPB1PeriphClock(), RCM_USB_DIV_1_5, and EINT_Config_T::trigger.
Referenced by USBD_Init().
USBD_VCP_InEpCallback()
void USBD_VCP_InEpCallback (uint8_t ep)
IN endpoint transfer done handler(except EP0)
Parameters
ep : IN endpoint
Return values
None
Definition at line 135 of file usbd_cdc.c.
References dataBuf, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USBD_EP_1, and USBD_RxData().
Referenced by CDC_Init().
USBD_VCP_OutEpCallback()
void USBD_VCP_OutEpCallback (uint8_t ep)
OUT endpoint transfer done handler(except EP0)
Parameters
ep : OUT endpoint
Return values
None
Definition at line 116 of file usbd_cdc.c.
References dataBuf, g_usbDev, USBD_Info_T::outBuf, USBD_EP_1, USBD_TxData(), and USBD_CtrlBuf_T::xferCnt.
Referenced by CDC_Init().
VCP_Reset()
void VCP_Reset (void)
Reset.
Parameters
None
Return values
None
Definition at line 75 of file usbd_cdc.c.
References USBD_EPConfig_T::epBufAddr, USBD_EPConfig_T::epNum, USBD_EPConfig_T::epStatus, USBD_EPConfig_T::epType, USBD_EPConfig_T::maxPackSize, USB_EP1_RX_ADDR, USB_EP1_TX_ADDR, USB_EP2_TX_ADDR, USBD_EP_1, USBD_EP_2, USBD_EP_STATUS_NAK, USBD_EP_TYPE_BULK, USBD_EP_TYPE_INTERRUPT, USBD_OpenInEP(), and USBD_OpenOutEP().
Referenced by CDC_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU