APM32F10x_SDK: ETH_Functions
ETH_Functions
APM32F10x_ETHDriver » ETH_Driver
Functions
void ETH_Reset (void)
void ETH_ConfigStructInit (ETH_Config_T *ethConfig)
uint32_t ETH_Config (ETH_Config_T *ethConfig, uint16_t addr)
void ETH_SoftwareReset (void)
uint8_t ETH_ReadSoftwareReset (void)
void ETH_Start (void)
void ETH_Stop (void)
uint32_t ETH_ReadRxPacketSize (ETH_DMADescConfig_T *DMARxDesc)
uint16_t ETH_ReadPHYRegister (uint16_t addr, uint16_t reg)
uint32_t ETH_WritePHYRegister (uint16_t addr, uint16_t reg, uint16_t data)
uint32_t ETH_EnablePHYLoopBack (uint16_t addr)
uint32_t ETH_DisablePHYLoopBack (uint16_t addr)
void ETH_EnableMACTransmission (void)
void ETH_DisableMACTransmission (void)
void ETH_EnableMACReceiver (void)
void ETH_DisableMACReceiver (void)
uint8_t ETH_ReadFlowControlBusyStatus (void)
void ETH_SetPauseControlFrame (void)
void ETH_EnableBackPressureActivation (void)
void ETH_DisableBackPressureActivation (void)
uint8_t ETH_ReadMACFlagStatus (ETH_MAC_FLAG_T flag)
void ETH_EnableMACInterrupt (uint32_t interrupt)
void ETH_DisableMACInterrupt (uint32_t interrupt)
void ETH_ConfigMACAddress (ETH_MAC_ADDRESS_T macAddr, uint8_t *addr)
void ETH_ReadMACAddress (ETH_MAC_ADDRESS_T macAddr, uint8_t *addr)
void ETH_EnableMACAddressPerfectFilter (ETH_MAC_ADDRESS_T macAddr)
void ETH_DisableMACAddressPerfectFilter (ETH_MAC_ADDRESS_T macAddr)
void ETH_ConfigMACAddressFilter (ETH_MAC_ADDRESS_T macAddr, ETH_MAC_ADDRESSFILTER_T filter)
void ETH_ConfigMACAddressMaskBytesFilter (ETH_MAC_ADDRESS_T macAddr, uint32_t maskByte)
void ETH_ConfigDMARxDescChain (ETH_DMADescConfig_T *DMARxDescTab, uint8_t *rxBuff, uint32_t rxBuffcount)
void ETH_ConfigDMATxDescChain (ETH_DMADescConfig_T *DMATxDescTab, uint8_t *txBuff, uint32_t txBuffcount)
uint32_t ETH_CheckReceivedFrame (void)
uint32_t ETH_Transmit_Descriptors (u16 frameLength)
ETH_Frame_T ETH_ReadReceivedFrame (void)
uint8_t ETH_ReadDMATxDescFlagStatus (ETH_DMADescConfig_T *DMATxDesc, ETH_DMATXDESC_FLAG_T flag)
uint32_t ETH_ReadDMATxDescCollisionCount (ETH_DMADescConfig_T *DMATxDesc)
void ETH_ConfigDMATxDescOwnBit (ETH_DMADescConfig_T *DMATxDesc)
void ETH_EnableDMATxDescTransmitInterrupt (ETH_DMADescConfig_T *DMATxDesc)
void ETH_DisableDMATxDescTransmitInterrupt (ETH_DMADescConfig_T *DMATxDesc)
void ETH_ConfigDMATxDescFrameSegment (ETH_DMADescConfig_T *DMATxDesc, ETH_DMATXDESC_SEGMENTS_T frameSegment)
void ETH_ConfigDMATxDescChecksumInsertion (ETH_DMADescConfig_T *DMATxDesc, ETH_DMATXDESC_CHECKSUMB_T checksum)
void ETH_EnableDMATxDescCRC (ETH_DMADescConfig_T *DMATxDesc)
void ETH_DisableDMATxDescCRC (ETH_DMADescConfig_T *DMATxDesc)
void ETH_EnableDMATxDescSecondAddressChained (ETH_DMADescConfig_T *DMATxDesc)
void ETH_DisableDMATxDescSecondAddressChained (ETH_DMADescConfig_T *DMATxDesc)
void ETH_EnableDMATxDescShortFramePadding (ETH_DMADescConfig_T *DMATxDesc)
void ETH_DisableDMATxDescShortFramePadding (ETH_DMADescConfig_T *DMATxDesc)
void ETH_ConfigDMATxDescBufferSize (ETH_DMADescConfig_T *DMATxDesc, uint32_t bufferSize1, uint32_t bufferSize2)
uint8_t ETH_ReadDMARxDescFlagStatus (ETH_DMADescConfig_T *DMARxDesc, ETH_DMARXDESC_FLAG_T flag)
void ETH_ConfigDMARxDescOwnBit (ETH_DMADescConfig_T *DMARxDesc)
uint32_t ETH_ReadDMARxDescFrameLength (ETH_DMADescConfig_T *DMARxDesc)
void ETH_EnableDMARxDescReceiveInterrupt (ETH_DMADescConfig_T *DMARxDesc)
void ETH_DisableDMARxDescReceiveInterrupt (ETH_DMADescConfig_T *DMATxDesc)
uint32_t ETH_ReadDMARxDescBufferSize (ETH_DMADescConfig_T *DMARxDesc, ETH_DMARXDESC_BUFFER_T buffer)
ETH_Frame_T ETH_ReadReceivedFrameInterrupt (void)
uint8_t ETH_ReadDMAFlagStatus (ETH_DMA_FLAG_T flag)
void ETH_ClearDMAFlag (uint32_t flag)
uint8_t ETH_ReadDMAIntFlag (ETH_DMA_INT_T flag)
void ETH_ClearDMAIntFlag (uint32_t flag)
uint32_t ETH_ReadTransmitProcessState (void)
uint32_t ETH_ReadReceiveProcessState (void)
void ETH_FlushTransmitFIFO (void)
uint8_t ETH_ReadFlushTransmitFIFOStatus (void)
void ETH_EnableDMATransmission (void)
void ETH_DisableDMATransmission (void)
void ETH_EnableDMAReceiver (void)
void ETH_DisableDMAReceiver (void)
void ETH_EnableDMAInterrupt (uint32_t interrupt)
void ETH_DisableDMAInterrupt (uint32_t interrupt)
uint8_t ETH_ReadDMAOverflowStatus (ETH_DMA_OVERFLOW_T overflow)
uint32_t ETH_ReadRxOverflowMissedFrameCounter (void)
uint32_t ETH_ReadBufferUnavailableMissedFrameCounter (void)
uint32_t ETH_ReadCurrentTxDescStartAddress (void)
uint32_t ETH_ReadCurrentRxDescStartAddress (void)
uint32_t ETH_ReadCurrentTxBufferAddress (void)
uint32_t ETH_ReadCurrentRxBufferAddress (void)
void ETH_ResetDMATransmission (void)
void ETH_ResetDMAReception (void)
void ETH_ResetWakeUpFrameFilterRegisterPointer (void)
void ETH_EnableGlobalUnicastWakeUp (void)
void ETH_DisableGlobalUnicastWakeUp (void)
uint8_t ETH_ReadPMTFlagStatus (ETH_PMT_FLAG_T flag)
void ETH_EnableWakeUpFrameDetection (void)
void ETH_DisableWakeUpFrameDetection (void)
void ETH_EnableMagicPacketDetection (void)
void ETH_DisableMagicPacketDetection (void)
void ETH_EnablePowerDown (void)
void ETH_DisablePowerDown (void)
void ETH_EnableMMCCounterFreeze (void)
void ETH_DisableMMCCounterFreeze (void)
void ETH_EnableMMCResetOnRead (void)
void ETH_DisableMMCResetOnRead (void)
void ETH_EnableMMCCounterRollover (void)
void ETH_DisableMMCCounterRollover (void)
void ETH_ResetMMCCounters (void)
void ETH_EnableMMCInterrupt (uint32_t interrupt)
void ETH_DisableMMCInterrupt (uint32_t interrupt)
uint8_t ETH_ReadMMCIntFlag (uint32_t flag)
uint32_t ETH_ReadMMCRegister (ETH_MMC_REG_T MMCReg)
Detailed Description
Function Documentation
ETH_CheckReceivedFrame()
uint32_t ETH_CheckReceivedFrame (void)
ETH_ClearDMAFlag()
void ETH_ClearDMAFlag (uint32_t flag)
ETH_ClearDMAIntFlag()
void ETH_ClearDMAIntFlag (uint32_t flag)
Referenced by ETH_IRQHandler().
ETH_Config()
uint32_t ETH_Config (ETH_Config_T * ethConfig, uint16_t addr)
ETH_ConfigDMARxDescChain()
void ETH_ConfigDMARxDescChain (ETH_DMADescConfig_T * DMARxDescTab, uint8_t * rxBuff, uint32_t rxBuffcount)
ETH_ConfigDMARxDescOwnBit()
void ETH_ConfigDMARxDescOwnBit (ETH_DMADescConfig_T * DMARxDesc)
ETH_ConfigDMATxDescBufferSize()
void ETH_ConfigDMATxDescBufferSize (ETH_DMADescConfig_T * DMATxDesc, uint32_t bufferSize1, uint32_t bufferSize2)
ETH_ConfigDMATxDescChain()
void ETH_ConfigDMATxDescChain (ETH_DMADescConfig_T * DMATxDescTab, uint8_t * txBuff, uint32_t txBuffcount)
ETH_ConfigDMATxDescChecksumInsertion()
void ETH_ConfigDMATxDescChecksumInsertion (ETH_DMADescConfig_T * DMATxDesc, ETH_DMATXDESC_CHECKSUMB_T checksum)
ETH_ConfigDMATxDescFrameSegment()
void ETH_ConfigDMATxDescFrameSegment (ETH_DMADescConfig_T * DMATxDesc, ETH_DMATXDESC_SEGMENTS_T frameSegment)
ETH_ConfigDMATxDescOwnBit()
void ETH_ConfigDMATxDescOwnBit (ETH_DMADescConfig_T * DMATxDesc)
ETH_ConfigMACAddress()
void ETH_ConfigMACAddress (ETH_MAC_ADDRESS_T macAddr, uint8_t * addr)
Referenced by LwIP_Init().
ETH_ConfigMACAddressFilter()
void ETH_ConfigMACAddressFilter (ETH_MAC_ADDRESS_T macAddr, ETH_MAC_ADDRESSFILTER_T filter)
ETH_ConfigMACAddressMaskBytesFilter()
void ETH_ConfigMACAddressMaskBytesFilter (ETH_MAC_ADDRESS_T macAddr, uint32_t maskByte)
ETH_ConfigStructInit()
void ETH_ConfigStructInit (ETH_Config_T * ethConfig)
ETH_DisableBackPressureActivation()
void ETH_DisableBackPressureActivation (void)
ETH_DisableDMAInterrupt()
void ETH_DisableDMAInterrupt (uint32_t interrupt)
ETH_DisableDMAReceiver()
void ETH_DisableDMAReceiver (void)
ETH_DisableDMARxDescReceiveInterrupt()
void ETH_DisableDMARxDescReceiveInterrupt (ETH_DMADescConfig_T * DMATxDesc)
ETH_DisableDMATransmission()
void ETH_DisableDMATransmission (void)
ETH_DisableDMATxDescCRC()
void ETH_DisableDMATxDescCRC (ETH_DMADescConfig_T * DMATxDesc)
ETH_DisableDMATxDescSecondAddressChained()
void ETH_DisableDMATxDescSecondAddressChained (ETH_DMADescConfig_T * DMATxDesc)
ETH_DisableDMATxDescShortFramePadding()
void ETH_DisableDMATxDescShortFramePadding (ETH_DMADescConfig_T * DMATxDesc)
ETH_DisableDMATxDescTransmitInterrupt()
void ETH_DisableDMATxDescTransmitInterrupt (ETH_DMADescConfig_T * DMATxDesc)
ETH_DisableGlobalUnicastWakeUp()
void ETH_DisableGlobalUnicastWakeUp (void)
ETH_DisableMACAddressPerfectFilter()
void ETH_DisableMACAddressPerfectFilter (ETH_MAC_ADDRESS_T macAddr)
ETH_DisableMACInterrupt()
void ETH_DisableMACInterrupt (uint32_t interrupt)
ETH_DisableMACReceiver()
void ETH_DisableMACReceiver (void)
ETH_DisableMACTransmission()
void ETH_DisableMACTransmission (void)
ETH_DisableMagicPacketDetection()
void ETH_DisableMagicPacketDetection (void)
ETH_DisableMMCCounterFreeze()
void ETH_DisableMMCCounterFreeze (void)
ETH_DisableMMCCounterRollover()
void ETH_DisableMMCCounterRollover (void)
ETH_DisableMMCInterrupt()
void ETH_DisableMMCInterrupt (uint32_t interrupt)
ETH_DisableMMCResetOnRead()
void ETH_DisableMMCResetOnRead (void)
ETH_DisablePHYLoopBack()
uint32_t ETH_DisablePHYLoopBack (uint16_t addr)
ETH_DisablePowerDown()
void ETH_DisablePowerDown (void)
ETH_DisableWakeUpFrameDetection()
void ETH_DisableWakeUpFrameDetection (void)
ETH_EnableBackPressureActivation()
void ETH_EnableBackPressureActivation (void)
ETH_EnableDMAInterrupt()
void ETH_EnableDMAInterrupt (uint32_t interrupt)
Referenced by Ethernet_Config().
ETH_EnableDMAReceiver()
void ETH_EnableDMAReceiver (void)
ETH_EnableDMARxDescReceiveInterrupt()
void ETH_EnableDMARxDescReceiveInterrupt (ETH_DMADescConfig_T * DMARxDesc)
ETH_EnableDMATransmission()
void ETH_EnableDMATransmission (void)
ETH_EnableDMATxDescCRC()
void ETH_EnableDMATxDescCRC (ETH_DMADescConfig_T * DMATxDesc)
ETH_EnableDMATxDescSecondAddressChained()
void ETH_EnableDMATxDescSecondAddressChained (ETH_DMADescConfig_T * DMATxDesc)
ETH_EnableDMATxDescShortFramePadding()
void ETH_EnableDMATxDescShortFramePadding (ETH_DMADescConfig_T * DMATxDesc)
ETH_EnableDMATxDescTransmitInterrupt()
void ETH_EnableDMATxDescTransmitInterrupt (ETH_DMADescConfig_T * DMATxDesc)
ETH_EnableGlobalUnicastWakeUp()
void ETH_EnableGlobalUnicastWakeUp (void)
ETH_EnableMACAddressPerfectFilter()
void ETH_EnableMACAddressPerfectFilter (ETH_MAC_ADDRESS_T macAddr)
ETH_EnableMACInterrupt()
void ETH_EnableMACInterrupt (uint32_t interrupt)
ETH_EnableMACReceiver()
void ETH_EnableMACReceiver (void)
ETH_EnableMACTransmission()
void ETH_EnableMACTransmission (void)
ETH_EnableMagicPacketDetection()
void ETH_EnableMagicPacketDetection (void)
ETH_EnableMMCCounterFreeze()
void ETH_EnableMMCCounterFreeze (void)
ETH_EnableMMCCounterRollover()
void ETH_EnableMMCCounterRollover (void)
ETH_EnableMMCInterrupt()
void ETH_EnableMMCInterrupt (uint32_t interrupt)
ETH_EnableMMCResetOnRead()
void ETH_EnableMMCResetOnRead (void)
ETH_EnablePHYLoopBack()
uint32_t ETH_EnablePHYLoopBack (uint16_t addr)
ETH_EnablePowerDown()
void ETH_EnablePowerDown (void)
ETH_EnableWakeUpFrameDetection()
void ETH_EnableWakeUpFrameDetection (void)
ETH_FlushTransmitFIFO()
void ETH_FlushTransmitFIFO (void)
ETH_ReadBufferUnavailableMissedFrameCounter()
uint32_t ETH_ReadBufferUnavailableMissedFrameCounter (void)
ETH_ReadCurrentRxBufferAddress()
uint32_t ETH_ReadCurrentRxBufferAddress (void)
ETH_ReadCurrentRxDescStartAddress()
uint32_t ETH_ReadCurrentRxDescStartAddress (void)
ETH_ReadCurrentTxBufferAddress()
uint32_t ETH_ReadCurrentTxBufferAddress (void)
ETH_ReadCurrentTxDescStartAddress()
uint32_t ETH_ReadCurrentTxDescStartAddress (void)
ETH_ReadDMAFlagStatus()
uint8_t ETH_ReadDMAFlagStatus (ETH_DMA_FLAG_T flag)
ETH_ReadDMAIntFlag()
uint8_t ETH_ReadDMAIntFlag (ETH_DMA_INT_T flag)
Referenced by ETH_IRQHandler().
ETH_ReadDMAOverflowStatus()
uint8_t ETH_ReadDMAOverflowStatus (ETH_DMA_OVERFLOW_T overflow)
ETH_ReadDMARxDescBufferSize()
uint32_t ETH_ReadDMARxDescBufferSize (ETH_DMADescConfig_T * DMARxDesc, ETH_DMARXDESC_BUFFER_T buffer)
ETH_ReadDMARxDescFlagStatus()
uint8_t ETH_ReadDMARxDescFlagStatus (ETH_DMADescConfig_T * DMARxDesc, ETH_DMARXDESC_FLAG_T flag)
ETH_ReadDMARxDescFrameLength()
uint32_t ETH_ReadDMARxDescFrameLength (ETH_DMADescConfig_T * DMARxDesc)
ETH_ReadDMATxDescCollisionCount()
uint32_t ETH_ReadDMATxDescCollisionCount (ETH_DMADescConfig_T * DMATxDesc)
ETH_ReadDMATxDescFlagStatus()
uint8_t ETH_ReadDMATxDescFlagStatus (ETH_DMADescConfig_T * DMATxDesc, ETH_DMATXDESC_FLAG_T flag)
ETH_ReadFlowControlBusyStatus()
uint8_t ETH_ReadFlowControlBusyStatus (void)
ETH_ReadFlushTransmitFIFOStatus()
uint8_t ETH_ReadFlushTransmitFIFOStatus (void)
ETH_ReadMACAddress()
void ETH_ReadMACAddress (ETH_MAC_ADDRESS_T macAddr, uint8_t * addr)
ETH_ReadMACFlagStatus()
uint8_t ETH_ReadMACFlagStatus (ETH_MAC_FLAG_T flag)
ETH_ReadMMCIntFlag()
uint8_t ETH_ReadMMCIntFlag (uint32_t flag)
ETH_ReadMMCRegister()
uint32_t ETH_ReadMMCRegister (ETH_MMC_REG_T MMCReg)
ETH_ReadPHYRegister()
uint16_t ETH_ReadPHYRegister (uint16_t addr, uint16_t reg)
ETH_ReadPMTFlagStatus()
uint8_t ETH_ReadPMTFlagStatus (ETH_PMT_FLAG_T flag)
ETH_ReadReceivedFrame()
ETH_Frame_T ETH_ReadReceivedFrame (void)
ETH_ReadReceivedFrameInterrupt()
ETH_Frame_T ETH_ReadReceivedFrameInterrupt (void)
ETH_ReadReceiveProcessState()
uint32_t ETH_ReadReceiveProcessState (void)
ETH_ReadRxOverflowMissedFrameCounter()
uint32_t ETH_ReadRxOverflowMissedFrameCounter (void)
ETH_ReadRxPacketSize()
uint32_t ETH_ReadRxPacketSize (ETH_DMADescConfig_T * DMARxDesc)
Referenced by main().
ETH_ReadSoftwareReset()
uint8_t ETH_ReadSoftwareReset (void)
ETH_ReadTransmitProcessState()
uint32_t ETH_ReadTransmitProcessState (void)
ETH_Reset()
void ETH_Reset (void)
ETH_ResetDMAReception()
void ETH_ResetDMAReception (void)
ETH_ResetDMATransmission()
void ETH_ResetDMATransmission (void)
ETH_ResetMMCCounters()
void ETH_ResetMMCCounters (void)
ETH_ResetWakeUpFrameFilterRegisterPointer()
void ETH_ResetWakeUpFrameFilterRegisterPointer (void)
ETH_SetPauseControlFrame()
void ETH_SetPauseControlFrame (void)
ETH_SoftwareReset()
void ETH_SoftwareReset (void)
ETH_Start()
void ETH_Start (void)
ETH_Stop()
void ETH_Stop (void)
ETH_Transmit_Descriptors()
uint32_t ETH_Transmit_Descriptors (u16 frameLength)
ETH_WritePHYRegister()
uint32_t ETH_WritePHYRegister (uint16_t addr, uint16_t reg, uint16_t data)
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU