APM32F10x_SDK: Functions
Functions
Examples » DMC_SDRAM
Functions
void SDRAM_Init (void)
SDRAM Init.
uint32_t SDRAM_Word_Test (void)
SDRAM Word Test.
uint32_t SDRAM_HalfWord_Test (void)
SDRAM HalfWord Test.
uint32_t SDRAM_Byte_Test (void)
SDRAM Byte Test.
void SDRAM_WriteWord (uint32_t address, uint32_t data)
SDRAM Write Word.
void SDRAM_WriteHalfWord (uint32_t address, uint16_t data)
SDRAM Write Half Word.
void SDRAM_WriteByte (uint32_t address, uint8_t data)
SDRAM Write Byte.
void Delay (void)
Delay.
void SystemCoreClockConfig (uint32_t pllMf, uint32_t latency)
Sets System clock frequency.
int main (void)
Main program.
Detailed Description
Function Documentation
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 231 of file EMMC/DMC_SDRAM/Source/main.c.
References tick.
main()
int main (void)
Main program.
Parameters
None
Return values
None
< 3*8 = 24MHz
Definition at line 90 of file EMMC/DMC_SDRAM/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDToggle(), USART_Config_T::baudRate, Err_Count_T::ByteCount, COM1, Delay(), Err_Count_T::HalfWordCount, USART_Config_T::hardwareFlow, LED2, LED3, MESSAGE0, MESSAGE1, MESSAGE2, MESSAGE3, MESSAGE4, MESSAGE5, USART_Config_T::mode, USART_Config_T::parity, RCM_ReadSYSCLKFreq(), SDRAM_Byte_Test(), SDRAM_HalfWord_Test(), SDRAM_Init(), SDRAM_Word_Test(), USART_Config_T::stopBits, SystemCoreClockConfig(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, Err_Count_T::WordCount, and USART_Config_T::wordLength.
SDRAM_Byte_Test()
uint32_t SDRAM_Byte_Test (void)
SDRAM Byte Test.
Parameters
None
Return values
i : W/R Err Count
Definition at line 135 of file dmc_sdram.c.
References SDRAM_END_ADDR, SDRAM_START_ADDR, and SDRAM_WriteByte().
Referenced by main().
SDRAM_HalfWord_Test()
uint32_t SDRAM_HalfWord_Test (void)
SDRAM HalfWord Test.
Parameters
None
Return values
i : W/R Err Count
Definition at line 106 of file dmc_sdram.c.
References SDRAM_END_ADDR, SDRAM_START_ADDR, and SDRAM_WriteHalfWord().
Referenced by main().
SDRAM_Init()
void SDRAM_Init (void)
SDRAM Init.
Parameters
None
Return values
None
Definition at line 63 of file dmc_sdram.c.
Referenced by main().
SDRAM_Word_Test()
uint32_t SDRAM_Word_Test (void)
SDRAM Word Test.
Parameters
None
Return values
i : W/R Err Count
Definition at line 77 of file dmc_sdram.c.
References SDRAM_END_ADDR, SDRAM_START_ADDR, and SDRAM_WriteWord().
Referenced by main().
SDRAM_WriteByte()
void SDRAM_WriteByte (uint32_t address, uint8_t data)
SDRAM Write Byte.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
None
Definition at line 196 of file dmc_sdram.c.
References data.
Referenced by SDRAM_Byte_Test().
SDRAM_WriteHalfWord()
void SDRAM_WriteHalfWord (uint32_t address, uint16_t data)
SDRAM Write Half Word.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
None
Definition at line 181 of file dmc_sdram.c.
References data.
Referenced by SDRAM_HalfWord_Test().
SDRAM_WriteWord()
void SDRAM_WriteWord (uint32_t address, uint32_t data)
SDRAM Write Word.
Parameters
address:the address to be programmed.
data the data to be programmed.
Return values
None
Definition at line 166 of file dmc_sdram.c.
References __IOM, and data.
Referenced by SDRAM_Word_Test().
SystemCoreClockConfig()
void SystemCoreClockConfig (uint32_t pllMf, uint32_t latency)
Sets System clock frequency.
Parameters
pllMf : PLL multiplication factor This parameter can be RCM_PLLMF_x where x can be a value from 2 to 16.
latency the FMC Latency value.
Return values
None
Definition at line 168 of file EMMC/DMC_SDRAM/Source/main.c.
References BIT_RESET, BIT_SET, FMC, HSE_STARTUP_TIMEOUT, and RCM.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU