APM32F10x_SDK: usbd_core.c File Reference
usbd_core.c File Reference
USB protocol core handler.
#include "usbd_core.h"
#include "usbd_stdReq.h"
Functions
void USBD_SetupProcess (void)
Endpoint 0 Setup process.
void USBD_CtrlInProcess (void)
Endpoint 0 USB Control in process.
void USBD_CtrlOutProcess (void)
Endpoint 0 USB Control out process.
void USBD_CtrlInData (uint8_t *buf, uint32_t len)
Send data or status in control in transation.
void USBD_CtrlOutData (uint8_t *buf, uint32_t len)
Read data or status in control out transation.
void USBD_DataInProcess (USBD_EP_T ep)
USB Data in process except endpoint 0.
void USBD_DataOutProcess (USBD_EP_T ep)
USB Data out process except endpoint 0.
void USBD_TxData (uint8_t ep, uint8_t *buf, uint32_t len)
Transfer data to host(except endpoint 0)
void USBD_RxData (uint8_t ep, uint8_t *buf, uint32_t len)
Receive data from host(except endpoint 0)
Variables
USBD_Info_T g_usbDev
USB information.
Detailed Description
USB protocol core handler.
Version
V1.0.0
Date
2021-12-06
Attention
Copyright (C) 2020-2022 Geehy Semiconductor
You may not use this file except in compliance with the GEEHY COPYRIGHT NOTICE (GEEHY SOFTWARE PACKAGE LICENSE).
The program is only for reference, which is distributed in the hope that it will be useful and instructional for customers to develop their software. Unless required by applicable law or agreed to in writing, the program is distributed on an "AS IS" BASIS, WITHOUT ANY WARRANTY OR CONDITIONS OF ANY KIND, either express or implied. See the GEEHY SOFTWARE PACKAGE LICENSE for the governing permissions and limitations under the License.
Definition in file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
Function Documentation
USBD_CtrlInData()
void USBD_CtrlInData (uint8_t * buf, uint32_t len)
Send data or status in control in transation.
Parameters
buf Buffer pointer
len Buffer length
Return values
None
Send a packet
deal with buffer
Definition at line 199 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
USBD_CtrlInProcess()
void USBD_CtrlInProcess (void)
Endpoint 0 USB Control in process.
Parameters
None
Return values
None
Definition at line 98 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
USBD_CtrlOutData()
void USBD_CtrlOutData (uint8_t * buf, uint32_t len)
Read data or status in control out transation.
Parameters
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 256 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
Referenced by USBD_CtrlOutProcess().
USBD_CtrlOutProcess()
void USBD_CtrlOutProcess (void)
Endpoint 0 USB Control out process.
Parameters
None
Return values
None
Definition at line 153 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
USBD_DataInProcess()
void USBD_DataInProcess (USBD_EP_T ep)
USB Data in process except endpoint 0.
Handler other Endpoint data transfer.
Parameters
ep : endpoint Number except endpoint 0
Return values
None
Definition at line 287 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, USBD_Info_T::inBuf, USBD_Info_T::inEpHandler, USBD_CtrlBuf_T::maxPackSize, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_EP_STATUS_VALID, USBD_SetEPTxCnt, USBD_SetEPTxStatus(), and USBD_WriteDataToEP().
USBD_DataOutProcess()
void USBD_DataOutProcess (USBD_EP_T ep)
USB Data out process except endpoint 0.
Parameters
ep : endpoint Number except endpoint 0
Return values
None
Definition at line 321 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, NULL, USBD_Info_T::outBuf, USBD_Info_T::outEpHandler, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_EP_STATUS_VALID, USBD_ReadDataFromEP(), USBD_ReadEPRxCnt, USBD_SetEPRxStatus(), and USBD_CtrlBuf_T::xferCnt.
USBD_RxData()
void USBD_RxData (uint8_t ep, uint8_t * buf, uint32_t len)
Receive data from host(except endpoint 0)
Parameters
ep Endpoint number except endpoint 0
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 394 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
USBD_SetupProcess()
void USBD_SetupProcess (void)
Endpoint 0 Setup process.
Handler Endpoint 0 control transfer.
Parameters
None
Return values
None
Definition at line 39 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
USBD_TxData()
void USBD_TxData (uint8_t ep, uint8_t * buf, uint32_t len)
Transfer data to host(except endpoint 0)
Parameters
ep Endpoint number except endpoint 0
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 358 of file USB_Device_Lib/Core_Device/Standard/src/usbd_core.c.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU