APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader
Typedefs
typedef void(* pFunction) (void)
function hook
Functions
void Delay (void)
Delay.
void Jump_to_App (uint8_t Application)
Jump to user application.
int main (void)
Main program.
Variables
volatile uint32_t tick
pFunction Jump_To_Application
uint32_t JumpAddress
Detailed Description
Typedef Documentation
pFunction
typedef void(* pFunction) (void)
function hook
Definition at line 59 of file IAP/IAP_BootLoader/Include/main.h.
Function Documentation
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 94 of file IAP/IAP_BootLoader/Source/main.c.
References tick.
Jump_to_App()
void Jump_to_App (uint8_t Application)
Jump to user application.
Parameters
Application : APP1 or APP2
Return values
None
Note
Definition at line 110 of file IAP/IAP_BootLoader/Source/main.c.
References APP1, FMC_Lock(), Jump_To_Application, JumpAddress, USER_APP1_START_ADDRESS, and USER_APP2_START_ADDRESS.
Referenced by main(), and Select_Menu().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 60 of file IAP/IAP_BootLoader/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOn(), APP1, DEBUG_USART_BAUDRATE, FLASH_IAP_Init(), Jump_to_App(), LED2, LED3, Select_Menu(), SendString, and USART_Init().
Variable Documentation
Jump_To_Application
pFunction Jump_To_Application extern
Definition at line 43 of file IAP/IAP_BootLoader/Source/main.c.
Referenced by Jump_to_App().
JumpAddress
uint32_t JumpAddress extern
Definition at line 42 of file IAP/IAP_BootLoader/Source/main.c.
Referenced by Jump_to_App().
tick
volatile uint32_t tick extern
Definition at line 58 of file EMMC/DMC_SDRAM/Source/main.c.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU