APM32F10x_SDK: Functions
Functions
Examples » I2S_Interrupt
Functions
void RCM_Configuration (void)
Configures the different system clocks.
void GPIO_Configuration (void)
Configures the different GPIO ports.
void NVIC_Configuration (void)
Configure the nested vectored interrupt controller.
uint8_t Buffercmp (uint16_t *pBuffer1, uint16_t *pBuffer2, uint16_t BufferLength)
Compares two buffers.
uint8_t Buffercmp24bits (uint16_t *pBuffer1, uint16_t *pBuffer2, uint16_t BufferLength)
Compares two buffers.
int main (void)
Main program.
Detailed Description
Function Documentation
Buffercmp()
uint8_t Buffercmp (uint16_t * pBuffer1, uint16_t * pBuffer2, uint16_t BufferLength)
Compares two buffers.
Parameters
pBuffer1 buffer1
pBuffer2 buffer2
BufferLength buffer length
Return values
None
Definition at line 244 of file I2S/I2S_Interrupt/Source/main.c.
References FAILED, and PASSED.
Buffercmp24bits()
uint8_t Buffercmp24bits (uint16_t * pBuffer1, uint16_t * pBuffer2, uint16_t BufferLength)
Compares two buffers.
Parameters
pBuffer1 buffer1
pBuffer2 buffer2
BufferLength buffer length
Return values
None
Definition at line 270 of file I2S/I2S_Interrupt/Source/main.c.
References FAILED, and PASSED.
Referenced by main().
GPIO_Configuration()
void GPIO_Configuration (void)
Configures the different GPIO ports.
Parameters
None
Return values
None
Definition at line 200 of file I2S/I2S_Interrupt/Source/main.c.
References GPIO_Config(), GPIO_ConfigPinRemap(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_5, GPIO_REMAP_SWJ_JTAGDISABLE, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIO_Config_T::mode, GPIO_Config_T::pin, and GPIO_Config_T::speed.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 77 of file I2S/I2S_Interrupt/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), I2S_Config_T::audioDiv, Buffercmp(), Buffercmp24bits(), GPIO_Configuration(), I2S2_Buffer_Rx, I2S3_Buffer_Tx, I2S_AUDIO_DIV_16K, I2S_AUDIO_DIV_48K, I2S_CLKPOL_LOW, I2S_Config(), I2S_DATA_LENGHT_16BEX, I2S_DATA_LENGHT_24B, I2S_Enable(), I2S_MCLK_OUTPUT_DISABLE, I2S_MODE_MASTER_TX, I2S_MODE_SLAVE_RX, I2S_STANDARD_PHILLIPS, LED2, LED3, I2S_Config_T::length, I2S_Config_T::MCLKOutput, I2S_Config_T::mode, NVIC_Configuration(), PASSED, I2S_Config_T::polarity, RCM_Configuration(), rxCnt, SPI2, SPI3, SPI_I2S_EnableInterrupt(), SPI_I2S_INT_RXBNE, SPI_I2S_INT_TXBE, SPI_I2S_Reset(), I2S_Config_T::standard, TransferStatus, and txCnt.
NVIC_Configuration()
void NVIC_Configuration (void)
Configure the nested vectored interrupt controller.
Parameters
None
Return values
None
Definition at line 227 of file I2S/I2S_Interrupt/Source/main.c.
References NVIC_EnableIRQRequest().
RCM_Configuration()
void RCM_Configuration (void)
Configures the different system clocks.
Parameters
None
Return values
None
Definition at line 165 of file I2S/I2S_Interrupt/Source/main.c.
References FMC_ConfigLatency(), FMC_EnablePrefetchBuffer(), FMC_LATENCY_2, RCM_AHB_DIV_1, RCM_APB1_PERIPH_SPI2, RCM_APB1_PERIPH_SPI3, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_GPIOB, RCM_APB_DIV_1, RCM_APB_DIV_2, RCM_ConfigADCCLK(), RCM_ConfigAHB(), RCM_ConfigAPB1(), RCM_ConfigAPB2(), RCM_ConfigHSE(), RCM_ConfigPLL(), RCM_ConfigSYSCLK(), RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), RCM_EnablePLL(), RCM_FLAG_PLLRDY, RCM_HSE_OPEN, RCM_PCLK2_DIV_4, RCM_PLLMF_9, RCM_PLLSEL_HSE, RCM_ReadStatusFlag(), RCM_ReadSYSCLKSource(), RCM_Reset(), RCM_SYSCLK_SEL_PLL, RCM_WaitHSEReady(), RESET, and SUCCESS.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU