APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader » MENU
Functions
void Select_Menu (void)
Display the Main Menu on HyperTerminal.
void Download (APP_TypeDef Application)
Download a file via serial port.
void Upload (APP_TypeDef Application)
Upload a file via serial port.
Detailed Description
Function Documentation
Download()
void Download (APP_TypeDef Application)
Download a file via serial port.
Parameters
Application : APP1 or APP2
Return values
None
Note
Definition at line 65 of file menu.c.
References filek, FileN, IntConStr(), recceiveFile(), and SendString.
Referenced by Select_Menu().
Select_Menu()
void Select_Menu (void)
Display the Main Menu on HyperTerminal.
Parameters
None
Return values
None
Note
Definition at line 172 of file menu.c.
References APP1, APP2, Download(), FMC_ReadOptionByteWriteProtection(), Jump_to_App(), MENU_WAIT_TIMEOUT, ReadKey_TimeOut(), SendString, and Upload().
Referenced by main().
Upload()
void Upload (APP_TypeDef Application)
Upload a file via serial port.
Parameters
Application : APP1 or APP2
Return values
None
Note
Definition at line 127 of file menu.c.
References APP1, FRAME_CRC16, ReadKey(), SendString, transmitFile(), USER_APP1_FLASH_SIZE, USER_APP1_START_ADDRESS, USER_APP2_FLASH_SIZE, and USER_APP2_START_ADDRESS.
Referenced by Select_Menu().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU