APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » IWDT Driver
Functions
void IWDT_Enable (void)
Enable IWDT.
void IWDT_Refresh (void)
Reload the IWDT counter with value.
void IWDT_ConfigReload (uint16_t reload)
Set IWDT count reload values.
void IWDT_ConfigDivider (uint8_t div)
Set IWDT frequency divider values.
void IWDT_EnableWriteAccess (void)
Enable the IWDT write access.
void IWDT_DisableWriteAccess (void)
Disable the IWDT write access.
uint8_t IWDT_ReadStatusFlag (uint16_t flag)
Read the specified IWDT flag.
Detailed Description
Function Documentation
IWDT_ConfigDivider()
void IWDT_ConfigDivider (uint8_t div)
Set IWDT frequency divider values.
Parameters
div IWDT frequency divider values This parameter can be one of the following values:
IWDT_DIVIDER_4 : prescaler divider equal to 4
IWDT_DIVIDER_8 : prescaler divider equal to 8
IWDT_DIVIDER_16 : prescaler divider equal to 16
IWDT_DIVIDER_32 : prescaler divider equal to 32
IWDT_DIVIDER_64 : prescaler divider equal to 64
IWDT_DIVIDER_128: prescaler divider equal to 128
IWDT_DIVIDER_256: prescaler divider equal to 256
Return values
None
Definition at line 116 of file apm32f10x_iwdt.c.
References IWDT.
Referenced by main().
IWDT_ConfigReload()
void IWDT_ConfigReload (uint16_t reload)
Set IWDT count reload values.
Parameters
reload IWDT count reload values
Return values
None
Definition at line 72 of file apm32f10x_iwdt.c.
References IWDT.
Referenced by main().
IWDT_DisableWriteAccess()
void IWDT_DisableWriteAccess (void)
Disable the IWDT write access.
Parameters
None
Return values
None
Definition at line 96 of file apm32f10x_iwdt.c.
References IWDT, and IWDT_WRITEACCESS_DISABLE.
IWDT_Enable()
void IWDT_Enable (void)
Enable IWDT.
Parameters
None
Return values
None
Definition at line 48 of file apm32f10x_iwdt.c.
References IWDT, and IWDT_KEYWORD_ENABLE.
Referenced by main().
IWDT_EnableWriteAccess()
void IWDT_EnableWriteAccess (void)
Enable the IWDT write access.
Parameters
None
Return values
None
Definition at line 84 of file apm32f10x_iwdt.c.
References IWDT, and IWDT_WRITEACCESS_ENABLE.
Referenced by main().
IWDT_ReadStatusFlag()
uint8_t IWDT_ReadStatusFlag (uint16_t flag)
Read the specified IWDT flag.
Parameters
flag specifies the flag to read This parameter can be one of the following values:
IWDT_FLAG_PSCU : Watchdog Prescaler Factor Update flag
IWDT_FLAG_CNTU : Watchdog Counter Reload Value Update flag
Return values
status of IWDT_FLAG (SET or RESET)
Definition at line 132 of file apm32f10x_iwdt.c.
References IWDT, RESET, and SET.
IWDT_Refresh()
void IWDT_Refresh (void)
Reload the IWDT counter with value.
Parameters
None
Return values
None
Definition at line 60 of file apm32f10x_iwdt.c.
References IWDT, and IWDT_KEYWORD_RELOAD.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU