APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Host » Standard » DataXfer
Typedefs
typedef USBH_CTRL_STATE_T(* USBH_CtrlStateHandler_T) (USBH_HostReqData_T *, uint8_t *)
Functions
USBH_CTRL_STATE_T USBH_ControlXferHandler (USBH_HostReqData_T *reqData, uint8_t *buf)
Handle Control Setup transfer.
void USBH_CtrlSetupReq (uint8_t chNum, USBH_HostReqData_T *reqData)
Start Control Setup transfer.
void USBH_CtrlOutData (uint8_t chNum, uint8_t *wBuf, uint32_t wLen)
Start Control OUT transfer.
void USBH_CtrlInData (uint8_t chNum, uint8_t *rBuf, uint32_t rLen)
Start Control IN transfer.
void USBH_InterruptOutData (uint8_t chNum, uint8_t *wBuf, uint32_t wLen)
Start Interrupt OUT transfer.
void USBH_InterruptInData (uint8_t chNum, uint8_t *rBuf, uint32_t rLen)
Start Interrupt IN transfer.
void USBH_BulkOutData (uint8_t chNum, uint8_t *wBuf, uint32_t wLen)
Start Bulk OUT transfer.
void USBH_BulkInData (uint8_t chNum, uint8_t *rBuf, uint32_t rLen)
Start Bulk IN transfer.
void USBH_IsocOutData (uint8_t chNum, uint8_t *wBuf, uint32_t wLen)
Start Isochronous OUT transfer.
void USBH_IsocInData (uint8_t chNum, uint8_t *rBuf, uint32_t rLen)
Start Isochronous IN transfer.
Detailed Description
Typedef Documentation
USBH_CtrlStateHandler_T
typedef USBH_CTRL_STATE_T(* USBH_CtrlStateHandler_T) (USBH_HostReqData_T *, uint8_t *)
Definition at line 84 of file usbh_dataXfer.h.
Function Documentation
USBH_BulkInData()
void USBH_BulkInData (uint8_t chNum, uint8_t * rBuf, uint32_t rLen)
Start Bulk IN transfer.
Parameters
chNum : Channel number
rBuf : Point to an IN data Buffer
rLen : Transfer length.
Return values
None
Definition at line 280 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_BULK, USB_OTG_EnableInChannelTransfer(), USBH_ReadDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
Referenced by USBH_CDCProcessGet().
USBH_BulkOutData()
void USBH_BulkOutData (uint8_t chNum, uint8_t * wBuf, uint32_t wLen)
Start Bulk OUT transfer.
Parameters
chNum : Channel number
wBuf : Point to an OUT data Buffer
wLen : Transfer length.
Return values
None
Definition at line 251 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_BULK, USB_OTG_EnableOutChannelTransfer(), USBH_ReadDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
Referenced by USBH_CDCProcessSend().
USBH_ControlXferHandler()
USBH_CTRL_STATE_T USBH_ControlXferHandler (USBH_HostReqData_T * reqData, uint8_t * buf)
Handle Control Setup transfer.
Parameters
reqData : Point to a USBH_HostReqData_T structure
buf : Point to a Buffer to be transfered(useless)
Return values
Return state of USBH_CTRL_STATE_T type enum
Definition at line 91 of file usbh_dataXfer.c.
USBH_CtrlInData()
void USBH_CtrlInData (uint8_t chNum, uint8_t * rBuf, uint32_t rLen)
Start Control IN transfer.
Parameters
chNum : Channel number
rBuf : Point to an IN data Buffer
rLen : Transfer length.
Return values
None
Definition at line 164 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_Info_T::control, USBH_XferPipe_T::dataPid, g_usbHost, USBH_Control_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_CONTROL, USB_OTG_EnableInChannelTransfer(), USBH_ConfigDataPid, USBH_ReadDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_CtrlOutData()
void USBH_CtrlOutData (uint8_t chNum, uint8_t * wBuf, uint32_t wLen)
Start Control OUT transfer.
Parameters
chNum : Channel number
wBuf : Point to an OUT data Buffer
wLen : Transfer length.
Return values
None
Definition at line 134 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_Info_T::control, USBH_XferPipe_T::dataPid, g_usbHost, USBH_Control_T::maxPackSize, USBH_XferPipe_T::pidToggle, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_CONTROL, USB_OTG_EnableOutChannelTransfer(), USBH_ReadDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_CtrlSetupReq()
void USBH_CtrlSetupReq (uint8_t chNum, USBH_HostReqData_T * reqData)
Start Control Setup transfer.
Parameters
chNum : Channel number
reqData : Point to a USBH_HostReqData_T structure
Return values
None
Definition at line 105 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_Info_T::control, g_usbHost, USBH_Control_T::maxPackSize, SETUP, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_CONTROL, USB_OTG_EnableOutChannelTransfer(), USBH_ConfigDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_InterruptInData()
void USBH_InterruptInData (uint8_t chNum, uint8_t * rBuf, uint32_t rLen)
Start Interrupt IN transfer.
Parameters
chNum : Channel number
rBuf : Point to an IN data Buffer
rLen : Transfer length.
Return values
None
Definition at line 222 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_INTERRUPT, USB_OTG_EnableInChannelTransfer(), USBH_ReadDataPid, USBH_ToggleDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_InterruptOutData()
void USBH_InterruptOutData (uint8_t chNum, uint8_t * wBuf, uint32_t wLen)
Start Interrupt OUT transfer.
Parameters
chNum : Channel number
wBuf : Point to an OUT data Buffer
wLen : Transfer length.
Return values
None
Definition at line 193 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_INTERRUPT, USB_OTG_EnableOutChannelTransfer(), USBH_ReadDataPid, USBH_ToggleDataPid, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_IsocInData()
void USBH_IsocInData (uint8_t chNum, uint8_t * rBuf, uint32_t rLen)
Start Isochronous IN transfer.
Parameters
chNum : Channel number
rBuf : Point to an OUT data Buffer
rLen : Transfer length.
Return values
None
Definition at line 337 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, DATA_0, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_ISO, USB_OTG_EnableInChannelTransfer(), USBH_URB_IDLE, and USBH_Info_T::xferPipe.
USBH_IsocOutData()
void USBH_IsocOutData (uint8_t chNum, uint8_t * wBuf, uint32_t wLen)
Start Isochronous OUT transfer.
Parameters
chNum : Channel number
wBuf : Point to an OUT data Buffer
wLen : Transfer length.
Return values
None
Definition at line 308 of file usbh_dataXfer.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, DATA_0, USBH_XferPipe_T::dataPid, g_usbHost, USBH_XferPipe_T::maxPackSize, USBH_XferPipe_T::urbStatus, USB_EP_TYPE_ISO, USB_OTG_EnableOutChannelTransfer(), USBH_URB_IDLE, and USBH_Info_T::xferPipe.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU