APM32F10x_SDK: Functions
Functions
Examples » USBH_HID
Functions
void USB_HardwareInit (void)
USB hardware Init.
void USB_Timer_IRQHandler (void)
Handle USB Timer interrupt.
void USB_usDelay (uint32_t delayTime)
microseconds delay function
void USB_msDelay (uint32_t delayTime)
milliseconds delay function
void ConfigDelayTimer (void)
Config Delay Timer 1ms Timer.
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
void USBH_HID_Init (void)
Init USB host HID.
int main (void)
Main program.
Detailed Description
Function Documentation
APM_BOARD_COMInit()
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 380 of file OTG_Host/USBH_HID/Source/usb_board.c.
References APM_MINI_COMInit().
ConfigDelayTimer()
void ConfigDelayTimer (void)
Config Delay Timer 1ms Timer.
Parameters
None
Return values
None
Definition at line 286 of file OTG_Host/USBH_HID/Source/usb_board.c.
References TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_BaseConfig_T::division, NVIC_EnableIRQRequest(), TMR_BaseConfig_T::period, RCM_APB1_PERIPH_TMR2, RCM_EnableAPB1PeriphClock(), RCM_ReadPCLKFreq(), TMR2, tmr2Clk, TMR_CLOCK_DIV_1, TMR_ConfigTimeBase(), TMR_COUNTER_MODE_UP, TMR_Enable(), TMR_EnableAutoReload(), TMR_EnableInterrupt(), and TMR_INT_UPDATE.
main()
int main (void)
Main program.
Parameters
None
Return values
int
Definition at line 48 of file OTG/OTG_Host/USBH_HID/Source/main.c.
References USBH_HID_Init(), and USBH_PollingProcess().
USB_HardwareInit()
void USB_HardwareInit (void)
USB hardware Init.
Parameters
None
Return values
None
Definition at line 64 of file OTG_Host/USBH_HID/Source/usb_board.c.
References BIT10, BIT12, BIT8, BIT9, BIT_SET, ConfigDelayTimer(), FMC, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_9, GPIO_PIN_SOURCE_0, GPIO_PIN_SOURCE_1, GPIO_PIN_SOURCE_10, GPIO_PIN_SOURCE_11, GPIO_PIN_SOURCE_12, GPIO_PIN_SOURCE_13, GPIO_PIN_SOURCE_14, GPIO_PIN_SOURCE_15, GPIO_PIN_SOURCE_3, GPIO_PIN_SOURCE_4, GPIO_PIN_SOURCE_5, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIOC, GPIO_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_1, GPIO_Config_T::pin, RCM, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, and USB_OTG_DisableAllGlobalInterrupt.
USB_msDelay()
void USB_msDelay (uint32_t delayTime)
milliseconds delay function
Parameters
delayTime : set the number of milliseconds to delay
Return values
None
Definition at line 270 of file OTG_Host/USBH_HID/Source/usb_board.c.
References USB_usDelay().
USB_Timer_IRQHandler()
void USB_Timer_IRQHandler (void)
Handle USB Timer interrupt.
Parameters
None
Return values
None
Definition at line 219 of file OTG_Host/USBH_HID/Source/usb_board.c.
References TMR2, TMR_ClearIntFlag(), TMR_delayCnt, TMR_Disable(), TMR_INT_UPDATE, and TMR_ReadIntFlag().
USB_usDelay()
void USB_usDelay (uint32_t delayTime)
microseconds delay function
Parameters
delayTime : set the number of microseconds to delay
Return values
None
Definition at line 244 of file OTG_Host/USBH_HID/Source/usb_board.c.
USBH_HID_Init()
void USBH_HID_Init (void)
Init USB host HID.
Parameters
None
Return values
None
Definition at line 50 of file usbh_hid.c.
References USBH_InitParam_T::classCoreHandler, USBH_InitParam_T::classDeInitHandler, USBH_InitParam_T::classInitHandler, USBH_InitParam_T::classReqHandler, USBH_InitParam_T::intHandler, NULL, USBH_InitParam_T::suspendHandler, USBH_HID_CoreHandler(), USBH_HID_DeInitHandler(), USBH_HID_InitHandler(), USBH_HID_ReqHandler(), USBH_Init(), and USBH_InitParam_T::wakeUpHandler.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU