APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader » BSP_USART
Functions
void USART_Init (uint32_t baudRate)
USART Init.
Detailed Description
Function Documentation
USART_Init()
void USART_Init (uint32_t baudRate)
USART Init.
Parameters
baudRate
Return values
None
Note
Definition at line 133 of file bsp_usart.c.
References USART_Config_T::baudRate, DEBUG_USART, DEBUG_USART_CLK, DEBUG_USART_RX_CLK, DEBUG_USART_RX_PIN, DEBUG_USART_RX_PORT, DEBUG_USART_TX_CLK, DEBUG_USART_TX_PIN, DEBUG_USART_TX_PORT, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_SPEED_50MHz, USART_Config_T::hardwareFlow, GPIO_Config_T::mode, USART_Config_T::mode, USART_Config_T::parity, GPIO_Config_T::pin, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART_Config(), USART_Enable(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU