APM32F10x_SDK: myiic.h File Reference
myiic.h File Reference
#include "apm32f10x.h"
#include "bsp_delay.h"
Macros
#define IIC_PIN_SCL GPIO_PIN_6
#define IIC_PIN_SDA GPIO_PIN_7
#define IIC_SCL_SET GPIO_SetBit(GPIOB,IIC_PIN_SCL)
#define IIC_SCL_RESET GPIO_ResetBit(GPIOB,IIC_PIN_SCL)
#define IIC_SDA_SET GPIO_SetBit(GPIOB,IIC_PIN_SDA)
#define IIC_SDA_RESET GPIO_ResetBit(GPIOB,IIC_PIN_SDA)
#define IIC_SDA_WRITE(n) GPIO_WriteBitValue(GPIOB,IIC_PIN_SDA,n)
#define IIC_READ_SDA GPIO_ReadInputBit(GPIOB,IIC_PIN_SDA)
Functions
void IIC_Init (void)
IIC Init.
void IIC_Start (void)
Generate IIC start signal.
void IIC_Stop (void)
Generate IIC stop signal.
void IIC_Send_Byte (uint8_t txd)
IIC sends a byte.
uint8_t IIC_Read_Byte (unsigned char ack)
read one byte
uint8_t IIC_Wait_Ack (void)
Wait for the answer signal to come.
void IIC_Ack (void)
Generate ACK response.
void IIC_NAck (void)
generate NACK response
void SDA_IN (void)
Configure SDA as input mode.
void SDA_OUT (void)
Configure SDA as output mode.
void IIC_Write_One_Byte (u8 daddr, u8 addr, u8 data)
uint8_t IIC_Read_One_Byte (u8 daddr, u8 addr)
Macro Definition Documentation
IIC_PIN_SCL
#define IIC_PIN_SCL GPIO_PIN_6
Definition at line 7 of file myiic.h.
IIC_PIN_SDA
#define IIC_PIN_SDA GPIO_PIN_7
Definition at line 8 of file myiic.h.
IIC_READ_SDA
#define IIC_READ_SDA GPIO_ReadInputBit(GPIOB,IIC_PIN_SDA)
Definition at line 15 of file myiic.h.
IIC_SCL_RESET
#define IIC_SCL_RESET GPIO_ResetBit(GPIOB,IIC_PIN_SCL)
Definition at line 11 of file myiic.h.
IIC_SCL_SET
#define IIC_SCL_SET GPIO_SetBit(GPIOB,IIC_PIN_SCL)
Definition at line 10 of file myiic.h.
IIC_SDA_RESET
#define IIC_SDA_RESET GPIO_ResetBit(GPIOB,IIC_PIN_SDA)
Definition at line 13 of file myiic.h.
IIC_SDA_SET
#define IIC_SDA_SET GPIO_SetBit(GPIOB,IIC_PIN_SDA)
Definition at line 12 of file myiic.h.
IIC_SDA_WRITE
#define IIC_SDA_WRITE (n) GPIO_WriteBitValue(GPIOB,IIC_PIN_SDA,n)
Definition at line 14 of file myiic.h.
Function Documentation
IIC_Ack()
void IIC_Ack (void)
Generate ACK response.
Parameters
None
Return values
None
Definition at line 129 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, and SDA_OUT().
Referenced by IIC_Read_Byte().
IIC_Init()
void IIC_Init (void)
IIC Init.
Parameters
None
Return values
None
Definition at line 40 of file myiic.c.
References GPIO_Config(), GPIO_MODE_OUT_PP, GPIO_SetBit(), GPIO_SPEED_50MHz, GPIOB, IIC_PIN_SCL, IIC_PIN_SDA, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by AT24CXX_Init().
IIC_NAck()
void IIC_NAck (void)
generate NACK response
Parameters
None
Return values
None
Definition at line 148 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_SET, and SDA_OUT().
Referenced by IIC_Read_Byte().
IIC_Read_Byte()
uint8_t IIC_Read_Byte (unsigned char ack)
read one byte
Parameters
ack Flag to send ACK or NACK
Return values
read data
Definition at line 193 of file myiic.c.
References Delay_us(), IIC_Ack(), IIC_NAck(), IIC_READ_SDA, IIC_SCL_RESET, IIC_SCL_SET, and SDA_IN().
Referenced by AT24CXX_ReadOneByte().
IIC_Read_One_Byte()
uint8_t IIC_Read_One_Byte (u8 daddr, u8 addr)
IIC_Send_Byte()
void IIC_Send_Byte (uint8_t txd)
IIC sends a byte.
Parameters
txd Data to send
Return values
Whether the slave responds 1: reponse 0: no reponse
Definition at line 168 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_WRITE, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
IIC_Start()
void IIC_Start (void)
Generate IIC start signal.
Parameters
None
Return values
None
Definition at line 60 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, IIC_SDA_SET, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
IIC_Stop()
void IIC_Stop (void)
Generate IIC stop signal.
Parameters
None
Return values
None
Definition at line 79 of file myiic.c.
References Delay_us(), IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_RESET, IIC_SDA_SET, and SDA_OUT().
Referenced by AT24CXX_ReadOneByte(), AT24CXX_WriteOneByte(), and IIC_Wait_Ack().
IIC_Wait_Ack()
uint8_t IIC_Wait_Ack (void)
Wait for the answer signal to come.
Parameters
None
Return values
uint8_t
Note
Return value: 1, failed to receive the response 0, the response is received successfully
Definition at line 100 of file myiic.c.
References Delay_us(), IIC_READ_SDA, IIC_SCL_RESET, IIC_SCL_SET, IIC_SDA_SET, IIC_Stop(), and SDA_IN().
Referenced by AT24CXX_ReadOneByte(), and AT24CXX_WriteOneByte().
IIC_Write_One_Byte()
void IIC_Write_One_Byte (u8 daddr, u8 addr, u8 data)
SDA_IN()
void SDA_IN (void)
Configure SDA as input mode.
Parameters
None
Return values
None
Definition at line 12 of file myiic.c.
References GPIOB.
Referenced by IIC_Read_Byte(), and IIC_Wait_Ack().
SDA_OUT()
void SDA_OUT (void)
Configure SDA as output mode.
Parameters
None
Return values
None
Definition at line 26 of file myiic.c.
References GPIOB.
Referenced by IIC_Ack(), IIC_NAck(), IIC_Send_Byte(), IIC_Start(), and IIC_Stop().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU