APM32F10x_SDK: 24cxx.h File Reference
24cxx.h File Reference
#include "myiic.h"
Macros
#define AT24C01 127
#define AT24C02 255
#define AT24C04 511
#define AT24C08 1023
#define AT24C16 2047
#define AT24C32 4095
#define AT24C64 8191
#define AT24C128 16383
#define AT24C256 32767
#define EE_TYPE AT24C02
Functions
uint8_t AT24CXX_ReadOneByte (uint16_t ReadAddr)
Read a data at the specified address of AT24CXX.
void AT24CXX_WriteOneByte (uint16_t WriteAddr, uint8_t DataToWrite)
Write a data at the specified address of AT24CXX.
void AT24CXX_WriteLenByte (uint16_t WriteAddr, uint32_t DataToWrite, uint8_t Len)
Start writing data with a length of Len at the specified address in AT24CXX.
uint32_t AT24CXX_ReadLenByte (uint16_t ReadAddr, uint8_t Len)
The specified address in AT24CXX starts to read the data whose length is Len.
void AT24CXX_Write (uint16_t WriteAddr, uint8_t *pBuffer, uint16_t NumToWrite)
Start writing the specified number of data at the specified address in AT24CXX.
void AT24CXX_Read (uint16_t ReadAddr, uint8_t *pBuffer, uint16_t NumToRead)
Start reading the specified number of data at the specified address in AT24CXX.
uint8_t AT24CXX_Check (void)
Check if AT24CXX is normal Here the last address (255) of 24XX is used to store the flag word.
void AT24CXX_Init (void)
Initialize the IIC interface.
Macro Definition Documentation
AT24C01
#define AT24C01 127
Definition at line 6 of file 24cxx.h.
AT24C02
#define AT24C02 255
Definition at line 7 of file 24cxx.h.
AT24C04
#define AT24C04 511
Definition at line 8 of file 24cxx.h.
AT24C08
#define AT24C08 1023
Definition at line 9 of file 24cxx.h.
AT24C128
#define AT24C128 16383
Definition at line 13 of file 24cxx.h.
AT24C16
#define AT24C16 2047
Definition at line 10 of file 24cxx.h.
AT24C256
#define AT24C256 32767
Definition at line 14 of file 24cxx.h.
AT24C32
#define AT24C32 4095
Definition at line 11 of file 24cxx.h.
AT24C64
#define AT24C64 8191
Definition at line 12 of file 24cxx.h.
EE_TYPE
#define EE_TYPE AT24C02
Definition at line 16 of file 24cxx.h.
Function Documentation
AT24CXX_Check()
uint8_t AT24CXX_Check (void)
Check if AT24CXX is normal Here the last address (255) of 24XX is used to store the flag word.
Parameters
None
Return values
1 failed 0: successed
Definition at line 137 of file 24cxx.c.
References AT24CXX_ReadOneByte(), AT24CXX_WriteOneByte(), and EE_TYPE.
Referenced by main().
AT24CXX_Init()
void AT24CXX_Init (void)
Initialize the IIC interface.
Parameters
None
Return values
None
Definition at line 12 of file 24cxx.c.
References IIC_Init().
Referenced by main().
AT24CXX_Read()
void AT24CXX_Read (uint16_t ReadAddr, uint8_t * pBuffer, uint16_t NumToRead)
Start reading the specified number of data at the specified address in AT24CXX.
Parameters
ReadAddr Start reading address
*pBuffer The first address of the data array
NumToRead The length of the data to be read
Return values
None
Definition at line 163 of file 24cxx.c.
References AT24CXX_ReadOneByte().
Referenced by main().
AT24CXX_ReadLenByte()
uint32_t AT24CXX_ReadLenByte (uint16_t ReadAddr, uint8_t Len)
The specified address in AT24CXX starts to read the data whose length is Len.
This function is used to write 16bit or 32bit data.
Parameters
ReadAddr start reading address
Len The length of the data to be read
Return values
data
Definition at line 116 of file 24cxx.c.
References AT24CXX_ReadOneByte().
AT24CXX_ReadOneByte()
uint8_t AT24CXX_ReadOneByte (uint16_t ReadAddr)
Read a data at the specified address of AT24CXX.
Parameters
ReadAddr Address to start reading
Return values
read data
Definition at line 25 of file 24cxx.c.
References AT24C16, EE_TYPE, IIC_Read_Byte(), IIC_Send_Byte(), IIC_Start(), IIC_Stop(), and IIC_Wait_Ack().
Referenced by AT24CXX_Check(), AT24CXX_Read(), and AT24CXX_ReadLenByte().
AT24CXX_Write()
void AT24CXX_Write (uint16_t WriteAddr, uint8_t * pBuffer, uint16_t NumToWrite)
Start writing the specified number of data at the specified address in AT24CXX.
Parameters
ReadAddr Start writing address
*pBuffer The first address of the data array
NumToRead The length of the data to be written
Return values
None
Definition at line 184 of file 24cxx.c.
References AT24CXX_WriteOneByte().
Referenced by main().
AT24CXX_WriteLenByte()
void AT24CXX_WriteLenByte (uint16_t WriteAddr, uint32_t DataToWrite, uint8_t Len)
Start writing data with a length of Len at the specified address in AT24CXX.
This function is used to write 16bit or 32bit data.
Parameters
WriteAddr Start writing address
DataToWrite The first address of the data array
Len The length of the data to be written
Return values
None
Definition at line 96 of file 24cxx.c.
References AT24CXX_WriteOneByte().
AT24CXX_WriteOneByte()
void AT24CXX_WriteOneByte (uint16_t WriteAddr, uint8_t DataToWrite)
Write a data at the specified address of AT24CXX.
Parameters
WriteAddr Destination address for writing data
DataToWrite Data to write
Return values
None
Definition at line 62 of file 24cxx.c.
References AT24C16, Delay_ms(), EE_TYPE, IIC_Send_Byte(), IIC_Start(), IIC_Stop(), and IIC_Wait_Ack().
Referenced by AT24CXX_Check(), AT24CXX_Write(), and AT24CXX_WriteLenByte().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU