APM32F10x_SDK: Functions
Functions
Examples » DMA_UsartToMemory
Functions
void USART1_RX_DMA_Init (void)
USART1 RX DMA Init.
void USART2_TX_DMA_Init (void)
USART2 TX DMA Init.
BOOL BufferCompare (uint8_t *buf1, uint8_t *buf2, uint8_t size)
Compares two buffers.
int main (void)
Main program.
Detailed Description
Function Documentation
BufferCompare()
BOOL BufferCompare (uint8_t * buf1, uint8_t * buf2, uint8_t size)
Compares two buffers.
Parameters
buf1 First buffer to be compared
buf1 Second buffer to be compared
size Buffer size
Return values
Return TRUE if buf1 = buf2. If not then return FALSE
Note
Definition at line 225 of file DMA/DMA_UsartToMemory/Source/main.c.
References FALSE, size, and TRUE.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 89 of file DMA/DMA_UsartToMemory/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), USART_Config_T::baudRate, BufferCompare(), BufSize, COM1, COM2, DMA1_FLAG_TC5, DMA1_FLAG_TC7, DMA_ReadStatusFlag(), DMA_USART1_RxBuf, DMA_USART2_TxBuf, USART_Config_T::hardwareFlow, LED2, LED3, USART_Config_T::mode, USART_Config_T::parity, RESET, USART_Config_T::stopBits, TRUE, USART1, USART1_RX_DMA_Init(), USART2, USART2_TX_DMA_Init(), USART_DMA_RX, USART_DMA_TX, USART_EnableDMA(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
USART1_RX_DMA_Init()
void USART1_RX_DMA_Init (void)
USART1 RX DMA Init.
Parameters
None
Return values
None
Definition at line 151 of file DMA/DMA_UsartToMemory/Source/main.c.
References DMA_Config_T::bufferSize, BufSize, DMA_Config_T::dir, DMA1_Channel5, DMA_Config(), DMA_DIR_PERIPHERAL_SRC, DMA_Enable(), DMA_M2MEN_DISABLE, DMA_MEMORY_DATA_SIZE_BYTE, DMA_MEMORY_INC_ENABLE, DMA_MODE_NORMAL, DMA_PERIPHERAL_DATA_SIZE_BYTE, DMA_PERIPHERAL_INC_DISABLE, DMA_PRIORITY_MEDIUM, DMA_USART1_RxBuf, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Config_T::priority, RCM_AHB_PERIPH_DMA1, RCM_EnableAHBPeriphClock(), and USART1_DR_ADDRESS.
Referenced by main().
USART2_TX_DMA_Init()
void USART2_TX_DMA_Init (void)
USART2 TX DMA Init.
Parameters
None
Return values
None
Definition at line 185 of file DMA/DMA_UsartToMemory/Source/main.c.
References DMA_Config_T::bufferSize, BufSize, DMA_Config_T::dir, DMA1_Channel7, DMA_Config(), DMA_DIR_PERIPHERAL_DST, DMA_Enable(), DMA_M2MEN_DISABLE, DMA_MEMORY_DATA_SIZE_BYTE, DMA_MEMORY_INC_ENABLE, DMA_MODE_NORMAL, DMA_PERIPHERAL_DATA_SIZE_BYTE, DMA_PERIPHERAL_INC_DISABLE, DMA_PRIORITY_HIGH, DMA_USART2_TxBuf, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Config_T::priority, RCM_AHB_PERIPH_DMA1, RCM_EnableAHBPeriphClock(), and USART2_DR_ADDRESS.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU