APM32F10x_SDK: Functions
Functions
Examples » USART_Interrupt
Macros
#define USART1_RX_MAX 256
Main program.
#define USART2_RX_MAX 256
Functions
void Delay (void)
Delay.
void USART1_Isr (void)
USART1_Interrupt.
void USART2_Isr (void)
USART2_Interrupt.
int main (void)
Main program.
void usart1_clr (void)
usart1_clr
void usart2_clr (void)
usart2_cle
void Usart_SendString (USART_T *usart, uint8_t *dat, uint32_t count)
Usart_SendString.
void DataAnalyze (void)
Variables
volatile int USART1_STA = 0
volatile int USART2_STA = 0
volatile char USART1_RXBUF [USART1_RX_MAX]
volatile char USART2_RXBUF [USART2_RX_MAX]
Detailed Description
Macro Definition Documentation
USART1_RX_MAX
#define USART1_RX_MAX 256
Main program.
Parameters
None
Return values
None
Definition at line 66 of file USART/USART_Interrupt_F1-F4/Source/main.c.
USART2_RX_MAX
#define USART2_RX_MAX 256
Definition at line 67 of file USART/USART_Interrupt_F1-F4/Source/main.c.
Function Documentation
DataAnalyze()
void DataAnalyze (void)
Definition at line 263 of file USART/USART_Interrupt_F1-F4/Source/main.c.
References APM_MINI_LEDOff(), APM_MINI_LEDOn(), LED2, LED3, USART1, usart1_clr(), USART1_RXBUF, USART2, usart2_clr(), USART2_RXBUF, and Usart_SendString().
Delay()
void Delay (void)
Delay.
Parameters
None
Return values
None
Definition at line 103 of file USART/USART_Interrupt/Source/main.c.
References tick.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 64 of file USART/USART_Interrupt/Source/main.c.
References APM_MINI_COMInit(), APM_MINI_LEDInit(), USART_Config_T::baudRate, COM1, COM2, USART_Config_T::hardwareFlow, LED2, LED3, USART_Config_T::mode, NVIC_EnableIRQRequest(), USART_Config_T::parity, RCM_APB1_PERIPH_USART2, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_USART1, RCM_EnableAPB1PeriphClock(), RCM_EnableAPB2PeriphClock(), USART_Config_T::stopBits, USART1, USART2, USART_EnableInterrupt(), USART_HARDWARE_FLOW_NONE, USART_INT_RXBNE, USART_INT_TXBE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
usart1_clr()
void usart1_clr (void)
usart1_clr
Parameters
None
Returns
None
Definition at line 226 of file USART/USART_Interrupt_F1-F4/Source/main.c.
References USART1_RXBUF, and USART1_STA.
Referenced by DataAnalyze().
USART1_Isr()
void USART1_Isr (void)
USART1_Interrupt.
Parameters
None
Return values
None
Definition at line 118 of file USART/USART_Interrupt/Source/main.c.
References APM_MINI_LEDToggle(), count, Delay(), LED2, txBuf, USART1, USART_INT_TXBE, USART_ReadIntFlag(), and USART_TxData().
Referenced by USART1_IRQHandler().
usart2_clr()
void usart2_clr (void)
usart2_cle
Parameters
None
Returns
None
Definition at line 239 of file USART/USART_Interrupt_F1-F4/Source/main.c.
References USART2_RXBUF, and USART2_STA.
Referenced by DataAnalyze().
USART2_Isr()
void USART2_Isr (void)
USART2_Interrupt.
Parameters
None
Return values
None
Definition at line 141 of file USART/USART_Interrupt/Source/main.c.
References APM_MINI_LEDToggle(), dat, LED3, USART2, USART_INT_RXBNE, USART_ReadIntFlag(), and USART_RxData().
Referenced by USART2_IRQHandler().
Usart_SendString()
void Usart_SendString (USART_T * usart, uint8_t * dat, uint32_t count)
Usart_SendString.
Parameters
usart Serial number
dat String data
count Data bits
Definition at line 253 of file USART/USART_Interrupt_F1-F4/Source/main.c.
References count, dat, RESET, USART_FLAG_TXBE, USART_ReadStatusFlag(), and USART_TxData().
Referenced by DataAnalyze().
Variable Documentation
USART1_RXBUF
volatile char USART1_RXBUF[USART1_RX_MAX]
Definition at line 72 of file USART/USART_Interrupt_F1-F4/Source/main.c.
Referenced by DataAnalyze(), and usart1_clr().
USART1_STA
volatile int USART1_STA = 0
Definition at line 69 of file USART/USART_Interrupt_F1-F4/Source/main.c.
Referenced by usart1_clr().
USART2_RXBUF
volatile char USART2_RXBUF[USART2_RX_MAX]
Definition at line 73 of file USART/USART_Interrupt_F1-F4/Source/main.c.
Referenced by DataAnalyze(), and usart2_clr().
USART2_STA
volatile int USART2_STA = 0
Definition at line 70 of file USART/USART_Interrupt_F1-F4/Source/main.c.
Referenced by usart2_clr().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU