APM32F10x_SDK: Functions
Functions
Examples » CAN_Normal
Functions
void USART_Init (void)
USART configs.
void CAN_GPIO_Init (void)
GPIO Init.
void CAN_Config_Init (void)
CAN Init.
void CAN_Transmit_Init (void)
CAN Transmit Init.
void CAN1_RX0_ISR (void)
CAN1 Rx interrupt.
void CAN2_RX0_ISR (void)
CAN2 Rx interrupt.
void NVIC_Configuration (void)
Configures NVIC.
int main (void)
Main program.
Detailed Description
Function Documentation
CAN1_RX0_ISR()
void CAN1_RX0_ISR (void)
CAN1 Rx interrupt.
Parameters
None
Return values
None
Definition at line 255 of file CAN/CAN_Normal/Source/main.c.
References APM_MINI_LEDOn(), CAN1, CAN_RX_FIFO_0, CAN_RxMessage(), CAN_TYPEID_STD, CAN_RxMessage_T::data, CAN_RxMessage_T::dataLengthCode, LED2, LED3, RxMessage, CAN_RxMessage_T::stdID, and CAN_RxMessage_T::typeID.
Referenced by USBD1_LP_CAN1_RX0_IRQHandler().
CAN2_RX0_ISR()
void CAN2_RX0_ISR (void)
CAN2 Rx interrupt.
Parameters
None
Return values
None
Definition at line 279 of file CAN/CAN_Normal/Source/main.c.
References APM_MINI_LEDOn(), CAN2, CAN_RX_FIFO_0, CAN_RxMessage(), CAN_TYPEID_STD, CAN_RxMessage_T::data, CAN_RxMessage_T::dataLengthCode, LED2, LED3, RxMessage, CAN_RxMessage_T::stdID, and CAN_RxMessage_T::typeID.
Referenced by USBD2_LP_CAN2_RX0_IRQHandler().
CAN_Config_Init()
void CAN_Config_Init (void)
CAN Init.
Parameters
None
Return values
None
Definition at line 187 of file CAN/CAN_Normal/Source/main.c.
References CAN_Config_T::autoBusOffManage, CAN_Config_T::autoWakeUpMode, CAN1, CAN2, CAN_Config(), CAN_ConfigFilter(), CAN_ConfigStructInit(), CAN_FILTER_FIFO_0, CAN_FILTER_MODE_IDMASK, CAN_FILTER_SCALE_32BIT, CAN_MODE_NORMAL, CAN_Reset(), CAN_SJW_1, CAN_TIME_SEGMENT1_3, CAN_TIME_SEGMENT2_2, DISABLE, ENABLE, CAN_FilterConfig_T::filterActivation, CAN_FilterConfig_T::filterFIFO, CAN_FilterConfig_T::filterIdHigh, CAN_FilterConfig_T::filterIdLow, CAN_FilterConfig_T::filterMaskIdHigh, CAN_FilterConfig_T::filterMaskIdLow, CAN_FilterConfig_T::filterMode, CAN_FilterConfig_T::filterNumber, CAN_FilterConfig_T::filterScale, CAN_Config_T::mode, CAN_Config_T::nonAutoRetran, CAN_Config_T::prescaler, RCM_APB1_PERIPH_CAN1, RCM_APB1_PERIPH_CAN2, RCM_EnableAPB1PeriphClock(), CAN_Config_T::rxFIFOLockMode, CAN_Config_T::syncJumpWidth, CAN_Config_T::timeSegment1, CAN_Config_T::timeSegment2, and CAN_Config_T::txFIFOPriority.
Referenced by main().
CAN_GPIO_Init()
void CAN_GPIO_Init (void)
GPIO Init.
Parameters
None
Return values
None
Definition at line 130 of file CAN/CAN_Normal/Source/main.c.
References GPIO_Config(), GPIO_ConfigPinRemap(), GPIO_MODE_AF_PP, GPIO_MODE_IN_PU, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_5, GPIO_PIN_6, GPIO_REMAP2_CAN1, GPIO_REMAP_CAN2, GPIO_SPEED_50MHz, GPIOB, GPIOD, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOB, RCM_APB2_PERIPH_GPIOD, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by main().
CAN_Transmit_Init()
void CAN_Transmit_Init (void)
CAN Transmit Init.
Parameters
None
Return values
None
Definition at line 238 of file CAN/CAN_Normal/Source/main.c.
References CAN_RTXR_DATA, CAN_TYPEID_STD, CAN_TxMessage_T::dataLengthCode, CAN_TxMessage_T::extID, CAN_TxMessage_T::remoteTxReq, CAN_TxMessage_T::stdID, TxMessage, and CAN_TxMessage_T::typeID.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 67 of file CAN/CAN_Normal/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), APM_MINI_PBGetState(), APM_MINI_PBInit(), BUTTON_KEY1, BUTTON_KEY2, BUTTON_MODE_GPIO, CAN1, CAN2, CAN_Config_Init(), CAN_EnableInterrupt(), CAN_GPIO_Init(), CAN_INT_F0MP, CAN_Transmit_Init(), CAN_TxMessage(), CAN_TxMessage_T::data, LED2, LED3, NVIC_Configuration(), RCM_APB1_PERIPH_CAN1, RCM_APB1_PERIPH_CAN2, RCM_EnableAPB1PeriphClock(), RESET, TxMessage, and USART_Init().
NVIC_Configuration()
void NVIC_Configuration (void)
Configures NVIC.
Parameters
None
Return values
None
Definition at line 302 of file CAN/CAN_Normal/Source/main.c.
References NVIC_EnableIRQRequest().
USART_Init()
void USART_Init (void)
USART configs.
Parameters
None
Return values
None
Definition at line 316 of file CAN/CAN_Normal/Source/main.c.
References APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, USART_Config_T::hardwareFlow, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU