APM32F10x_SDK: Functions
Functions
Examples » USB_MSC_Disk
Typedefs
typedef uint8_t(* STORAGE_Init_T) (uint8_t lun)
typedef uint8_t(* STORAGE_ReadCapacity_T) (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
typedef uint8_t(* STORAGE_CheckReady_T) (uint8_t lun)
typedef uint8_t(* STORAGE_CheckWPR_T) (uint8_t lun)
typedef uint8_t(* STORAGE_Read_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
typedef uint8_t(* STORAGE_Write_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Functions
void USBD_HardWareInit (void)
void MSC_Init (void)
MSC init.
void MSC_Proc (void)
void MSC_SetConfigCallBack (void)
int main (void)
Main program.
void USBD_MSC_OutEpCallback (uint8_t ep)
MSC Out endpoint initialization call back.
void USBD_MSC_InEpCallback (uint8_t ep)
MSC In endpoint initialization call back.
void MSC_Reset (void)
Reset.
uint8_t STORAGE_Init (uint8_t lun)
Initialize the medium.
uint8_t STORAGE_ReadCapacity (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
Read medium capacity and block size.
uint8_t STORAGE_CheckReady (uint8_t lun)
return medium ready Status
uint8_t STORAGE_CheckWPR (uint8_t lun)
return medium write-protected Status
uint8_t STORAGE_ReadData (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Read data from the medium.
uint8_t STORAGE_WriteData (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Write data to the medium.
Variables
STORAGE_Callback_T g_storageCallBack
Detailed Description
Typedef Documentation
STORAGE_CheckReady_T
typedef uint8_t(* STORAGE_CheckReady_T) (uint8_t lun)
Definition at line 57 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
STORAGE_CheckWPR_T
typedef uint8_t(* STORAGE_CheckWPR_T) (uint8_t lun)
Definition at line 58 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
STORAGE_Init_T
typedef uint8_t(* STORAGE_Init_T) (uint8_t lun)
Definition at line 55 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
STORAGE_Read_T
typedef uint8_t(* STORAGE_Read_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Definition at line 59 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
STORAGE_ReadCapacity_T
typedef uint8_t(* STORAGE_ReadCapacity_T) (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
Definition at line 56 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
STORAGE_Write_T
typedef uint8_t(* STORAGE_Write_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Definition at line 60 of file USB/USB_MSC_Disk/Include/usbd_storage_disk.h.
Function Documentation
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 50 of file USB/USB_MSC_Disk/Source/main.c.
References MSC_Init().
MSC_Init()
void MSC_Init (void)
MSC init.
Parameters
None
Return values
None
Definition at line 155 of file USB/USB_MSC_Disk/Source/usbd_msc.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_stdReqCallback, g_stringDescriptor, USBD_InitParam_T::inEpHandler, MSC_Reset(), USBD_InitParam_T::outEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, USBD_InitParam_T::resetHandler, USBD_Init(), USBD_InitParamStructInit(), USBD_MSC_ClassHandler(), USBD_MSC_InEpCallback(), and USBD_MSC_OutEpCallback().
Referenced by main().
MSC_Proc()
void MSC_Proc (void)
MSC_Reset()
void MSC_Reset (void)
Reset.
Parameters
None
Return values
None
Definition at line 132 of file USB/USB_MSC_Disk/Source/usbd_msc.c.
References USBD_EPConfig_T::epBufAddr, USBD_EPConfig_T::epNum, USBD_EPConfig_T::epStatus, USBD_EPConfig_T::epType, USBD_EPConfig_T::maxPackSize, USB_EP1_RX_ADDR, USB_EP1_TX_ADDR, USBD_EP_1, USBD_EP_STATUS_NAK, USBD_EP_TYPE_BULK, USBD_OpenInEP(), and USBD_OpenOutEP().
Referenced by MSC_Init().
MSC_SetConfigCallBack()
void MSC_SetConfigCallBack (void)
STORAGE_CheckReady()
uint8_t STORAGE_CheckReady (uint8_t lun)
return medium ready Status
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 124 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_CheckWPR()
uint8_t STORAGE_CheckWPR (uint8_t lun)
return medium write-protected Status
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 136 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_Init()
uint8_t STORAGE_Init (uint8_t lun)
Initialize the medium.
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 93 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_ReadCapacity()
uint8_t STORAGE_ReadCapacity (uint8_t lun, uint32_t * blockNum, uint32_t * blockSize)
Read medium capacity and block size.
Parameters
lun Logical unit number
blockNum number of physical block
blockSize size of a physical block
Return values
SCSI_OK or SCSI_FAILL
Definition at line 109 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References SCSI_OK, STORAGE_BLK_NBR, and STORAGE_BLK_SIZ.
STORAGE_ReadData()
uint8_t STORAGE_ReadData (uint8_t lun, uint8_t * buf, uint32_t blkAddr, uint16_t blkLen)
Read data from the medium.
Parameters
lun Logical unit number
buf Pointer to the buffer to get data
blkAddr block address of first physical block to be read
blkLen number of physical block to be read
Return values
SCSI_OK or SCSI_FAILL
Definition at line 154 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References dataBuf, SCSI_OK, and STORAGE_BLK_SIZ.
STORAGE_WriteData()
uint8_t STORAGE_WriteData (uint8_t lun, uint8_t * buf, uint32_t blkAddr, uint16_t blkLen)
Write data to the medium.
Parameters
lun Logical unit number
buf Pointer to the buffer to write data
blkAddr block address of first physical block to be write
blkLen number of physical block to be write
Return values
SCSI_OK or SCSI_FAILL
Definition at line 182 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
References dataBuf, SCSI_OK, and STORAGE_BLK_SIZ.
USBD_HardWareInit()
void USBD_HardWareInit (void)
Definition at line 41 of file USB_MSC_Disk/Source/usb_bsp.c.
References EINT_Config(), EINT_LINE_18, EINT_MODE_INTERRUPT, EINT_TRIGGER_RISING, ENABLE, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, NVIC_EnableIRQRequest(), RCM_APB1_PERIPH_USB, RCM_ConfigUSBCLK(), RCM_EnableAPB1PeriphClock(), RCM_USB_DIV_1_5, and EINT_Config_T::trigger.
USBD_MSC_InEpCallback()
void USBD_MSC_InEpCallback (uint8_t ep)
MSC In endpoint initialization call back.
Parameters
ep : endpoint number
Return values
None
Definition at line 117 of file USB/USB_MSC_Disk/Source/usbd_msc.c.
References MSC_IN_EP, and USBD_MSC_BOT_InData().
Referenced by MSC_Init().
USBD_MSC_OutEpCallback()
void USBD_MSC_OutEpCallback (uint8_t ep)
MSC Out endpoint initialization call back.
Parameters
ep : endpoint number
Return values
None
Definition at line 102 of file USB/USB_MSC_Disk/Source/usbd_msc.c.
References MSC_OUT_EP, and USBD_MSC_BOT_OutData().
Referenced by MSC_Init().
Variable Documentation
g_storageCallBack
STORAGE_Callback_T g_storageCallBack
Initial value:
=
{
    STORAGE_Init,
    STORAGE_ReadCapacity,
    STORAGE_CheckReady,
    STORAGE_CheckWPR,
    STORAGE_ReadData,
    STORAGE_WriteData,
    (uint8_t *)s_inquirydata
}
Definition at line 75 of file USB/USB_MSC_Disk/Source/usbd_storage_disk.c.
Referenced by USBD_MSC_BOT_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU