APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » BAKPR Driver
Functions
void BAKPR_Reset (void)
Reset the BAKPR peripheral registers to their default reset values.
void BAKPR_ConfigTamperPinLevel (BAKPR_TAMPER_PIN_LEVEL_T value)
Deinitializes the BAKPR peripheral registers to their default reset values.
void BAKPR_EnableTamperPin (void)
Enables the Tamper Pin activation.
void BAKPR_DisableTamperPin (void)
Disables the Tamper Pin activation.
void BAKPR_ConfigRTCOutput (BAKPR_RTC_OUTPUT_SOURCE_T soure)
Select the RTC output source to output on the Tamper pin.
void BAKPR_ConfigRTCCalibrationValue (uint8_t calibrationValue)
Sets RTC Clock Calibration value.
void BAKPR_ConfigBackupRegister (BAKPR_DATA_T bakrData, uint16_t data)
Set user data to the specified Data Backup Register.
uint16_t BAKPR_ReadBackupRegister (BAKPR_DATA_T bakrData)
Reads user data from the specified Data Backup Register.
void BAKPR_EnableInterrupt (void)
Enables the Tamper Pin Interrupt.
void BAKPR_DisableInterrupt (void)
Disables the Tamper Pin Interrupt.
uint8_t BAKPR_ReadStatusFlag (void)
Read whether the Tamper Pin Event flag is set or not.
void BAKPR_ClearStatusFlag (void)
Clears Tamper Pin Event pending flag.
uint8_t BAKPR_ReadIntFlag (void)
Get whether the Tamper Pin Interrupt has occurred or not.
void BAKPR_ClearIntFlag (void)
Clears Tamper Pin Interrupt pending bit.
Detailed Description
Function Documentation
BAKPR_ClearIntFlag()
void BAKPR_ClearIntFlag (void)
Clears Tamper Pin Interrupt pending bit.
Parameters
None
Return values
None
Definition at line 245 of file apm32f10x_bakpr.c.
References BAKPR, and BIT_SET.
Referenced by TAMPER_IRQHandler().
BAKPR_ClearStatusFlag()
void BAKPR_ClearStatusFlag (void)
Clears Tamper Pin Event pending flag.
Parameters
None
Return values
None
Definition at line 221 of file apm32f10x_bakpr.c.
References BAKPR, and BIT_SET.
Referenced by main(), and TAMPER_IRQHandler().
BAKPR_ConfigBackupRegister()
void BAKPR_ConfigBackupRegister (BAKPR_DATA_T bakrData, uint16_t data)
Set user data to the specified Data Backup Register.
Parameters
bakrData : specifies the Data Backup Register. This parameter can be BAKPR_DATAx where x is between 1 and 42.
data : data to set This parameter can be a 16bit value.
Return values
None
Definition at line 174 of file apm32f10x_bakpr.c.
References __IOM, BAKPR_BASE, and data.
Referenced by WriteDataToBackupReg().
BAKPR_ConfigRTCCalibrationValue()
void BAKPR_ConfigRTCCalibrationValue (uint8_t calibrationValue)
Sets RTC Clock Calibration value.
Parameters
calibrationValue Specifies the calibration value. This parameter must be a number between 0 and 0x7F.
Return values
None
Definition at line 158 of file apm32f10x_bakpr.c.
References BAKPR.
BAKPR_ConfigRTCOutput()
void BAKPR_ConfigRTCOutput (BAKPR_RTC_OUTPUT_SOURCE_T soure)
Select the RTC output source to output on the Tamper pin.
Parameters
soure specifies the RTC output source. This parameter can be one of the following values:
BAKPR_RTC_OUTPUT_SOURCE_NONE : no RTC output on the Tamper pin.
BAKPR_RTC_OUTPUT_SOURCE_CALIBRATION_CLOCK: output the RTC clock with frequency divided by 64 on the Tamper pin.
BAKPR_RTC_OUTPUT_SOURCE_ALARM : output the RTC Alarm pulse signal on the Tamper pin.
BAKPR_RTC_OUTPUT_SOURCE_SECOND : output the RTC Second pulse signal on the Tamper pin.
Return values
None
Definition at line 130 of file apm32f10x_bakpr.c.
References BAKPR, BAKPR_RTC_OUTPUT_SOURCE_ALARM, BAKPR_RTC_OUTPUT_SOURCE_CALIBRATION_CLOCK, BAKPR_RTC_OUTPUT_SOURCE_NONE, BAKPR_RTC_OUTPUT_SOURCE_SECOND, BIT_SET, and RESET.
BAKPR_ConfigTamperPinLevel()
void BAKPR_ConfigTamperPinLevel (BAKPR_TAMPER_PIN_LEVEL_T value)
Deinitializes the BAKPR peripheral registers to their default reset values.
Parameters
value specifies the RTC output source. This parameter can be one of the following values:
BAKPR_TAMPER_PIN_LEVEL_HIGH: Tamper pin active on high level
BAKPR_TAMPER_PIN_LEVEL_LOW: Tamper pin active on low level
Return values
None
Definition at line 65 of file apm32f10x_bakpr.c.
References BAKPR.
Referenced by main().
BAKPR_DisableInterrupt()
void BAKPR_DisableInterrupt (void)
Disables the Tamper Pin Interrupt.
Parameters
None
Return values
None
Definition at line 113 of file apm32f10x_bakpr.c.
References BAKPR, and DISABLE.
Referenced by main().
BAKPR_DisableTamperPin()
void BAKPR_DisableTamperPin (void)
Disables the Tamper Pin activation.
Parameters
None
Return values
None
Definition at line 89 of file apm32f10x_bakpr.c.
References BAKPR, and DISABLE.
Referenced by main(), and TAMPER_IRQHandler().
BAKPR_EnableInterrupt()
void BAKPR_EnableInterrupt (void)
Enables the Tamper Pin Interrupt.
Parameters
None
Return values
None
Definition at line 101 of file apm32f10x_bakpr.c.
References BAKPR, and ENABLE.
Referenced by main().
BAKPR_EnableTamperPin()
void BAKPR_EnableTamperPin (void)
Enables the Tamper Pin activation.
Parameters
None
Return values
None
Definition at line 77 of file apm32f10x_bakpr.c.
References BAKPR, and ENABLE.
Referenced by main(), and TAMPER_IRQHandler().
BAKPR_ReadBackupRegister()
uint16_t BAKPR_ReadBackupRegister (BAKPR_DATA_T bakrData)
Reads user data from the specified Data Backup Register.
Parameters
bakrData : specifies the Data Backup Register. This parameter can be BAKPR_DATAx where x is between 1 and 42.
Return values
The content of the specified Data Backup Register
Definition at line 192 of file apm32f10x_bakpr.c.
References __IOM, and BAKPR_BASE.
Referenced by CheckBackupRegData(), and CheckBackupRegIsReset().
BAKPR_ReadIntFlag()
uint8_t BAKPR_ReadIntFlag (void)
Get whether the Tamper Pin Interrupt has occurred or not.
Parameters
None
Return values
Tamper Pin Interrupt State
Definition at line 233 of file apm32f10x_bakpr.c.
References BAKPR.
Referenced by TAMPER_IRQHandler().
BAKPR_ReadStatusFlag()
uint8_t BAKPR_ReadStatusFlag (void)
Read whether the Tamper Pin Event flag is set or not.
Parameters
None
Return values
Tamper Pin Event flag state
Definition at line 209 of file apm32f10x_bakpr.c.
References BAKPR.
BAKPR_Reset()
void BAKPR_Reset (void)
Reset the BAKPR peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 49 of file apm32f10x_bakpr.c.
References RCM_DisableBackupReset(), and RCM_EnableBackupReset().
Referenced by RTC_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU