APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » WWDT Driver
Functions
void WWDT_Reset (void)
Reset the WWDT peripheral registers.
void WWDT_ConfigTimebase (WWDT_TIME_BASE_T timeBase)
Configures the WWDT Timebase.
void WWDT_ConfigWindowData (uint8_t windowData)
Configures the WWDT Window data.
void WWDT_ConfigCounter (uint8_t counter)
Configures the WWDT counter value.
void WWDT_EnableEWI (void)
Enable the WWDT Early Wakeup interrupt.
void WWDT_Enable (uint8_t counter)
Enable WWDT and set the counter value.
uint8_t WWDT_ReadFlag (void)
Read the Early Wakeup interrupt flag.
void WWDT_ClearFlag (void)
Clear the Early Wakeup interrupt flag.
Detailed Description
Function Documentation
WWDT_ClearFlag()
void WWDT_ClearFlag (void)
Clear the Early Wakeup interrupt flag.
Parameters
None
Return values
None
Definition at line 153 of file apm32f10x_wwdt.c.
References RESET, and WWDT.
WWDT_ConfigCounter()
void WWDT_ConfigCounter (uint8_t counter)
Configures the WWDT counter value.
Parameters
counter Specifies the watchdog counter value
Return values
None
Note
The counter between 0x40 and 0x7F
Definition at line 103 of file apm32f10x_wwdt.c.
References WWDT.
Referenced by main().
WWDT_ConfigTimebase()
void WWDT_ConfigTimebase (WWDT_TIME_BASE_T timeBase)
Configures the WWDT Timebase.
Parameters
timebase WWDT Prescaler The parameter can be one of following values:
WWDT_TIME_BASE_1: WWDT counter clock = (PCLK1/4096)/1
WWDT_TIME_BASE_2: WWDT counter clock = (PCLK1/4096)/2
WWDT_TIME_BASE_4: WWDT counter clock = (PCLK1/4096)/4
WWDT_TIME_BASE_8: WWDT counter clock = (PCLK1/4096)/8
Return values
None
Definition at line 67 of file apm32f10x_wwdt.c.
References WWDT.
Referenced by main().
WWDT_ConfigWindowData()
void WWDT_ConfigWindowData (uint8_t windowData)
Configures the WWDT Window data.
Parameters
windowdata window data which compare with the downcounter
Return values
None
Note
The windowdata must be lower than 0x80
Definition at line 85 of file apm32f10x_wwdt.c.
References WWDT.
Referenced by main().
WWDT_Enable()
void WWDT_Enable (uint8_t counter)
Enable WWDT and set the counter value.
Parameters
counter the window watchdog counter value
Return values
None
Note
The counter between 0x40 and 0x7F
Definition at line 129 of file apm32f10x_wwdt.c.
References WWDT.
Referenced by main().
WWDT_EnableEWI()
void WWDT_EnableEWI (void)
Enable the WWDT Early Wakeup interrupt.
Parameters
None
Return values
None
Definition at line 115 of file apm32f10x_wwdt.c.
References SET, and WWDT.
WWDT_ReadFlag()
uint8_t WWDT_ReadFlag (void)
Read the Early Wakeup interrupt flag.
Parameters
None
Return values
the state of the Early Wakeup interrupt flagte
Definition at line 141 of file apm32f10x_wwdt.c.
References WWDT.
WWDT_Reset()
void WWDT_Reset (void)
Reset the WWDT peripheral registers.
Parameters
None
Return values
None
Definition at line 49 of file apm32f10x_wwdt.c.
References RCM_APB1_PERIPH_WWDT, RCM_DisableAPB1PeriphReset(), and RCM_EnableAPB1PeriphReset().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU