APM32F10x_SDK: Functions
Functions
Examples » DMA_ADC
Functions
void ADC_Isr (void)
ADC interrupt service routine.
void Delay (uint32_t count)
Delay.
void DMA_Init (uint32_t *Buf)
DMA Init.
void ADC_Init (void)
ADC Init.
int main (void)
Main program.
Detailed Description
Function Documentation
ADC_Init()
void ADC_Init (void)
ADC Init.
Parameters
None
Return values
None
Definition at line 161 of file DMA/DMA_ADC/Source/main.c.
References ADC1, ADC_CHANNEL_0, ADC_Config(), ADC_ConfigRegularChannel(), ADC_ConfigStructInit(), ADC_DATA_ALIGN_RIGHT, ADC_Enable(), ADC_EnableDMA(), ADC_EnableSoftwareStartConv(), ADC_EXT_TRIG_CONV_None, ADC_Reset(), ADC_SAMPLETIME_239CYCLES5, ADC_Config_T::continuosConvMode, ADC_Config_T::dataAlign, DISABLE, ENABLE, ADC_Config_T::externalTrigConv, GPIO_Config(), GPIO_ConfigStructInit(), GPIO_MODE_ANALOG, GPIO_PIN_0, GPIO_SPEED_50MHz, GPIOA, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_ADC1, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), ADC_Config_T::scanConvMode, and GPIO_Config_T::speed.
Referenced by main().
ADC_Isr()
void ADC_Isr (void)
ADC interrupt service routine.
Parameters
None
Return values
None
Definition at line 197 of file DAC/DAC_ADC/Source/main.c.
References ADC1, ADC_ClearStatusFlag(), ADC_FLAG_EOC, ADC_ReadConversionValue(), ADC_ReadStatusFlag(), adcData, APM_MINI_LEDOff(), APM_MINI_LEDOn(), DAC_ALIGN_12BIT_R, DAC_ConfigChannel1Data(), dacData, Delay(), LED2, and LED3.
Referenced by ADC1_2_IRQHandler().
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 207 of file DMA/DMA_ADC/Source/main.c.
References count, and systick.
DMA_Init()
void DMA_Init (uint32_t * Buf)
DMA Init.
Parameters
Buf memory addr
Return values
None
Definition at line 131 of file DMA/DMA_ADC/Source/main.c.
References ADC1, DMA_Config_T::bufferSize, DMA_Config_T::dir, DMA1_Channel1, DMA_Config(), DMA_DIR_PERIPHERAL_SRC, DMA_Enable(), DMA_EnableInterrupt(), DMA_INT_TC, DMA_M2MEN_DISABLE, DMA_MEMORY_DATA_SIZE_HALFWORD, DMA_MEMORY_INC_DISABLE, DMA_MODE_CIRCULAR, DMA_PERIPHERAL_DATA_SIZE_HALFWORD, DMA_PERIPHERAL_INC_DISABLE, DMA_PRIORITY_HIGH, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Config_T::priority, RCM_AHB_PERIPH_DMA1, and RCM_EnableAHBPeriphClock().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 74 of file DMA/DMA_ADC/Source/main.c.
References ADC_Init(), APM_MINI_COMInit(), APM_MINI_LEDInit(), USART_Config_T::baudRate, COM1, Delay(), DMA1_FLAG_TC1, DMA_ClearStatusFlag(), DMA_Init(), DMA_ReadStatusFlag(), USART_Config_T::hardwareFlow, LED2, LED3, USART_Config_T::mode, USART_Config_T::parity, SET, USART_Config_T::stopBits, SystemCoreClock, USART_ConfigStructInit(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU