APM32F10x_SDK: usbd_init.c File Reference
usbd_init.c File Reference
USB initialization management.
#include "usbd_init.h"
#include "usb_bsp.h"
Functions
void USBD_Init (USBD_InitParam_T *param)
USB initialization.
void USBD_InitParamStructInit (USBD_InitParam_T *param)
Init parameter in param.
void USBD_PowerOn (void)
USB Power on.
void USBD_PowerOff (void)
USB Power off.
void USBD_OpenOutEP (USBD_EPConfig_T *epConfig)
Open OUT endpoint.
void USBD_OpenInEP (USBD_EPConfig_T *epConfig)
Open IN endpoint.
void USBD_CloseOutEP (USBD_EP_T ep)
Close OUT endpoint.
void USBD_CloseInEP (USBD_EP_T ep)
Close IN endpoint.
Detailed Description
USB initialization management.
Version
V1.0.0
Date
2021-12-06
Attention
Copyright (C) 2020-2022 Geehy Semiconductor
You may not use this file except in compliance with the GEEHY COPYRIGHT NOTICE (GEEHY SOFTWARE PACKAGE LICENSE).
The program is only for reference, which is distributed in the hope that it will be useful and instructional for customers to develop their software. Unless required by applicable law or agreed to in writing, the program is distributed on an "AS IS" BASIS, WITHOUT ANY WARRANTY OR CONDITIONS OF ANY KIND, either express or implied. See the GEEHY SOFTWARE PACKAGE LICENSE for the governing permissions and limitations under the License.
Definition in file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
Function Documentation
USBD_CloseInEP()
void USBD_CloseInEP (USBD_EP_T ep)
Close IN endpoint.
Parameters
ep IN endpoint Number
Return values
None
Definition at line 208 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_EP_STATUS_DISABLE, and USBD_SetEPTxStatus().
USBD_CloseOutEP()
void USBD_CloseOutEP (USBD_EP_T ep)
Close OUT endpoint.
Parameters
ep OUT endpoint Number
Return values
None
Definition at line 194 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USBD_EP_STATUS_DISABLE, and USBD_SetEPRxStatus().
USBD_Init()
void USBD_Init (USBD_InitParam_T * param)
USB initialization.
USB init.
Parameters
param Initialization parameter
Return values
None
Definition at line 38 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
USBD_InitParamStructInit()
void USBD_InitParamStructInit (USBD_InitParam_T * param)
Init parameter in param.
Parameters
param Initialization parameter
Return values
None
Definition at line 80 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
USBD_OpenInEP()
void USBD_OpenInEP (USBD_EPConfig_T * epConfig)
Open IN endpoint.
Parameters
epConfig Point to USBD_EPConfig_T structure
Return values
None
Definition at line 168 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References USBD_EPConfig_T::epBufAddr, USBD_EPConfig_T::epKind, USBD_EPConfig_T::epNum, USBD_EPConfig_T::epStatus, USBD_EPConfig_T::epType, g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_EPConfig_T::maxPackSize, USBD_ResetEPKind(), USBD_SetEPKind(), USBD_SetEPTxAddr, USBD_SetEPTxStatus(), and USBD_SetEPType().
Referenced by HidMouse_Reset(), MSC_Reset(), and VCP_Reset().
USBD_OpenOutEP()
void USBD_OpenOutEP (USBD_EPConfig_T * epConfig)
Open OUT endpoint.
Endpoint init.
Parameters
epConfig Point to USBD_EPConfig_T structure
Return values
None
Definition at line 141 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References USBD_EPConfig_T::epBufAddr, USBD_EPConfig_T::epKind, USBD_EPConfig_T::epNum, USBD_EPConfig_T::epStatus, USBD_EPConfig_T::epType, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_EPConfig_T::maxPackSize, USBD_Info_T::outBuf, USBD_ResetEPKind(), USBD_SetEPKind(), USBD_SetEPRxAddr, USBD_SetEPRxCnt(), USBD_SetEPRxStatus(), and USBD_SetEPType().
Referenced by MSC_Reset(), and VCP_Reset().
USBD_PowerOff()
void USBD_PowerOff (void)
USB Power off.
Parameters
None
Return values
None
Power down and Force USB Reset
Definition at line 124 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References USBD_ClearIntFlag, USBD_DisableInterrupt, USBD_INT_ALL, and USBD_SetRegCTRL.
USBD_PowerOn()
void USBD_PowerOn (void)
USB Power on.
power
Parameters
None
Return values
None
Definition at line 104 of file USB_Device_Lib/Core_Device/Standard/src/usbd_init.c.
References USB_INT_SOURCE, USBD_ClearIntFlag, USBD_DisableInterrupt, USBD_EnableInterrupt, USBD_INT_ALL, USBD_ResetForceReset, USBD_ResetPowerDown, and USBD_SetForceReset.
Referenced by USBD_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU