APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » RTC Driver
Functions
void RTC_EnableConfigMode (void)
Enter RTC configuration mode.
void RTC_DisableConfigMode (void)
Exit RTC configuration mode.
uint32_t RTC_ReadCounter (void)
Read the RTC counter value.
void RTC_ConfigCounter (uint32_t value)
Configures the RTC counter value.
void RTC_ConfigPrescaler (uint32_t value)
Configures the RTC prescaler value.
void RTC_ConfigAlarm (uint32_t value)
Configures the RTC alarm value.
uint32_t RTC_ReadDivider (void)
Read the RTC divider value.
void RTC_WaitForLastTask (void)
Waits until last write operation on RTC registers has finished.
void RTC_WaitForSynchro (void)
Waits until the RTC registers Synchronized.
void RTC_EnableInterrupt (uint16_t interrupt)
Enable RTC interrupts.
void RTC_DisableInterrupt (uint16_t interrupt)
Disable RTC interrupts.
uint8_t RTC_ReadStatusFlag (RTC_FLAG_T flag)
Read flag bit.
void RTC_ClearStatusFlag (uint16_t flag)
Clear flag bit.
uint8_t RTC_ReadIntFlag (RTC_INT_T flag)
Read interrupt flag bit is set.
void RTC_ClearIntFlag (uint16_t flag)
Clear RTC interrupt flag bit.
Detailed Description
Function Documentation
RTC_ClearIntFlag()
void RTC_ClearIntFlag (uint16_t flag)
Clear RTC interrupt flag bit.
Parameters
flag specifies the flag to clear. This parameter can be one of the following values:
RTC_INT_OVR : Overflow interrupt
RTC_INT_ALR : Alarm interrupt
RTC_INT_SEC : Second interrupt
Return values
None
Definition at line 258 of file apm32f10x_rtc.c.
References RTC.
Referenced by RTC_IRQHandler(), and RTC_Isr().
RTC_ClearStatusFlag()
void RTC_ClearStatusFlag (uint16_t flag)
Clear flag bit.
Parameters
flag specifies the flag to clear. This parameter can be any combination of the following values:
RTC_FLAG_OVR : Overflow flag
RTC_FLAG_ALR : Alarm flag
RTC_FLAG_SEC : Second flag
Return values
None
Definition at line 226 of file apm32f10x_rtc.c.
References RTC.
Referenced by EINT1_IRQHandler().
RTC_ConfigAlarm()
void RTC_ConfigAlarm (uint32_t value)
Configures the RTC alarm value.
Parameters
value RTC alarm new value.
Return values
None
Definition at line 117 of file apm32f10x_rtc.c.
References RTC, RTC_DisableConfigMode(), and RTC_EnableConfigMode().
Referenced by EINT1_IRQHandler(), EINT1_Isr(), and RTC_Init().
RTC_ConfigCounter()
void RTC_ConfigCounter (uint32_t value)
Configures the RTC counter value.
Parameters
value RTC counter new value.
Return values
None
Definition at line 87 of file apm32f10x_rtc.c.
References RTC, RTC_DisableConfigMode(), and RTC_EnableConfigMode().
Referenced by RTC_Init().
RTC_ConfigPrescaler()
void RTC_ConfigPrescaler (uint32_t value)
Configures the RTC prescaler value.
Parameters
value RTC prescaler new value.
Return values
None
Definition at line 102 of file apm32f10x_rtc.c.
References RTC, RTC_DisableConfigMode(), and RTC_EnableConfigMode().
Referenced by RTC_Config(), and RTC_Init().
RTC_DisableConfigMode()
void RTC_DisableConfigMode (void)
Exit RTC configuration mode.
Parameters
None
Return values
None
Definition at line 60 of file apm32f10x_rtc.c.
References BIT_RESET, and RTC.
Referenced by RTC_ConfigAlarm(), RTC_ConfigCounter(), and RTC_ConfigPrescaler().
RTC_DisableInterrupt()
void RTC_DisableInterrupt (uint16_t interrupt)
Disable RTC interrupts.
Parameters
interrupt specifies the RTC interrupt sources to be disabled This parameter can be any combination of the following values:
RTC_INT_OVR : Overflow interrupt
RTC_INT_ALR : Alarm interrupt
RTC_INT_SEC : Second interrupt
Return values
None
Definition at line 192 of file apm32f10x_rtc.c.
References RTC.
RTC_EnableConfigMode()
void RTC_EnableConfigMode (void)
Enter RTC configuration mode.
Parameters
None
Return values
None
Definition at line 48 of file apm32f10x_rtc.c.
References BIT_SET, and RTC.
Referenced by RTC_ConfigAlarm(), RTC_ConfigCounter(), and RTC_ConfigPrescaler().
RTC_EnableInterrupt()
void RTC_EnableInterrupt (uint16_t interrupt)
Enable RTC interrupts.
Parameters
interrupt specifies the RTC interrupt sources to be enabled This parameter can be any combination of the following values:
RTC_INT_OVR : Overflow interrupt
RTC_INT_ALR : Alarm interrupt
RTC_INT_SEC : Second interrupt
Definition at line 176 of file apm32f10x_rtc.c.
References RTC.
Referenced by RTC_Config(), and RTC_Init().
RTC_ReadCounter()
uint32_t RTC_ReadCounter (void)
Read the RTC counter value.
Parameters
None
Return values
RTC counter value.
Definition at line 72 of file apm32f10x_rtc.c.
References RTC.
Referenced by EINT1_IRQHandler(), EINT1_Isr(), and RTC_Isr().
RTC_ReadDivider()
uint32_t RTC_ReadDivider (void)
Read the RTC divider value.
Parameters
None
Return values
RTC Divider value.
Definition at line 132 of file apm32f10x_rtc.c.
References RTC.
RTC_ReadIntFlag()
uint8_t RTC_ReadIntFlag (RTC_INT_T flag)
Read interrupt flag bit is set.
Parameters
flag specifies the flag to check. This parameter can be any combination of the following values:
RTC_INT_OVR : Overflow interrupt
RTC_INT_ALR : Alarm interrupt
RTC_INT_SEC : Second interrupt
Return values
None
Definition at line 242 of file apm32f10x_rtc.c.
References RESET, RTC, and SET.
Referenced by RTC_IRQHandler().
RTC_ReadStatusFlag()
uint8_t RTC_ReadStatusFlag (RTC_FLAG_T flag)
Read flag bit.
Parameters
flag specifies the flag to check. This parameter can be one of the following values:
RTC_FLAG_OC : RTC Operation Complete flag
RTC_FLAG_RSYNC: Registers Synchronized flag
RTC_FLAG_OVR : Overflow flag
RTC_FLAG_ALR : Alarm flag
RTC_FLAG_SEC : Second flag
Return values
SET or RESET
Definition at line 210 of file apm32f10x_rtc.c.
References RESET, RTC, and SET.
Referenced by EINT1_IRQHandler().
RTC_WaitForLastTask()
void RTC_WaitForLastTask (void)
Waits until last write operation on RTC registers has finished.
Parameters
None
Return values
None
Definition at line 147 of file apm32f10x_rtc.c.
References BIT_RESET, and RTC.
Referenced by EINT1_IRQHandler(), EINT1_Isr(), RTC_Config(), RTC_Init(), and RTC_IRQHandler().
RTC_WaitForSynchro()
void RTC_WaitForSynchro (void)
Waits until the RTC registers Synchronized.
Parameters
None
Return values
None
Definition at line 161 of file apm32f10x_rtc.c.
References BIT_RESET, and RTC.
Referenced by RTC_Config(), and RTC_Init().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU