APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » PMU Driver
Functions
void PMU_Reset (void)
Reset the PMU peripheral register.
void PMU_EnableBackupAccess (void)
Enables access to the RTC and backup registers.
void PMU_DisableBackupAccess (void)
Disables access to the RTC and backup registers.
void PMU_EnablePVD (void)
Enables the Power Voltage Detector(PVD).
void PMU_DisablePVD (void)
Disables the Power Voltage Detector(PVD).
void PMU_ConfigPVDLevel (PMU_PVD_LEVEL_T level)
Configure a voltage threshold detected by a power supply voltage detector (PVD).
void PMU_EnableWakeUpPin (void)
Enables the WakeUp Pin functionality.
void PMU_DisableWakeUpPin (void)
Diaables the WakeUp Pin functionality.
void PMU_EnterSTOPMode (PMU_REGULATOR_T regulator, PMU_STOP_ENTRY_T entry)
Enters STOP mode.
void PMU_EnterSTANDBYMode (void)
Enters STANDBY mode.
uint8_t PMU_ReadStatusFlag (PMU_FLAG_T flag)
Read the specified PWR flag is set or not.
void PMU_ClearStatusFlag (PMU_FLAG_T flag)
Clears the PWR's pending flags.
Detailed Description
Function Documentation
PMU_ClearStatusFlag()
void PMU_ClearStatusFlag (PMU_FLAG_T flag)
Clears the PWR's pending flags.
Parameters
flag£ºClears the status of specifies the flag. This parameter can be one of the following values:
PMU_FLAG_WUE : Wake Up flag
PMU_FLAG_SB : StandBy flag
Return values
None
Definition at line 255 of file apm32f10x_pmu.c.
References BIT_SET, PMU, PMU_FLAG_SB, and PMU_FLAG_WUE.
Referenced by RTC_Init().
PMU_ConfigPVDLevel()
void PMU_ConfigPVDLevel (PMU_PVD_LEVEL_T level)
Configure a voltage threshold detected by a power supply voltage detector (PVD).
Parameters
level£ºspecifies the PVD detection level This parameter can be one of the following values:
PMU_PVD_LEVEL_2V2 : Config PVD detection level to 2.2V
PMU_PVD_LEVEL_2V3 : Config PVD detection level to 2.3V
PMU_PVD_LEVEL_2V4 : Config PVD detection level to 2.4V
PMU_PVD_LEVEL_2V5 : Config PVD detection level to 2.5V
PMU_PVD_LEVEL_2V6 : Config PVD detection level to 2.6V
PMU_PVD_LEVEL_2V7 : Config PVD detection level to 2.7V
PMU_PVD_LEVEL_2V8 : Config PVD detection level to 2.8V
PMU_PVD_LEVEL_2V9 : Config PVD detection level to 2.9V
Return values
None
Definition at line 119 of file apm32f10x_pmu.c.
References PMU.
PMU_DisableBackupAccess()
void PMU_DisableBackupAccess (void)
Disables access to the RTC and backup registers.
Parameters
None
Return values
None
Definition at line 74 of file apm32f10x_pmu.c.
References DISABLE, and PMU.
PMU_DisablePVD()
void PMU_DisablePVD (void)
Disables the Power Voltage Detector(PVD).
Parameters
None
Return values
None
Definition at line 98 of file apm32f10x_pmu.c.
References DISABLE, and PMU.
PMU_DisableWakeUpPin()
void PMU_DisableWakeUpPin (void)
Diaables the WakeUp Pin functionality.
Parameters
None
Return values
None
Definition at line 147 of file apm32f10x_pmu.c.
References DISABLE, and PMU.
PMU_EnableBackupAccess()
void PMU_EnableBackupAccess (void)
Enables access to the RTC and backup registers.
Parameters
None
Return values
None
Definition at line 62 of file apm32f10x_pmu.c.
References ENABLE, and PMU.
Referenced by main(), RTC_Config(), and RTC_Init().
PMU_EnablePVD()
void PMU_EnablePVD (void)
Enables the Power Voltage Detector(PVD).
Parameters
None
Return values
None
Definition at line 86 of file apm32f10x_pmu.c.
References ENABLE, and PMU.
PMU_EnableWakeUpPin()
void PMU_EnableWakeUpPin (void)
Enables the WakeUp Pin functionality.
Parameters
None
Return values
None
Definition at line 135 of file apm32f10x_pmu.c.
References ENABLE, and PMU.
Referenced by main().
PMU_EnterSTANDBYMode()
void PMU_EnterSTANDBYMode (void)
Enters STANDBY mode.
Parameters
None
Return values
None
Definition at line 199 of file apm32f10x_pmu.c.
References BIT_SET, and PMU.
Referenced by EINT1_IRQHandler().
PMU_EnterSTOPMode()
void PMU_EnterSTOPMode (PMU_REGULATOR_T regulator, PMU_STOP_ENTRY_T entry)
Enters STOP mode.
Parameters
regulator specifies the regulator state in STOP mode. This parameter can be one of the following values:
PMU_REGULATOR_ON : STOP mode with regulator ON
PMU_REGULATOR_LOWPOWER: STOP mode with regulator in low power mode
entry specifies if STOP mode in entered with WFI or WFE instruction. This parameter can be one of the following values:
PMU_STOP_ENTRY_WFI: Enter STOP mode with WFI instruction
PMU_STOP_ENTRY_WFE: Enter STOP mode with WFE instruction
Return values
None
Definition at line 167 of file apm32f10x_pmu.c.
References PMU, and PMU_STOP_ENTRY_WFI.
Referenced by Eint1_Isr().
PMU_ReadStatusFlag()
uint8_t PMU_ReadStatusFlag (PMU_FLAG_T flag)
Read the specified PWR flag is set or not.
Parameters
flag£ºReads the status of specifies the flag. This parameter can be one of the following values:
PMU_FLAG_WUE : Wake Up flag
PMU_FLAG_SB : StandBy flag
PMU_FLAG_PVDO: PVD Output flag
Return values
The new state of PMU_FLAG (SET or RESET).
Definition at line 226 of file apm32f10x_pmu.c.
References BIT_RESET, PMU, PMU_FLAG_PVDO, PMU_FLAG_SB, and PMU_FLAG_WUE.
Referenced by RTC_Init().
PMU_Reset()
void PMU_Reset (void)
Reset the PMU peripheral register.
Parameters
None
Return values
None
Definition at line 49 of file apm32f10x_pmu.c.
References RCM_APB1_PERIPH_PMU, RCM_DisableAPB1PeriphReset(), and RCM_EnableAPB1PeriphReset().
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU