APM32F10x_SDK: Functions
Functions
Examples » SPI FullDuplex
Functions
void SPI_FullDuplex_Init ()
SPI Init.
void USART_FullDuplex_Init ()
USART Init.
void Delay (uint32_t count)
Delay.
void SPI_WriteByte (uint8_t dat)
SPI Write uint8_t data.
uint8_t BufferCompare (uint8_t *buf1, uint8_t *buf2, uint8_t size)
Compares two buffers.
int main (void)
Main program.
Detailed Description
Function Documentation
BufferCompare()
uint8_t BufferCompare (uint8_t * buf1, uint8_t * buf2, uint8_t size)
Compares two buffers.
Parameters
buf1 First buffer to be compared
buf1 Second buffer to be compared
size Buffer size
Return values
Return PASSED if buf1 = buf2. If not then return FAILED
Definition at line 274 of file SPI/SPI_FullDuplex/Source/main.c.
References FAILED, PASSED, and size.
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 255 of file SPI/SPI_FullDuplex/Source/main.c.
References count.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 57 of file SPI/SPI_FullDuplex/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), APM_MINI_LEDToggle(), BufferCompare(), DATA_BUF_SIZE, Delay(), FAILED, LED2, LED3, RESET, SPI1, SPI_FLAG_RXBNE, SPI_FullDuplex_Init(), SPI_I2S_ReadStatusFlag(), SPI_I2S_RxData(), SPI_WriteByte(), USART1, USART_FLAG_RXBNE, USART_FullDuplex_Init(), USART_ReadStatusFlag(), USART_RxData(), and USART_TxData().
SPI_FullDuplex_Init()
void SPI_FullDuplex_Init (void)
SPI Init.
Parameters
None
Return values
None
Definition at line 134 of file SPI/SPI_FullDuplex/Source/main.c.
References SPI_Config_T::baudrateDiv, SPI_Config_T::direction, SPI_Config_T::firstBit, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_PU, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7, GPIO_SPEED_50MHz, GPIOA, SPI_Config_T::length, GPIO_Config_T::mode, SPI_Config_T::mode, SPI_Config_T::nss, SPI_Config_T::phase, GPIO_Config_T::pin, SPI_Config_T::polarity, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_SPI1, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, SPI1, SPI_BAUDRATE_DIV_32, SPI_CLKPHA_1EDGE, SPI_CLKPOL_LOW, SPI_Config(), SPI_ConfigDataSize(), SPI_ConfigStructInit(), SPI_DATA_LENGTH_8B, SPI_DIRECTION_2LINES_FULLDUPLEX, SPI_Enable(), SPI_FIRSTBIT_LSB, SPI_MODE_SLAVE, and SPI_NSS_SOFT.
Referenced by main().
SPI_WriteByte()
void SPI_WriteByte (uint8_t dat)
SPI Write uint8_t data.
Parameters
None
Return values
None
Definition at line 119 of file SPI/SPI_FullDuplex/Source/main.c.
References dat, RESET, SPI1, SPI_FLAG_TXBE, SPI_I2S_ReadStatusFlag(), and SPI_I2S_TxData().
Referenced by main().
USART_FullDuplex_Init()
void USART_FullDuplex_Init (void)
USART Init.
Parameters
None
Return values
None
Definition at line 188 of file SPI/SPI_FullDuplex/Source/main.c.
References USART_Config_T::baudRate, USART_ClockConfig_T::clock, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_PU, GPIO_PIN_8, GPIO_SPEED_50MHz, GPIOA, USART_Config_T::hardwareFlow, USART_ClockConfig_T::lastBit, MINI_COM1_CLK, MINI_COM1_RX_GPIO_PORT, MINI_COM1_RX_PIN, MINI_COM1_TX_GPIO_CLK, MINI_COM1_TX_GPIO_PORT, MINI_COM1_TX_PIN, GPIO_Config_T::mode, USART_Config_T::mode, USART_Config_T::parity, USART_ClockConfig_T::phase, GPIO_Config_T::pin, USART_ClockConfig_T::polarity, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART1, USART_CLKEN_ENABLE, USART_CLKPHA_1EDGE, USART_CLKPOL_LOW, USART_Config(), USART_ConfigClock(), USART_Enable(), USART_HARDWARE_FLOW_NONE, USART_LBCP_ENABLE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU