APM32F10x_SDK: Functions
Functions
Examples » USBD_HID
Functions
void USB_HardwareInit (void)
USB hardware Init.
void USBD_ConfigSerialString (uint8_t *string)
Config Serial String.
void USBD_HID_Init (void)
USB initialization for HID.
void USBD_HID_Proc (void)
Mouse process.
void USBD_HID_GPIOInit (void)
HID test key GPIO init.
int main (void)
Main program.
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
void USBD_HID_EPHandler (uint8_t ep)
Endpoint handler.
void USBD_HID_Write (uint8_t key)
Mouse write.
uint8_t USBD_HID_ReadKey (void)
Read key.
Detailed Description
Function Documentation
APM_BOARD_COMInit()
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 221 of file OTG_Device/USBD_HID/Source/usb_board.c.
References APM_MINI_COMInit(), and COM1.
Referenced by USB_HardwareInit().
main()
int main (void)
Main program.
Parameters
None
Return values
int
Definition at line 50 of file OTG/OTG_Device/USBD_HID/Source/main.c.
References USBD_HID_GPIOInit(), USBD_HID_Init(), and USBD_HID_Proc().
USB_HardwareInit()
void USB_HardwareInit (void)
USB hardware Init.
Parameters
None
Return values
None
< APM32F40X
Definition at line 54 of file OTG_Device/USBD_HID/Source/usb_board.c.
References APM_BOARD_COMInit(), USART_Config_T::baudRate, BIT10, BIT12, BIT8, BIT9, BIT_SET, COM1, FMC, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_9, GPIO_PIN_SOURCE_0, GPIO_PIN_SOURCE_1, GPIO_PIN_SOURCE_10, GPIO_PIN_SOURCE_11, GPIO_PIN_SOURCE_12, GPIO_PIN_SOURCE_13, GPIO_PIN_SOURCE_14, GPIO_PIN_SOURCE_15, GPIO_PIN_SOURCE_3, GPIO_PIN_SOURCE_4, GPIO_PIN_SOURCE_5, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIOC, USART_Config_T::hardwareFlow, GPIO_Config_T::mode, USART_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_1, USART_Config_T::parity, GPIO_Config_T::pin, RCM, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, USB_OTG_DisableAllGlobalInterrupt, and USART_Config_T::wordLength.
Referenced by USBD_Init(), and USBH_Init().
USBD_ConfigSerialString()
void USBD_ConfigSerialString (uint8_t * string)
Config Serial String.
Parameters
string point to the Serial String
Return values
None
Definition at line 310 of file OTG/OTG_Device/USBD_HID/Source/usbd_descriptor.c.
References UID_ADDRESS1, UID_ADDRESS2, UID_ADDRESS3, and USBD_NumberToChar.
Referenced by USBD_Init().
USBD_HID_EPHandler()
void USBD_HID_EPHandler (uint8_t ep)
Endpoint handler.
Parameters
ep Endpoint number
Return values
None
Definition at line 125 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References USB_EP_1.
Referenced by USBD_HID_Init().
USBD_HID_GPIOInit()
void USBD_HID_GPIOInit (void)
HID test key GPIO init.
Parameters
None
Return values
None
Definition at line 262 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References APM_MINI_PBInit(), BUTTON_KEY1, BUTTON_KEY2, and BUTTON_MODE_GPIO.
Referenced by main().
USBD_HID_Init()
void USBD_HID_Init (void)
USB initialization for HID.
Parameters
None
Return values
None
Definition at line 236 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_qualifierDescriptor, g_stringDescriptor, USBD_InitParam_T::inEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pQualifierDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, stdReqCallback, USBD_ClassHandler(), USBD_HID_EPHandler(), USBD_Init(), and USBD_InitParamStructInit().
Referenced by main().
USBD_HID_Proc()
void USBD_HID_Proc (void)
Mouse process.
Parameters
None
Return values
None
Definition at line 206 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References USBD_Info_T::devState, g_usbDev, HID_MOUSE_KEY_NULL, USBD_DEVICE_STATE_CONFIGURED, USBD_HID_ReadKey(), and USBD_HID_Write().
Referenced by main().
USBD_HID_ReadKey()
uint8_t USBD_HID_ReadKey (void)
Read key.
Parameters
None
Return values
None
Definition at line 182 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References APM_MINI_PBGetState(), BUTTON_KEY1, BUTTON_KEY2, HID_MOUSE_KEY_LEFT, HID_MOUSE_KEY_NULL, and HID_MOUSE_KEY_RIGHT.
Referenced by USBD_HID_Proc().
USBD_HID_Write()
void USBD_HID_Write (uint8_t key)
Mouse write.
Parameters
key Mouse key
Return values
None
Definition at line 140 of file OTG/OTG_Device/USBD_HID/Source/usbd_hid.c.
References HID_MOUSE_KEY_DOWN, HID_MOUSE_KEY_LEFT, HID_MOUSE_KEY_RIGHT, HID_MOUSE_KEY_UP, USB_EP_1, USBD_TxData(), x, and y.
Referenced by USBD_HID_Proc().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU