APM32F10x_SDK: Functions
Functions
Examples » USBD_VCP
Functions
void USBD_ConfigSerialString (uint8_t *string)
Config Serial String.
void USBD_VCP_Init (void)
VCP initialization.
void USBD_VCP_Proc (void)
Start to reveive OUT packet.
void USBD_VCP_OutEpCallback (uint8_t ep)
OUT endpoint transfer done handler(except EP0)
void USBD_VCP_InEpCallback (uint8_t ep)
IN endpoint transfer done handler(except EP0)
Detailed Description
Function Documentation
USBD_ConfigSerialString()
void USBD_ConfigSerialString (uint8_t * string)
Config Serial String.
Parameters
string point to the Serial String
Return values
None
Definition at line 310 of file OTG/OTG_Device/USBD_HID/Source/usbd_descriptor.c.
References UID_ADDRESS1, UID_ADDRESS2, UID_ADDRESS3, and USBD_NumberToChar.
Referenced by USBD_Init().
USBD_VCP_InEpCallback()
void USBD_VCP_InEpCallback (uint8_t ep)
IN endpoint transfer done handler(except EP0)
Parameters
ep : IN endpoint
Return values
None
Definition at line 117 of file usbd_vcp.c.
References dataBuf, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USB_EP_1, and USBD_RxData().
Referenced by USBD_VCP_Init().
USBD_VCP_Init()
void USBD_VCP_Init (void)
VCP initialization.
Parameters
None
Return values
None
Definition at line 144 of file usbd_vcp.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_qualifierDescriptor, g_stringDescriptor, USBD_InitParam_T::inEpHandler, NULL, USBD_InitParam_T::outEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pQualifierDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, stdReqCallback, USBD_InitParam_T::stdReqExceptionHandler, USBD_ClassHandler(), USBD_Init(), USBD_InitParamStructInit(), USBD_VCP_InEpCallback(), and USBD_VCP_OutEpCallback().
USBD_VCP_OutEpCallback()
void USBD_VCP_OutEpCallback (uint8_t ep)
OUT endpoint transfer done handler(except EP0)
Parameters
ep : OUT endpoint
Return values
None
Definition at line 98 of file usbd_vcp.c.
References dataBuf, g_usbDev, USBD_Info_T::outBuf, USB_EP_1, USBD_TxData(), and USBD_CtrlBuf_T::xferCnt.
Referenced by USBD_VCP_Init().
USBD_VCP_Proc()
void USBD_VCP_Proc (void)
Start to reveive OUT packet.
Parameters
None
Return values
None
Definition at line 132 of file usbd_vcp.c.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU