APM32F10x_SDK: Functions
Functions
Examples » IAP_BootLoader » COMMON
Functions
void IntConStr (uint8_t *str, int32_t conint)
Integer number convert to string.
uint32_t StrConInt (uint8_t *str, int32_t *conint)
string type convert to integer type
uint32_t GetKeyPressed (uint8_t *inputKey)
Get a key from the HyperTerminal.
uint8_t ReadKey (void)
Read a key from the HyperTerminal.
uint8_t ReadKey_TimeOut (uint32_t delay_timeOut)
Read a key from the HyperTerminal.
void Send_Char (uint8_t character)
Send a character on the HyperTerminal.
void Serial_SendString (uint8_t *str)
Send a string on the HyperTerminal.
void ReadInputString (uint8_t *p)
uint32_t Str_Hex_ConInt (uint8_t *hexstr, int32_t *conint)
string convert to an integer number
uint32_t Str_Dec_ConInt (uint8_t *decstr, int32_t *conint)
decimal string convert to an integer
Detailed Description
Function Documentation
GetKeyPressed()
uint32_t GetKeyPressed (uint8_t * inputKey)
Get a key from the HyperTerminal.
Parameters
inputKey User input key pressed
Return values
SUCCESS ERROR
Note
Definition at line 246 of file common.c.
References ERROR, SUCCESS, USART_COM_RXDATA, and USART_COM_RXREADY.
Referenced by ReadKey(), and ReadKey_TimeOut().
IntConStr()
void IntConStr (uint8_t * str, int32_t conint)
Integer number convert to string.
Parameters
str string buffer
conint specific interger number
Return values
None
Note
Definition at line 55 of file common.c.
Referenced by Download(), and PreFirstPack().
ReadInputString()
void ReadInputString (uint8_t * p)
ReadKey()
uint8_t ReadKey (void)
Read a key from the HyperTerminal.
Parameters
None
Return values
The input key pressed
Note
Definition at line 268 of file common.c.
References GetKeyPressed(), and SUCCESS.
Referenced by Upload().
ReadKey_TimeOut()
uint8_t ReadKey_TimeOut (uint32_t delay_timeOut)
Read a key from the HyperTerminal.
Parameters
delay_timeOut£ºread input key timeout
Return values
The input key pressed
Note
Definition at line 294 of file common.c.
References GetKeyPressed(), and SUCCESS.
Referenced by Select_Menu().
Send_Char()
void Send_Char (uint8_t character)
Send a character on the HyperTerminal.
Parameters
character The character need to be sent
Return values
None
Note
Definition at line 320 of file common.c.
References USART_COM_TXDATA, and USART_COM_TXFINISH.
Referenced by Serial_SendString().
Serial_SendString()
void Serial_SendString (uint8_t * str)
Send a string on the HyperTerminal.
Parameters
str The string need to be sent
Return values
None
Note
Definition at line 338 of file common.c.
References Send_Char().
Str_Dec_ConInt()
uint32_t Str_Dec_ConInt (uint8_t * decstr, int32_t * conint)
decimal string convert to an integer
Parameters
decstr dec string buffer
conint specific interger number
Return values
SUCCESS ERROR
Note
Definition at line 158 of file common.c.
References CHECK_DEC, CON_DEC, ERROR, and SUCCESS.
Referenced by StrConInt().
Str_Hex_ConInt()
uint32_t Str_Hex_ConInt (uint8_t * hexstr, int32_t * conint)
string convert to an integer number
Parameters
hexstr hex string type data
conint specific interger number
Return values
SUCCESS ERROR
Note
Definition at line 99 of file common.c.
References CHECK_HEX, CON_HEX, ERROR, and SUCCESS.
Referenced by StrConInt().
StrConInt()
uint32_t StrConInt (uint8_t * str, int32_t * conint)
string type convert to integer type
Parameters
str string buffer
conint specific interger number
Return values
SUCCESS ERROR
Note
Definition at line 221 of file common.c.
References ERROR, Str_Dec_ConInt(), and Str_Hex_ConInt().
Referenced by recceiveFile().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU