APM32F10x_SDK: Functions
Functions
Examples » RT5
Functions
void USART_Write (USART_T *usart, uint8_t *dat)
void Delay (uint32_t count)
Delay.
void USART_Init (void)
USARTS Initialization.
BOOL BufferCompare (uint8_t *buf1, uint8_t *buf2, uint8_t size)
Compares two buffers.
void UserTaskInit (void *pvParameters)
Start task.
void vTaskLedToggle (void *pvParameters)
Led toggle task.
void vTaskUsartTest (void *pvParameters)
usart task
int main (void)
Main program.
Detailed Description
Function Documentation
BufferCompare()
BOOL BufferCompare (uint8_t * buf1, uint8_t * buf2, uint8_t size)
Compares two buffers.
Parameters
buf1 First buffer to be compared
buf1 Second buffer to be compared
size Buffer size
Return values
Return SET if buf1 = buf2. If not then return RESET
Definition at line 348 of file RTOS/RTX5/Source/main.c.
References FALSE, size, and TRUE.
Referenced by vTaskUsartTest().
Delay()
void Delay (uint32_t count)
Delay.
Parameters
count delay count
Return values
None
Definition at line 402 of file RTOS/RTX5/Source/main.c.
References count.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 133 of file RTOS/RTX5/Source/main.c.
References NULL, ThreadIdStart, ThreadStart_Attr, and UserTaskInit().
USART_Init()
void USART_Init (void)
USARTS Initialization.
Parameters
None
Return values
None
Definition at line 370 of file RTOS/RTX5/Source/main.c.
References APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, COM2, Delay(), USART_Config_T::hardwareFlow, MINI_COM1, MINI_COM2, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_ClearStatusFlag(), USART_DisableInterrupt(), USART_FLAG_RXBNE, USART_HARDWARE_FLOW_NONE, USART_INT_RXBNE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
Referenced by UserTaskInit().
USART_Write()
void USART_Write (USART_T * usart, uint8_t * dat)
UserTaskInit()
void UserTaskInit (void * pvParameters)
Start task.
Parameters
pvParameters - passed into the task function as the function parameters
Return values
None
Definition at line 154 of file RTOS/RTX5/Source/main.c.
References APM_MINI_LEDInit(), LED2, LED3, SystemCoreClock, SystemCoreClockUpdate(), tick, and USART_Init().
Referenced by main().
vTaskLedToggle()
void vTaskLedToggle (void * pvParameters)
Led toggle task.
Parameters
pvParameters - passed into the task function as the function parameters
Return values
None
Definition at line 305 of file RTOS/RTX5/Source/main.c.
References APM_MINI_LEDToggle(), LED2, and tick.
vTaskUsartTest()
void vTaskUsartTest (void * pvParameters)
usart task
Parameters
pvParameters - passed into the task function as the function parameters
Return values
None
Definition at line 189 of file RTOS/RTX5/Source/main.c.
References APM_MINI_LEDOff(), APM_MINI_LEDOn(), BufferCompare(), DATA_BUF_SIZE, LED3, MINI_COM1, MINI_COM2, RESET, rxDataBufUSART1, rxDataBufUSART2, TRUE, txDataBufUSART1, txDataBufUSART2, USART_FLAG_RXBNE, USART_FLAG_TXBE, USART_ReadStatusFlag(), USART_RxData(), and USART_TxData().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU