APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » DAC Driver
Functions
void DAC_Reset (void)
Reset dac peripheral registers to their default reset values.
void DAC_Config (uint32_t channel, DAC_Config_T *dacConfig)
Config the DAC peripheral according to the specified parameters in the dacConfig.
void DAC_ConfigStructInit (DAC_Config_T *dacConfig)
Fills each DAC_Config_T member with its default value.
void DAC_Enable (DAC_CHANNEL_T channel)
Enables the specified DAC peripheral.
void DAC_Disable (DAC_CHANNEL_T channel)
Disables the specified DAC peripheral.
void DAC_DMA_Enable (DAC_CHANNEL_T channel)
Enables the specified DAC channel DMA request.
void DAC_DMA_Disable (DAC_CHANNEL_T channel)
Disables the specified DAC channel DMA request.
void DAC_EnableSoftwareTrigger (DAC_CHANNEL_T channel)
Enables the selected DAC channel software trigger.
void DAC_DisableSoftwareTrigger (DAC_CHANNEL_T channel)
Disable the selected DAC channel software trigger.
void DAC_EnableDualSoftwareTrigger (void)
Enables simultaneously the two DAC channels software.
void DAC_DisableDualSoftwareTrigger (void)
Disables simultaneously the two DAC channels software.
void DAC_EnableWaveGeneration (DAC_CHANNEL_T channel, DAC_WAVE_GENERATION_T wave)
Enables the selected DAC channel wave generation.
void DAC_DisableWaveGeneration (DAC_CHANNEL_T channel, DAC_WAVE_GENERATION_T wave)
Disables the selected DAC channel wave generation.
void DAC_ConfigChannel1Data (DAC_ALIGN_T align, uint16_t data)
Set the specified data holding register value for DAC channel 1.
void DAC_ConfigChannel2Data (DAC_ALIGN_T align, uint16_t data)
Set the specified data holding register value for DAC channel 2.
void DAC_ConfigDualChannelData (DAC_ALIGN_T align, uint16_t data2, uint16_t data1)
Set the specified data holding register value for dual DAC channel.
uint16_t DAC_ReadDataOutputValue (DAC_CHANNEL_T channel)
Reads the specified DAC channel data output value.
Detailed Description
Function Documentation
DAC_Config()
void DAC_Config (uint32_t channel, DAC_Config_T * dacConfig)
Config the DAC peripheral according to the specified parameters in the dacConfig.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
dacConfig pointer to a DAC_Config_T structure
Return values
None
Definition at line 67 of file apm32f10x_dac.c.
References DAC, DAC_Config_T::maskAmplitudeSelect, DAC_Config_T::outputBuffer, DAC_Config_T::trigger, and DAC_Config_T::waveGeneration.
Referenced by DAC_Init(), and main().
DAC_ConfigChannel1Data()
void DAC_ConfigChannel1Data (DAC_ALIGN_T align, uint16_t data)
Set the specified data holding register value for DAC channel 1.
Parameters
align DAC channel 1 data alignment This parameter can be one of the following values:
DAC_ALIGN_12BIT_R : 12-bit right-aligned data
DAC_ALIGN_12BIT_L : 12-bit left-aligned data
DAC_ALIGN_8BIT_R : 8-bit right-aligned data
data The data to be loaded in the selected data register.
Return values
None
Definition at line 318 of file apm32f10x_dac.c.
References DAC_BASE, and data.
Referenced by ADC_Isr(), and main().
DAC_ConfigChannel2Data()
void DAC_ConfigChannel2Data (DAC_ALIGN_T align, uint16_t data)
Set the specified data holding register value for DAC channel 2.
Parameters
align DAC channel 2 data alignment This parameter can be one of the following values:
DAC_ALIGN_12BIT_R : 12-bit right-aligned data
DAC_ALIGN_12BIT_L : 12-bit left-aligned data
DAC_ALIGN_8BIT_R : 8-bit right-aligned data
data The data to be loaded in the selected data register.
Return values
None
Definition at line 342 of file apm32f10x_dac.c.
References DAC_BASE, and data.
DAC_ConfigDualChannelData()
void DAC_ConfigDualChannelData (DAC_ALIGN_T align, uint16_t data2, uint16_t data1)
Set the specified data holding register value for dual DAC channel.
Parameters
align Dual DAC channel data alignment This parameter can be one of the following values:
DAC_ALIGN_12BIT_R : 12-bit right-aligned data
DAC_ALIGN_12BIT_L : 12-bit left-aligned data
DAC_ALIGN_8BIT_R : 8-bit right-aligned data
data2 Data for channel2 to be loaded in the selected data register.
data1 Data for channel1 to be loaded in the selected data register
Return values
None
Definition at line 368 of file apm32f10x_dac.c.
References DAC_ALIGN_8BIT_R, DAC_BASE, and data.
DAC_ConfigStructInit()
void DAC_ConfigStructInit (DAC_Config_T * dacConfig)
Fills each DAC_Config_T member with its default value.
Parameters
dacConfig pointer to a DAC_Config_T structure which will be initialized
Return values
None
Definition at line 92 of file apm32f10x_dac.c.
References DAC_LFSR_MASK_BIT11_1, DAC_OUTPUT_BUFFER_ENBALE, DAC_TRIGGER_NONE, DAC_WAVE_GENERATION_NONE, DAC_Config_T::maskAmplitudeSelect, DAC_Config_T::outputBuffer, DAC_Config_T::trigger, and DAC_Config_T::waveGeneration.
Referenced by DAC_Init().
DAC_Disable()
void DAC_Disable (DAC_CHANNEL_T channel)
Disables the specified DAC peripheral.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 136 of file apm32f10x_dac.c.
References BIT_RESET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
DAC_DisableDualSoftwareTrigger()
void DAC_DisableDualSoftwareTrigger (void)
Disables simultaneously the two DAC channels software.
Parameters
None
Return values
None
Definition at line 256 of file apm32f10x_dac.c.
References BIT_RESET, and DAC.
DAC_DisableSoftwareTrigger()
void DAC_DisableSoftwareTrigger (DAC_CHANNEL_T channel)
Disable the selected DAC channel software trigger.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 225 of file apm32f10x_dac.c.
References BIT_RESET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
DAC_DisableWaveGeneration()
void DAC_DisableWaveGeneration (DAC_CHANNEL_T channel, DAC_WAVE_GENERATION_T wave)
Disables the selected DAC channel wave generation.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
wave Select the wave This parameter can be one of the following values:
DAC_WAVE_GENERATION_NONE : no wave generation
DAC_WAVE_GENERATION_NOISE : Noise wave generation
DAC_WAVE_GENERATION_TRIANGLE : Triangle wave generation
Return values
None
Definition at line 300 of file apm32f10x_dac.c.
References DAC.
DAC_DMA_Disable()
void DAC_DMA_Disable (DAC_CHANNEL_T channel)
Disables the specified DAC channel DMA request.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 181 of file apm32f10x_dac.c.
References BIT_RESET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
DAC_DMA_Enable()
void DAC_DMA_Enable (DAC_CHANNEL_T channel)
Enables the specified DAC channel DMA request.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 159 of file apm32f10x_dac.c.
References BIT_SET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
DAC_Enable()
void DAC_Enable (DAC_CHANNEL_T channel)
Enables the specified DAC peripheral.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 114 of file apm32f10x_dac.c.
References BIT_SET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
Referenced by DAC_Init(), and main().
DAC_EnableDualSoftwareTrigger()
void DAC_EnableDualSoftwareTrigger (void)
Enables simultaneously the two DAC channels software.
Parameters
None
Return values
None
Definition at line 243 of file apm32f10x_dac.c.
References BIT_SET, and DAC.
DAC_EnableSoftwareTrigger()
void DAC_EnableSoftwareTrigger (DAC_CHANNEL_T channel)
Enables the selected DAC channel software trigger.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
None
Definition at line 203 of file apm32f10x_dac.c.
References BIT_SET, DAC, DAC_CHANNEL_1, and DAC_CHANNEL_2.
Referenced by main().
DAC_EnableWaveGeneration()
void DAC_EnableWaveGeneration (DAC_CHANNEL_T channel, DAC_WAVE_GENERATION_T wave)
Enables the selected DAC channel wave generation.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
wave Select the wave This parameter can be one of the following values:
DAC_WAVE_GENERATION_NONE : no wave generation
DAC_WAVE_GENERATION_NOISE : Noise wave generation
DAC_WAVE_GENERATION_TRIANGLE : Triangle wave generation
Return values
None
Definition at line 278 of file apm32f10x_dac.c.
References DAC.
DAC_ReadDataOutputValue()
uint16_t DAC_ReadDataOutputValue (DAC_CHANNEL_T channel)
Reads the specified DAC channel data output value.
Parameters
channel Select the DAC channel. This parameter can be one of the following values:
DAC_CHANNEL_1 : DAC channel 1
DAC_CHANNEL_2 : DAC channel 2
Return values
The data output value of the specified DAC channel.
Definition at line 399 of file apm32f10x_dac.c.
References DAC_BASE.
DAC_Reset()
void DAC_Reset (void)
Reset dac peripheral registers to their default reset values.
Parameters
None
Return values
None
Definition at line 49 of file apm32f10x_dac.c.
References RCM_APB1_PERIPH_DAC, RCM_DisableAPB1PeriphReset(), and RCM_EnableAPB1PeriphReset().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU