APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » CAN Driver
Functions
void CAN_Reset (CAN_T *can)
Reset CAN registers.
uint8_t CAN_Config (CAN_T *can, CAN_Config_T *canConfig)
Initialization parameter configuration.
void CAN_ConfigFilter (CAN_T *can, CAN_FilterConfig_T *filterConfig)
Congig the CAN peripheral according to the specified parameters in the filterConfig.
void CAN_ConfigStructInit (CAN_Config_T *canConfig)
Initialize a CAN_Config_T structure with the initial value.
void CAN_EnableDBGFreeze (CAN_T *can)
Enables the DBG Freeze for CAN.
void CAN_DisableDBGFreeze (CAN_T *can)
Disable the DBG Freeze for CAN.
uint8_t CAN_TxMessage (CAN_T *can, CAN_TxMessage_T *TxMessage)
Initiates the transmission of a message.
uint8_t CAN_TxMessageStatus (CAN_T *can, CAN_TX_MAILBIX_T TxMailbox)
Checks the transmission of a message.
void CAN_CancelTxMailbox (CAN_T *can, CAN_TX_MAILBIX_T TxMailbox)
Cancels a transmit request.
void CAN_RxMessage (CAN_T *can, CAN_RX_FIFO_T FIFONumber, CAN_RxMessage_T *RxMessage)
Receives a message and save to a CAN_RxMessage_T structure.
void CAN_ReleaseFIFO (CAN_T *can, CAN_RX_FIFO_T FIFONumber)
Releases the specified FIFO.
uint8_t CAN_PendingMessage (CAN_T *can, CAN_RX_FIFO_T FIFONumber)
Returns the number of pending messages.
uint8_t CAN_OperatingMode (CAN_T *can, CAN_OPERATING_MODE_T operatingMode)
Select the CAN Operation mode.
uint8_t CAN_SleepMode (CAN_T *can)
Into the low power mode.
uint8_t CAN_WakeUpMode (CAN_T *can)
Wakes the CAN up.
uint8_t CAN_ReadLastErrorCode (CAN_T *can)
Read the can's last error code (LERRC)
uint8_t CAN_ReadRxErrorCounter (CAN_T *can)
Read the can Receive Error Counter(RXERRCNT)
uint8_t CAN_ReadLSBTxErrorCounter (CAN_T *can)
Read the LSB of the 9-bit can Transmit Error Counter(TXERRCNT).
void CAN_EnableInterrupt (CAN_T *can, uint32_t interrupts)
Enables the specified can interrupts.
void CAN_DisableInterrupt (CAN_T *can, uint32_t interrupts)
Disable the specified can interrupts.
uint8_t CAN_ReadStatusFlag (CAN_T *can, CAN_FLAG_T flag)
Read whether the specified CAN flag is set or not.
void CAN_ClearStatusFlag (CAN_T *can, CAN_FLAG_T flag)
Clears the CAN's pending flags.
uint8_t CAN_ReadIntFlag (CAN_T *can, CAN_INT_T flag)
Read whether the specified can interrupt has occurred or not.
void CAN_ClearIntFlag (CAN_T *can, CAN_INT_T flag)
Clears the can's interrupt flag.
Detailed Description
Function Documentation
CAN_CancelTxMailbox()
void CAN_CancelTxMailbox (CAN_T * can, CAN_TX_MAILBIX_T TxMailbox)
Cancels a transmit request.
Parameters
can Select the CAN peripheral.
mailBox the number of the mailbox This parameter can be one of the following values:
CAN_TX_MAILBIX_0 : Tx mailbox 0
CAN_TX_MAILBIX_1 : Tx mailbox 1
CAN_TX_MAILBIX_2 : Tx mailbox 2
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 524 of file apm32f10x_can.c.
References CAN_T::ABREQFLG0, CAN_T::ABREQFLG1, CAN_T::ABREQFLG2, BIT_SET, CAN_TX_MAILBIX_0, CAN_TX_MAILBIX_1, CAN_TX_MAILBIX_2, and CAN_T::TXSTS_B.
CAN_ClearIntFlag()
void CAN_ClearIntFlag (CAN_T * can, CAN_INT_T flag)
Clears the can's interrupt flag.
Parameters
can Select the CAN peripheral.
flag Interrupt pending bit to clear This parameter can be one of the following values:
CAN_INT_TXME : Transmit mailbox empty Interrupt
CAN_INT_F0FULL : FIFO 0 full Interrupt
CAN_INT_F0OVR : FIFO 0 overrun Interrupt
CAN_INT_F1FULL : FIFO 1 full Interrupt
CAN_INT_F1OVR : FIFO 1 overrun Interrupt
CAN_INT_ERRW : Error warning Interrupt
CAN_INT_ERRP : Error passive Interrupt
CAN_INT_BOF : Bus-off Interrupt
CAN_INT_LEC : Last error record code Interrupt
CAN_INT_ERR : Error Interrupt
CAN_INT_WUP : Wake-up Interrupt
CAN_INT_SLEEP : Sleep acknowledge Interrupt
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 1127 of file apm32f10x_can.c.
References BIT_RESET, BIT_SET, CAN_INT_BOF, CAN_INT_ERR, CAN_INT_ERRP, CAN_INT_ERRW, CAN_INT_F0FULL, CAN_INT_F0OVR, CAN_INT_F1FULL, CAN_INT_F1OVR, CAN_INT_LEC, CAN_INT_SLEEP, CAN_INT_TXME, CAN_INT_WUP, CAN_T::ERRIFLG, CAN_T::ERRSTS_B, CAN_T::FFULLFLG0, CAN_T::FFULLFLG1, CAN_T::FOVRFLG0, CAN_T::FOVRFLG1, CAN_T::LERRC, CAN_T::MSTS_B, CAN_T::REQCFLG0, CAN_T::REQCFLG1, CAN_T::REQCFLG2, CAN_T::RXF0_B, CAN_T::RXF1_B, CAN_T::SLEEPIFLG, CAN_T::TXSTS_B, and CAN_T::WUPIFLG.
CAN_ClearStatusFlag()
void CAN_ClearStatusFlag (CAN_T * can, CAN_FLAG_T flag)
Clears the CAN's pending flags.
Parameters
can Select the CAN peripheral.
flag specifies the CAN flag. This parameter can be one of the following values:
CAN_FLAG_LERRC : Last error record code Flag
CAN_FLAG_WUPI : Wake up Flag
CAN_FLAG_SLEEP : Sleep acknowledge Flag
CAN_FLAG_F0FULL: FIFO 0 Full Flag
CAN_FLAG_F0OVR : FIFO 0 Overrun Flag
CAN_FLAG_F1FULL: FIFO 1 Full Flag
CAN_FLAG_F1OVR : FIFO 1 Overrun Flag
CAN_FLAG_REQC0 : Request MailBox0 Flag
CAN_FLAG_REQC1 : Request MailBox1 Flag
CAN_FLAG_REQC2 : Request MailBox2 Flag
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 982 of file apm32f10x_can.c.
References CAN_T::ERRSTS, CAN_T::MSTS, RESET, CAN_T::RXF0, CAN_T::RXF1, and CAN_T::TXSTS.
CAN_Config()
uint8_t CAN_Config (CAN_T * can, CAN_Config_T * canConfig)
Initialization parameter configuration.
Parameters
can Select the CAN peripheral which can be CAN1 or CAN2.
canConfig Point to a CAN_Config_T structure.
Return values
ERROR or SUCCEESS
Note
CAN2 applies only to APM32F103xC device.
Definition at line 76 of file apm32f10x_can.c.
References CAN_T::ALBOFFM, CAN_T::ARTXMD, CAN_Config_T::autoBusOffManage, CAN_Config_T::autoWakeUpMode, CAN_T::AWUPCFG, BIT_RESET, BIT_SET, CAN_T::BITTIM, CAN_T::BITTIM_B, CAN_T::BRPSC, ENABLE, ERROR, CAN_T::INITFLG, CAN_T::INITREQ, CAN_T::MCTRL_B, CAN_Config_T::mode, CAN_T::MSTS_B, CAN_Config_T::nonAutoRetran, CAN_Config_T::prescaler, CAN_T::RSYNJW, CAN_Config_T::rxFIFOLockMode, CAN_T::RXFLOCK, CAN_T::SLEEPREQ, SUCCESS, CAN_Config_T::syncJumpWidth, CAN_Config_T::timeSegment1, CAN_Config_T::timeSegment2, CAN_T::TIMSEG1, CAN_T::TIMSEG2, CAN_Config_T::txFIFOPriority, and CAN_T::TXFPCFG.
Referenced by CAN_Config_Init(), CAN_Interrupt(), and CAN_Polling().
CAN_ConfigFilter()
void CAN_ConfigFilter (CAN_T * can, CAN_FilterConfig_T * filterConfig)
Congig the CAN peripheral according to the specified parameters in the filterConfig.
Parameters
can Select the CAN peripheral which can be CAN1 or CAN2.
filterConfig :Point to a CAN_FilterConfig_T structure.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 270 of file apm32f10x_can.c.
References BIT_RESET, BIT_SET, CAN_FILTER_FIFO_0, CAN_FILTER_FIFO_1, CAN_FILTER_MODE_IDMASK, CAN_FILTER_SCALE_16BIT, CAN_FILTER_SCALE_32BIT, ENABLE, CAN_T::FACT, CAN_FilterRegister_T::FBANK1, CAN_FilterRegister_T::FBANK2, CAN_T::FCTRL_B, CAN_T::FFASS, CAN_FilterConfig_T::filterActivation, CAN_FilterConfig_T::filterFIFO, CAN_FilterConfig_T::filterIdHigh, CAN_FilterConfig_T::filterIdLow, CAN_FilterConfig_T::filterMaskIdHigh, CAN_FilterConfig_T::filterMaskIdLow, CAN_FilterConfig_T::filterMode, CAN_FilterConfig_T::filterNumber, CAN_FilterConfig_T::filterScale, CAN_T::FINITEN, CAN_T::FMCFG, CAN_T::FSCFG, and CAN_T::sFilterRegister.
Referenced by CAN_Config_Init(), CAN_Interrupt(), and CAN_Polling().
CAN_ConfigStructInit()
void CAN_ConfigStructInit (CAN_Config_T * canConfig)
Initialize a CAN_Config_T structure with the initial value.
Parameters
canConfig :Point to a CAN_Config_T structure.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 342 of file apm32f10x_can.c.
References CAN_Config_T::autoBusOffManage, CAN_Config_T::autoWakeUpMode, CAN_MODE_NORMAL, CAN_SJW_1, CAN_TIME_SEGMENT1_4, CAN_TIME_SEGMENT2_3, DISABLE, CAN_Config_T::mode, CAN_Config_T::nonAutoRetran, CAN_Config_T::prescaler, CAN_Config_T::rxFIFOLockMode, CAN_Config_T::syncJumpWidth, CAN_Config_T::timeSegment1, CAN_Config_T::timeSegment2, and CAN_Config_T::txFIFOPriority.
Referenced by CAN_Config_Init(), CAN_Interrupt(), and CAN_Polling().
CAN_DisableDBGFreeze()
void CAN_DisableDBGFreeze (CAN_T * can)
Disable the DBG Freeze for CAN.
Parameters
can Select the CAN peripheral.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 379 of file apm32f10x_can.c.
References CAN_T::DBGFRZE, DISABLE, and CAN_T::MCTRL_B.
CAN_DisableInterrupt()
void CAN_DisableInterrupt (CAN_T * can, uint32_t interrupts)
Disable the specified can interrupts.
Parameters
can Select the CAN peripheral.
interrupts specifies the CAN interrupt sources This parameter can be any combination of the following values:
CAN_INT_TXME : Transmit mailbox empty Interrupt
CAN_INT_F0MP : FIFO 0 message pending Interrupt
CAN_INT_F0FULL : FIFO 0 full Interrupt
CAN_INT_F0OVR : FIFO 0 overrun Interrupt
CAN_INT_F1MP : FIFO 1 message pending Interrupt
CAN_INT_F1FULL : FIFO 1 full Interrupt
CAN_INT_F1OVR : FIFO 1 overrun Interrupt
CAN_INT_ERRW : Error warning Interrupt
CAN_INT_ERRP : Error passive Interrupt
CAN_INT_BOF : Bus-off Interrupt
CAN_INT_LEC : Last error record code Interrupt
CAN_INT_ERR : Error Interrupt
CAN_INT_WUP : Wake-up Interrupt
CAN_INT_SLEEP : Sleep acknowledge Interrupt
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 866 of file apm32f10x_can.c.
References CAN_T::INTEN.
Referenced by CAN_Interrupt().
CAN_EnableDBGFreeze()
void CAN_EnableDBGFreeze (CAN_T * can)
Enables the DBG Freeze for CAN.
Parameters
can Select the CAN peripheral.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 365 of file apm32f10x_can.c.
References CAN_T::DBGFRZE, ENABLE, and CAN_T::MCTRL_B.
CAN_EnableInterrupt()
void CAN_EnableInterrupt (CAN_T * can, uint32_t interrupts)
Enables the specified can interrupts.
Parameters
can Select the CAN peripheral.
interrupts specifies the CAN interrupt sources This parameter can be any combination of the following values:
CAN_INT_TXME : Transmit mailbox empty Interrupt
CAN_INT_F0MP : FIFO 0 message pending Interrupt
CAN_INT_F0FULL : FIFO 0 full Interrupt
CAN_INT_F0OVR : FIFO 0 overrun Interrupt
CAN_INT_F1MP : FIFO 1 message pending Interrupt
CAN_INT_F1FULL : FIFO 1 full Interrupt
CAN_INT_F1OVR : FIFO 1 overrun Interrupt
CAN_INT_ERRW : Error warning Interrupt
CAN_INT_ERRP : Error passive Interrupt
CAN_INT_BOF : Bus-off Interrupt
CAN_INT_LEC : Last error record code Interrupt
CAN_INT_ERR : Error Interrupt
CAN_INT_WUP : Wake-up Interrupt
CAN_INT_SLEEP : Sleep acknowledge Interrupt
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 835 of file apm32f10x_can.c.
References CAN_T::INTEN.
Referenced by CAN_Interrupt(), and main().
CAN_OperatingMode()
uint8_t CAN_OperatingMode (CAN_T * can, CAN_OPERATING_MODE_T operatingMode)
Select the CAN Operation mode.
Parameters
can Select the CAN peripheral.
operatingMode CAN Operating Mode This parameter can be one of the following values:
CAN_OPERATING_MODE_INIT : Initialization mode
CAN_OPERATING_MODE_NORMAL: Normal mode
CAN_OPERATING_MODE_SLEEP : sleep mode
Return values
modeState:status of the requested mode 0:CAN failed entering the specific mode 1:CAN Succeed entering the specific mode
Note
CAN2 applies only to APM32F103xC device.
Definition at line 663 of file apm32f10x_can.c.
References BIT_RESET, BIT_SET, CAN_OPERATING_MODE_INIT, CAN_OPERATING_MODE_NORMAL, CAN_OPERATING_MODE_SLEEP, CAN_T::INITFLG, CAN_T::INITREQ, CAN_T::MCTRL_B, CAN_T::MSTS_B, CAN_T::SLEEPFLG, and CAN_T::SLEEPREQ.
CAN_PendingMessage()
uint8_t CAN_PendingMessage (CAN_T * can, CAN_RX_FIFO_T FIFONumber)
Returns the number of pending messages.
Parameters
can Select the CAN peripheral.
FIFONumber Receive FIFO number This parameter can be one of the following values:
CAN_RX_FIFO_0 : Receive FIFO 0
CAN_RX_FIFO_1 : Receive FIFO 1
Return values
The number of pending message.
Note
CAN2 applies only to APM32F103xC device.
Definition at line 634 of file apm32f10x_can.c.
References CAN_RX_FIFO_0, CAN_T::RXF0, and CAN_T::RXF1.
Referenced by CAN_Polling().
CAN_ReadIntFlag()
uint8_t CAN_ReadIntFlag (CAN_T * can, CAN_INT_T flag)
Read whether the specified can interrupt has occurred or not.
Parameters
can Select the CAN peripheral.
flag specifies the CAN interrupt sources This parameter can be one of the following values:
CAN_INT_TXME : Transmit mailbox empty Interrupt
CAN_INT_F0MP : FIFO 0 message pending Interrupt
CAN_INT_F0FULL : FIFO 0 full Interrupt
CAN_INT_F0OVR : FIFO 0 overrun Interrupt
CAN_INT_F1MP : FIFO 1 message pending Interrupt
CAN_INT_F1FULL : FIFO 1 full Interrupt
CAN_INT_F1OVR : FIFO 1 overrun Interrupt
CAN_INT_ERRW : Error warning Interrupt
CAN_INT_ERRP : Error passive Interrupt
CAN_INT_BOF : Bus-off Interrupt
CAN_INT_LEC : Last error record code Interrupt
CAN_INT_ERR : Error Interrupt
CAN_INT_WUP : Wake-up Interrupt
CAN_INT_SLEEP : Sleep acknowledge Interrupt
Return values
status : SET or RESET
Note
CAN2 applies only to APM32F103xC device.
Definition at line 1039 of file apm32f10x_can.c.
References CAN_T::BOFLG, CAN_INT_BOF, CAN_INT_ERR, CAN_INT_ERRP, CAN_INT_ERRW, CAN_INT_F0FULL, CAN_INT_F0MP, CAN_INT_F0OVR, CAN_INT_F1FULL, CAN_INT_F1MP, CAN_INT_F1OVR, CAN_INT_LEC, CAN_INT_SLEEP, CAN_INT_TXME, CAN_INT_WUP, CAN_T::ERRIFLG, CAN_T::ERRPFLG, CAN_T::ERRSTS_B, CAN_T::ERRWFLG, CAN_T::FFULLFLG0, CAN_T::FFULLFLG1, CAN_T::FMNUM0, CAN_T::FMNUM1, CAN_T::FOVRFLG0, CAN_T::FOVRFLG1, CAN_T::INTEN, CAN_T::LERRC, CAN_T::MSTS_B, CAN_T::REQCFLG0, CAN_T::REQCFLG1, CAN_T::REQCFLG2, RESET, CAN_T::RXF0_B, CAN_T::RXF1_B, CAN_T::SLEEPIFLG, CAN_T::TXSTS_B, and CAN_T::WUPIFLG.
CAN_ReadLastErrorCode()
uint8_t CAN_ReadLastErrorCode (CAN_T * can)
Read the can's last error code (LERRC)
Parameters
can Select the CAN peripheral.
Return values
The Last Error Code.
Note
CAN2 applies only to APM32F103xC device.
Definition at line 776 of file apm32f10x_can.c.
References CAN_T::ERRSTS_B, and CAN_T::LERRC.
CAN_ReadLSBTxErrorCounter()
uint8_t CAN_ReadLSBTxErrorCounter (CAN_T * can)
Read the LSB of the 9-bit can Transmit Error Counter(TXERRCNT).
Parameters
can Select the CAN peripheral.
Return values
Least Significant Byte Of The 9-Bit Transmit Error Counter.
Note
CAN2 applies only to APM32F103xC device.
Definition at line 804 of file apm32f10x_can.c.
References CAN_T::ERRSTS_B, and CAN_T::TXERRCNT.
CAN_ReadRxErrorCounter()
uint8_t CAN_ReadRxErrorCounter (CAN_T * can)
Read the can Receive Error Counter(RXERRCNT)
Parameters
can Select the CAN peripheral.
Return values
CAN Receive Error Counter.
Note
CAN2 applies only to APM32F103xC device.
Definition at line 790 of file apm32f10x_can.c.
References CAN_T::ERRSTS_B, and CAN_T::RXERRCNT.
CAN_ReadStatusFlag()
uint8_t CAN_ReadStatusFlag (CAN_T * can, CAN_FLAG_T flag)
Read whether the specified CAN flag is set or not.
Parameters
can Select the CAN peripheral.
flag specifies the CAN flag. This parameter can be one of the following values:
CAN_FLAG_ERRW : Error Warning Flag
CAN_FLAG_ERRP : Error Passive Flag
CAN_FLAG_BOF : Bus-Off Flag
CAN_FLAG_LERRC : Last error record code Flag
CAN_FLAG_WUPI : Wake up Flag
CAN_FLAG_SLEEP : Sleep acknowledge Flag
CAN_FLAG_F0MP : FIFO 0 Message Pending Flag
CAN_FLAG_F0FULL : FIFO 0 Full Flag
CAN_FLAG_F0OVR : FIFO 0 Overrun Flag
CAN_FLAG_F1MP : FIFO 1 Message Pending Flag
CAN_FLAG_F1FULL : FIFO 1 Full Flag
CAN_FLAG_F1OVR : FIFO 1 Overrun Flag
CAN_FLAG_REQC0 : Request MailBox0 Flag
CAN_FLAG_REQC1 : Request MailBox1 Flag
CAN_FLAG_REQC2 : Request MailBox2 Flag
Return values
flag staus: RESET or SET
Note
CAN2 applies only to APM32F103xC device.
Definition at line 898 of file apm32f10x_can.c.
References CAN_T::ERRSTS, CAN_T::MSTS, RESET, CAN_T::RXF0, CAN_T::RXF1, SET, and CAN_T::TXSTS.
CAN_ReleaseFIFO()
void CAN_ReleaseFIFO (CAN_T * can, CAN_RX_FIFO_T FIFONumber)
Releases the specified FIFO.
Parameters
can Select the CAN peripheral.
FIFONumber Receive FIFO number This parameter can be one of the following values:
CAN_RX_FIFO_0 : Receive FIFO 0
CAN_RX_FIFO_1 : Receive FIFO 1
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 608 of file apm32f10x_can.c.
References BIT_SET, CAN_RX_FIFO_0, CAN_T::RFOM0, CAN_T::RFOM1, CAN_T::RXF0_B, and CAN_T::RXF1_B.
CAN_Reset()
void CAN_Reset (CAN_T * can)
Reset CAN registers.
Parameters
can Select the CAN peripheral.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 51 of file apm32f10x_can.c.
References CAN1, CAN2, RCM_APB1_PERIPH_CAN1, RCM_APB1_PERIPH_CAN2, RCM_DisableAPB1PeriphReset(), and RCM_EnableAPB1PeriphReset().
Referenced by CAN_Config_Init(), CAN_Interrupt(), and CAN_Polling().
CAN_RxMessage()
void CAN_RxMessage (CAN_T * can, CAN_RX_FIFO_T FIFONumber, CAN_RxMessage_T * RxMessage)
Receives a message and save to a CAN_RxMessage_T structure.
Parameters
can Select the CAN peripheral.
FIFONumber Receive FIFO number. This parameter can be one of the following values:
CAN_RX_FIFO_0 : Receive FIFO 0
CAN_RX_FIFO_1 : Receive FIFO 1
RxMessage pointer to a structure to receive the message.
Return values
None
Note
CAN2 applies only to APM32F103xC device.
Definition at line 558 of file apm32f10x_can.c.
References BIT_SET, CAN_RX_FIFO_0, CAN_TYPEID_STD, CAN_RxMessage_T::data, CAN_RxMailBox_T::DATABYTE0, CAN_RxMailBox_T::DATABYTE1, CAN_RxMailBox_T::DATABYTE2, CAN_RxMailBox_T::DATABYTE3, CAN_RxMailBox_T::DATABYTE4, CAN_RxMailBox_T::DATABYTE5, CAN_RxMailBox_T::DATABYTE6, CAN_RxMailBox_T::DATABYTE7, CAN_RxMessage_T::dataLengthCode, CAN_RxMailBox_T::DLCODE, CAN_RxMessage_T::extID, CAN_RxMessage_T::filterMatchIndex, CAN_RxMailBox_T::FMIDX, CAN_RxMessage_T::remoteTxReq, CAN_T::RFOM0, CAN_T::RFOM1, CAN_RxMailBox_T::RFTXREQ, CAN_RxMailBox_T::RXDLEN_B, CAN_T::RXF0_B, CAN_T::RXF1_B, CAN_RxMailBox_T::RXMDH_B, CAN_RxMailBox_T::RXMDL_B, RxMessage, CAN_RxMailBox_T::RXMID, CAN_RxMailBox_T::RXMID_B, CAN_T::sRxMailBox, CAN_RxMessage_T::stdID, and CAN_RxMessage_T::typeID.
Referenced by CAN1_RX0_ISR(), CAN2_RX0_ISR(), CAN_Polling(), and USBD1_LP_CAN1_RX0_IRQHandler().
CAN_SleepMode()
uint8_t CAN_SleepMode (CAN_T * can)
Into the low power mode.
Parameters
can Select the CAN peripheral.
Return values
status Status of entering sleep mode. 0: Enter sleep fail 1: Enter sleep success
Note
CAN2 applies only to APM32F103xC device.
Definition at line 728 of file apm32f10x_can.c.
References BIT_RESET, BIT_SET, CAN_T::INITFLG, CAN_T::INITREQ, CAN_T::MCTRL_B, CAN_T::MSTS_B, CAN_T::SLEEPFLG, and CAN_T::SLEEPREQ.
CAN_TxMessage()
uint8_t CAN_TxMessage (CAN_T * can, CAN_TxMessage_T * TxMessage)
Initiates the transmission of a message.
Parameters
can Select the CAN peripheral.
TxMessage pointer to a CAN_TxMessage_T structure.
Return values
The number of the mailbox which is used for transmission or 3 if No mailbox is empty.
Note
CAN2 applies only to APM32F103xC device.
< No mailbox is empty
Definition at line 395 of file apm32f10x_can.c.
References CAN_TYPEID_STD, CAN_TxMessage_T::data, CAN_TxMessage_T::dataLengthCode, CAN_TxMessage_T::extID, CAN_TxMessage_T::remoteTxReq, CAN_TxMessage_T::stdID, CAN_T::sTxMailBox, CAN_TxMailBox_T::TXDLEN, CAN_TxMailBox_T::TXMDH, CAN_TxMailBox_T::TXMDL, TxMessage, CAN_TxMailBox_T::TXMID, CAN_T::TXSTS, and CAN_TxMessage_T::typeID.
Referenced by CAN_Interrupt(), CAN_Polling(), and main().
CAN_TxMessageStatus()
uint8_t CAN_TxMessageStatus (CAN_T * can, CAN_TX_MAILBIX_T TxMailbox)
Checks the transmission of a message.
Parameters
can Select the CAN peripheral.
transmitMailbox the number of the mailbox
Return values
state 0: Status of transmission is Failed 1: Status of transmission is Ok 2: transmit pending
Note
CAN2 applies only to APM32F103xC device.
Definition at line 457 of file apm32f10x_can.c.
References CAN_TX_MAILBIX_0, CAN_TX_MAILBIX_1, CAN_TX_MAILBIX_2, and CAN_T::TXSTS.
Referenced by CAN_Polling().
CAN_WakeUpMode()
uint8_t CAN_WakeUpMode (CAN_T * can)
Wakes the CAN up.
Parameters
can Select the CAN peripheral.
Return values
status Status of waking the CAN up 0: WakeUp CAN fail, 1: WakeUp CAN success
Note
CAN2 applies only to APM32F103xC device.
Definition at line 751 of file apm32f10x_can.c.
References BIT_RESET, CAN_T::MCTRL_B, CAN_T::MSTS_B, CAN_T::SLEEPFLG, and CAN_T::SLEEPREQ.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU