APM32F10x_SDK: Functions
Functions
Examples » USB_HID_Mouse
Functions
void USBD_HardWareInit (void)
void HidMouse_Init (void)
HID mouse init.
void HidMouse_Proc (void)
Mouse process.
void HidMouse_SetConfigCallBack (void)
Standard request set configuration call back.
int main (void)
Main program.
void HidMouse_Reset (void)
Reset.
void HidMouse_EPHandler (uint8_t ep)
Endpoint handler.
void HidMouse_GPIOInit (void)
GPIO init.
void HidMouse_Write (uint8_t key)
Mouse write.
void HidMouse_ReportDescriptor (USBD_DevReqData_T *reqData)
Standard request Report HID Descriptor.
uint8_t HidMouse_ReadKey (void)
Read key.
Detailed Description
Function Documentation
HidMouse_EPHandler()
void HidMouse_EPHandler (uint8_t ep)
Endpoint handler.
Parameters
ep Endpoint number
dir Direction.0: Out; 1: In
Return values
None
Definition at line 101 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
Referenced by HidMouse_Init().
HidMouse_GPIOInit()
void HidMouse_GPIOInit (void)
GPIO init.
Parameters
None
Return values
None
Definition at line 125 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References GPIO_Config(), GPIO_MODE_IN_PU, GPIO_PIN_0, GPIO_PIN_1, GPIO_SPEED_50MHz, GPIOA, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by HidMouse_Init().
HidMouse_Init()
void HidMouse_Init (void)
HID mouse init.
Parameters
None
Return values
None
Definition at line 271 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_stringDescriptor, HidMouse_EPHandler(), HidMouse_GPIOInit(), HidMouse_ReportDescriptor(), HidMouse_Reset(), USBD_InitParam_T::inEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, USBD_InitParam_T::resetHandler, s_stdCallback, USBD_InitParam_T::stdReqExceptionHandler, USBD_ClassHandler(), USBD_Init(), and USBD_InitParamStructInit().
Referenced by main().
HidMouse_Proc()
void HidMouse_Proc (void)
Mouse process.
Parameters
None
Return values
None
Definition at line 245 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References HID_MOUSE_KEY_NULL, HidMouse_ReadKey(), and HidMouse_Write().
Referenced by main().
HidMouse_ReadKey()
uint8_t HidMouse_ReadKey (void)
Read key.
Parameters
None
Return values
None
Definition at line 221 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References GPIO_PIN_0, GPIO_PIN_1, GPIO_ReadInputBit(), GPIOA, HID_MOUSE_KEY_LEFT, HID_MOUSE_KEY_NULL, and HID_MOUSE_KEY_RIGHT.
Referenced by HidMouse_Proc().
HidMouse_ReportDescriptor()
void HidMouse_ReportDescriptor (USBD_DevReqData_T * reqData)
Standard request Report HID Descriptor.
Parameters
reqData Standard request data
Return values
None
Definition at line 189 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, USBD_DevReqData_T::bRequest, USBD_DevReqData_T::byte, g_configDescriptor, g_ReportDescriptor, USBD_Descriptor_T::pDesc, USBD_REQ_TYPE_T::recipient, USBD_Descriptor_T::size, USBD_REQ_TYPE_T::type, USB_MIN, USBD_CtrlInData(), USBD_EP_0, USBD_EP_STATUS_STALL, USBD_GET_DESCRIPTOR, USBD_RECIPIENT_INTERFACE, USBD_REQ_TYPE_STANDARD, USBD_SetEPTxRxStatus(), USBD_DevReqData_T::wLength, and USBD_DevReqData_T::wValue.
Referenced by HidMouse_Init().
HidMouse_Reset()
void HidMouse_Reset (void)
Reset.
Parameters
None
Return values
None
Definition at line 75 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References USBD_EPConfig_T::epBufAddr, USBD_EPConfig_T::epNum, USBD_EPConfig_T::epStatus, USBD_EPConfig_T::epType, USBD_EPConfig_T::maxPackSize, USB_EP1_TX_ADDR, USBD_EP_1, USBD_EP_STATUS_DISABLE, USBD_EP_STATUS_NAK, USBD_EP_TYPE_INTERRUPT, USBD_OpenInEP(), and USBD_SetEPRxStatus().
Referenced by HidMouse_Init().
HidMouse_SetConfigCallBack()
void HidMouse_SetConfigCallBack (void)
Standard request set configuration call back.
Parameters
None
Return values
None
Definition at line 113 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
HidMouse_Write()
void HidMouse_Write (uint8_t key)
Mouse write.
Parameters
key Mouse key
Return values
None
Definition at line 146 of file USB/USB_HID_Mouse/Source/usbd_hid.c.
References HID_MOUSE_KEY_DOWN, HID_MOUSE_KEY_LEFT, HID_MOUSE_KEY_RIGHT, HID_MOUSE_KEY_UP, USBD_EP_1, USBD_TxData(), x, and y.
Referenced by HidMouse_Proc().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 50 of file USB/USB_HID_Mouse/Source/main.c.
References HidMouse_Init(), and HidMouse_Proc().
USBD_HardWareInit()
void USBD_HardWareInit (void)
Definition at line 41 of file USB_HID_Mouse/Source/usb_bsp.c.
References EINT_Config(), EINT_LINE_18, EINT_MODE_INTERRUPT, EINT_TRIGGER_RISING, ENABLE, EINT_Config_T::line, EINT_Config_T::lineCmd, EINT_Config_T::mode, NVIC_EnableIRQRequest(), RCM_APB1_PERIPH_USB, RCM_ConfigUSBCLK(), RCM_EnableAPB1PeriphClock(), RCM_USB_DIV_1_5, and EINT_Config_T::trigger.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU