APM32F10x_SDK: Functions
Functions
Examples » FPU_Math
Functions
float sc_math_dot (float *x, float *y, unsigned char n)
float sc_math_sin (float x)
float sc_math_cos (float x)
float sc_math_tan (float x)
float sc_math_asin (float x)
float sc_math_acos (float x)
float sc_math_atan (float x)
float sc_math_atan2 (float y, float x)
float sc_math_invsqrt (float x)
float sc_math_mac (float x, float y, float z)
float sc_math_sum_N (float *x, unsigned char n)
float sc_math_sub_N (float *x, unsigned char n)
float sc_math_prdct (float *x, unsigned char n)
float sc_math_sumsq (float *x, unsigned char n)
int main (void)
Main program.
void USART_Init (void)
USART configs.
Detailed Description
Function Documentation
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 69 of file FPU/FPU_Math/Source/main.c.
References a, ans, b, USART_Config_T::baudRate, BIT27, databuff, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_PIN_9, GPIO_SPEED_50MHz, GPIOA, USART_Config_T::hardwareFlow, GPIO_Config_T::mode, USART_Config_T::mode, USART_Config_T::parity, PI, GPIO_Config_T::pin, RCM, RCM_AHB_PERIPH_FPU, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_USART1, RCM_EnableAHBPeriphClock(), RCM_EnableAPB2PeriphClock(), s, sc_math_acos(), sc_math_asin(), sc_math_atan(), sc_math_atan2(), sc_math_cos(), sc_math_invsqrt(), sc_math_mac(), sc_math_prdct(), sc_math_sin(), sc_math_sub_N(), sc_math_sum_N(), sc_math_sumsq(), sc_math_tan(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART1, USART_Config(), USART_Enable(), USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, USART_Config_T::wordLength, X, x, y, and z.
sc_math_acos()
float sc_math_acos (float x) extern
Referenced by main().
sc_math_asin()
float sc_math_asin (float x) extern
Referenced by main().
sc_math_atan()
float sc_math_atan (float x) extern
Referenced by main().
sc_math_atan2()
float sc_math_atan2 (float y, float x) extern
Referenced by main().
sc_math_cos()
float sc_math_cos (float x) extern
Referenced by main().
sc_math_dot()
float sc_math_dot (float * x, float * y, unsigned char n) extern
sc_math_invsqrt()
float sc_math_invsqrt (float x) extern
Referenced by main().
sc_math_mac()
float sc_math_mac (float x, float y, float z) extern
Referenced by main().
sc_math_prdct()
float sc_math_prdct (float * x, unsigned char n) extern
Referenced by main().
sc_math_sin()
float sc_math_sin (float x) extern
Referenced by main().
sc_math_sub_N()
float sc_math_sub_N (float * x, unsigned char n) extern
Referenced by main().
sc_math_sum_N()
float sc_math_sum_N (float * x, unsigned char n) extern
Referenced by main().
sc_math_sumsq()
float sc_math_sumsq (float * x, unsigned char n) extern
Referenced by main().
sc_math_tan()
float sc_math_tan (float x) extern
Referenced by main().
USART_Init()
void USART_Init (void)
USART configs.
Parameters
None
Return values
None
Definition at line 491 of file FPU/FPU_Math/Source/main.c.
References APM_MINI_COMInit(), USART_Config_T::baudRate, COM1, USART_Config_T::hardwareFlow, USART_Config_T::mode, USART_Config_T::parity, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, and USART_Config_T::wordLength.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU