APM32F10x_SDK: Functions
Functions
Examples » CAN_LoopBack
Functions
void NVIC_Configuration (void)
Configures NVIC and Vector Table base location.
uint8_t CAN_Polling (void)
Configures the CAN, transmit and receive by polling.
uint8_t CAN_Interrupt (void)
Configures the CAN, transmit and receive using interrupt.
int main (void)
Main program.
Detailed Description
Function Documentation
CAN_Interrupt()
uint8_t CAN_Interrupt (void)
Configures the CAN, transmit and receive using interrupt.
Parameters
None
Return values
PASSED if the reception is well done, FAILED in other case
Definition at line 218 of file CAN/CAN_LoopBack/Source/main.c.
References CAN_Config_T::autoBusOffManage, CAN_Config_T::autoWakeUpMode, CAN_Config(), CAN_ConfigFilter(), CAN_ConfigStructInit(), CAN_DisableInterrupt(), CAN_EnableInterrupt(), CAN_FILTER_FIFO_0, CAN_FILTER_MODE_IDMASK, CAN_FILTER_SCALE_32BIT, CAN_INT_F0MP, CAN_MODE_LOOPBACK, CAN_Reset(), CAN_RTXR_DATA, CAN_SJW_1, CAN_TIME_SEGMENT1_2, CAN_TIME_SEGMENT2_3, CAN_TxMessage(), CAN_TYPEID_EXT, CANx, CAN_TxMessage_T::data, CAN_TxMessage_T::dataLengthCode, DISABLE, ENABLE, CAN_TxMessage_T::extID, CAN_FilterConfig_T::filterActivation, CAN_FilterConfig_T::filterFIFO, CAN_FilterConfig_T::filterIdHigh, CAN_FilterConfig_T::filterIdLow, CAN_FilterConfig_T::filterMaskIdHigh, CAN_FilterConfig_T::filterMaskIdLow, CAN_FilterConfig_T::filterMode, CAN_FilterConfig_T::filterNumber, CAN_FilterConfig_T::filterScale, intFlag, CAN_Config_T::mode, CAN_Config_T::nonAutoRetran, CAN_Config_T::prescaler, CAN_TxMessage_T::remoteTxReq, CAN_Config_T::rxFIFOLockMode, CAN_TxMessage_T::stdID, CAN_Config_T::syncJumpWidth, CAN_Config_T::timeSegment1, CAN_Config_T::timeSegment2, CAN_Config_T::txFIFOPriority, TxMessage, and CAN_TxMessage_T::typeID.
Referenced by main().
CAN_Polling()
uint8_t CAN_Polling (void)
Configures the CAN, transmit and receive by polling.
Parameters
None
Return values
PASSED if the reception is well done, FAILED in other case
Definition at line 118 of file CAN/CAN_LoopBack/Source/main.c.
References CAN_Config_T::autoBusOffManage, CAN_Config_T::autoWakeUpMode, CAN_Config(), CAN_ConfigFilter(), CAN_ConfigStructInit(), CAN_FILTER_FIFO_0, CAN_FILTER_MODE_IDMASK, CAN_FILTER_SCALE_32BIT, CAN_MODE_LOOPBACK, CAN_PendingMessage(), CAN_Reset(), CAN_RTXR_DATA, CAN_RX_FIFO_0, CAN_RxMessage(), CAN_SJW_1, CAN_TIME_SEGMENT1_2, CAN_TIME_SEGMENT2_3, CAN_TX_MAILBIX_1, CAN_TxMessage(), CAN_TxMessageStatus(), CAN_TYPEID_STD, CANx, CAN_TxMessage_T::data, CAN_RxMessage_T::data, CAN_TxMessage_T::dataLengthCode, CAN_RxMessage_T::dataLengthCode, DISABLE, ENABLE, FAILED, CAN_FilterConfig_T::filterActivation, CAN_FilterConfig_T::filterFIFO, CAN_FilterConfig_T::filterIdHigh, CAN_FilterConfig_T::filterIdLow, CAN_FilterConfig_T::filterMaskIdHigh, CAN_FilterConfig_T::filterMaskIdLow, CAN_FilterConfig_T::filterMode, CAN_FilterConfig_T::filterNumber, CAN_FilterConfig_T::filterScale, CAN_Config_T::mode, CAN_Config_T::nonAutoRetran, PASSED, CAN_Config_T::prescaler, CAN_TxMessage_T::remoteTxReq, CAN_Config_T::rxFIFOLockMode, RxMessage, CAN_TxMessage_T::stdID, CAN_RxMessage_T::stdID, CAN_Config_T::syncJumpWidth, CAN_Config_T::timeSegment1, CAN_Config_T::timeSegment2, CAN_Config_T::txFIFOPriority, TxMessage, CAN_TxMessage_T::typeID, and CAN_RxMessage_T::typeID.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 65 of file CAN/CAN_LoopBack/Source/main.c.
References APM_MINI_LEDInit(), APM_MINI_LEDOff(), APM_MINI_LEDOn(), CAN_Interrupt(), CAN_Polling(), FAILED, LED2, LED3, NVIC_Configuration(), RCM_APB1_PERIPH_CAN1, and RCM_EnableAPB1PeriphClock().
NVIC_Configuration()
void NVIC_Configuration (void)
Configures NVIC and Vector Table base location.
Parameters
None
Return values
None
Definition at line 298 of file CAN/CAN_LoopBack/Source/main.c.
References NVIC_EnableIRQRequest().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU