APM32F10x_SDK: Functions
Functions
APM32F10x_StdPeriphDriver » RCM Driver
Functions
void RCM_Reset (void)
Reset the clock configuration to the default state.
void RCM_ConfigHSE (RCM_HSE_T state)
Configures the HSE oscillator.
uint8_t RCM_WaitHSEReady (void)
Wait for HSE to be ready.
void RCM_ConfigHSITrim (uint8_t HSITrim)
Configures HSI trimming value.
void RCM_EnableHSI (void)
Enable the HSI.
void RCM_DisableHSI (void)
Disable the HSI.
void RCM_ConfigLSE (RCM_LSE_T state)
Configures the External Low Speed oscillator (LSE)
void RCM_EnableLSI (void)
Enable the Internal Low Speed oscillator (LSI)
void RCM_DisableLSI (void)
Disable the Internal Low Speed oscillator (LSI)
void RCM_ConfigPLL (RCM_PLLSEL_T pllSelect, RCM_PLLMF_T pllMf)
Configures the PLL clock source and multiplication factor.
void RCM_EnablePLL (void)
Enable the PLL.
void RCM_DisablePLL (void)
Disable the PLL.
void RCM_EnableCSS (void)
Enable the Clock Security System.
void RCM_DisableCSS (void)
Disable the Clock Security System.
void RCM_ConfigMCO (RCM_MCOCLK_T mcoClock)
Select the MCO pin clock output source.
void RCM_ConfigSYSCLK (RCM_SYSCLK_SEL_T sysClkSelect)
Configures the system clock source.
RCM_SYSCLK_SEL_T RCM_ReadSYSCLKSource (void)
Return the clock source which is used as system clock.
void RCM_ConfigAHB (RCM_AHB_DIV_T AHBDiv)
Configures the AHB clock prescaler.
void RCM_ConfigAPB1 (RCM_APB_DIV_T APB1Div)
Configures the APB1 clock prescaler.
void RCM_ConfigAPB2 (RCM_APB_DIV_T APB2Div)
Configures the APB2 clock prescaler.
void RCM_ConfigUSBCLK (RCM_USB_DIV_T USBDiv)
Configures the USB clock prescaler.
void RCM_ConfigFPUCLK (RCM_FPU_DIV_T FPUDiv)
Configures the FPU clock prescaler.
void RCM_ConfigADCCLK (RCM_PCLK2_DIV_T ADCDiv)
Configures the ADC clock prescaler.
void RCM_ConfigRTCCLK (RCM_RTCCLK_T rtcClkSelect)
Configures the RTC clock source.
void RCM_EnableRTCCLK (void)
Enable the RTC clock.
void RCM_DisableRTCCLK (void)
Disable the RTC clock.
uint32_t RCM_ReadSYSCLKFreq (void)
Read the frequency of SYSCLK.
uint32_t RCM_ReadHCLKFreq (void)
Read the frequency of HCLK(AHB)
void RCM_ReadPCLKFreq (uint32_t *PCLK1, uint32_t *PCLK2)
Read the frequency of PCLK1 And PCLK2.
uint32_t RCM_ReadADCCLKFreq (void)
Read the frequency of ADCCLK.
void RCM_EnableAHBPeriphClock (uint32_t AHBPeriph)
Enable AHB peripheral clock.
void RCM_DisableAHBPeriphClock (uint32_t AHBPeriph)
Disable AHB peripheral clock.
void RCM_EnableAPB2PeriphClock (uint32_t APB2Periph)
Enable the High Speed APB (APB2) peripheral clock.
void RCM_DisableAPB2PeriphClock (uint32_t APB2Periph)
Disable the High Speed APB (APB2) peripheral clock.
void RCM_EnableAPB1PeriphClock (uint32_t APB1Periph)
Enable the Low Speed APB (APB1) peripheral clock.
void RCM_DisableAPB1PeriphClock (uint32_t APB1Periph)
Disable the Low Speed APB (APB1) peripheral clock.
void RCM_EnableAPB2PeriphReset (uint32_t APB2Periph)
Enable High Speed APB (APB2) peripheral reset.
void RCM_DisableAPB2PeriphReset (uint32_t APB2Periph)
Disable High Speed APB (APB2) peripheral reset.
void RCM_EnableAPB1PeriphReset (uint32_t APB1Periph)
Enable Low Speed APB (APB1) peripheral reset.
void RCM_DisableAPB1PeriphReset (uint32_t APB1Periph)
Disable Low Speed APB (APB1) peripheral reset.
void RCM_EnableBackupReset (void)
Enable the Backup domain reset.
void RCM_DisableBackupReset (void)
Disable the Backup domain reset.
void RCM_EnableInterrupt (uint32_t interrupt)
Enable RCM interrupts.
void RCM_DisableInterrupt (uint32_t interrupt)
Disable RCM interrupts.
uint8_t RCM_ReadStatusFlag (RCM_FLAG_T flag)
Read the specified RCM flag status.
void RCM_ClearStatusFlag (void)
Clear all the RCM reset flags.
uint8_t RCM_ReadIntFlag (RCM_INT_T flag)
Read the specified RCM interrupt Flag.
void RCM_ClearIntFlag (uint32_t flag)
Clear the interrupt flag.
Detailed Description
Function Documentation
RCM_ClearIntFlag()
void RCM_ClearIntFlag (uint32_t flag)
Clear the interrupt flag.
Parameters
flag : Clear specifies interrupt flag.
RCM_INT_LSIRDY : Clear LSI ready interrupt flag
RCM_INT_LSERDY : Clear LSE ready interrupt flag
RCM_INT_HSIRDY : Clear HSI ready interrupt flag
RCM_INT_HSERDY : Clear HSE ready interrupt flag
RCM_INT_PLLRDY : Clear PLL ready interrupt flag
RCM_INT_PLL2RDY: Clear PLL2 ready interrupt flag
RCM_INT_PLL3RDY: Clear PLL3 ready interrupt flag
RCM_INT_CSS : Clear Clock Security System interrupt flag
Return values
None
Definition at line 1367 of file apm32f10x_rcm.c.
References RCM.
RCM_ClearStatusFlag()
void RCM_ClearStatusFlag (void)
Clear all the RCM reset flags.
Parameters
None
Return values
None
Note
The reset flags are: RCM_FLAG_PINRST, RCM_FLAG_PWRST, RCM_FLAG_SWRST RCM_FLAG_IWDTRST, RCM_FLAG_WWDTRST, RCM_FLAG_LPRRST
Definition at line 1326 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by main().
RCM_ConfigADCCLK()
void RCM_ConfigADCCLK (RCM_PCLK2_DIV_T ADCDiv)
Configures the ADC clock prescaler.
Parameters
ADCDiv : Specifies the ADC clock prescaler from the APB2 clock. This parameter can be one of the following values:
RCM_PCLK2_DIV_2: ADCCLK = PCLK2 / 2
RCM_PCLK2_DIV_4: ADCCLK = PCLK2 / 4
RCM_PCLK2_DIV_6: ADCCLK = PCLK2 / 6
RCM_PCLK2_DIV_8: ADCCLK = PCLK2 / 8
Return values
None
Definition at line 639 of file apm32f10x_rcm.c.
References RCM.
Referenced by ADC_Init(), and RCM_Configuration().
RCM_ConfigAHB()
void RCM_ConfigAHB (RCM_AHB_DIV_T AHBDiv)
Configures the AHB clock prescaler.
Parameters
AHBDiv : Specifies the AHB clock prescaler from the system clock. This parameter can be one of the following values:
RCM_AHB_DIV_1 : HCLK = SYSCLK
RCM_AHB_DIV_2 : HCLK = SYSCLK / 2
RCM_AHB_DIV_4 : HCLK = SYSCLK / 4
RCM_AHB_DIV_8 : HCLK = SYSCLK / 8
RCM_AHB_DIV_16 : HCLK = SYSCLK / 16
RCM_AHB_DIV_64 : HCLK = SYSCLK / 64
RCM_AHB_DIV_128 : HCLK = SYSCLK / 128
RCM_AHB_DIV_256 : HCLK = SYSCLK / 256
RCM_AHB_DIV_512 : HCLK = SYSCLK / 512
Return values
None
Definition at line 502 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigAPB1()
void RCM_ConfigAPB1 (RCM_APB_DIV_T APB1Div)
Configures the APB1 clock prescaler.
Parameters
APB1Div Specifies the APB1 clock prescaler from the AHB clock. This parameter can be one of the following values:
RCM_APB_DIV_1 : PCLK1 = HCLK
RCM_APB_DIV_2 : PCLK1 = HCLK / 2
RCM_APB_DIV_4 : PCLK1 = HCLK / 4
RCM_APB_DIV_8 : PCLK1 = HCLK / 8
RCM_APB_DIV_16 : PCLK1 = HCLK / 16
Return values
None
Definition at line 520 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigAPB2()
void RCM_ConfigAPB2 (RCM_APB_DIV_T APB2Div)
Configures the APB2 clock prescaler.
Parameters
APB2Div Specifies the APB2 clock prescaler from the AHB clock. This parameter can be one of the following values:
RCM_APB_DIV_1 : PCLK2 = HCLK
RCM_APB_DIV_2 : PCLK2 = HCLK / 2
RCM_APB_DIV_4 : PCLK2 = HCLK / 4
RCM_APB_DIV_8 : PCLK2 = HCLK / 8
RCM_APB_DIV_16 : PCLK2 = HCLK / 16
Return values
None
Definition at line 538 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigFPUCLK()
void RCM_ConfigFPUCLK (RCM_FPU_DIV_T FPUDiv)
Configures the FPU clock prescaler.
Parameters
FPUDiv Specifies the FPU clock prescaler from the AHB clock. This parameter can be one of the following values:
RCM_FPU_DIV_1 : FPUCLK = HCLK
RCM_FPU_DIV_2 : FPUCLK = HCLK /2
Return values
None
Definition at line 620 of file apm32f10x_rcm.c.
References RCM.
RCM_ConfigHSE()
void RCM_ConfigHSE (RCM_HSE_T state)
Configures the HSE oscillator.
Parameters
state state of the HSE This parameter can be one of the following values:
RCM_HSE_CLOSE: Turn off the HSE oscillator
RCM_HSE_OPEN: Turn on the HSE oscillator
RCM_HSE_BYPASS: HSE oscillator bypassed with external clock
Return values
None
Note
When HSE is not used directly or through the PLL as system clock, it can be stopped.
Definition at line 95 of file apm32f10x_rcm.c.
References BIT_RESET, BIT_SET, RCM, RCM_HSE_BYPASS, and RCM_HSE_OPEN.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigHSITrim()
void RCM_ConfigHSITrim (uint8_t HSITrim)
Configures HSI trimming value.
Parameters
HSITrim HSI trimming value This parameter must be a number between 0 and 0x1F.
Return values
None
Definition at line 145 of file apm32f10x_rcm.c.
References RCM.
RCM_ConfigLSE()
void RCM_ConfigLSE (RCM_LSE_T state)
Configures the External Low Speed oscillator (LSE)
Parameters
state : Specifies the new state of the LSE This parameter can be one of the following values:
RCM_LSE_CLOSE : Close the LSE
RCM_LSE_OPEN : Open the LSE
RCM_LSE_BYPASS : LSE bypass
Return values
None
Definition at line 188 of file apm32f10x_rcm.c.
References BIT_RESET, BIT_SET, RCM, RCM_LSE_BYPASS, and RCM_LSE_OPEN.
Referenced by RTC_Init().
RCM_ConfigMCO()
void RCM_ConfigMCO (RCM_MCOCLK_T mcoClock)
Select the MCO pin clock output source.
Parameters
mcoClock specifies the clock source to output This parameter can be one of the following values:
RCM_MCOCLK_NO_CLOCK : No clock selected.
RCM_MCOCLK_SYSCLK : System clock selected.
RCM_MCOCLK_HSI : HSI oscillator clock selected.
RCM_MCOCLK_HSE : HSE oscillator clock selected.
RCM_MCOCLK_PLLCLK_DIV_2 : PLL clock divided by 2 selected. The following values is only for APM32F105xx or APM32F107xx:
RCM_MCOCLK_PLL2CLK : PLL2 clock selected.
RCM_MCOCLK_PLL3CLK_DIV_2 : PLL3 clock divided by 2 selected.
RCM_MCOCLK_OSCCLK : OSC clock selected.
RCM_MCOCLK_PLL3CLK : PLL3 clock selected.
Return values
None
Definition at line 452 of file apm32f10x_rcm.c.
References RCM.
Referenced by main().
RCM_ConfigPLL()
void RCM_ConfigPLL (RCM_PLLSEL_T pllSelect, RCM_PLLMF_T pllMf)
Configures the PLL clock source and multiplication factor.
Parameters
pllSelect PLL entry clock source select This parameter can be one of the following values: For APM32F105xx and APM32F107xx devices:
RCM_PLLSEL_HSI_DIV_2: HSI clock divided by 2 selected as PLL clock source
RCM_PLLSEL_PREDIV1 : PLL prescaler 1 clock selected as PLL clock source For other devices:
RCM_PLLSEL_HSI_DIV_2: HSI clock divided by 2 selected as PLL clock source
RCM_PLLSEL_HSE : HSE clock selected as PLL clock source
RCM_PLLSEL_HSE_DIV2 : HSE clock divided by 2 selected as PLL clock source
pllMf PLL multiplication factor For APM32F105xx and APM32F107xx devices: This parameter can be one of the following values:
RCM_PLLMF_4 : PLL Multiplication Factor Configures to 4
RCM_PLLMF_5 : PLL Multiplication Factor Configures to 5
RCM_PLLMF_6 : PLL Multiplication Factor Configures to 6
RCM_PLLMF_7 : PLL Multiplication Factor Configures to 7
RCM_PLLMF_8 : PLL Multiplication Factor Configures to 8
RCM_PLLMF_9 : PLL Multiplication Factor Configures to 9
RCM_PLLMF_6_5: PLL Multiplication Factor Configures to 6.5 For other devices: This parameter can be RCM_PLLMF_x where x can be a value from 2 to 16.
Return values
None
Note
PLL should be disabled while use this function.
Definition at line 258 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigRTCCLK()
void RCM_ConfigRTCCLK (RCM_RTCCLK_T rtcClkSelect)
Configures the RTC clock source.
Parameters
rtcClkSelect : specifies the RTC clock source. This parameter can be one of the following values:
RCM_RTCCLK_LSE : RTCCLK = LSE clock
RCM_RTCCLK_LSI : RTCCLK = LSI clock
RCM_RTCCLK_HSE_DIV_128: RTCCLK = HSE clock / 128
Return values
None
Note
Once the RTC clock is configured it can't be changed unless reset the Backup domain.
Definition at line 657 of file apm32f10x_rcm.c.
References RCM.
Referenced by RTC_Config(), and RTC_Init().
RCM_ConfigSYSCLK()
void RCM_ConfigSYSCLK (RCM_SYSCLK_SEL_T sysClkSelect)
Configures the system clock source.
Parameters
sysClkSelect specifies the clock source used as system clock This parameter can be one of the following values:
RCM_SYSCLK_SEL_HSI: HSI is selected as system clock source
RCM_SYSCLK_SEL_HSE: HSE is selected as system clock source
RCM_SYSCLK_SEL_PLL: PLL is selected as system clock source
Return values
None
Definition at line 468 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_ConfigUSBCLK()
void RCM_ConfigUSBCLK (RCM_USB_DIV_T USBDiv)
Configures the USB clock prescaler.
Parameters
USBDiv Specifies the USB clock prescaler from the PLL clock. This parameter can be one of the following values:
RCM_USB_DIV_1_5 : USBCLK = PLL clock /1.5
RCM_USB_DIV_1 : USBCLK = PLL clock
RCM_USB_DIV_2 : USBCLK = PLL clock / 2
RCM_USB_DIV_2_5 : USBCLK = PLL clock / 2.5 (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 605 of file apm32f10x_rcm.c.
References RCM.
Referenced by USBD_HardWareInit().
RCM_DisableAHBPeriphClock()
void RCM_DisableAHBPeriphClock (uint32_t AHBPeriph)
Disable AHB peripheral clock.
Parameters
AHBPeriph : Enable the specifies clock of AHB peripheral. This parameter can be any combination of the following values:
RCM_AHB_PERIPH_DMA1 : Disable DMA1 clock
RCM_AHB_PERIPH_DMA2 : Disable DMA2 clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_SRAM : Disable SRAM clock
RCM_AHB_PERIPH_FPU : Disable FPU clock
RCM_AHB_PERIPH_FMC : Disable FMC clock
RCM_AHB_PERIPH_QSPI : Disable QSPI clock
RCM_AHB_PERIPH_CRC : Disable CRC clock
RCM_AHB_PERIPH_EMMC : Disable EMMC clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_SDIO : Disable SDIO clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_OTG_FS : Disable OTG FS clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC : Disable Ethernet MAC clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC_TX : Disable Ethernet MAC TX clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC_RX : Disable Ethernet MAC RX clock (Only for APM32F105xx or APM32F107xx)
Return values
None
Definition at line 906 of file apm32f10x_rcm.c.
References RCM.
RCM_DisableAPB1PeriphClock()
void RCM_DisableAPB1PeriphClock (uint32_t APB1Periph)
Disable the Low Speed APB (APB1) peripheral clock.
Parameters
APB1Periph : Disable specifies clock of the APB1 peripheral. This parameter can be any combination of the following values:
RCM_APB1_PERIPH_TMR2 : Disable TMR2 clock
RCM_APB1_PERIPH_TMR3 : Disable TMR3 clock
RCM_APB1_PERIPH_TMR4 : Disable TMR4 clock
RCM_APB1_PERIPH_TMR5 : Disable TMR5 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR6 : Disable TMR6 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR7 : Disable TMR7 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_WWDT : Disable WWDT clock
RCM_APB1_PERIPH_SPI2 : Disable SPI2 clock
RCM_APB1_PERIPH_SPI3 : Disable SPI3 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_USART2 : Disable USART2 clock
RCM_APB1_PERIPH_USART3 : Disable USART3 clock
RCM_APB1_PERIPH_UART4 : Disable UART4 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_UART5 : Disable UART5 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_I2C1 : Disable I2C1 clock
RCM_APB1_PERIPH_I2C2 : Disable I2C2 clock
RCM_APB1_PERIPH_USB : Disable USB clock
RCM_APB1_PERIPH_CAN1 : Disable CAN1 clock
RCM_APB1_PERIPH_CAN2 : Disable CAN2 clock (only for APM32F103xC device)
RCM_APB1_PERIPH_BAKR : Disable BAKR clock
RCM_APB1_PERIPH_PMU : Disable PMU clock
RCM_APB1_PERIPH_DAC : Disable DAC clock (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 1030 of file apm32f10x_rcm.c.
References RCM.
RCM_DisableAPB1PeriphReset()
void RCM_DisableAPB1PeriphReset (uint32_t APB1Periph)
Disable Low Speed APB (APB1) peripheral reset.
Parameters
APB1Periph : Disable specifies APB1 peripheral reset. This parameter can be any combination of the following values:
RCM_APB1_PERIPH_TMR2 : Disable TMR2 reset
RCM_APB1_PERIPH_TMR3 : Disable TMR3 reset
RCM_APB1_PERIPH_TMR4 : Disable TMR4 reset
RCM_APB1_PERIPH_TMR5 : Disable TMR5 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR6 : Disable TMR6 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR7 : Disable TMR7 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_WWDT : Disable WWDT reset
RCM_APB1_PERIPH_SPI2 : Disable SPI2 reset
RCM_APB1_PERIPH_SPI3 : Disable SPI3 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_USART2 : Disable USART2 reset
RCM_APB1_PERIPH_USART3 : Disable USART3 reset
RCM_APB1_PERIPH_UART4 : Disable UART4 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_UART5 : Disable UART5 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_I2C1 : Disable I2C1 reset
RCM_APB1_PERIPH_I2C2 : Disable I2C2 reset
RCM_APB1_PERIPH_USB : Disable USB reset
RCM_APB1_PERIPH_CAN1 : Disable CAN1 reset
RCM_APB1_PERIPH_CAN2 : Disable CAN2 reset (only for APM32F103xC device)
RCM_APB1_PERIPH_BAKR : Disable BAKR reset
RCM_APB1_PERIPH_PMU : Disable PMU reset
RCM_APB1_PERIPH_DAC : Disable DAC reset
Return values
None
Definition at line 1184 of file apm32f10x_rcm.c.
References RCM.
Referenced by CAN_Reset(), DAC_Reset(), I2C_Reset(), PMU_Reset(), SCI2C_Reset(), SPI_I2S_Reset(), TMR_Reset(), USART_Reset(), and WWDT_Reset().
RCM_DisableAPB2PeriphClock()
void RCM_DisableAPB2PeriphClock (uint32_t APB2Periph)
Disable the High Speed APB (APB2) peripheral clock.
Parameters
APB2Periph : Disable specifies clock of the APB2 peripheral. This parameter can be any combination of the following values:
RCM_APB2_PERIPH_AFIO : Disable AFIO clock
RCM_APB2_PERIPH_GPIOA : Disable GPIOA clock
RCM_APB2_PERIPH_GPIOB : Disable GPIOB clock
RCM_APB2_PERIPH_GPIOC : Disable GPIOC clock
RCM_APB2_PERIPH_GPIOD : Disable GPIOD clock
RCM_APB2_PERIPH_GPIOE : Disable GPIOE clock
RCM_APB2_PERIPH_GPIOF : Disable GPIOF clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_GPIOG : Disable GPIOG clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_ADC1 : Disable ADC1 clock
RCM_APB2_PERIPH_ADC2 : Disable ADC2 clock
RCM_APB2_PERIPH_TMR1 : Disable TMR1 clock
RCM_APB2_PERIPH_SPI1 : Disable SPI1 clock
RCM_APB2_PERIPH_TMR8 : Disable TMR8 clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_USART1 : Disable USART1 clock
RCM_APB2_PERIPH_ADC3 : Disable ADC3 clock (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 962 of file apm32f10x_rcm.c.
References RCM.
RCM_DisableAPB2PeriphReset()
void RCM_DisableAPB2PeriphReset (uint32_t APB2Periph)
Disable High Speed APB (APB2) peripheral reset.
Parameters
APB2Periph : Disable specifies APB2 peripheral reset. This parameter can be any combination of the following values:
RCM_APB2_PERIPH_AFIO : Disable AFIO reset
RCM_APB2_PERIPH_GPIOA : Disable GPIOA reset
RCM_APB2_PERIPH_GPIOB : Disable GPIOB reset
RCM_APB2_PERIPH_GPIOC : Disable GPIOC reset
RCM_APB2_PERIPH_GPIOD : Disable GPIOD reset
RCM_APB2_PERIPH_GPIOE : Disable GPIOE reset
RCM_APB2_PERIPH_GPIOF : Disable GPIOF reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_GPIOG : Disable GPIOG reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_ADC1 : Disable ADC1 reset
RCM_APB2_PERIPH_ADC2 : Disable ADC2 reset
RCM_APB2_PERIPH_TMR1 : Disable TMR1 reset
RCM_APB2_PERIPH_SPI1 : Disable SPI1 reset
RCM_APB2_PERIPH_TMR8 : Disable TMR8 reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_USART1 : Disable USART1 reset
RCM_APB2_PERIPH_ADC3 : Disable ADC3 reset (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 1116 of file apm32f10x_rcm.c.
References RCM.
Referenced by ADC_Reset(), GPIO_AFIOReset(), GPIO_Reset(), SPI_I2S_Reset(), TMR_Reset(), and USART_Reset().
RCM_DisableBackupReset()
void RCM_DisableBackupReset (void)
Disable the Backup domain reset.
Parameters
None
Return values
None
Definition at line 1209 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
Referenced by BAKPR_Reset().
RCM_DisableCSS()
void RCM_DisableCSS (void)
Disable the Clock Security System.
Parameters
None
Return values
None
Definition at line 429 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
RCM_DisableHSI()
void RCM_DisableHSI (void)
Disable the HSI.
Parameters
None
Return values
None
Note
When HSI is not used directly or through the PLL as system clock, it can be stopped.
Definition at line 172 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
RCM_DisableInterrupt()
void RCM_DisableInterrupt (uint32_t interrupt)
Disable RCM interrupts.
Parameters
interrupt : Disable specifies RCM interrupt sources. This parameter can be any combination of the following values:
RCM_INT_LSIRDY : LSI ready interrupt
RCM_INT_LSERDY : LSE ready interrupt
RCM_INT_HSIRDY : HSI ready interrupt
RCM_INT_HSERDY : HSE ready interrupt
RCM_INT_PLLRDY : PLL ready interrupt
Return values
None
Definition at line 1251 of file apm32f10x_rcm.c.
References RCM.
RCM_DisableLSI()
void RCM_DisableLSI (void)
Disable the Internal Low Speed oscillator (LSI)
Parameters
None
Return values
None
Definition at line 223 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
RCM_DisablePLL()
void RCM_DisablePLL (void)
Disable the PLL.
Parameters
None
Return values
None
Note
When PLL is not used as system clock, it can be stopped.
Definition at line 289 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
RCM_DisableRTCCLK()
void RCM_DisableRTCCLK (void)
Disable the RTC clock.
Parameters
None
Return values
None
Definition at line 681 of file apm32f10x_rcm.c.
References BIT_RESET, and RCM.
RCM_EnableAHBPeriphClock()
void RCM_EnableAHBPeriphClock (uint32_t AHBPeriph)
Enable AHB peripheral clock.
Parameters
AHBPeriph : Enable the specifies clock of AHB peripheral. This parameter can be any combination of the following values:
RCM_AHB_PERIPH_DMA1 : Enable DMA1 clock
RCM_AHB_PERIPH_DMA2 : Enable DMA2 clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_SRAM : Enable SRAM clock
RCM_AHB_PERIPH_FPU : Enable FPU clock
RCM_AHB_PERIPH_FMC : Enable FMC clock
RCM_AHB_PERIPH_QSPI : Enable QSPI clock
RCM_AHB_PERIPH_CRC : Enable CRC clock
RCM_AHB_PERIPH_EMMC : Enable EMMC clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_SDIO : Enable SDIO clock (Only for High-density devices for APM32F103xx)
RCM_AHB_PERIPH_OTG_FS : Enable OTG FS clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC : Enable Ethernet MAC clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC_TX : Enable Ethernet MAC TX clock (Only for APM32F105xx or APM32F107xx)
RCM_AHB_PERIPH_ETH_MAC_RX : Enable Ethernet MAC RX clock (Only for APM32F105xx or APM32F107xx)
Return values
None
Definition at line 880 of file apm32f10x_rcm.c.
References RCM.
Referenced by DMA_Init(), DMA_Init(), main(), RCM_Configuration(), USART1_RX_DMA_Init(), and USART2_TX_DMA_Init().
RCM_EnableAPB1PeriphClock()
void RCM_EnableAPB1PeriphClock (uint32_t APB1Periph)
Enable the Low Speed APB (APB1) peripheral clock.
Parameters
APB1Periph : Enable specifies clock of the APB1 peripheral. This parameter can be any combination of the following values:
RCM_APB1_PERIPH_TMR2 : Enable TMR2 clock
RCM_APB1_PERIPH_TMR3 : Enable TMR3 clock
RCM_APB1_PERIPH_TMR4 : Enable TMR4 clock
RCM_APB1_PERIPH_TMR5 : Enable TMR5 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR6 : Enable TMR6 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR7 : Enable TMR7 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_WWDT : Enable WWDT clock
RCM_APB1_PERIPH_SPI2 : Enable SPI2 clock
RCM_APB1_PERIPH_SPI3 : Enable SPI3 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_USART2 : Enable USART2 clock
RCM_APB1_PERIPH_USART3 : Enable USART3 clock
RCM_APB1_PERIPH_UART4 : Enable UART4 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_UART5 : Enable UART5 clock (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_I2C1 : Enable I2C1 clock
RCM_APB1_PERIPH_I2C2 : Enable I2C2 clock
RCM_APB1_PERIPH_USB : Enable USB clock
RCM_APB1_PERIPH_CAN1 : Enable CAN1 clock
RCM_APB1_PERIPH_CAN2 : Enable CAN2 clock (only for APM32F103xC device)
RCM_APB1_PERIPH_BAKR : Enable BAKR clock
RCM_APB1_PERIPH_PMU : Enable PMU clock
RCM_APB1_PERIPH_DAC : Enable DAC clock (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 996 of file apm32f10x_rcm.c.
References RCM.
Referenced by APM_MINI_COMInit(), CAN_Config_Init(), ConfigDelayTimer(), DAC_Init(), I2C_Init(), IrDAInit(), LINInit(), main(), RCM_Configuration(), RTC_Config(), RTC_Init(), SmartcardInit(), and USBD_HardWareInit().
RCM_EnableAPB1PeriphReset()
void RCM_EnableAPB1PeriphReset (uint32_t APB1Periph)
Enable Low Speed APB (APB1) peripheral reset.
Parameters
APB1Periph : Enable specifies APB1 peripheral reset. This parameter can be any combination of the following values:
RCM_APB1_PERIPH_TMR2 : Enable TMR2 reset
RCM_APB1_PERIPH_TMR3 : Enable TMR3 reset
RCM_APB1_PERIPH_TMR4 : Enable TMR4 reset
RCM_APB1_PERIPH_TMR5 : Enable TMR5 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR6 : Enable TMR6 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_TMR7 : Enable TMR7 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_WWDT : Enable WWDT reset
RCM_APB1_PERIPH_SPI2 : Enable SPI2 reset
RCM_APB1_PERIPH_SPI3 : Enable SPI3 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_USART2 : Enable USART2 reset
RCM_APB1_PERIPH_USART3 : Enable USART3 reset
RCM_APB1_PERIPH_UART4 : Enable UART4 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_UART5 : Enable UART5 reset (Only for High-density devices for APM32F103xx)
RCM_APB1_PERIPH_I2C1 : Enable I2C1 reset
RCM_APB1_PERIPH_I2C2 : Enable I2C2 reset
RCM_APB1_PERIPH_USB : Enable USB reset
RCM_APB1_PERIPH_CAN1 : Enable CAN1 reset
RCM_APB1_PERIPH_CAN2 : Enable CAN2 reset (only for APM32F103xC device)
RCM_APB1_PERIPH_BAKR : Enable BAKR reset
RCM_APB1_PERIPH_PMU : Enable PMU reset
RCM_APB1_PERIPH_DAC : Enable DAC reset
Return values
None
Definition at line 1150 of file apm32f10x_rcm.c.
References RCM.
Referenced by CAN_Reset(), DAC_Reset(), I2C_Reset(), PMU_Reset(), SCI2C_Reset(), SPI_I2S_Reset(), TMR_Reset(), USART_Reset(), and WWDT_Reset().
RCM_EnableAPB2PeriphClock()
void RCM_EnableAPB2PeriphClock (uint32_t APB2Periph)
Enable the High Speed APB (APB2) peripheral clock.
Parameters
APB2Periph : Enable specifies clock of the APB2 peripheral. This parameter can be any combination of the following values:
RCM_APB2_PERIPH_AFIO : Enable AFIO clock
RCM_APB2_PERIPH_GPIOA : Enable GPIOA clock
RCM_APB2_PERIPH_GPIOB : Enable GPIOB clock
RCM_APB2_PERIPH_GPIOC : Enable GPIOC clock
RCM_APB2_PERIPH_GPIOD : Enable GPIOD clock
RCM_APB2_PERIPH_GPIOE : Enable GPIOE clock
RCM_APB2_PERIPH_GPIOF : Enable GPIOF clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_GPIOG : Enable GPIOG clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_ADC1 : Enable ADC1 clock
RCM_APB2_PERIPH_ADC2 : Enable ADC2 clock
RCM_APB2_PERIPH_TMR1 : Enable TMR1 clock
RCM_APB2_PERIPH_SPI1 : Enable SPI1 clock
RCM_APB2_PERIPH_TMR8 : Enable TMR8 clock (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_USART1 : Enable USART1 clock
RCM_APB2_PERIPH_ADC3 : Enable ADC3 clock (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 934 of file apm32f10x_rcm.c.
References RCM.
Referenced by ADC_Init(), APM_MINI_COMInit(), APM_MINI_LEDInit(), APM_MINI_PBInit(), CAN_GPIO_Init(), DAC_Init(), GPIO_Init(), HidMouse_GPIOInit(), I2C_Init(), IIC_Init(), IrDAInit(), LINInit(), main(), RCM_Configuration(), SmartcardInit(), SPI_FullDuplex_Init(), USART_FullDuplex_Init(), USART_Init(), and USB_HardwareInit().
RCM_EnableAPB2PeriphReset()
void RCM_EnableAPB2PeriphReset (uint32_t APB2Periph)
Enable High Speed APB (APB2) peripheral reset.
Parameters
APB2Periph : Enable specifies APB2 peripheral reset. This parameter can be any combination of the following values:
RCM_APB2_PERIPH_AFIO : Enable AFIO reset
RCM_APB2_PERIPH_GPIOA : Enable GPIOA reset
RCM_APB2_PERIPH_GPIOB : Enable GPIOB reset
RCM_APB2_PERIPH_GPIOC : Enable GPIOC reset
RCM_APB2_PERIPH_GPIOD : Enable GPIOD reset
RCM_APB2_PERIPH_GPIOE : Enable GPIOE reset
RCM_APB2_PERIPH_GPIOF : Enable GPIOF reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_GPIOG : Enable GPIOG reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_ADC1 : Enable ADC1 reset
RCM_APB2_PERIPH_ADC2 : Enable ADC2 reset
RCM_APB2_PERIPH_TMR1 : Enable TMR1 reset
RCM_APB2_PERIPH_SPI1 : Enable SPI1 reset
RCM_APB2_PERIPH_TMR8 : Enable TMR8 reset (Only for High-density devices for APM32F103xx)
RCM_APB2_PERIPH_USART1 : Enable USART1 reset
RCM_APB2_PERIPH_ADC3 : Enable ADC3 reset (Only for High-density devices for APM32F103xx)
Return values
None
Definition at line 1088 of file apm32f10x_rcm.c.
References RCM.
Referenced by ADC_Reset(), GPIO_AFIOReset(), GPIO_Reset(), SPI_I2S_Reset(), TMR_Reset(), and USART_Reset().
RCM_EnableBackupReset()
void RCM_EnableBackupReset (void)
Enable the Backup domain reset.
Parameters
None
Return values
None
Definition at line 1197 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by BAKPR_Reset().
RCM_EnableCSS()
void RCM_EnableCSS (void)
Enable the Clock Security System.
Parameters
None
Return values
None
Definition at line 417 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by main().
RCM_EnableHSI()
void RCM_EnableHSI (void)
Enable the HSI.
Parameters
None
Return values
None
Definition at line 157 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
RCM_EnableInterrupt()
void RCM_EnableInterrupt (uint32_t interrupt)
Enable RCM interrupts.
Parameters
interrupt : Enable specifies RCM interrupt sources. This parameter can be any combination of the following values:
RCM_INT_LSIRDY : LSI ready interrupt
RCM_INT_LSERDY : LSE ready interrupt
RCM_INT_HSIRDY : HSI ready interrupt
RCM_INT_HSERDY : HSE ready interrupt
RCM_INT_PLLRDY : PLL ready interrupt
RCM_INT_PLL2RDY: PLL2 ready interrupt
RCM_INT_PLL3RDY: PLL3 ready interrupt
Return values
None
Definition at line 1229 of file apm32f10x_rcm.c.
References RCM.
RCM_EnableLSI()
void RCM_EnableLSI (void)
Enable the Internal Low Speed oscillator (LSI)
Parameters
None
Return values
None
Definition at line 211 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by RTC_Config(), and RTC_Init().
RCM_EnablePLL()
void RCM_EnablePLL (void)
Enable the PLL.
Parameters
None
Return values
None
Definition at line 275 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_EnableRTCCLK()
void RCM_EnableRTCCLK (void)
Enable the RTC clock.
Parameters
None
Return values
None
Definition at line 669 of file apm32f10x_rcm.c.
References BIT_SET, and RCM.
Referenced by RTC_Config(), and RTC_Init().
RCM_ReadADCCLKFreq()
uint32_t RCM_ReadADCCLKFreq (void)
Read the frequency of ADCCLK.
Parameters
None
Return values
Return the frequency of ADCCLK
Definition at line 845 of file apm32f10x_rcm.c.
References NULL, RCM, and RCM_ReadPCLKFreq().
RCM_ReadHCLKFreq()
uint32_t RCM_ReadHCLKFreq (void)
Read the frequency of HCLK(AHB)
Parameters
None
Return values
Return the frequency of HCLK
Definition at line 796 of file apm32f10x_rcm.c.
References RCM, and RCM_ReadSYSCLKFreq().
Referenced by RCM_ReadPCLKFreq(), and TMR5_IRQHandler().
RCM_ReadIntFlag()
uint8_t RCM_ReadIntFlag (RCM_INT_T flag)
Read the specified RCM interrupt Flag.
Parameters
flag Reads specifies RCM interrupt flag. This parameter can be one of the following values:
RCM_INT_LSIRDY : LSI ready interrupt flag
RCM_INT_LSERDY : LSE ready interrupt flag
RCM_INT_HSIRDY : HSI ready interrupt flag
RCM_INT_HSERDY : HSE ready interrupt flag
RCM_INT_PLLRDY : PLL ready interrupt flag
RCM_INT_PLL2RDY: PLL2 ready interrupt flag
RCM_INT_PLL3RDY: PLL3 ready interrupt flag
RCM_INT_CSS : Clock Security System interrupt flag
Return values
The new state of intFlag (SET or RESET)
Definition at line 1347 of file apm32f10x_rcm.c.
References RCM, RESET, and SET.
RCM_ReadPCLKFreq()
void RCM_ReadPCLKFreq (uint32_t * PCLK1, uint32_t * PCLK2)
Read the frequency of PCLK1 And PCLK2.
Parameters
PCLK1 : Return the frequency of PCLK1
PCLK1 : Return the frequency of PCLK2
Return values
None
Definition at line 818 of file apm32f10x_rcm.c.
References RCM, and RCM_ReadHCLKFreq().
Referenced by ConfigDelayTimer(), I2C_Config(), RCM_ReadADCCLKFreq(), and USART_Config().
RCM_ReadStatusFlag()
uint8_t RCM_ReadStatusFlag (RCM_FLAG_T flag)
Read the specified RCM flag status.
Parameters
flag : Return specifies the flag status. This parameter can be one of the following values:
RCM_FLAG_HSIRDY : HSI ready flag
RCM_FLAG_HSERDY : HSE ready flag
RCM_FLAG_PLLRDY : PLL ready flag
RCM_FLAG_PLL2RDY : PLL2 ready flag (Only for APM32F105xx or APM32F107xx)
RCM_FLAG_PLL3RDY : PLL3 ready flag (Only for APM32F105xx or APM32F107xx)
RCM_FLAG_LSERDY : LSE ready flag
RCM_FLAG_LSIRDY : LSI ready flag
RCM_FLAG_PINRST : NRST PIN Reset Occur Flag
RCM_FLAG_PORRST : POR/PDR Reset Occur Flag
RCM_FLAG_SWRST : Software Reset Occur Flag
RCM_FLAG_IWDTRST : Independent Watchdog Reset Occur Flag
RCM_FLAG_WWDTRST : Window Watchdog Reset Occur Flag
RCM_FLAG_LPRRST : Low Power Reset Occur Flag
Return values
The new state of flag (SET or RESET)
Definition at line 1281 of file apm32f10x_rcm.c.
References RCM, RESET, and SET.
Referenced by main(), RCM_Configuration(), RTC_Config(), RTC_Init(), and SetSysClock().
RCM_ReadSYSCLKFreq()
uint32_t RCM_ReadSYSCLKFreq (void)
Read the frequency of SYSCLK.
Parameters
None
Return values
Return the frequency of SYSCLK
Definition at line 693 of file apm32f10x_rcm.c.
References BIT_SET, HSE_VALUE, HSI_VALUE, RCM, RCM_SYSCLK_SEL_HSE, RCM_SYSCLK_SEL_HSI, and RCM_SYSCLK_SEL_PLL.
Referenced by I2S_Config(), main(), and RCM_ReadHCLKFreq().
RCM_ReadSYSCLKSource()
RCM_SYSCLK_SEL_T RCM_ReadSYSCLKSource (void)
Return the clock source which is used as system clock.
Parameters
None
Return values
The clock source used as system clock
Definition at line 480 of file apm32f10x_rcm.c.
References RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_Reset()
void RCM_Reset (void)
Reset the clock configuration to the default state.
Parameters
None
Return values
None
Definition at line 48 of file apm32f10x_rcm.c.
References BIT_RESET, BIT_SET, and RCM.
Referenced by RCM_Configuration(), and SetSysClock().
RCM_WaitHSEReady()
uint8_t RCM_WaitHSEReady (void)
Wait for HSE to be ready.
Parameters
None
Return values
SUCCESS HSE oscillator is ready ERROR : HSE oscillator is not ready
Definition at line 122 of file apm32f10x_rcm.c.
References BIT_SET, ERROR, HSE_STARTUP_TIMEOUT, RCM, and SUCCESS.
Referenced by RCM_Configuration(), and SetSysClock().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU