APM32F10x_SDK: Functions
Functions
Examples » TMR_TMR1DMABurst
Functions
void GPIO_Init (void)
GPIO Init.
void DMA_Init (void)
DMA Init.
int main (void)
Main program.
Detailed Description
Function Documentation
DMA_Init()
void DMA_Init (void)
DMA Init.
Parameters
None
Return values
None
Definition at line 150 of file TMR/TMR_TMR1DMABurst/Source/main.c.
References DMA_Config_T::bufferSize, ConfigBuf, DMA_Config_T::dir, DMA1_Channel5, DMA_Config(), DMA_DIR_PERIPHERAL_DST, DMA_Enable(), DMA_M2MEN_DISABLE, DMA_MEMORY_DATA_SIZE_HALFWORD, DMA_MEMORY_INC_ENABLE, DMA_MODE_NORMAL, DMA_PERIPHERAL_DATA_SIZE_HALFWORD, DMA_PERIPHERAL_INC_DISABLE, DMA_PRIORITY_HIGH, DMA_Config_T::loopMode, DMA_Config_T::M2M, DMA_Config_T::memoryBaseAddr, DMA_Config_T::memoryDataSize, DMA_Config_T::memoryInc, DMA_Config_T::peripheralBaseAddr, DMA_Config_T::peripheralDataSize, DMA_Config_T::peripheralInc, DMA_Config_T::priority, RCM_AHB_PERIPH_DMA1, RCM_EnableAHBPeriphClock(), and TMR1.
Referenced by main().
GPIO_Init()
void GPIO_Init (void)
GPIO Init.
Parameters
None
Return values
None
Note
Definition at line 126 of file TMR/TMR_TMR1DMABurst/Source/main.c.
References GPIO_Config(), GPIO_MODE_AF_PP, GPIO_PIN_10, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_8, GPIO_PIN_9, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIO_Config_T::mode, GPIO_Config_T::pin, RCM_APB2_PERIPH_GPIOA, RCM_APB2_PERIPH_GPIOB, RCM_EnableAPB2PeriphClock(), and GPIO_Config_T::speed.
Referenced by main().
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 60 of file TMR/TMR_TMR1DMABurst/Source/main.c.
References TMR_BaseConfig_T::clockDivision, TMR_BaseConfig_T::countMode, TMR_BaseConfig_T::division, DMA_Init(), GPIO_Init(), TMR_OCConfig_T::idleState, TMR_OCConfig_T::mode, TMR_OCConfig_T::nIdleState, TMR_OCConfig_T::nPolarity, TMR_OCConfig_T::outputNState, TMR_OCConfig_T::outputState, TMR_BaseConfig_T::period, TMR_OCConfig_T::polarity, TMR_OCConfig_T::pulse, RCM_APB2_PERIPH_TMR1, RCM_EnableAPB2PeriphClock(), TMR1, TMR_CLOCK_DIV_1, TMR_ConfigDMA(), TMR_ConfigOC1(), TMR_ConfigOC2(), TMR_ConfigOC3(), TMR_ConfigTimeBase(), TMR_COUNTER_MODE_UP, TMR_DMA_BASE_AUTORLD, TMR_DMA_BURSTLENGTH_5TRANSFERS, TMR_DMA_SOURCE_UPDATE, TMR_Enable(), TMR_EnableDMASoure(), TMR_EnablePWMOutputs(), TMR_OC_IDLE_STATE_RESET, TMR_OC_MODE_PWM1, TMR_OC_NIDLE_STATE_RESET, TMR_OC_NPOLARITY_HIGH, TMR_OC_NSTATE_ENABLE, TMR_OC_POLARITY_HIGH, and TMR_OC_STATE_ENABLE.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU