APM32F10x_SDK: Functions
Functions
USB OTG Library » Driver » USB_Host
Functions
uint8_t USB_OTG_ReadPortSpeed (void)
Read Port Speed.
void USB_OTG_PortReset (void)
Reset Host Port.
void USB_OTG_EnableOutChannelTransfer (uint16_t chNum, uint8_t *transferBuff, uint32_t transferLen, uint16_t maxPackSize, uint8_t dataPid, uint8_t epType)
Enable OUT channel to start transfer.
void USB_OTG_EnableInChannelTransfer (uint16_t chNum, uint32_t transferLen, uint16_t maxPackSize, uint8_t dataPid, uint8_t epType)
Enable IN channel to start transfer.
void USB_OTG_HaltChannel (uint16_t chNum)
Halt channel.
void USB_OTG_InitChannel (USB_ChannelConfig_T *channelConfig)
Init channel.
void USB_OTG_EnableChannelPing (uint8_t chNum)
Enable channel ping.
void USB_OTG_StopHost (void)
Stop Host.
Detailed Description
Function Documentation
USB_OTG_EnableChannelPing()
void USB_OTG_EnableChannelPing (uint8_t chNum)
Enable channel ping.
Parameters
chNum : Select channel.
Return values
None
Definition at line 411 of file drv_usb_host.c.
References USB_OTG_H_ConfigPacketCount, USB_OTG_H_EnableChannel, and USB_OTG_H_EnableDoPing.
USB_OTG_EnableInChannelTransfer()
void USB_OTG_EnableInChannelTransfer (uint16_t chNum, uint32_t transferLen, uint16_t maxPackSize, uint8_t dataPid, uint8_t epType)
Enable IN channel to start transfer.
Parameters
chNum : Select channel.
transferLen : transfer data length.
maxPackSize : The Max sizeof Packet to transfer.
dataPid : Channel data PID. This value can be one of the following values:
DATA_0 : DATA0.
DATA_1 : DATA1.
DATA_2 : DATA2.
MDATA : Controled transmission.
SETUP : UnControled transmission.
epType : Endpoint type. This value can be one of the following values:
EP_TYPE_CONTROL : Control type.
EP_TYPE_ISO : Isochronous type.
EP_TYPE_BULK : Batch type.
EP_TYPE_INTERRUPT : Interrupt type.
Return values
None
Definition at line 221 of file drv_usb_host.c.
References USB_OTG_H_ConfigDataPID, USB_OTG_H_ConfigPacketCount, USB_OTG_H_ConfigTransferSize, USB_OTG_H_DisableDoPing, USB_OTG_H_EnableChannel, USB_OTG_H_ReadFrameNum, USB_OTG_H_TxUseEvenFrame, and USB_OTG_H_TxUseOddFrame.
Referenced by USBH_BulkInData(), USBH_CtrlInData(), USBH_InterruptInData(), and USBH_IsocInData().
USB_OTG_EnableOutChannelTransfer()
void USB_OTG_EnableOutChannelTransfer (uint16_t chNum, uint8_t * transferBuff, uint32_t transferLen, uint16_t maxPackSize, uint8_t dataPid, uint8_t epType)
Enable OUT channel to start transfer.
Parameters
chNum : Select channel.
transferBuff : point to transfer buff.
transferLen : transfer data length.
maxPackSize : The Max sizeof Packet to transfer.
dataPid : Channel data PID. This value can be one of the following values:
DATA_0 : DATA0.
DATA_1 : DATA1.
DATA_2 : DATA2.
MDATA : Controled transmission.
SETUP : UnControled transmission.
epType : Endpoint type. This value can be one of the following values:
EP_TYPE_CONTROL : Control type.
EP_TYPE_ISO : Isochronous type.
EP_TYPE_BULK : Batch type.
EP_TYPE_INTERRUPT : Interrupt type.
Return values
None
Definition at line 113 of file drv_usb_host.c.
References USB_EP_TYPE_BULK, USB_EP_TYPE_CONTROL, USB_EP_TYPE_INTERRUPT, USB_EP_TYPE_ISO, USB_FIFO_WriteFifoPacket(), USB_INT_G_NPTXFEM, USB_INT_G_PTXFE, USB_OTG_EnableGlobalInterrupt, USB_OTG_H_ConfigDataPID, USB_OTG_H_ConfigPacketCount, USB_OTG_H_ConfigTransferSize, USB_OTG_H_DisableDoPing, USB_OTG_H_EnableChannel, USB_OTG_H_ReadFrameNum, USB_OTG_H_TxUseEvenFrame, and USB_OTG_H_TxUseOddFrame.
Referenced by USBH_BulkOutData(), USBH_CtrlOutData(), USBH_CtrlSetupReq(), USBH_InterruptOutData(), and USBH_IsocOutData().
USB_OTG_HaltChannel()
void USB_OTG_HaltChannel (uint16_t chNum)
Halt channel.
Parameters
chNum : Select channel.
Return values
None
Definition at line 274 of file drv_usb_host.c.
References EP_TYPE_BULK, EP_TYPE_CONTROL, USB_OTG_H_ClearQueue, USB_OTG_H_DisableChannel, USB_OTG_H_ReadEpType, and USB_OTG_H_ReadTxQueueRemainSpace.
Referenced by CDC_DisableGet().
USB_OTG_InitChannel()
void USB_OTG_InitChannel (USB_ChannelConfig_T * channelConfig)
Init channel.
Parameters
channelConfig : Config channel struct.
Return values
None
Definition at line 306 of file drv_usb_host.c.
References CHANNEL_INT_ALL, CHANNEL_INT_BABBLE, CHANNEL_INT_DTOG, CHANNEL_INT_FOVR, CHANNEL_INT_RXNAK, CHANNEL_INT_RXNYET, CHANNEL_INT_RXSTALL, CHANNEL_INT_RXTXACK, CHANNEL_INT_TERR, CHANNEL_INT_TSFCMPN, USB_ChannelConfig_T::chNum, USB_ChannelConfig_T::devAddr, USB_ChannelConfig_T::devSpeed, USB_ChannelConfig_T::direction, USB_ChannelConfig_T::enbalePing, EP_DIR_IN, USB_ChannelConfig_T::epNum, USB_ChannelConfig_T::epType, USB_ChannelConfig_T::maxPackSize, SPEED_LS, USB_EP_TYPE_BULK, USB_EP_TYPE_CONTROL, USB_EP_TYPE_INTERRUPT, USB_EP_TYPE_ISO, USB_INT_G_HCHAN, USB_OTG_EnableGlobalInterrupt, USB_OTG_H_ClearChannelIntFlag, USB_OTG_H_ConfigDeviceAddr, USB_OTG_H_ConfigEpDirection, USB_OTG_H_ConfigEpMaxPSize, USB_OTG_H_ConfigEpNum, USB_OTG_H_ConfigEpType, USB_OTG_H_DisableChannelInt, USB_OTG_H_DisableLowSpeedDevice, USB_OTG_H_EnableAllChannelsInt, USB_OTG_H_EnableChannelInt, USB_OTG_H_EnableLowSpeedDevice, USB_OTG_H_TxUseEvenFrame, and USB_OTG_H_TxUseOddFrame.
Referenced by USBH_CH_OpenChannel().
USB_OTG_PortReset()
void USB_OTG_PortReset (void)
Reset Host Port.
Parameters
None
Return values
None
Definition at line 66 of file drv_usb_host.c.
References USB_Delay_us(), USB_OTG_H_ClearPenBitChangeFlag, USB_OTG_H_ClearPovcBitChangeFlag, USB_OTG_H_DisablePort, USB_OTG_H_DisablePortReset, and USB_OTG_H_EnablePortReset.
Referenced by USB_HostInit().
USB_OTG_ReadPortSpeed()
uint8_t USB_OTG_ReadPortSpeed (void)
Read Port Speed.
Parameters
None
Return values
Return the Port Speed(SPEED_HS or SPEED_FS or SPEED_LS)
Definition at line 54 of file drv_usb_host.c.
References USB_OTG_H_ReadPortSpeedType.
USB_OTG_StopHost()
void USB_OTG_StopHost (void)
Stop Host.
Parameters
None
Return values
None
Definition at line 429 of file drv_usb_host.c.
References EP_DIR_OUT, HOST_CHANNEL_NUM, USB_H_CHANNEL_ALL, USB_OTG_FlushRxFIFO(), USB_OTG_FlushTxFIFO(), USB_OTG_H_ClearQueue, USB_OTG_H_ConfigEpDirection, and USB_OTG_H_DisableAllChannelsInt.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU