APM32F10x_SDK: Functions
Functions
Examples » DAC_NoiseWave
Functions
void RCM_Configuration (void)
Configures the different system clocks.
void GPIO_Configuration (void)
Configures the different GPIO ports.
int main (void)
Main program.
Detailed Description
Function Documentation
GPIO_Configuration()
void GPIO_Configuration (void)
Configures the different GPIO ports.
Parameters
None
Return values
None
Definition at line 93 of file DAC/DAC_NoiseWave/Source/main.c.
References GPIO_Config(), GPIO_MODE_ANALOG, GPIO_PIN_4, GPIOA, GPIO_Config_T::mode, and GPIO_Config_T::pin.
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 49 of file DAC/DAC_NoiseWave/Source/main.c.
References DAC_ALIGN_12BIT_L, DAC_CHANNEL_1, DAC_Config(), DAC_ConfigChannel1Data(), DAC_Enable(), DAC_EnableSoftwareTrigger(), DAC_LFSR_MASK_BIT11_6, DAC_OUTPUT_BUFFER_ENBALE, DAC_TRIGGER_SOFT, DAC_WAVE_GENERATION_NOISE, GPIO_Configuration(), DAC_Config_T::maskAmplitudeSelect, DAC_Config_T::outputBuffer, RCM_Configuration(), DAC_Config_T::trigger, and DAC_Config_T::waveGeneration.
RCM_Configuration()
void RCM_Configuration (void)
Configures the different system clocks.
Parameters
None
Return values
None
Definition at line 80 of file DAC/DAC_NoiseWave/Source/main.c.
References RCM_APB1_PERIPH_DAC, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB1PeriphClock(), and RCM_EnableAPB2PeriphClock().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU