APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Device » Standrad | USB OTG Library » Core Host » Standard » Core
Typedefs
typedef void(* USBH_CoreHandler_T) (void)
typedef void(* USBH_ClassCallBack_T) (void)
typedef void(* USBH_SuspendCallBack_T) (void)
typedef void(* USBH_WakeUpCallBack_T) (void)
typedef void(* USBH_IntCallBack_T) (void)
Functions
void USBD_SetupProcess (void)
Setup process.
void USBD_CtrlOutProcess (void)
OUT process for EP0.
void USBD_CtrlInProcess (void)
IN process.
void USBD_CtrlOutData (uint8_t *buf, uint32_t len)
Config the buffer to receive OUT transaction data and start to transfer.
void USBD_CtrlInData (uint8_t *buf, uint32_t len)
Config the buffer for IN transaction and start to transfer.
void USBD_CtrlRxStatus (void)
Receive OUT status in control transfer.
void USBD_CtrlTxStatus (void)
Send IN status in control transfer.
void USBD_RxData (uint8_t ep, uint8_t *buf, uint32_t len)
Receive OUT data.
void USBD_TxData (uint8_t ep, uint8_t *buf, uint32_t len)
Send IN data.
void USBD_PushDataToTxFIFO (uint8_t ep)
Push data to TxFIFO.
void USBD_Reset (void)
void USBH_PollingProcess (void)
Host state machine polling Process.
Detailed Description
Typedef Documentation
USBH_ClassCallBack_T
typedef void(* USBH_ClassCallBack_T) (void)
Definition at line 220 of file usbh_core.h.
USBH_CoreHandler_T
typedef void(* USBH_CoreHandler_T) (void)
Definition at line 217 of file usbh_core.h.
USBH_IntCallBack_T
typedef void(* USBH_IntCallBack_T) (void)
Definition at line 229 of file usbh_core.h.
USBH_SuspendCallBack_T
typedef void(* USBH_SuspendCallBack_T) (void)
Definition at line 223 of file usbh_core.h.
USBH_WakeUpCallBack_T
typedef void(* USBH_WakeUpCallBack_T) (void)
Definition at line 226 of file usbh_core.h.
Function Documentation
USBD_CtrlInData()
void USBD_CtrlInData (uint8_t * buf, uint32_t len)
Config the buffer for IN transaction and start to transfer.
Send data or status in control in transation.
Parameters
buf Buffer pointer
len Buffer length
Return values
None
Send a packet
deal with buffer
Definition at line 194 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, USBD_CtrlBuf_T::bufLen, USBD_DevReqData_T::byte, USBD_Info_T::ctrlState, USBD_REQ_TYPE_T::dir, USBD_DevReqData_T::domain, g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_Info_T::reqData, USB_EP_0, USB_MIN, USB_OTG_EnableInEpEmptyInterrupt, USB_OTG_EnableInEpTransfer(), USBD_CTRL_STATE_DATA_IN, USBD_CTRL_STATE_IN_DATA, USBD_CTRL_STATE_WAIT_STATUS_IN, USBD_CtrlTxStatus, USBD_EP_0, USBD_EP_STATUS_NAK, USBD_EP_STATUS_VALID, USBD_SetEPTxCnt, USBD_SetEPTxRxStatus(), USBD_SetEPTxStatus(), USBD_WriteDataToEP(), USBD_DevReqData_T::wLength, and USBD_CtrlBuf_T::zeroPackFill.
Referenced by HidMouse_ReportDescriptor(), USBD_ClassHandler(), and USBD_MSC_ClassHandler().
USBD_CtrlInProcess()
void USBD_CtrlInProcess (void)
IN process.
Endpoint 0 USB Control in process.
Parameters
None
Return values
None
Definition at line 125 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_DevReqData_T::bRequest, USBD_CtrlBuf_T::bufLen, USBD_DevReqData_T::byte, USBD_Info_T::ctrlState, g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_Info_T::reqData, USBD_Info_T::rxStatusHandler, USB_EP_0, USB_MIN, USB_OTG_EnableInEpEmptyInterrupt, USB_OTG_EnableInEpTransfer(), USBD_CTRL_STATE_DATA_IN, USBD_CTRL_STATE_IN_DATA, USBD_CTRL_STATE_WAIT_STATUS_IN, USBD_CTRL_STATE_WAIT_STATUS_OUT, USBD_CtrlRxStatus, USBD_EP_0, USBD_EP_STATUS_NAK, USBD_EP_STATUS_VALID, USBD_SET_ADDRESS, USBD_SetDeviceAddr, USBD_SetEPTxCnt, USBD_SetEPTxRxStatus(), USBD_SetEPTxStatus(), USBD_WriteDataToEP(), USBD_DevReqData_T::wValue, and USBD_CtrlBuf_T::zeroPackFill.
USBD_CtrlOutData()
void USBD_CtrlOutData (uint8_t * buf, uint32_t len)
Config the buffer to receive OUT transaction data and start to transfer.
Read data or status in control out transation.
Parameters
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 170 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, USBD_Info_T::ctrlState, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USB_EP_0, USB_MIN, USB_OTG_EnableOutEpTransfer(), USBD_CTRL_STATE_DATA_OUT, USBD_CTRL_STATE_OUT_DATA, USBD_CTRL_STATE_WAIT_STATUS_OUT, USBD_EP_0, USBD_EP_STATUS_NAK, USBD_EP_STATUS_VALID, and USBD_SetEPTxRxStatus().
Referenced by USBD_ClassHandler().
USBD_CtrlOutProcess()
void USBD_CtrlOutProcess (void)
OUT process for EP0.
Endpoint 0 USB Control out process.
Parameters
None
Return values
None
Definition at line 97 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, USBD_Info_T::ctrlState, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USBD_Info_T::txStatusHandler, USB_EP_0, USB_MIN, USB_OTG_EnableOutEpTransfer(), USBD_CTRL_STATE_DATA_OUT, USBD_CTRL_STATE_OUT_DATA, USBD_CtrlOutData(), USBD_CtrlTxStatus, USBD_EP_0, and USBD_ReadDataFromEP().
USBD_CtrlRxStatus()
void USBD_CtrlRxStatus (void)
Receive OUT status in control transfer.
Parameters
None
Return values
None
Definition at line 235 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::rxStatusHandler, USB_EP_0, USB_OTG_EnableOutEpTransfer(), and USB_OTG_ReceiveSetupPacket().
USBD_CtrlTxStatus()
void USBD_CtrlTxStatus (void)
Send IN status in control transfer.
Parameters
None
Return values
None
Definition at line 255 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References g_usbDev, USBD_Info_T::txStatusHandler, USB_EP_0, USB_OTG_EnableInEpTransfer(), and USB_OTG_ReceiveSetupPacket().
USBD_PushDataToTxFIFO()
void USBD_PushDataToTxFIFO (uint8_t ep)
Push data to TxFIFO.
Parameters
ep : EP number for TxFIFO
Return values
None
Definition at line 323 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, NULL, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USB_FIFO_WriteFifoPacket(), USB_MIN, USB_OTG_DisableInEpEmptyInterrupt, and USB_OTG_ReadTxFifoAvailable.
USBD_Reset()
void USBD_Reset (void)
USBD_RxData()
void USBD_RxData (uint8_t ep, uint8_t * buf, uint32_t len)
Receive OUT data.
Receive data from host(except endpoint 0)
Parameters
ep : except EP0
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 279 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, USBD_CtrlBuf_T::maxPackSize, USBD_Info_T::outBuf, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USB_MIN, USB_OTG_EnableOutEpTransfer(), USBD_EP_STATUS_VALID, USBD_SetEPRxCnt(), and USBD_SetEPRxStatus().
Referenced by USBD_MSC_BOT_Init(), USBD_MSC_BOT_Reset(), USBD_MSC_BOT_TxCSW(), and USBD_VCP_InEpCallback().
USBD_SetupProcess()
void USBD_SetupProcess (void)
Setup process.
Handler Endpoint 0 control transfer.
Parameters
None
Return values
None
Definition at line 66 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_REQ_TYPE_T::bit, USBD_DevReqData_T::bmRequestType, USBD_DevReqData_T::bRequest, USBD_REQ_TYPE_T::byte, USBD_DevReqData_T::byte, USBD_Info_T::classReqHandler, dataBuf, USBD_DevReqData_T::domain, g_usbDev, USBD_Info_T::reqData, USBD_REQ_TYPE_T::type, USB_EP_0, USB_OTG_SetStall(), USBD_EP_0, USBD_EP_STATUS_STALL, USBD_ReadDataFromEP(), USBD_ReadEPRxCnt, USBD_REQ_TYPE_CLASS, USBD_REQ_TYPE_STANDARD, USBD_REQ_TYPE_VENDOR, USBD_SetEPTxRxStatus(), USBD_StandardReqeust(), USBD_Info_T::vendorReqHandler, USBD_DevReqData_T::wIndex, USBD_DevReqData_T::wLength, and USBD_DevReqData_T::wValue.
USBD_TxData()
void USBD_TxData (uint8_t ep, uint8_t * buf, uint32_t len)
Send IN data.
Transfer data to host(except endpoint 0)
Parameters
ep : except EP0
buf Buffer pointer
len Buffer length
Return values
None
Definition at line 303 of file USB_OTG_Lib/Core_Device/Standard/src/usbd_core.c.
References USBD_CtrlBuf_T::bufLen, g_usbDev, USBD_Info_T::inBuf, USBD_CtrlBuf_T::maxPackSize, USBD_CtrlBuf_T::packNum, USBD_CtrlBuf_T::pBuf, USB_OTG_EnableInEpEmptyInterrupt, USB_OTG_EnableInEpTransfer(), USBD_EP_STATUS_VALID, USBD_SetEPTxCnt, USBD_SetEPTxStatus(), and USBD_WriteDataToEP().
Referenced by HidMouse_Write(), USBD_HID_Write(), USBD_MSC_BOT_TxCSW(), and USBD_VCP_OutEpCallback().
USBH_PollingProcess()
void USBH_PollingProcess (void)
Host state machine polling Process.
Parameters
None
Return values
None
Definition at line 109 of file usbh_core.c.
References USBH_Info_T::connectedFlag, USBH_Info_T::curHostState, g_usbHost, USBH_Info_T::portEnable, USBH_ConfigHostState, USBH_HOST_DEVICE_DETACHED, USBH_HOST_IDLE, and USBH_ReadCurHostState.
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU