APM32F10x_SDK: Functions
Functions
Examples » RTC Second
Functions
void RTC_Config (void)
RTC Config.
int main (void)
Main program.
Detailed Description
Function Documentation
main()
int main (void)
Main program.
Parameters
None
Return values
None
Definition at line 49 of file RTC/RTC_Second/Source/main.c.
References APM_MINI_LEDInit(), LED2, and RTC_Config().
RTC_Config()
void RTC_Config (void)
RTC Config.
Parameters
None
Return values
None
Definition at line 67 of file RTC/RTC_Second/Source/main.c.
References NVIC_EnableIRQRequest(), PMU_EnableBackupAccess(), RCM_APB1_PERIPH_PMU, RCM_ConfigRTCCLK(), RCM_EnableAPB1PeriphClock(), RCM_EnableLSI(), RCM_EnableRTCCLK(), RCM_FLAG_LSIRDY, RCM_ReadStatusFlag(), RCM_RTCCLK_LSI, RESET, RTC_ConfigPrescaler(), RTC_EnableInterrupt(), RTC_INT_SEC, RTC_IRQn, RTC_WaitForLastTask(), and RTC_WaitForSynchro().
Referenced by main().
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU