APM32F10x_SDK: Functions
Functions
USB OTG Library » Core Host » Standard » Channel
Functions
int8_t USBH_CH_AllocChannel (uint8_t epAddr)
Alloc a channel for a endpoint by address.
void USBH_CH_FreeChannel (uint8_t chNum)
Free the channel.
void USBH_CH_FreeAllChannel (void)
Free All of the channel.
USBH_CH_STATUS_T USBH_CH_OpenChannel (uint8_t chNum, uint8_t devAddr, uint8_t epType, uint16_t maxPackSize)
Config the channel to transfer.
uint8_t USBH_ReadEpAddrChannel (uint8_t epAddr)
Read the channel number of endpoint.
Detailed Description
Function Documentation
USBH_CH_AllocChannel()
int8_t USBH_CH_AllocChannel (uint8_t epAddr)
Alloc a channel for a endpoint by address.
Parameters
epAddr : endpoint address to be alloc channel.
Return values
channel number.
Definition at line 76 of file usbh_channel.c.
References USBH_XferPipe_T::channelUsedFlag, USBH_XferPipe_T::epAddr, g_usbHost, USBH_CHANNEL_USED, and USBH_Info_T::xferPipe.
Referenced by USBH_CDC_ClassInitHandler(), USBH_HID_InitHandler(), and USBH_MSC_ClassInitHandler().
USBH_CH_FreeAllChannel()
void USBH_CH_FreeAllChannel (void)
Free All of the channel.
Parameters
chNum : channel to be free.
Return values
None.
Definition at line 122 of file usbh_channel.c.
References HOST_CHANNEL_NUM, and USBH_CH_FreeChannel().
USBH_CH_FreeChannel()
void USBH_CH_FreeChannel (uint8_t chNum)
Free the channel.
Parameters
chNum : channel to be free.
Return values
None.
Definition at line 96 of file usbh_channel.c.
References USBH_XferPipe_T::buf, USBH_XferPipe_T::bufCount, USBH_XferPipe_T::bufLen, USBH_XferPipe_T::channelUsedFlag, USBH_XferPipe_T::dataPid, USBH_XferPipe_T::dir, USBH_XferPipe_T::enbalePing, USBH_XferPipe_T::epAddr, g_usbHost, USBH_XferPipe_T::maxPackSize, NULL, USBH_XferPipe_T::pidToggle, PIPE_OK, USBH_XferPipe_T::pipeState, USBH_XferPipe_T::urbStatus, USBH_CHANNEL_FREE, USBH_URB_IDLE, and USBH_Info_T::xferPipe.
Referenced by USBH_CH_FreeAllChannel(), and USBH_DeInit().
USBH_CH_OpenChannel()
USBH_CH_STATUS_T USBH_CH_OpenChannel (uint8_t chNum, uint8_t devAddr, uint8_t epType, uint16_t maxPackSize)
Config the channel to transfer.
Parameters
chNum : channel to be configed.
devAddr : device address.
epType : endpoint type of the channel.
maxPackSize : endpoint max pack size.
Return values
USBH_CH_OK or USBH_CH_FAIL.
< High speed enable Ping
Definition at line 145 of file usbh_channel.c.
References USB_ChannelConfig_T::chNum, USB_ChannelConfig_T::devAddr, USB_ChannelConfig_T::devSpeed, USB_ChannelConfig_T::direction, USBH_XferPipe_T::enbalePing, USB_ChannelConfig_T::enbalePing, USBH_XferPipe_T::epAddr, USB_ChannelConfig_T::epNum, USB_ChannelConfig_T::epType, g_usbHost, USBH_XferPipe_T::maxPackSize, USB_ChannelConfig_T::maxPackSize, USBH_Info_T::speed, USB_OTG_InitChannel(), USBH_CH_FAIL, USBH_CH_OK, USBH_CHANNEL_MAX_NUM, and USBH_Info_T::xferPipe.
Referenced by USBH_CDC_ClassInitHandler(), USBH_HID_InitHandler(), and USBH_MSC_ClassInitHandler().
USBH_ReadEpAddrChannel()
uint8_t USBH_ReadEpAddrChannel (uint8_t epAddr)
Read the channel number of endpoint.
Parameters
epAddr : endpoint address which you want to fine the channel.
Return values
Return the channel number, if no channel, then return 0xFF.
Definition at line 181 of file usbh_channel.c.
References USBH_XferPipe_T::channelUsedFlag, USBH_XferPipe_T::epAddr, g_usbHost, USBH_CHANNEL_MAX_NUM, and USBH_Info_T::xferPipe.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU