APM32F10x_SDK: Functions
Functions
Examples » USBD_MSC
Typedefs
typedef uint8_t(* STORAGE_Init_T) (uint8_t lun)
typedef uint8_t(* STORAGE_ReadCapacity_T) (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
typedef uint8_t(* STORAGE_CheckReady_T) (uint8_t lun)
typedef uint8_t(* STORAGE_CheckWPR_T) (uint8_t lun)
typedef uint8_t(* STORAGE_Read_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
typedef uint8_t(* STORAGE_Write_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Functions
void USB_HardwareInit (void)
USB hardware Init.
void USBD_ConfigSerialString (uint8_t *string)
Config Serial String.
void USBD_MSC_Init (void)
MSC initialization.
void USBD_MSC_BOT_Reset (void)
BOT Process Reset.
void USBD_MSC_BOT_Init (void)
BOT Process initialization.
void USBD_MSC_BOT_OutData (uint8_t ep)
Bulk OUT data handler.
void USBD_MSC_BOT_InData (uint8_t ep)
Bulk IN data handler.
void USBD_MSC_BOT_TxCSW (uint8_t cswStatus)
Send CSW.
void USBD_MSV_BOT_ClearFeatureHandler (void)
handler clearFeature in standard request.
uint8_t SCSI_CmdHandler (uint8_t lun, uint8_t *command)
SCSI command handler.
void SCSI_PutSenseCode (uint8_t lun, uint8_t sKey, uint8_t ASC, uint8_t ASCQ)
Put the sense code to array.
int main (void)
Main program.
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T *configStruct)
Configures COM port.
void USBD_MSC_OutEpCallback (uint8_t ep)
MSC Out endpoint initialization call back.
void USBD_MSC_InEpCallback (uint8_t ep)
MSC In endpoint initialization call back.
uint8_t STORAGE_Init (uint8_t lun)
Initialize the medium.
uint8_t STORAGE_ReadCapacity (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
Read medium capacity and block size.
uint8_t STORAGE_CheckReady (uint8_t lun)
return medium ready Status
uint8_t STORAGE_CheckWPR (uint8_t lun)
return medium write-protected Status
uint8_t STORAGE_ReadData (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Read data from the medium.
uint8_t STORAGE_WriteData (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Write data to the medium.
Detailed Description
Typedef Documentation
STORAGE_CheckReady_T
typedef uint8_t(* STORAGE_CheckReady_T) (uint8_t lun)
Definition at line 57 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
STORAGE_CheckWPR_T
typedef uint8_t(* STORAGE_CheckWPR_T) (uint8_t lun)
Definition at line 58 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
STORAGE_Init_T
typedef uint8_t(* STORAGE_Init_T) (uint8_t lun)
Definition at line 55 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
STORAGE_Read_T
typedef uint8_t(* STORAGE_Read_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Definition at line 59 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
STORAGE_ReadCapacity_T
typedef uint8_t(* STORAGE_ReadCapacity_T) (uint8_t lun, uint32_t *blockNum, uint32_t *blockSize)
Definition at line 56 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
STORAGE_Write_T
typedef uint8_t(* STORAGE_Write_T) (uint8_t lun, uint8_t *buf, uint32_t blkAddr, uint16_t blkLen)
Definition at line 60 of file OTG/OTG_Device/USBD_MSC/Include/usbd_storage_disk.h.
Function Documentation
APM_BOARD_COMInit()
void APM_BOARD_COMInit (COM_TypeDef COM, USART_Config_T * configStruct)
Configures COM port.
Parameters
COM Specifies the COM port to be configured. This parameter can be one of following parameters:
COM1
COM2
Return values
None
Definition at line 221 of file OTG_Device/USBD_MSC/Source/usb_board.c.
References APM_MINI_COMInit(), and COM1.
Referenced by USB_HardwareInit().
main()
int main (void)
Main program.
Parameters
None
Return values
int
Definition at line 48 of file OTG/OTG_Device/USBD_MSC/Source/main.c.
References USBD_MSC_Init().
SCSI_CmdHandler()
uint8_t SCSI_CmdHandler (uint8_t lun, uint8_t * command)
SCSI command handler.
Parameters
lun Logical unit number
command Command pointer
Return values
SCSI_OK or SCSI_FAILL
Definition at line 123 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_scsi.c.
References SCSI_ASC_INVALID_CDB, SCSI_CMD_ALLOW_MEDIUM_REMOVAL, SCSI_CMD_INQUIRY, SCSI_CMD_MODE_SENSE_10, SCSI_CMD_MODE_SENSE_6, SCSI_CMD_READ_10, SCSI_CMD_READ_CAPACITY_10, SCSI_CMD_READ_FORMAT_CAPACITIES, SCSI_CMD_REQUEST_SENSE, SCSI_CMD_START_STOP_UNIT, SCSI_CMD_TEST_UNIT_READY, SCSI_CMD_VERIFY_10, SCSI_CMD_WRITE10, SCSI_FAIL, SCSI_OK, SCSI_PutSenseCode(), and SCSI_SKEY_ILLEGAL_REQUEST.
Referenced by USBD_MSC_BOT_InData(), and USBD_MSC_BOT_OutData().
SCSI_PutSenseCode()
void SCSI_PutSenseCode (uint8_t lun, uint8_t sKey, uint8_t ASC, uint8_t ASCQ)
Put the sense code to array.
Parameters
sKey sense Key
ASC Additional Sense Code
ASCQ Additional Sense Code Qualifier
Return values
None
Definition at line 193 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_scsi.c.
References SCSI_Sense_T::ASC, SCSI_Sense_T::ASCQ, g_scsiSenseCode, g_sensePutCnt, SCSI_SENSE_LIST_NUMBER, and SCSI_Sense_T::sensekey.
Referenced by SCSI_CmdHandler().
STORAGE_CheckReady()
uint8_t STORAGE_CheckReady (uint8_t lun)
return medium ready Status
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 137 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_CheckWPR()
uint8_t STORAGE_CheckWPR (uint8_t lun)
return medium write-protected Status
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 149 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_Init()
uint8_t STORAGE_Init (uint8_t lun)
Initialize the medium.
Parameters
lun Logical unit number
Return values
SCSI_OK or SCSI_FAILL
Definition at line 106 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References SCSI_OK.
STORAGE_ReadCapacity()
uint8_t STORAGE_ReadCapacity (uint8_t lun, uint32_t * blockNum, uint32_t * blockSize)
Read medium capacity and block size.
Parameters
lun Logical unit number
blockNum number of physical block
blockSize size of a physical block
Return values
SCSI_OK or SCSI_FAILL
Definition at line 122 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References SCSI_OK, STORAGE_BLK_NBR, and STORAGE_BLK_SIZ.
STORAGE_ReadData()
uint8_t STORAGE_ReadData (uint8_t lun, uint8_t * buf, uint32_t blkAddr, uint16_t blkLen)
Read data from the medium.
Parameters
lun Logical unit number
buf Pointer to the buffer to get data
blkAddr block address of first physical block to be read
blkLen number of physical block to be read
Return values
SCSI_OK or SCSI_FAILL
Definition at line 167 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References dataBuf, SCSI_OK, and STORAGE_BLK_SIZ.
STORAGE_WriteData()
uint8_t STORAGE_WriteData (uint8_t lun, uint8_t * buf, uint32_t blkAddr, uint16_t blkLen)
Write data to the medium.
Parameters
lun Logical unit number
buf Pointer to the buffer to write data
blkAddr block address of first physical block to be write
blkLen number of physical block to be write
Return values
SCSI_OK or SCSI_FAILL
Definition at line 195 of file OTG/OTG_Device/USBD_MSC/Source/usbd_storage_disk.c.
References dataBuf, SCSI_OK, and STORAGE_BLK_SIZ.
USB_HardwareInit()
void USB_HardwareInit (void)
USB hardware Init.
Parameters
None
Return values
None
< APM32F40X
< APM32F40X
Definition at line 54 of file OTG_Device/USBD_MSC/Source/usb_board.c.
References APM_BOARD_COMInit(), USART_Config_T::baudRate, BIT10, BIT12, BIT8, BIT9, BIT_SET, COM1, FMC, GPIO_Config(), GPIO_MODE_AF_PP, GPIO_MODE_IN_FLOATING, GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_10, GPIO_PIN_11, GPIO_PIN_12, GPIO_PIN_13, GPIO_PIN_14, GPIO_PIN_15, GPIO_PIN_3, GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_9, GPIO_PIN_SOURCE_0, GPIO_PIN_SOURCE_1, GPIO_PIN_SOURCE_10, GPIO_PIN_SOURCE_11, GPIO_PIN_SOURCE_12, GPIO_PIN_SOURCE_13, GPIO_PIN_SOURCE_14, GPIO_PIN_SOURCE_15, GPIO_PIN_SOURCE_3, GPIO_PIN_SOURCE_4, GPIO_PIN_SOURCE_5, GPIO_SPEED_50MHz, GPIOA, GPIOB, GPIOC, USART_Config_T::hardwareFlow, GPIO_Config_T::mode, USART_Config_T::mode, NVIC_ConfigPriorityGroup(), NVIC_EnableIRQRequest(), NVIC_PRIORITY_GROUP_1, USART_Config_T::parity, GPIO_Config_T::pin, RCM, RCM_APB2_PERIPH_AFIO, RCM_APB2_PERIPH_GPIOA, RCM_EnableAPB2PeriphClock(), GPIO_Config_T::speed, USART_Config_T::stopBits, USART_HARDWARE_FLOW_NONE, USART_MODE_TX_RX, USART_PARITY_NONE, USART_STOP_BIT_1, USART_WORD_LEN_8B, USB_OTG_DisableAllGlobalInterrupt, and USART_Config_T::wordLength.
USBD_ConfigSerialString()
void USBD_ConfigSerialString (uint8_t * string)
Config Serial String.
Parameters
string point to the Serial String
Return values
None
Definition at line 257 of file OTG/OTG_Device/USBD_MSC/Source/usbd_descriptor.c.
References UID_ADDRESS1, UID_ADDRESS2, UID_ADDRESS3, and USBD_NumberToChar.
USBD_MSC_BOT_InData()
void USBD_MSC_BOT_InData (uint8_t ep)
Bulk IN data handler.
Parameters
ep : IN endpoint
Return values
None
Definition at line 120 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_CBW_T::bLUN, BOT_CSW_STATUS_CMD_FAIL, BOT_CSW_STATUS_CMD_OK, BOT_STATE_DATA_IN, BOT_STATE_LAST_DATA_IN, BOT_STATE_SEND_DATA, BOT_CBW_T::CB, BOT_Info_T::CBW, g_BOTInfo, SCSI_CmdHandler(), SCSI_OK, BOT_Info_T::state, and USBD_MSC_BOT_TxCSW().
Referenced by USBD_MSC_InEpCallback().
USBD_MSC_BOT_Init()
void USBD_MSC_BOT_Init (void)
BOT Process initialization.
Parameters
None
Return values
None
Definition at line 78 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_STATE_IDLE, BOT_STATUS_NORMAL, BOT_Info_T::CBW, g_BOTInfo, g_storageCallBack, STORAGE_Callback_T::Init, MSC_BOT_CBW_LENGTH, MSC_IN_EP, MSC_OUT_EP, BOT_Info_T::state, BOT_Info_T::status, USB_OTG_FlushRxFIFO(), USB_OTG_FlushTxFIFO(), and USBD_RxData().
USBD_MSC_BOT_OutData()
void USBD_MSC_BOT_OutData (uint8_t ep)
Bulk OUT data handler.
Parameters
ep : OUT endpoint
Return values
None
Definition at line 98 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_CBW_T::bLUN, BOT_CSW_STATUS_CMD_FAIL, BOT_STATE_DATA_OUT, BOT_STATE_IDLE, BOT_CBW_T::CB, BOT_Info_T::CBW, g_BOTInfo, SCSI_CmdHandler(), SCSI_OK, BOT_Info_T::state, and USBD_MSC_BOT_TxCSW().
Referenced by USBD_MSC_OutEpCallback().
USBD_MSC_BOT_Reset()
void USBD_MSC_BOT_Reset (void)
BOT Process Reset.
Parameters
None
Return values
None
Definition at line 63 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_STATE_IDLE, BOT_STATUS_RECOVERY, BOT_Info_T::CBW, g_BOTInfo, MSC_BOT_CBW_LENGTH, BOT_Info_T::state, BOT_Info_T::status, USB_EP_0, and USBD_RxData().
Referenced by USBD_MSC_ClassHandler().
USBD_MSC_BOT_TxCSW()
void USBD_MSC_BOT_TxCSW (uint8_t cswStatus)
Send CSW.
Parameters
cswStatus : status of CSW
Return values
None
Definition at line 208 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_STATE_IDLE, BOT_CSW_T::bStatus, BOT_Info_T::CBW, BOT_Info_T::CSW, BOT_CSW_T::dSignature, g_BOTInfo, MSC_BOT_CBW_LENGTH, MSC_BOT_CSW_LENGTH, MSC_BOT_CSW_SIGNATURE, MSC_IN_EP, MSC_OUT_EP, BOT_Info_T::state, USBD_RxData(), and USBD_TxData().
Referenced by USBD_MSC_BOT_InData(), USBD_MSC_BOT_OutData(), and USBD_MSV_BOT_ClearFeatureHandler().
USBD_MSC_InEpCallback()
void USBD_MSC_InEpCallback (uint8_t ep)
MSC In endpoint initialization call back.
Parameters
ep : endpoint number
Return values
None
Definition at line 142 of file OTG/OTG_Device/USBD_MSC/Source/usbd_msc.c.
References MSC_IN_EP, and USBD_MSC_BOT_InData().
Referenced by USBD_MSC_Init().
USBD_MSC_Init()
void USBD_MSC_Init (void)
MSC initialization.
Parameters
None
Return values
None
Definition at line 157 of file OTG/OTG_Device/USBD_MSC/Source/usbd_msc.c.
References USBD_InitParam_T::classReqHandler, g_configDescriptor, g_deviceDescriptor, g_qualifierDescriptor, g_stdReqCallback, g_stringDescriptor, USBD_InitParam_T::inEpHandler, USBD_InitParam_T::outEpHandler, USBD_InitParam_T::pConfigurationDesc, USBD_InitParam_T::pDeviceDesc, USBD_InitParam_T::pQualifierDesc, USBD_InitParam_T::pStdReqCallback, USBD_InitParam_T::pStringDesc, USBD_Init(), USBD_InitParamStructInit(), USBD_MSC_ClassHandler(), USBD_MSC_InEpCallback(), and USBD_MSC_OutEpCallback().
Referenced by main().
USBD_MSC_OutEpCallback()
void USBD_MSC_OutEpCallback (uint8_t ep)
MSC Out endpoint initialization call back.
Parameters
ep : endpoint number
Return values
None
Definition at line 127 of file OTG/OTG_Device/USBD_MSC/Source/usbd_msc.c.
References MSC_OUT_EP, and USBD_MSC_BOT_OutData().
Referenced by USBD_MSC_Init().
USBD_MSV_BOT_ClearFeatureHandler()
void USBD_MSV_BOT_ClearFeatureHandler (void)
handler clearFeature in standard request.
Parameters
None
Return values
None
Definition at line 228 of file Examples/OTG/OTG_Device/USBD_MSC/Source/usbd_msc_bot.c.
References BOT_CSW_STATUS_CMD_FAIL, BOT_STATUS_ERROR, BOT_STATUS_NORMAL, BOT_STATUS_RECOVERY, USBD_DevReqData_T::domain, g_BOTInfo, g_usbDev, MSC_IN_EP, USBD_Info_T::reqData, BOT_Info_T::status, USB_OTG_ClearInEpStall(), USBD_MSC_BOT_TxCSW(), and USBD_DevReqData_T::wIndex.
For complete documentation on APM32 Microcontrollers visit www.geehy.com/MCU